### ISSUE TITLE
Crashed with bus error at closing

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#10001]
After already the previous leaving of ipython was suspiciously slow, this time it trashed:
```bash
Do you really want to exit ([y]/n)? y
[1]    41616 bus error  ipython
```
Here's the system output for the crash:
https://gist.github.com/michaelaye/9e8c3bc1e6401f5cb7579ecfd1b9ad21

My sys_info:
```bash
(stable) └─❱❱❱ python -c "import IPython; print(IPython.sys_info())"     +6637 18:42 ❰─┘
{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-15.6.0-x86_64-i386-64bit',
 'sys_executable': '/Users/klay6683/miniconda3/envs/stable/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.2 | packaged by conda-forge | (default, Jul 26 2016, '
                '01:37:38) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]'}
```
Working with conda 3.x, Python 3.5.x on macOS 10.11.6

**Comment by minrk** [comment]
Ooh, that's a new one. Since we don't have any compiled code, this is likely a bug in something else. Hunches:

- sqlite
- select

Is this repeatable?

**Comment by michaelaye** [comment]
Yep, just not everytime (the worst!):

```bash
In [19]:
Do you really want to exit ([y]/n)? y
python(75852,0x7fff7c665000) malloc: *** error for object 0x10bfeb668: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    75852 abort      ipython
```
Stack trace here: http://gist.github.com/b995b5dc6d440eb52cea4397b497dc98

**Comment by michaelaye** [comment]
And only happening in ipython terminal, btw.

**Comment by minrk** [comment]
Stack trace points to HDF5 being the culprit. Do you have HDF5 files open when you are exiting?

**Comment by michaelaye** [comment]
didn't open HDF5 files manually since long. Unless pd.read_hdf() somehow forgets to close down the file? Will check...

**Comment by michaelaye** [comment]
Here's another stack trace. This time I just played a bit with astropy.coordinates, nothing with HDF5 at all:
https://gist.github.com/d065bd61378f4b0d30ce5f2fe653799d

**Comment by i336** [comment]
Interesting, I just found this.

I get the same issue with the QT Console on FreeBSD 11.0-RELEASE. I wouldn't put it past a configuration error, as I rebuilt everything (including Python 3.4 and **Qt5**) from source, since the python35 pkg seems to be producing the same errors.

The ResourceWarnings occur at startup; I can't seem to silence them, and they're probably unrelated (maybe newly introduced 3.5 sanity checks perhaps?). Once IPython is running it seems ok. The SIGBUS happens upon shutdown.

I was actually setting this up for a friend - Python/Jupyter have been on my own "that would be a really good idea to learn" todo list for a while but I'm not there yet, so I have no idea what I'm doing. :P I'm happy to try stuff though.

```
$ gdb --args python3.5 `which jupyter-qtconsole`
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) run
Starting program: /usr/local/bin/python3.5 /usr/local/bin/jupyter-qtconsole
[New LWP 101640]
[New Thread 801e16000 (LWP 101640/python3.5)]
/usr/local/lib/python3.5/site-packages/qtconsole/qt_loaders.py:126: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/lib/python3.5/site-packages/PyQt5/QtCore.so'>
  imp.find_module('QtCore', mod.__path__)
/usr/local/lib/python3.5/site-packages/qtconsole/qt_loaders.py:127: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/lib/python3.5/site-packages/PyQt5/QtGui.so'>
  imp.find_module('QtGui', mod.__path__)
/usr/local/lib/python3.5/site-packages/qtconsole/qt_loaders.py:128: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/lib/python3.5/site-packages/PyQt5/QtSvg.so'>
  imp.find_module('QtSvg', mod.__path__)
/usr/local/lib/python3.5/site-packages/qtconsole/qt_loaders.py:131: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/lib/python3.5/site-packages/PyQt5/QtWidgets.so'>
  imp.find_module('QtWidgets', mod.__path__)
warning: Lowest section in /usr/local/lib/libicudata.so.57 is .hash at 0000000000000120
[New Thread 8106bdc00 (LWP 101860/python3.5)]

Program received signal SIGBUS, Bus error.
[Switching to Thread 801e16000 (LWP 101640/python3.5)]
qpycore_qobject_metaobject (pySelf=0x8140f67d8, base=0x80bf84260) at ../qpy/QtCore/qpycore_qobject_helpers.cpp:52
52          if (pySelf && ((pyqtWrapperType *)Py_TYPE(pySelf))->metaobject)
Current language:  auto; currently c++
(gdb) bt
#0  qpycore_qobject_metaobject (pySelf=0x8140f67d8, base=0x80bf84260) at ../qpy/QtCore/qpycore_qobject_helpers.cpp:52
#1  0x000000080b70cba5 in sipQMainWindow::metaObject (this=0x81d26f1c0) at sipQtWidgetsQMainWindow.cpp:400
#2  0x0000000803897942 in QObject::~QObject () from /usr/local/lib/libQt5Core.so.5
#3  0x00000008068e8913 in QAccessibleCache::deleteInterface () from /usr/local/lib/libQt5Gui.so.5
#4  0x00000008018b0dd2 in __cxa_finalize () from /lib/libc.so.7
#5  0x0000000801840141 in exit () from /lib/libc.so.7
#6  0x0000000800da8ef4 in Py_Exit (sts=<value optimized out>) at Python/pylifecycle.c:1467
#7  0x0000000800daca1c in handle_system_exit () at Python/pythonrun.c:602
#8  0x0000000800dac4e9 in PyErr_PrintEx (set_sys_last_vars=1) at Python/pythonrun.c:612
#9  0x0000000800dab74c in PyRun_SimpleFileExFlags (fp=<value optimized out>, filename=<value optimized out>, closeit=1, flags=<value optimized out>)
    at Python/pythonrun.c:508
#10 0x0000000800dcaa65 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:318
#11 0x0000000000400c5c in main (argc=<value optimized out>, argv=0x7fffffffeb88) at ./Programs/python.c:65
(gdb) 
```
