### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by spring19940512** [ipython/ipython#10007]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

```
In [1]:
Traceback (most recent call last):
  File "f:\program files\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "f:\program files\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\Program Files\python\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "f:\program files\python\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "f:\program files\python\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "f:\program files\python\lib\site-packages\IPython\terminal\ipapp.py", line 348, in start
    self.shell.mainloop()
  File "f:\program files\python\lib\site-packages\IPython\terminal\interactiveshell.py", line 440, in mainloop
    self.interact()
  File "f:\program files\python\lib\site-packages\IPython\terminal\interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "f:\program files\python\lib\site-packages\IPython\terminal\interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "f:\program files\python\lib\site-packages\prompt_toolkit\interface.py", line 399, in run
    self._redraw()
  File "f:\program files\python\lib\site-packages\prompt_toolkit\interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "f:\program files\python\lib\site-packages\prompt_toolkit\renderer.py", line 449, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "f:\program files\python\lib\site-packages\prompt_toolkit\renderer.py", line 159, in _output_screen_diff
    current_pos = move_cursor(Point(y=y, x=c))
  File "f:\program files\python\lib\site-packages\prompt_toolkit\renderer.py", line 89, in move_cursor
    _output_cursor_forward(new.x)
  File "f:\program files\python\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 249, in cursor_forward
    sr = self.get_win32_screen_buffer_info().dwCursorPosition
  File "f:\program files\python\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 50, in __init__
    xterm = 'xterm' in os.environ.get('TERM')
TypeError: argument of type 'NoneType' is not iterable

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Carreau** [comment]
THis [has been fixed upstream a month an a half ago](https://github.com/jonathanslenders/python-prompt-toolkit/commit/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d). you can try to update prompt_toolkit, and if it does not work, as a work around set your TERM environment variable to empty string should fix this.
