### ISSUE TITLE
ERROR Converting notebook to PDF

### ISSUE THREAD

**Issue by kivenlee** [ipython/ipython#10053]
Traceback (most recent call last):
  File "/Users/kiven/anaconda2/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 289, in start
    self.convert_notebooks()
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 412, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 383, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 335, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/pdf.py", line 138, in from_notebook_node
    self.texinputs = os.getcwd()
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 558, in __set__
    self.set(obj, value)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 532, in set
    new_value = self._validate(obj, value)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 564, in _validate
    value = self.validate(obj, value)
  File "/Users/kiven/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 1926, in validate
    raise TraitError(msg.format(value, self.name, class_of(obj)))
traitlets.traitlets.TraitError: Could not decode '/Users/kiven/Documents/02-\xe5\xad\xa6\xe4\xb9\xa0/020-Coursera&51cto/03-ML-UniversityOfWashington-02-regression' for unicode trait 'texinputs' of a PDFExporter instance.

**Comment by takluyver** [comment]
Until we get round to fixing this (probably in nbconvert), I'd strongly recommend using Anaconda with Python 3 when your file paths have non-ascii characters in.

**Comment by srinivasreddy** [comment]
@kivenlee  I raised a PR https://github.com/jupyter/nbconvert/pull/502 for you. Enjoy!!

**Comment by srinivasreddy** [comment]
Now that PR  jupyter/nbconvert#502 has been merged. shall we close this?
