### ISSUE TITLE
How to solve this issue? ("RuntimeError: Reloading numpy._globals is not allowed")

### ISSUE THREAD

**Issue by shuoy** [ipython/ipython#10084]
```
$ iptest lib

Test group: lib
.....E.....................S/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
...................S....................S.....
======================================================================
ERROR: Test that NumPy can be deep reloaded.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/testing/decorators.py", line 212, in skipper_func
    return f(*args, **kwargs)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/tests/test_deepreload.py", line 38, in test_deepreload_numpy
    dreload(numpy, exclude=exclude)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/deepreload.py", line 341, in reload
    return deep_reload_hook(module)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/deepreload.py", line 311, in deep_reload_hook
    newm = imp.load_module(name, fp, filename, stuff)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/numpy/__init__.py", line 112, in <module>
    from ._globals import ModuleDeprecationWarning, VisibleDeprecationWarning
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/deepreload.py", line 252, in deep_import_hook
    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/deepreload.py", line 156, in load_next
    result = import_submodule(mod, subname, buf)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython/lib/deepreload.py", line 201, in import_submodule
    m = imp.load_module(fullname, fp, filename, stuff)
  File "/Users/syang1/.virtualenvs/deeplearning/lib/python2.7/site-packages/numpy/_globals.py", line 29, in <module>
    raise RuntimeError('Reloading numpy._globals is not allowed')
RuntimeError: Reloading numpy._globals is not allowed
-------------------- >> begin captured stdout << ---------------------
Reloading __future__
Reloading warnings
Reloading linecache
Reloading os
Reloading errno
Reloading posix
Reloading posixpath
Reloading stat
Reloading genericpath
Reloading copy_reg
Reloading types
Reloading _warnings
Reloading numpy._globals

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 74 tests in 1.400s

FAILED (SKIP=3, errors=1)

______________________________________________________________________
Test suite completed for system with the following information:
IPython version: 5.1.0
IPython commit : 5c9c918 (installation)
IPython package: ~/.virtualenvs/deeplearning/lib/python2.7/site-packages/IPython
Python version : 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
sys.executable : ~/.virtualenvs/deeplearning/bin/python
Platform       : Darwin-14.5.0-x86_64-i386-64bit

Tools and libraries available at test time:
   matplotlib pygments sqlite3

Status: ERROR - 1 out of 1 test groups failed (lib). Took 2.270s.

You may wish to rerun these, with:
  iptest lib
```

**Comment by takluyver** [comment]
numpy no longer allows reloading, so please ignore the failure. That test was removed in #10025.
