### ISSUE TITLE
Ipython 5.1.0 default prompt broken

### ISSUE THREAD

**Issue by omri7** [ipython/ipython#10109]
I just installed ipython on my windows 10, and it fails to start properly.
python version - 2.7.6
I did manage to get ipython to run by using --simple-prompt.

(I am using cmd.exe)

Traceback:

Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: In [1]:                                                                                                                                               Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\python27\scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in start
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 440, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 404, in run
    self._redraw()
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 351, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\python27\lib\site-packages\prompt_toolkit\renderer.py", line 442, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\python27\lib\site-packages\prompt_toolkit\renderer.py", line 153, in _output_screen_diff
    current_pos = move_cursor(Point(y=y, x=c))
  File "c:\python27\lib\site-packages\prompt_toolkit\renderer.py", line 88, in move_cursor
    _output_cursor_forward(new.x)
  File "c:\python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 249, in cursor_forward
    sr = self.get_win32_screen_buffer_info().dwCursorPosition
  File "c:\python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by takluyver** [comment]
This sounds similar to #10070 - can you comment there to help get it resolved?
