### ISSUE TITLE
Tab completions error

### ISSUE THREAD

**Issue by anceschialberto** [ipython/ipython#10222]
Hi, I'm using python 2.7.13 with ipython 5.2.0 and ipdb 0.10.2 in a virtualenv. OS is windows 10.
When I run my script in the system shell and stop my code with `ipdb.set_trace()` and I try to use completions with tab, I immediately encounter this error:

```
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\web\findomestic-etl\.venv\lib\site-packages\prompt_toolkit\interface.py", line 840, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\web\findomestic-etl\.venv\lib\site-packages\IPython\terminal\ptutils.py", line 45, in get_completions
    with self.shell.pt_cli.patch_stdout_context():
AttributeError: 'NoneType' object has no attribute 'pt_cli'
```

Any idea? Thank you in advance.

**Comment by takluyver** [comment]
Sorry, I think that just got broken in 5.2. #10223 should fix it.
