### ISSUE TITLE
first time to install jupyter notebook, and when i import it i find error

### ISSUE THREAD

**Issue by curry111** [ipython/ipython#10234]
i installed jupyter notebook in ubuntu 14.04 using "sudo pip install jupyter"
and when i type "jupyter notebook" in the command line, i find this error

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1136, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 93, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 138, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/usr/local/lib/python2.7/dist-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

**Comment by takluyver** [comment]
The error is coming from a package we don't control. Try upgrading (`pip install --upgrade`) setuptools and packaging.

**Comment by shankaribm** [comment]
Yes you are correct ...
pip install --upgrade setuptools 
  did the trick, and now iPython is no longer crashing after this

**Comment by VinACE** [comment]
pip install --upgrade setuptools
pip3 install --upgrade setuptools

Did the trick, thank you
