### ISSUE TITLE
AttributeError: module 'select' has no attribute 'kevent'

### ISSUE THREAD

**Issue by gonulsabah** [ipython/ipython#10251]
In [1]: from locust import TaskSet

In [2]:
Traceback (most recent call last):
  File "./manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python3.5/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../lib/python3.5/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File ".../lib/python3.5/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File ".../lib/python3.5/site-packages/django_extensions/management/commands/shell_plus.py", line 418, in handle
    shell()
  File ".../lib/python3.5/site-packages/django_extensions/management/commands/shell_plus.py", line 282, in run_ipython
    start_ipython(argv=ipython_arguments, user_ns=imported_objects)
  File ".../lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File ".../lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File ".../lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File ".../lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File ".../lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File ".../lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File ".../lib/python3.5/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File ".../lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 92, in run
    self.add_reader(stdin, read_from_stdin)
  File ".../lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 280, in add_reader
    self.selector.register(fd)
  File ".../lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 75, in register
    sel.register(fd)
  File ".../lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 130, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/selectors.py", line 525, in register
    kev = select.kevent(key.fd, select.KQ_FILTER_READ,
AttributeError: module 'select' has no attribute 'kevent'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by takluyver** [comment]
I see that [locust uses gevent](https://github.com/locustio/locust/blob/master/locust/core.py), and here's a [similar but different issue filed on gevent](https://github.com/gevent/gevent/issues/446). So my guess would be that this is gevent casually [breaking the standard library](https://github.com/gevent/gevent/blob/8412311e9b29c3317941a5306176faf535f6f4b1/src/gevent/monkey.py#L494).

**Comment by jeffwidman** [comment]
Gevent's actually done some improvements here beyond the fix you linked to: 
https://github.com/gevent/gevent/issues/591
https://github.com/gevent/gevent/issues/835

What version of gevent are you using?

**Comment by orikey0** [comment]
I'd just try to upgrade my Ipython with cmd : pip install --upgrade ipython .
it's work for me
