### ISSUE TITLE
Missing dependency: scandir

### ISSUE THREAD

**Issue by kbiernat** [ipython/ipython#10262]
I just did a  pip install ipython  on an almost-clean system.
Setup.py seems to be lacking dependency on scandir module

$ ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core import magic_arguments
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/magic_arguments.py", line 60, in <module>
    from IPython.utils.text import dedent
  File "/usr/local/lib/python2.7/dist-packages/IPython/utils/text.py", line 21, in <module>
    from pathlib2 import Path
  File "/usr/local/lib/python2.7/dist-packages/pathlib2.py", line 46, in <module>
    from scandir import scandir as os_scandir
ImportError: No module named scandir

**Comment by takluyver** [comment]
It's not a dependency of ours, but of [pathlib2](https://pypi.python.org/pypi/pathlib2/), which does list it as a dependency. However, the way it lists it may require a relatively new `setuptools` and `pip`. So before installing IPython, try:

```
pip install --upgrade setuptools pip
```

**Comment by kbiernat** [comment]
I believe I did that just before installing.
Anyway, I just tried it in a clean ubuntu container and it worked fine.
Thank you.
