### ISSUE TITLE
Hinting (?) for string literal methods

### ISSUE THREAD

**Issue by karolciba** [ipython/ipython#10298]
In [7]: "".replace
Out[7]: <function replace>

In [8]: "".replace?
Object `replace` not found.

In [9]: "".replace?
Traceback (most recent call last):
  File "/home/karolc/.pyenv/versions/2.7.13/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/home/karolc/.pyenv/versions/2.7.13/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by karolciba** [comment]
Duplicate https://github.com/ipython/ipython/issues/10289
