### ISSUE TITLE
Magic %run fails to re-evaluate file

### ISSUE THREAD

**Issue by cdosborn** [ipython/ipython#10297]
### Problem
Multiple occurrences of `%run` fail to pickup changes in the underlying file.

### Test case
Install `ipython` and `celery`:
```
pip install celery==3.1.23 ipython==5.1.0
```

Create a file `input.py`
```
cat <<EOF > input.py
from celery import task

@task
def t2():
    raise "haylp"

t2()
EOF
```
Start ipython and perform the following `run` call:
```
%run input.py
```
You should see a traceback containing: `TypeError: exceptions must be old-style classes or derived from BaseException, not str`

Keep that session open and in another terminal overwrite `input.py`:
```
cat <<EOF > input.py
from celery import task

@task
def t2():
    raise Exception("haylp")

t2()
EOF
```

Switch pack to your open `ipython` session, and run:
```
%run input.py
```

**IPython displays the proper file in it's traceback, but the error in the traceback is from the old file.**

The file is not getting re-evaluated correctly.

I did a little exploring and found that the issue is related to something specific to the `celery` decorator. I could not replicate it without `celery`.

### Version
```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/opt/env/atmo/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-106-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/opt/env/atmo/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Oct 26 2016, 20:30:19) \n[GCC 4.8.4]'}
```

**Comment by Carreau** [comment]
That's not an IPython thing, that's a celery thing:
```
>>> from celery import task
>>>
>>> @task
... def t2():
...     raise "haylp"
...
>>> t2()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bussonniermatthias/anaconda/envs/36/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/bussonniermatthias/anaconda/envs/36/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "<stdin>", line 3, in t2
TypeError: exceptions must derive from BaseException
>>> @task
... def t2():
...     raise Exception("haylp")
...
>>> t2()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bussonniermatthias/anaconda/envs/36/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/bussonniermatthias/anaconda/envs/36/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "<stdin>", line 3, in t2
TypeError: exceptions must derive from BaseException
```

It seem you can't reuse the same task name. Rename to t3 and it works. 
It celery have state, you need to clear its state.

Try your example without `@task`, and it work as expected.  So I don't think we can do anything.

**Comment by cdosborn** [comment]
Hrm, I didn't consider that. Thanks for your time.
