### ISSUE TITLE
IPython 5.2.2 crash in prompt_toolkit

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#10339]
Current IPython (5.2.2, pip -U updated) crashes console on expression:

```python
sim.robots[0].move?
```

Here is the full trace:

```shell
$ ipython3 -i jyro/simulator/simulation.py 
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: sim.robots[0].move
Out[1]: <bound method Robot.move of <jyro.simulator.robot.Pioneer object at 0x7fabc40fd390>>

In [2]: sim.robots[0].move?
Object `move` not found.

In [3]: sim.robots[0].move?                                                     
Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.5/dist-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
$ [back to shell!]
```

Looking at move, there are no non-dunder methods:

```python
In [1]: dir(sim.robots[0].move)
Out[1]: 
['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']
```

**Comment by takluyver** [comment]
Thanks, this should be fixed in 5.3 soon. In the meantime, downgrading prompt_toolkit to < 1.0.10 should work around the issue.

**Comment by dsblank** [comment]
Oh, sorry to report a known issue. It would be great if there were a short status page that had information on the current state of the major projects where known downgrades were advised. Thanks for the info!

**Comment by dsblank** [comment]
This indeed "fixed" the issue (eg, doesn't crash):

pip install prompt_toolkit==1.0.9

**Comment by takluyver** [comment]
5.3 is now out, so you should be able to upgrade again.
