### ISSUE TITLE
Getting help (?) on expression crashes the session

### ISSUE THREAD

**Issue by jorisvandenbossche** [ipython/ipython#10348]
With the latest IPython, if you do something like (both are cases where you type `?` after an 'expression' or something that has to be evaluated first):

```
In [1]: d = {'a': 'str'}
In [2]: d['a'].capitalize?
```

or 

```
In [1]: import os
In [2]: d = os.listdir?
```

the session crashes:

```
(dev) joris@joris-XPS-13-9350:~/scipy$ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: d = {'a': 'str'}

In [2]: d['a'].capitalize?
Object `capitalize` not found.

In [3]: d['a'].capitalize?                                                                                                                                                                                  
Traceback (most recent call last):
  File "/home/joris/miniconda3/envs/dev/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/home/joris/miniconda3/envs/dev/lib/python3.5/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

(dev) joris@joris-XPS-13-9350:~/scipy$
```

To clarify, the `In [3] ..` I didn't type myself (I typed up to `In [2]`), and is also greyed out. 

Up to IPython 5.1, this just gave only the "Object `capitalize` not found." without crashing the session. So apparently a regression in IPython 5.2

Using IPython 5.2.2 and prompt_toolkit 1.0.13, both from conda-forge.

**Comment by takluyver** [comment]
That's not the latest IPython! 5.3.0 is the latest IPython.  ;-) I made the release to fix this bug, which came about when prompt_toolkit 1.0.10 changed some stuff.

We need to update conda-forge, though...

**Comment by takluyver** [comment]
I've made a PR to update it on conda-forge (conda-forge/ipython-feedstock#28), but it usually takes hours to days for the OSX builds to run before the PR will be merged.

In the meantime, you can either update IPython to 5.3.0 using pip, or downgrade prompt_toolkit to 1.0.9.

**Comment by jorisvandenbossche** [comment]
Aha :-) has there been a release announcement on the list yet?

(it's not that important, as you normally don't do that, so I can wait until conda-forge is updated)

**Comment by jorisvandenbossche** [comment]
And I see now that I should have looked in the reported issues first ... there were already multiple :-)

**Comment by takluyver** [comment]
I haven't announced it. We've got so many packages now, I get release fatigue a bit.

We were lucky with the Travis builds today; I've merged the PR, so the new version should appear soon.
