### ISSUE TITLE
`help list` in ipdb yields AttributeError

### ISSUE THREAD

**Issue by gerritholl** [ipython/ipython#10398]
`help list` results in `AttributeError: 'NoneType' object has no attribute 'rstrip'`, as shown below.  I [raised it with `ipdb`](https://github.com/gotcha/ipdb/issues/127) but I [was directed here](https://github.com/gotcha/ipdb/issues/127#issuecomment-286767440) instead.

```
$ python3.5 -mipdb empty.py
Python are go!
/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/ipdb/__main__.py:73: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'context' in getargspec(Pdb.__init__)[0]:
> /tmp/empty.py(1)<module>()

ipdb> help list
Traceback (most recent call last):
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/ipdb/__main__.py", line 168, in main
    pdb._runscript(mainpyfile)
  File "/home/users/gholl/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/home/users/gholl/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/tmp/empty.py", line 1, in <module>
  File "/tmp/empty.py", line 1, in <module>
  File "/home/users/gholl/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/users/gholl/lib/python3.5/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/home/users/gholl/lib/python3.5/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/IPython/core/debugger.py", line 255, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/users/gholl/lib/python3.5/pdb.py", line 346, in interaction
    self._cmdloop()
  File "/home/users/gholl/lib/python3.5/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 69, in cmdloop
    stop = self.onecmd(line)
  File "/home/users/gholl/lib/python3.5/pdb.py", line 412, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/home/users/gholl/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/users/gholl/lib/python3.5/pdb.py", line 1473, in do_help
    self.message(command.__doc__.rstrip())
AttributeError: 'NoneType' object has no attribute 'rstrip'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/users/gholl/lib/python3.5/pdb.py(1473)do_help()
   1471                            'if you need command help' % arg)
   1472                 return
-> 1473             self.message(command.__doc__.rstrip())
   1474 
   1475     do_h = do_help

```

**Comment by takluyver** [comment]
Thanks, looks like there were a couple of docstrings missing that should be there. See #10399 .
