### ISSUE TITLE
There is no current wx.App object - creating one now.

### ISSUE THREAD

**Issue by iqbalhabibie** [ipython/ipython#10401]
I am using python 2.7.13 and running hypercube from spectral http://www.spectralpython.net/#, but I cant run this app because there is some bug or error. Please help me to solve it.

C:\Python2.7.13>ipython --pylab=wx
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from spectral import *

In [2]: data = open_image('92AV3C.lan').load()

In [3]: gt = open_image('92AV3GT.GIS').read_band(0)

In [4]: pc = principal_components(data)

In [5]: xdata = pc.transform(data)

In [6]: w = view_nd(xdata[:,:,:15], classes=gt)
c:\python2.7.13\lib\site-packages\spectral\graphics\graphics.py:789: UserWarning:
There is no current wx.App object - creating one now.
  UserWarning)

In [7]:
Traceback (most recent call last):
  File "C:\Python2.7.13\Scripts\ipython-script.py", line 11, in <module>
    load_entry_point('ipython==5.3.0', 'console_scripts', 'ipython')()
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python2.7.13\lib\site-packages\traitlets-4.3.2-py2.7.egg\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\ipapp.py", line 348, in start
    self.shell.mainloop()
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\interactiveshell.py", line 486, in mainloop
    self.interact()
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\interactiveshell.py", line 469, in interact
    code = self.prompt_for_code()
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\interactiveshell.py", line 363, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "build\bdist.win32\egg\prompt_toolkit\interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "build\bdist.win32\egg\prompt_toolkit\eventloop\win32.py", line 66, in run
    self._inputhook_context.call_inputhook(ready)
  File "build\bdist.win32\egg\prompt_toolkit\eventloop\inputhook.py", line 74, in call_inputhook
    self.inputhook(self)
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\interactiveshell.py", line 501, in inputhook
    self._inputhook(context)
  File "c:\python2.7.13\lib\site-packages\ipython-5.3.0-py2.7.egg\IPython\terminal\pt_inputhooks\wx.py", line 99, in inputhook_wx3
    assert wx.Thread_IsMain()
AttributeError: 'module' object has no attribute 'Thread_IsMain'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by jaredl7** [comment]
@patrickcgray: I'm using IPython 6.2.1 but I believe a fix I found should work for your version as well: https://github.com/ipython/ipython/issues/10055#issuecomment-365521238
