### ISSUE TITLE
Introspection / crashing with AssertionError on inspection with conditional

### ISSUE THREAD

**Issue by tucobenedicto** [ipython/ipython#10418]
Hi,
I ran into the following while typing a question mark instead of a colon to get:
`if var?`
Resulted in an AssertionError and crashed my iPython.
I realize this isn't a condition that you should ever really actually check for any reason, but thought I would come here to report it in case it's an unintended side effect.
If the behavior is correct, feel free to close the issue.
Thanks for all your work and let me know if there's any way I can help.
```
Python 2.7.6 (default, Oct 26 2016, 20:32:47) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: var=''

In [2]: if var?
Type:        str
String form: 
Length:      0
Docstring:  
str(object='') -> string

Return a nice string representation of the object.
If the argument is a string, the return value is the same object.

In [3]: if var?                                                                                                                                                                      
Traceback (most recent call last):
  File "/home/vagrant/afterxmas/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/home/vagrant/afterxmas/local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError
```

**Comment by takluyver** [comment]
Should be fixed if you upgrade to IPython 5.3. If you can't do that for some reason, you'll need to downgrade prompt_toolkit to... 1.0.8, I think it was.
