### ISSUE TITLE
Builds Installing IPython Fail in Travis on 2.7 and 3.4

### ISSUE THREAD

**Issue by naftulikay** [ipython/ipython#10420]
I have [the following build](https://travis-ci.org/naftulikay/aws-env/builds/216454874) which uses Buildout to install IPython for local introspection.

My [buildout.cfg](https://github.com/naftulikay/aws-env/blob/master/buildout.cfg) installs the latest IPython:

```
[buildout]
parts = python ipython test
develop = .
eggs = awsenv
versions = versions

[versions]
# blank for now

[python]
recipe = zc.recipe.egg
interpreter = python
eggs = ${buildout:eggs}

[test]
recipe = pbp.recipe.noserunner
eggs = ${buildout:eggs}
    pbp.recipe.noserunner
script = test

[ipython]
recipe = zc.recipe.egg:scripts
eggs = ${buildout:eggs}
    ipython
scripts = ipython
```

This works fine locally on CentOS 7 with Python 3.4, but fails [remotely in Travis](https://travis-ci.org/naftulikay/aws-env/jobs/216454877#L173):

```
Installing ipython.
Getting distribution for 'ipython'.
error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"
An error occurred when trying to install /tmp/tmprLOC_8get_dist/ipython-5.3.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing ipython.
  Getting distribution for 'ipython'.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 1982, in main
    getattr(buildout, command)(args)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 668, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 1419, in _call
    return f()
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
```

I'm not sure what's causing the problem, but I can only run my builds on Python 3.5 on Travis, and only Python 3.4 and 3.5 locally. Is there something that I'm missing that I need to do to get this building on 2.7, 3.4, and 3.5?

**Comment by Carreau** [comment]
I don't know of anyone using buildout to distribute IPython, and haven't used it myself. It seem like the UNPACKER unpack nothing in `tmp_dest`, so it is likely a buildout issue that should detect this. I'm unsure what can go wrong.

**Comment by willingc** [comment]
This looks like it is failing on build on Travis:

```
python_version >= "3.4"
```

Make sure that you have `typing` installed in your build script recipe when running `python<=3.4`
https://github.com/ipython/ipython/blob/master/setup.py#L220

**Comment by naftulikay** [comment]
@Carreau it's not so much distributing IPython as providing IPython as a utility for messing around within a project. 

@willingc I'm going to try that out.

**Comment by naftulikay** [comment]
@willingc that apparently still did not fix it on < 3.5: 

```
Got typing 3.6.1.
Getting distribution for 'ipython'.
error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"
An error occurred when trying to install /tmp/tmp1Vu4Ayget_dist/ipython-5.3.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing ipython.
  Getting distribution for 'ipython'.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/travis/build/naftulikay/aws-env/eggs/zc.buildout-2.9.3-py2.7.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
```

https://travis-ci.org/naftulikay/aws-env/jobs/218298353

It's kind of strange that this happens in Travis but not on local CentOS 7.3 with Python 3.4.

**Comment by willingc** [comment]
This line in the error log concerns me:
```
Error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"
```
Are you sure that you have the buildout environments correct for CentOS and have valid POSIX paths?

Also, we don't use buildout so you may have more success asking on buildout help. Thanks!

**Comment by naftulikay** [comment]
This is really weird because it's running in _Travis CI_. On my local dev machine, it works flawlessly on Python 3.4. There must be something wrong in the Travis environment. Do you have any idea what I should test for?

**Comment by willingc** [comment]
I don't sorry. I would look at the buildout project and other repos using it to see how they have their `travis.yml` set up.  Also the docs for Travis are pretty good too.

I'm going to go ahead and close this since I don't think that this is an IPython issue. Good luck @naftulikay!

**Comment by naftulikay** [comment]
okay, thanks for looking into it anyway!

**Comment by Carreau** [comment]
> Error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"

Ah Good cath @willingc  ! Then pip is out of date ! Travis have `6.0.something`, and we **really strongly encourage** to have 9+
try to add a `pip install pip --upgrade` in your `travis.yml`

**Comment by Carreau** [comment]
> and we **really strongly encourage** to have pip  9+

Read in that: installing IPython 6.0 **will break on Python 2** if you have pip < 9.

**Comment by naftulikay** [comment]
For all interested, I had to [do the following]() to get things working:

```yaml
---
dist: trusty
sudo: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

cache:
  pip: true
  directories:
  - eggs/

before_install:
  - pip install --upgrade pip

install:
  - pip --version
  - python bootstrap.py
  - bin/buildout

script: bin/test

notifications:
  email:
    on_success: change
    on_failure: always
```

**Comment by willingc** [comment]
@naftulikay Glad you got it working. And thanks for sharing how you solved it!

**Comment by naftulikay** [comment]
@willingc Not a problem! Thanks for all your help. I am unfortunately quite perplexed at this, as this is the second time that changing the same thing over to their "beta" `trusty` image just fixed a Python project.
