### ISSUE TITLE
unable to import path

### ISSUE THREAD

**Issue by RaymondDavidson** [ipython/ipython#10452]
no file in /usr/lib/python2.7/dist-packages/IPython/utilsis able to execute

``` 
from IPython.external.path import path as Path
```

i get 
```
Traceback (most recent call last):
  File "/usr/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 33, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 70, in <module>
    from IPython.utils.pickleshare import PickleShareDB
  File "/usr/lib/python2.7/dist-packages/IPython/utils/pickleshare.py", line 37, in <module>
    from IPython.external.path import path as Path
ImportError: cannot import name path
```

when running 
```
python -m IPython
```
i get
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/usr/lib/python2.7/dist-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 32, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 32, in <module>
    from .loader import Config, LazyConfigValue
  File "/usr/lib/python2.7/dist-packages/IPython/config/loader.py", line 34, in <module>
    from IPython.utils.path import filefind, get_ipython_dir
  File "/usr/lib/python2.7/dist-packages/IPython/utils/path.py", line 22, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "io.py", line 26, in <module>
    from .capture import CapturedIO, capture_output
ValueError: Attempted relative import in non-package
```

**Comment by RaymondDavidson** [comment]
added extra info

**Comment by Carreau** [comment]
Which version of IPython are you using ? IPython.external.path has been removed about 4 years ago. 

What is the content of your current working directory? And how did you install ipython ?

**Comment by RaymondDavidson** [comment]
i used apt

**Comment by RaymondDavidson** [comment]
sudo apt install ipython -y

**Comment by RaymondDavidson** [comment]
i just tried 
```
sudo apt install --upgrade ipython -y
```

**Comment by RaymondDavidson** [comment]
no effect

**Comment by Carreau** [comment]
Which folder are you running this from ? And did you recently did a `sudo pip install` (or do you never use pip ?). Because this look like you have a partial install (or a mix install) from error 1, and running for a  folder that may have Python files in it from error 2.

**Comment by RaymondDavidson** [comment]
how do i fix the sudo pip install

**Comment by RaymondDavidson** [comment]
thing

**Comment by Carreau** [comment]
> how do i fix the sudo pip install

If you did use that, that's going to be a mess. 
You basically overwrote system packages with non-system ones and apt-get will be really-unhappy. 
I would suggest forcibly uninstall IPython using apt-get, make sure there are no remaining py ,or pyc files left and then reinstall using apt-get. But that's only if you did use `sudo pip` If you did not we should find the root reason of this.

**Comment by takluyver** [comment]
- Avoid installing the same packages with different package systems, unless one of them is installing into a separate environment or container.
- If you have installed the same package from multiple package managers, the usual fix is to uninstall it using all of them, and then reinstall it with just one.
- Installing IPython from apt often gets you a badly out of date version.

**Comment by davidlowryduda** [comment]
Is there anything left to be resolved in this issue, or perhaps it can be closed now?

**Comment by Pierrocana** [comment]
I encontered the same issue. 
`sudo apt-get install --reinstall python-pip` solved it.

**Comment by MrMino** [comment]
I don't think there's anything relevant to be added here. If anyone disagrees, please don't hesitate to ping us, we'll reopen this issue.
