### ISSUE TITLE
MultipleInstanceError errors for IPython with Scrapy Inspect_Response in second-level crawls

### ISSUE THREAD

**Issue by roablep** [ipython/ipython#10486]
I'm getting acquainted with Scrapy and heavily relying on the interactive debugger, `inspect_response()`. 

I'm starting by scraping events off a calendar. Step 1 is to get the overview, step 2 is to get the details:

    |-- Calendar List Page
    |   `-- Calendar Event Details Page

Here is my implementation:

    class QuotesSpider(scrapy.Spider):
        name = "my first spider"
    
        def start_requests(self):
            urls = ['https://www.ticketfly.com/venue/7337-output/']
            for url in urls:
                yield scrapy.Request(url=url, callback=self.parse_overview)
    
        def parse_overview(self, response):
            for event in response.css('.list-view-item'):
                # This works fine: inspect_response(response, self)
                details = event.css('span.ticket-link.primary-link a::attr(href)').extract_first()
    
                if details is not None:
                  yield scrapy.Request(response.urljoin(details),
                                       callback=self.parse_url)
    
        def parse_url(self, response):
            inspect_response(response, self) # This breaks

`inspect_response()` works fine on in step 1, but fails in step 2:

    2017-04-22 10:30:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.ticketfly.com/purchase/event/1465896/tfly> (referer: https://www.ticketfly.com/venue/7337-output/)
    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/Users/me/test/scrapy/test/test/spiders/my_spider.py", line 37, in parse_url
        inspect_response(response, self)
      File "//anaconda/lib/python2.7/site-packages/scrapy/shell.py", line 167, in inspect_response
        Shell(spider.crawler).start(response=response)
      File "//anaconda/lib/python2.7/site-packages/scrapy/shell.py", line 81, in start
        banner=self.vars.pop('banner', ''))
      File "//anaconda/lib/python2.7/site-packages/scrapy/utils/console.py", line 82, in start_python_console
        shell(namespace=namespace, banner=banner)
      File "//anaconda/lib/python2.7/site-packages/scrapy/utils/console.py", line 22, in wrapper
        banner1=banner, user_ns=namespace, config=config)
      File "//anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 416, in instance
        '%s are being created.' % cls.__name__
    MultipleInstanceError: Multiple incompatible subclass instances of InteractiveShellEmbed are being created.
    2017-04-22 10:30:47 [root] DEBUG: Using default logger
    2017-04-22 10:30:47 [root] DEBUG: Using default logger
    2017-04-22 10:30:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.ticketfly.com/purchase/event/1457966/tfly> (referer: https://www.ticketfly.com/venue/7337-output/)
    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/Users/me/test/scrapy/test/test/spiders/my_spider.py", line 37, in parse_url
        inspect_response(response, self)
      File "//anaconda/lib/python2.7/site-packages/scrapy/shell.py", line 167, in inspect_response
        Shell(spider.crawler).start(response=response)
      File "//anaconda/lib/python2.7/site-packages/scrapy/shell.py", line 81, in start
        banner=self.vars.pop('banner', ''))
      File "//anaconda/lib/python2.7/site-packages/scrapy/utils/console.py", line 82, in start_python_console
        shell(namespace=namespace, banner=banner)
      File "//anaconda/lib/python2.7/site-packages/scrapy/utils/console.py", line 22, in wrapper
        banner1=banner, user_ns=namespace, config=config)
      File "//anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 416, in instance
        '%s are being created.' % cls.__name__
    MultipleInstanceError: Multiple incompatible subclass instances of InteractiveShellEmbed are being created.

This issue does NOT occur if I use bpython or python interactive shell (setting `shell = python` in `scrapy.cfg`)

**Comment by takluyver** [comment]
I think this is probably a bug in scrapy - they appear to have had some trouble with embedding IPython before (e.g. scrapy/scrapy#2418). So you may want to report it to them, but feel free to put them in touch with us to help work the issue out. And don't forget to mention what IPython and scrapy versions are involved!

**Comment by Carreau** [comment]
I don't think there is anything we can do for now, and IIRC there is still an issue tracking the abulity to have many instances of InteractiveShellEmbed, so closing here, we can still reopen if needed and feel free to keep commenting.
