### ISSUE TITLE
autoreload of __mp_main__ failed when running script

### ISSUE THREAD

**Issue by lukepfister** [ipython/ipython#10522]
This is a continuation of #8564.  After modifying a script, re-running it produces the following error:
```python
In [2]: run foo
[autoreload of __mp_main__ failed: Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/nsp2/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
AttributeError: module has no attribute '__name__'
]
```
This occurs when using both `%autoreload 2` and `c.InteractiveShell.deep_reload = True`.

The merged fix, #8568, hasn't improved the issue for me.  I've had a local workaround for a while:  see my comment [here](https://github.com/ipython/ipython/issues/8564#issuecomment-150321942).  I'll submit a pull request shortly.

System information:
```
python -c "import IPython; print(IPython.sys_info())"

{'commit_hash': '5a894b9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/luke/software/python/miniconda/envs/nsp2/lib/python3.6/site-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-4.8.0-34-generic-x86_64-with-debian-stretch-sid',
 'sys_executable': '/home/luke/software/python/miniconda/envs/nsp2/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, '
                '12:22:00) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

**Comment by felipegb94** [comment]
I am still getting a similar issue as the one described above even with #10523 . I get the following error:

```
[autoreload of __mp_main__ failed: Traceback (most recent call last):
  File "/home/felipe/anaconda3/envs/cvxenv/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/felipe/anaconda3/envs/cvxenv/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 349, in superreload
    if not hasattr(obj, '__module__') or obj.__module__ != module.__name__:
AttributeError: module has no attribute '__name__'
]
```

This happens when loading a third-party library as I comment and uncomment the following import statement:

```
import cvxpy as cvx
```

My current IPython setup is:

```
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/felipe/anaconda3/envs/cvxenv/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-89-generic-x86_64-with-debian-stretch-sid',
 'sys_executable': '/home/felipe/anaconda3/envs/cvxenv/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, '
                '13:51:32) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

**Comment by lukepfister** [comment]
I still get this occasionally as well, but very intermittently.  The fix in
#10523 apparently insufficient.  Try the fix outlined at

https://github.com/ipython/ipython/issues/8564#issuecomment-150321942
