### ISSUE TITLE
Tab Completion Failed in Python 6.0.0 

### ISSUE THREAD

**Issue by gerdm** [ipython/ipython#10560]
I have a problem while trying to do a tab completion in IPython. Specifically, if I write
`from sci<tab>`
then this error appears
```Python 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sciUnhandled exception in thread started by <bound method Thread._bootstrap of <Thread(
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/IPython/core/application.py", line 256, 
    return crashhandler.crash_handler_lite(etype, evalue, tb)
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/IPython/core/crashhandler.py", line 205,
    traceback.print_exception(etype, evalue, tb)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/Users/gerardo/anaconda/lib/python3.5/traceback.py", line 463, in __init__```
```

After it repeats many more times, the following appears:
```
 Original exception was:
Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 39
    return _loaded_grammars[path]
KeyError: '/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/grammar3.5.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 42
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gerardo/anaconda/lib/python3.5/site-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 39
    return _loaded_grammars[path]
KeyError: '/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 42
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gerardo/anaconda/lib/python3.5/site-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 39
    return _loaded_grammars[path]
KeyError: '/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 42
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gerardo/anaconda/lib/python3.5/site-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 39
    return _loaded_grammars[path]
KeyError: '/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 42
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gerardo/anaconda/lib/python3.5/site-

During handling of the above exception, another exception occurred:
```

Finally, the following appears:
```

Traceback (most recent call last):
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 48
    return load_grammar()
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 48
    return load_grammar()
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 48
    return load_grammar()
  File "/Users/gerardo/anaconda/lib/python3.5/site-packages/jedi/parser/python/__init__.py", line 48
    return load_grammar()
```

Again repeating over and over again
What could be the problem? I'm not sure how to try to fix this.

Thanks in advance!

**Comment by gerdm** [comment]
I momentarily fixed it by downgrading to IPython 5.3.0; still not sure what the problem is

**Comment by cottrell** [comment]
Are you using conda to install? I haven't found the real cause yet but in both a 3.5 and 3.6 env if "conda uninstall ipython && pip install ipython" the problem goes away.

**Comment by moskomule** [comment]
I'm using Python3.6.1 with Anaconda and after upgrading iPython to 6.0.0 using `conda`, I got a similar error with tab completion. Which says,

```
In [1]: import pandas as pd

In [2]: raw_data = pd.reUnhandled exception in thread started by <bound method >
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/USER/anaconda/lib/python3.6/site-packages/IPython/core/applicatk
    return crashhandler.crash_handler_lite(etype, evalue, tb)
  File "/Users/USER/anaconda/lib/python3.6/site-packages/IPython/core/crashhane
    traceback.print_exception(etype, evalue, tb)
  File "/Users/USER/anaconda/lib/python3.6/traceback.py", line 100, in print_en
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/Users/USER/anaconda/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  File "/Users/USER/anaconda/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  File "/Users/USER/anaconda/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  [Previous line repeated 494 more times]
RecursionError: maximum recursion depth exceeded
```

And of course when using Jupyter, you cannot use tab completion because of this error. When you press tab key then the kernel stops.

**Comment by mingwandroid** [comment]
Can you try `conda update jedi` please?

**Comment by gerdm** [comment]
Sure, 
this is what comes up:

```
# All requested packages already installed.
# packages in environment at /Users/gerardo/anaconda:
#
jedi                      0.10.2                   py35_0  
```

**Comment by mingwandroid** [comment]
Yeah, we are missing the grammar*.txt files here, not sure why, I've assigned the bug over at https://github.com/ContinuumIO/anaconda-issues/issues/1725 to myself.

**Comment by Carreau** [comment]
Thanks for digging into that, you might be able to install [jedi from conda-forge](https://github.com/conda-forge/jedi-feedstock) in the meantime.

**Comment by moskomule** [comment]
@mingwandroid Thank you. There was an update: `jedi:0.10.2-py36_1 --> 0.10.2-py36_2`.
After updating, everything is all right. No error occurs with tab completion.

**Comment by gerdm** [comment]
No errors and now it is working.

Thank you!

**Comment by johnsonice** [comment]
@mingwandroid  Thanks. fixed

**Comment by mingwandroid** [comment]
Great. Thanks for the feedback.
