### ISSUE TITLE
ipython notebook "ImportError: No module named ssl_match_hostname" after recent scipy pip installation

### ISSUE THREAD

**Issue by robb-chemist** [ipython/ipython#10579]
I went to install scypy through pip

`pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose`

and when I went to load ipython notebook, I now get an error:

```
Traceback (most recent call last):
  File "/home/rmann34/yt-x86_64/bin/ipython", line 5, in <module>
    start_ipython()
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/config/application.py", line 406, in initialize_subcommand
    subapp = import_item(subapp)
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 62, in <module>
    from tornado import httpserver
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-x86_64.egg/tornado/http1connection.py", line 30, in <module>
    from tornado import iostream
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-x86_64.egg/tornado/iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError
  File "/home/rmann34/yt-x86_64/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-x86_64.egg/tornado/netutil.py", line 44, in <module>
    import backports.ssl_match_hostname
ImportError: No module named ssl_match_hostname
```

I've tried other solutions suggested such as 

`pip install backports.ssl_match_hostname`

but:

`Requirement already satisfied: backports.ssl_match_hostname in ./yt-x86_64/lib/python2.7/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg`

I am using Ubuntu 12.04 LTS

**Comment by takluyver** [comment]
Namespace packages strike again. :angry: 

We're up to 80 comments on #9815 trying to work out issues with another `backports` package. We haven't been able to get much further than 'uninstall and reinstall stuff until it works'.

**Comment by victormm88** [comment]
try `pip install tornado` or  `pip install --upgrade tornado`
I've solved this on macOs
