### ISSUE TITLE
method? AssertionError cursor_position

### ISSUE THREAD

**Issue by rgom** [ipython/ipython#10584]
When executing ? for particular line of code the following assertion is raised:

>>> IdentityCommon(ch)[1].svc.get_attribute_list?
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_i
python
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 658
, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in s
tart
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 455, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 438, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 408, in
 run
    self._pre_run(pre_run)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 383, in
 _pre_run
    pre_run()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "c:\python27\lib\site-packages\prompt_toolkit\buffer.py", line 371, in te
xt
    assert self.cursor_position <= len(value)
AssertionError

The code for which I see the problem is proprietary, so I can't share it.

Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.

os.path? works fine

Regards,
Robert

**Comment by takluyver** [comment]
Upgrading IPython to 5.3 should fix it.

**Comment by rgom** [comment]
Confirmed, it helped.
Feel free to close the ticket.

Best regards,
Robert

**Comment by takluyver** [comment]
Already  did ;-)
