### ISSUE TITLE
Cannot launch Ipython3. OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by KHN190** [ipython/ipython#10602]
```
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:                                                                                                                                               
Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.5/dist-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/ipapp.py", line 353, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 459, in mainloop
    self.interact()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 442, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 355, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py", line 411, in run
    with self.input.raw_mode():
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/terminal/vt100_input.py", line 473, in __enter__
    os.write(self.fileno, b'\x1b[?1l')
OSError: [Errno 9] Bad file descriptor

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by takluyver** [comment]
What platform are you on? Is there anything unusual about how you launch it? Do you use an unusual terminal emulator or shell or anything?

Ping @jonathanslenders - any idea how the error above might come about?

**Comment by KHN190** [comment]
@takluyver Ubuntu 16.04, launched normally from command line with  `ipython3`
Weirdly I can't reproduce the problem. So I have no clue.

**Comment by takluyver** [comment]
Bizarre. I'm using Ubuntu 16.04 as well. I'll leave it open for a bit in case we work anything out, but if we can't reproduce it, we may have to say it was a one-off.

**Comment by malthejorgensen** [comment]
This happened to me on OS X 10.12.6 in a long lived `tmux` tab. I use `fish` as my shell. Starting the iPython REPL in any of the other tabs in the same `tmux` session worked.
Reconnecting to the session and trying in the same tab still gave the same error.

In my case I believe, something happened to that particular `fish` session.

**Comment by refi64** [comment]
I actually think this is an IPython bug. Here's what I've found:

In many cases, stdout and stdin both are pointing to the same PTY device, so if they're open as read-write, writing to stdin is actually writing to stdout, and reading from stdout is actually reading from stdin. You can observe this by running: `os.write(0, b'test\n')` in Python: it'll write to the same PTY.

However, according to [the posix standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stdin.html), nothing is mentioned about stdin being writable or stdout being readable. (It *does* say that stderr must be rw.)

Thus, in this case, I think IPython could get identical behavior by writing to stdout instead. In theory this would differ if stdin were a tty and stdout were a different one, but tbh I've never seen that before, and I'm not sure what exactly would be going on there or what type of behavior would even be expected.
