### ISSUE TITLE
AutoComplete crashes and ceases to work when trying to complete a filename with underscores located in a sibling to pwd.

### ISSUE THREAD

**Issue by Michael-F-Ellis** [ipython/ipython#10626]
**I can reproduce from the command line as follows:**
```
~ mellis$ mkdir Test1
~ mellis$ mkdir Test2
~ mellis$ touch Test2/foobar.py
~ mellis$ touch Test2/namehas_underscore.py
~ mellis$ cd Test1/
Test1 mellis$ ipython
/Users/mellis/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:431: UserWarning: As of IPython 5.0 `PromptManager` config will have no effect and has been replaced by TerminalInteractiveShell.prompts_class
  warn('As of IPython 5.0 `PromptManager` config will have no effect'
Python 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ## can use completion to list foobar.py in sibling directory

In [2]: ls ../Test2/foobar.py
../Test2/foobar.py

In [3]: ## crash when trying to complete namehas_underscore.py

In [4]: ls ../Test2/nameException in thread Thread-462:
Traceback (most recent call last):
  File "/Users/mellis/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/mellis/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 860, in r
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 75, in ge
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 115, in _
    yield Completion(c.text, start_position=c.start - offset, display=_elide(display_text), display_meta
  File "/Users/mellis/anaconda3/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 39, in _e
    return '{}.{}\N{HORIZONTAL ELLIPSIS}{}.{}'.format(parts[0], parts[1][0], parts[-2][-1], parts[-1])
IndexError: string index out of range

In [4]: ls ../Test2/name
ls: ../Test2/name: No such file or directory

In [5]: ## after the crash, completion ceases to work at all.
```
**Here's my IPython sys_info:**
```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '51ce9d73b',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/mellis/anaconda3/lib/python3.5/site-packages/IPython',
 'ipython_version': '6.0.0',
 'os_name': 'posix',
 'platform': 'Darwin-15.6.0-x86_64-i386-64bit',
 'sys_executable': '/Users/mellis/anaconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, '
                '12:15:08) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'}
```

**Comment by takluyver** [comment]
@Carreau do I recall that this is something you already fixed? Is it just waiting for 6.1?

**Comment by Carreau** [comment]
Yes, it should. I'll try to release in a few hours.

**Comment by Michael-F-Ellis** [comment]
6.1.0 fixes it for me. Thanks!
