### ISSUE TITLE
KeyError: 'prompts'

### ISSUE THREAD

**Issue by flrgsr** [ipython/ipython#10690]
I wanted to start ipython3 this morning and was greeted with this nasty welcome:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 490, in get
    value = obj._trait_values[self.name]
KeyError: 'prompts'
```

```
ipython3 --version                                                                                                                                              
6.1.0
python3 --version
Python 3.6.1
```

full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 490, in get
    value = obj._trait_values[self.name]
KeyError: 'prompts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/config/application.py", line 830, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/config/application.py", line 88, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/config/configurable.py", line 508, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 426, in __init__
    self.init_prompt_toolkit_cli()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 275, in init_prompt_toolkit_cli
    **self._layout_options()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 353, in _layout_options
    'get_prompt_tokens':self.prompts.in_prompt_tokens,
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 525, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 493, in get
    default = obj.trait_defaults(self.name)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 1477, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets/traitlets/traitlets.py", line 928, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 168, in _prompts_default
    return self.prompts_class(self)
  File "/usr/local/lib/python3.6/site-packages/powerline/bindings/ipython/since_5.py", line 62, in __init__
    powerline.do_setup(shell, self, shutdown_hook)
  File "/usr/local/lib/python3.6/site-packages/powerline/bindings/ipython/since_5.py", line 26, in do_setup
    saved_msfn = ip._make_style_from_name
AttributeError: 'TerminalInteractiveShell' object has no attribute '_make_style_from_name'
```

**Comment by flrgsr** [comment]
fix: 

`pip3 install --upgrade powerline-status

**Comment by Carreau** [comment]
From the last frame of the tracebacks, that seem like a bug in powerline.

**Comment by takluyver** [comment]
The last bit is the real exception, and it's coming from the 'powerline' package. It appears to be calling a private method from IPython which has changed. So this is not a bug from our point of view. If the powerline people need better public APIs, they're welcome to ask for them.
