### ISSUE TITLE
Jupyter's kernal dies, restarts and dies again

### ISSUE THREAD

**Issue by tariqkhaleeq** [ipython/ipython#10691]
Hey guys,

I am using a Mac and I have Jupyter installed. The typical way I would run it is type <code>jupyter notebook</code> and connect via localhost and be on my merry way. It was working fine until recently the kernel started crashing. I tried creating a new file, select python[default] and wait for the kernel to connect. It would connect and exactly 1 to 3 secs later report that the kernel has died and needs restarting. It restarts, connects and dies again. This is happening when  there is nothing to execute and the file is completely empty. The same thing happens with a python file aswell.

Is there a fix? I cannot seem to find anything relevant to my scenario.

```
[I 14:41:28.276 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 14:41:28.276 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)
[W 14:41:32.892 NotebookApp] Native kernel (python2) is not available
[W 14:41:33.069 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (::1) 11.36ms referer=None
[W 14:41:33.120 NotebookApp] 404 GET /apple-touch-icon.png (::1) 1.51ms referer=None
[I 14:41:52.588 NotebookApp] Creating new notebook in 
[W 14:41:52.873 NotebookApp] Native kernel (python2) is not available
[I 14:41:53.044 NotebookApp] Kernel started: dc906f7d-e6ff-40af-bad7-259e7bd55061
Traceback (most recent call last):
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
[W 14:41:54.302 NotebookApp] Could not import nbconvert: cannot import name configparser
[E 14:41:54.302 NotebookApp] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "*/*", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python2", 
      "X-Requested-With": "XMLHttpRequest"
    }
[E 14:41:54.303 NotebookApp] 500 GET /api/nbconvert (::1) 1.99ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python2
[I 14:41:56.045 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
[I 14:41:59.054 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
[I 14:42:02.064 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
[W 14:42:03.192 NotebookApp] Timeout waiting for kernel_info reply from dc906f7d-e6ff-40af-bad7-259e7bd55061
[I 14:42:05.074 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel dc906f7d-e6ff-40af-bad7-259e7bd55061 restarted
Traceback (most recent call last):
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/tariqkhaleeq/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
[W 14:42:08.083 NotebookApp] KernelRestarter: restart failed
[W 14:42:08.083 NotebookApp] Kernel dc906f7d-e6ff-40af-bad7-259e7bd55061 died, removing from map.
ERROR:root:kernel dc906f7d-e6ff-40af-bad7-259e7bd55061 restarted failed!
[W 14:42:08.098 NotebookApp] Kernel deleted before session
[W 14:42:08.098 NotebookApp] 410 DELETE /api/sessions/9959c3f0-9703-469e-a6bc-2489c537ce01 (::1) 4.76ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python2
[I 14:43:53.097 NotebookApp] Saving file at /Untitled2.ipynb
```

**Comment by takluyver** [comment]
It's the infamous 'shutil_get_terminal_size' error. Upgrade your IPython to 5.4.1 (the latest version compatible with Python 2), and it should work.

**Comment by tariqkhaleeq** [comment]
@takluyver Thank you so much for pointing me in the right direction! I was still running into the same kernel problem but realized that i had to upgrade ipython using `pip` not `conda` because `conda` (for some reason) upgraded it to `5.3` not `5.4.1`. Running `pip install` resulted in upgrading it to the version you recommended.

Once again thanks alot!

**Comment by takluyver** [comment]
Great :-)
