### ISSUE TITLE
ipdb crashes when builtin AttributeError is redefined

### ISSUE THREAD

**Issue by yoyoyopcp** [ipython/ipython#10735]
```
import __builtin__
import ipdb

class AttributeError(AttributeError):
    pass

__builtin__.AttributeError = AttributeError
```

will crash leaving this output:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/history.py", line 853, in stop
    self.join()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 930, in join
    if self is current_thread():
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1154, in currentThread
    return _DummyThread()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1122, in __init__
    Thread.__init__(self, name=_newname("Dummy-%d"))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 680, in __init__
    self.__started = Event()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 550, in Event
    return _Event(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 563, in __init__
    self.__cond = Condition(Lock())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 253, in Condition
    return _Condition(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 272, in __init__
    self._release_save = lock._release_save
AttributeError: 'thread.lock' object has no attribute '_release_save'
```
Python 2.7.13
ipython==5.4.1
ipdb==0.10.3

**Comment by takluyver** [comment]
I think redefining builtin exception classes is not something we can protect our code against. I would expect all kinds of stuff to break if you start doing that.

**Comment by yoyoyopcp** [comment]
I understand that it's a dangerous pattern, but it doesn't break with pdb, which is why I thought it was a bug.

**Comment by takluyver** [comment]
The more stuff the interface tries to do, the greater the chance it will run into something that's broken. Others might disagree, but I wouldn't consider that a bug.

It's also coming from several levels down inside the threading module, so we can't easily do much about it. I'd guess that something inside threading catches that AttributeError, but it's trying to catch your redefined AttributeError instead of the real one, so the exception escapes.

**Comment by yoyoyopcp** [comment]
After further digging, it seems you were absolutely right. Closing this as Not a Bug--I was foolish to try this and blame ipython for the error.
