### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by winner1986** [ipython/ipython#10779]
C:\Users\lenovo\Desktop\vn.how\performance>ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in fu
ture versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press
 Ctrl-C to quit now.
[I 11:30:33.138 NotebookApp] Serving notebooks from local directory: C:\Users\lenovo\Desktop\vn.how\
performance
[I 11:30:33.138 NotebookApp] 0 active kernels
[I 11:30:33.140 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 11:30:33.141 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to s
kip confirmation).
[I 11:30:33.144 NotebookApp] Shutting down kernels
Traceback (most recent call last):
  File "E:\vnpy\Anaconda2\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(IPython.start_ipython())
  File "E:\vnpy\Anaconda2\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "E:\vnpy\Anaconda2\lib\site-packages\traitlets\config\application.py", line 596, in launch_in
stance
    app.start()
  File "E:\vnpy\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py", line 341, in start
    return self.subapp.start()
  File "E:\vnpy\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1112, in start
    self.io_loop.start()
  File "E:\vnpy\Anaconda2\lib\site-packages\zmq\eventloop\ioloop.py", line 168, in start
    raise e
ZMQError: Unknown error

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by Carreau** [comment]
Hi there, 

1) I would suggest getting used to use `jupyter notebook` instead of `ipython notebook` as the notebook is now separate from ipython. That won't help for your issue though. 

2) ZMQ raises an unknown error, so it's hard to know what's happening. Have you tried uninstalling and reinstalling ZMQ ? How are you install Jupyter/IPython ? pip ? Which Python distribution  ? Conda ? 
Are you on a machine with limited privileges ? If you have an antivirus/firewall can you disable temporarily and retry ?

**Comment by winner1986** [comment]
First, Thank you very much for giving your advises.
Second,My machine is windows8 64-bit and  is not  limited privileges,the antivirus/firewall is disableI all the time,I have reinstalled ZMQ for 3 times ,there is Anaconda on my machine,its distribution is 4.0.0(32-bit),ZMQ maybe is 0.0.0,what the machine shows(pip list,I do not know why),pyzmq is 16.0.2,python is 2.7.13

**Comment by minrk** [comment]
I think this unknown error case occurs when a zmq API call fails, raising ZMQError, but libzmq fails to set an errno (or a weird errno is set or the errno has been consumed somehow before it is retrieved). It's a pretty weird situation to be in and I haven't seen it recently. You can retrieve the errno with `zmq.zmq_errno()`. I would guess that it's zero in this case, though. It might be useful if it's another value, though, so it's a good idea to retrieve it.

**Comment by winner1986** [comment]
what a surprise!  The jupyter notebook can work very well  when I run  the anaconda jupyter notebook shortcut
