### ISSUE TITLE
ipython hangs on input

### ISSUE THREAD

**Issue by enedil** [ipython/ipython#10776]
Hello. My setup:
```
Distributor ID:	Fedora
Release:	25

Python 3.5.3 (default, May 10 2017, 15:05:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

installed from Fedora repos, used from terminal
```

Upon entering expression `2**8**16`, iPython hangs and I can only kill it.

**Comment by takluyver** [comment]
I can't immediately replicate this, but I'd guess that for some reason it was trying to compile the expression - maybe for introspection or completion. Compiling code is usually fast, but there's a corner case with expressions involving only constants and operators which evaluate to very large numbers: Python implements a 'constant folding' optimisation, which means that these expressions are calculated at compile time rather than at run time.

You can see this using the `dis` module to examine the bytecode:

```
 6│ dis.dis(compile('2 ** 8', '<string>', 'eval'))
  1           0 LOAD_CONST               2 (256)
              2 RETURN_VALUE
```

Because this is being calculated in C, you can't easily interrupt Python while it's happening.

**Comment by enedil** [comment]
Maybe some details aren't clear for me, but standard Python REPL does not suffer this problem.

**Comment by Carreau** [comment]
Is that reproducible for you ? When you kill it can you get a stack trace ? Or did you inadvertently types something like `Ctrl-Space` that can make the UI _look_ irresponsive ?

**Comment by enedil** [comment]
When I run ipython using strace, this is what I get:
```
Traceback (most recent call last):
  File "/usr/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/lib/python3.5/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 463, in interact
    code = self.prompt_for_code()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 235, in prompt
    isp.push(line)
  File "/usr/lib/python3.5/site-packages/IPython/core/inputsplitter.py", line 702, in push
    out = self.push_line(line)
  File "/usr/lib/python3.5/site-packages/IPython/core/inputsplitter.py", line 743, in push_line
    return super(IPythonInputSplitter, self).push(line)
  File "/usr/lib/python3.5/site-packages/IPython/core/inputsplitter.py", line 422, in push
    self.code = self._compile(source, symbol="exec")
  File "/usr/lib64/python3.5/codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib64/python3.5/codeop.py", line 82, in _maybe_compile
    code = compiler(source, filename, symbol)
  File "/usr/lib64/python3.5/codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
SystemError: <built-in function compile> returned a result with an error set
```

My shell tells me `fish: “ipython3” terminated by signal SIGKILL (Forced quit)`

How to check stack trace? Or is what I gave you a stack trace?

**Comment by takluyver** [comment]
Yup, what you gave is a stack trace, thanks!

That shows exactly what I guessed: it's stuck compiling the expression. The other frames of the stack trace show that it's doing so as part of a check to see whether it should execute now or let you enter another line of code.
