### ISSUE TITLE
Tab-completion crashes on ``current_thread().`` in IPython 6.2.0

### ISSUE THREAD

**Issue by TitanSnow** [ipython/ipython#10819]
Reproduce steps:

1. open IPython 6.2.0 (This bug does not exists in older versions)
2. type this:
  ```python
  In [1]: from threading import current_thread
  In [2]: current_thread().
  ```
3. press tab

Log:
```
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/ts/.local/lib/python3.5/site-packages/jedi/cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ts/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 84, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 94, in _get_completions
    for c in completions:
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 1792, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 1845, in _completions
    signature = _make_signature(jm)
  File "/home/ts/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 989, in _make_signature
    return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for p in completion.params) if f])
  File "/home/ts/.local/lib/python3.5/site-packages/jedi/cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/ts/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 360, in params
    raise AttributeError()
AttributeError
```

**Comment by takluyver** [comment]
I guess this is because prompt_toolkit handles completions on a separate thread. @Carreau , do you know what you want to do about it?

**Comment by dimpase** [comment]
Is it possible to provide a non-interactive test for tab completion? I have a similar issue involving ipython 5.1.0, the one included in Sagemath 8.0, and I need to do this kind of test (hit TAB to complete a Python command) many time to track down a [regression](https://trac.sagemath.org/ticket/23700#comment:11).

And it's good to have a test in docstrings, so that we know things don't get broken.

**Comment by takluyver** [comment]
It's certainly possible to write tests for our tab completion machinery (see [some of our tests](https://github.com/ipython/ipython/blob/master/IPython/core/tests/test_completer.py)), but it doesn't test it through prompt_toolkit, which is what's running it in a separate thread. I don't know of a way to do that.

**Comment by dimpase** [comment]
The whole point that it **does** run in a separate thread, and that's what causes the segfault in my case. (It calls an extension initialised in the main thread, that's why).

**Comment by Carreau** [comment]
I'll see if we can protect from any exception here. It's just jedi raising so  it should be easyish to mock.

**Comment by dimpase** [comment]
I don't see how it can be easy --- short of running single-thread. Indeed, the extension I am talking around has an embedded Common Lisp system ECL, which uses Boehm GC. The latter (and thus the whole memory management of ECL) needs to know the thread it is called from for correct execution. 
Now, with the introduction of a separate thread for tab completion, one can e.g. start the extension in the main thread and then call it in the tab completion thread (or the other way around) and get a segfault.

**Comment by dimpase** [comment]
Can tab completion involve importing of modules? If you do importing from several threads, it might end in a race of some sort.

**Comment by ritiek** [comment]
Ditto same error appears with [PlasmaPy](https://github.com/PlasmaPy/PlasmaPy):
```python
>>> from plasmapy.atomic import Particle
# AttributeError
>>> Particle('He').<tab>
```
Although, it works fine if we assign `Particle` to a variable first:
```python
>>> from plasmapy.atomic import Particle
>>> x = Particle('He')
# Works OK
>>> x.<tab>
```
I am not sure if `threading` is responsible in this case as well.

**Comment by antontarasenko** [comment]
I had a similar error with autocompletion in `pandas`. Updating to `jedi-0.13.2` helped:

```
pip3 install --upgrade jedi
```
