### ISSUE TITLE
Jupyter Notebook Error: Cannot open ipynb

### ISSUE THREAD

**Issue by bgpatel** [ipython/ipython#10827]
I have a similar issue as mentioned in previous issues # 9163 and #10174 

An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

Ques: I tried looking for this log file but cannot find it. If someone can point me where to locate it?

I have tried the following methods as suggested on similar issues, but none worked. In my case it just says these files don't exist.

cd $(jupyter --data-dir) mv nbsignatures.db nbsignatures.db.bak

rm ~/Library/Jupyter/nbsignatures.db

rm ~/.ipython/profile_default/history_sqlite

rm ~/.ipython/profile_default/security/nbsignatures.db

**Comment by bgpatel** [comment]
I found the log file and here is what I get:
[E 10:41:26.697 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'notary'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'db_file'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/dell/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/dell/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/dell/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 124, in get
        path=path, type=type, format=format, content=content,
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 384, in get
        model = self._notebook_model(path, content=content)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 344, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 456, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/home/dell/anaconda3/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 58, in _notary_default
        return sign.NotebookNotary(parent=self)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/nbformat/sign.py", line 392, in __init__
        self.store = self.store_factory()
      File "/home/dell/anaconda3/lib/python3.6/site-packages/nbformat/sign.py", line 340, in factory
        return SQLiteSignatureStore(self.db_file)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/home/dell/anaconda3/lib/python3.6/site-packages/nbformat/sign.py", line 351, in _db_file_default
        if not self.data_dir:
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/home/dell/anaconda3/lib/python3.6/site-packages/nbformat/sign.py", line 328, in _data_dir_default
        return app.data_dir
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/home/dell/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 93, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/home/dell/anaconda3/lib/python3.6/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
        os.makedirs(path, mode=mode)
      File "/home/dell/anaconda3/lib/python3.6/os.py", line 210, in makedirs
        makedirs(head, mode, exist_ok)
      File "/home/dell/anaconda3/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/dell/.local/share'
[E 10:41:26.699 NotebookApp] {
      "Host": "localhost:9999",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|eeb01bc2|b567fe2d3f482be8df6b0cdd237601fb|1506219929",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36",
      "Referer": "http://localhost:9999/notebooks/downloads/nbs/lesson1.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "_xsrf=2|eeb01bc2|b567fe2d3f482be8df6b0cdd237601fb|1506219929; username-localhost-9999=\"2|1:0|10:1506267674|23:username-localhost-9999|44:MTMzYWUyZmU4NjIxNDdlNDk4ZDkwZTg4MjQ3NTA2NDc=|8896fcdddf582e05445572344815bf68677faf67a36d45d35de3115493edd4ec\""
    }
[E 10:41:26.699 NotebookApp] 500 GET /api/contents/downloads/nbs/lesson1.ipynb?type=notebook&_=1506267686739 (::1) 46.16ms referer=http://localhost:9999/notebooks/downloads/nbs/lesson1.ipynb

**Comment by bgpatel** [comment]
I fixed it. I had multiple issues, since I was accessing the server remotely from my client, I had my ssh pointing to the incorrect port on which nbs was running. I fixed that and after that I had permission issues and once I fixed it, I was able to open files.
Thanks
