### ISSUE TITLE
nbconvert json decoding error

### ISSUE THREAD

**Issue by kambysese** [ipython/ipython#10844]
I believe this error might be related to #8009. I've managed to get the hooks in this thread to work (somewhat) producing desired `.py` and `.html` files after a checkpoint. However, I am getting a `ValueError: No JSON object could be decoded` having to do with my nb config `.json` file that I don't really understand. Any ideas what I am doing wrong here?

I am working in a Py27 Anaconda virtual env with following packages:

> jupyter 1.0.0 
> jupyter_client 5.1.0
> jupyter_console 5.1.0
> jupyter_core 4.3.0
> nbconvert 5.2.1
> nbformat 4.4.0

My `jupyter_nbconvert_config.json` file looks like:
```
{
  "Exporter": {
    "template_path": [
      ".",
      "/home/ktavabi/.jupyter/templates"
    ],
    "preprocessors": [
      "jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
      "jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
    ]
  },
  "version": 1
}
```
I get the following error in the console:

> [NbConvertApp] ERROR | Exception while loading config file /home/ktavabi/.jupyter/jupyter_nbconvert_config.json
> Traceback (most recent call last):
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
>     config = loader.load_config()
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/loader.py", line 406, in load_config
>     dct = self._read_file_as_dict()
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/loader.py", line 412, in _read_file_as_dict
>     return json.load(f)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/__init__.py", line 291, in load
>     **kw)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

**Comment by takluyver** [comment]
Do you get the same error if you try to load it directly?

```python
import json
with open("/home/ktavabi/.jupyter/jupyter_nbconvert_config.json") as f:
    json.load(f)
```

**Comment by kambysese** [comment]
@takluyver yes I do. I don't know anything about working with json. Do I need to set anything up differently considering I am using a virtual env in a miniconda root?

**Comment by takluyver** [comment]
No, the environment shouldn't make any difference to loading json.

The sample you've shown above is totally valid JSON as far as I can tell. Is that *exactly* what is in the file? Check for trailing commas (`,` after the last value of a list or dict), which JSON doesn't allow. Also check for 'smart quotes', `“ ”`, which you can get if something has been copied from e.g. MS Word. JSON, like most programming stuff, expects `"dumb quotes"`.
