### ISSUE TITLE
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO

### ISSUE THREAD

**Issue by Mrhjx2** [ipython/ipython#10855]
python 2.7.11
ipython 5.5.0
windows 7
Traceback (most recent call last):
  File "d:\program files\python2_7\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\program files\python2_7\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Program Files\python2_7\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "d:\program files\python2_7\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "d:\program files\python2_7\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "d:\program files\python2_7\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\program files\python2_7\lib\site-packages\IPython\terminal\ipapp.py", line 316, in initialize
    self.init_shell()
  File "d:\program files\python2_7\lib\site-packages\IPython\terminal\ipapp.py", line 332, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "d:\program files\python2_7\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "d:\program files\python2_7\lib\site-packages\IPython\terminal\interactiveshell.py", line 439, in __init__
    self.init_prompt_toolkit_cli()
  File "d:\program files\python2_7\lib\site-packages\IPython\terminal\interactiveshell.py", line 274, in init_prompt_toolkit_cli
    output=create_output(true_color=self.true_color))
  File "d:\program files\python2_7\lib\site-packages\prompt_toolkit\shortcuts.py", line 118, in create_output
    return Win32Output(stdout)
  File "d:\program files\python2_7\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "d:\program files\python2_7\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 164, in get_win32_screen_buffer_info
    success = windll.kernel32.GetConsoleScreenBufferInfo(self.hconsole, byref(sbinfo))
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by takluyver** [comment]
@jonathanslenders any ideas?

**Comment by remcoboerma** [comment]
Don't know if it helps, since is issue seems quite outdated. but have a very similar issue with xonsh using the new windows terminal. 
```
  File "C:\Users\p2jlxe5\virtualenv\xonsh\Lib\site-packages\xonsh\vended_ptk\prompt_toolkit\output\win32.py", line 195, in get_win32_screen_buffer_info
    success = windll.kernel32.GetConsoleScreenBufferInfo(
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP__CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
```

**Comment by nlazouzi** [comment]
same issue with xonsh as well.
