### ISSUE TITLE
Using `%matplotlib notebook` with animation after `%matplotlib inline` fails (`self.event_source is None`)

### ISSUE THREAD

**Issue by shoeffner** [ipython/ipython#10873]
### Issue:

When using a `(Timed)Animation` inside a `%matplotlib notebook` cell after a `%matplotlib inline` cell, the first call to that cell fails with `AttributeError: 'NoneType' object has no attribute 'remove_callback'`:

```
Traceback (most recent call last):
  File "/Users/shoeffner/.virtualenvs/cvloop/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/Users/shoeffner/.virtualenvs/cvloop/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/Users/shoeffner/.virtualenvs/cvloop/lib/python3.6/site-packages/matplotlib/animation.py", line 1560, in _stop
    self.event_source.remove_callback(self._loop_delay)
AttributeError: 'NoneType' object has no attribute 'remove_callback'
```

### MWE

General idea:
```python
%matplotlib inline
# some plotting
```
```python
%matplotlib notebook
# some animation -> this fails
```
I created a [small example notebook](https://gist.github.com/shoeffner/07c1c9ba7407684141372e2e862d0503) showing off the problem, adapted from an issue here: https://github.com/shoeffner/cvloop/issues/20#issuecomment-339791438 . 

### Workaround

The MWE above also shows a quick and dirty workaround: **Calling `%matplotlib notebook` twice**.
```python
%matplotlib inline
# some plotting
```
```python
%matplotlib notebook
%matplotlib notebook
# some animation -> this succeeds
```

### Other details

IPython details:
```
{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/Users/shoeffner/.virtualenvs/cvloop/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.2.1',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/shoeffner/.virtualenvs/cvloop/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 (default, Oct  4 2017, 06:09:15) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]'}
```

And after upgrading to master:
```
{'commit_hash': 'dfb458636',
 'commit_source': 'repository',
 'default_encoding': 'utf-8',
 'ipython_path': '/Users/shoeffner/.virtualenvs/cvloop/src/ipython/IPython',
 'ipython_version': '6.2.0.dev',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/shoeffner/.virtualenvs/cvloop/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 (default, Oct  4 2017, 06:09:15) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]'}
```

The problem seems to be OS independent, as it is reproducible on Mac OS Sierra (10.12.6) and Ubuntu 16.04 (see [original issue here](https://github.com/shoeffner/cvloop/issues/20#issuecomment-339448200)).

**Comment by shoeffner** [comment]
@krumnack made some deeper analysis of the underlying problems here: https://github.com/shoeffner/cvloop/issues/20#issuecomment-340292628

**Comment by ghmz** [comment]
NameError: name 'ax' is not defined

**Comment by ghmz** [comment]
![image](https://user-images.githubusercontent.com/65145161/82719931-57a18800-9ce1-11ea-82ce-734995402658.png)

**Comment by shoeffner** [comment]
I think that might be a different issue, maybe you can open a new issue and
describe your problem there? Can you describe your problem further?
Have you tried setting `%matplotlib notebook` at the top of your cell?
