### ISSUE TITLE
Syntax error with %timeit and set literals

### ISSUE THREAD

**Issue by pitrou** [ipython/ipython#10920]
This is with IPython 6.2.1 on Python 3.6:
```python
>>> import enum
>>> State = enum.Enum('State', ('released', 'memory', 'erred'))
>>> st = State.memory
>>> st in {State.erred, State.memory}
True
>>> %timeit st in {State.erred, State.memory}
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-352090464b59>", line 1, in <module>
    get_ipython().run_line_magic('timeit', 'st in {State.erred, State.memory}')
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-61>", line 2, in timeit
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/IPython/core/magics/execution.py", line 1041, in timeit
    ast_stmt = self.shell.compile.ast_parse(transform(stmt))
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/IPython/core/compilerop.py", line 99, in ast_parse
    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)
  File "<unknown>", line 1
    st in (<State.erred: 3>, <State.memory: 2>)
           ^
SyntaxError: invalid syntax
```

**Comment by takluyver** [comment]
The `{}` act as string formatting to interpolate a Python expression into a magic command. There's no need for it on timeit, but for historical reasons it does that on all %magic and !system commands.

Doubling the braces `{{State.erred, State.memory}}` should escape them.

**Comment by blaiseli** [comment]
I could have a related issue.

Attempts at timing set intersection operations (that work perfectly well otherwise) fail:

```{python}
In [34]: %timeit s & {2}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-c6066eb98afc> in <module>()
----> 1 get_ipython().run_line_magic('timeit', 's & {2}')

~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2093                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2094             with self.builtin_trap:
-> 2095                 result = fn(*args,**kwargs)
   2096             return result
   2097 

<decorator-gen-61> in timeit(self, line, cell, local_ns)

~/.local/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.local/lib/python3.6/site-packages/IPython/core/magics/execution.py in timeit(self, line, cell, local_ns)
   1096             for index in range(0, 10):
   1097                 number = 10 ** index
-> 1098                 time_number = timer.timeit(number)
   1099                 if time_number >= 0.2:
   1100                     break

~/.local/lib/python3.6/site-packages/IPython/core/magics/execution.py in timeit(self, number)
    158         gc.disable()
    159         try:
--> 160             timing = self.inner(it, self.timer)
    161         finally:
    162             if gcold:

<magic-timeit> in inner(_it, _timer)

TypeError: unsupported operand type(s) for &: 'set' and 'int'
```

And:

```{python}
In [40]: %timeit s.intersection({2})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-d2cf5cc5314f> in <module>()
----> 1 get_ipython().run_line_magic('timeit', 's.intersection({2})')

~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2093                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2094             with self.builtin_trap:
-> 2095                 result = fn(*args,**kwargs)
   2096             return result
   2097 

<decorator-gen-61> in timeit(self, line, cell, local_ns)

~/.local/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.local/lib/python3.6/site-packages/IPython/core/magics/execution.py in timeit(self, line, cell, local_ns)
   1096             for index in range(0, 10):
   1097                 number = 10 ** index
-> 1098                 time_number = timer.timeit(number)
   1099                 if time_number >= 0.2:
   1100                     break

~/.local/lib/python3.6/site-packages/IPython/core/magics/execution.py in timeit(self, number)
    158         gc.disable()
    159         try:
--> 160             timing = self.inner(it, self.timer)
    161         finally:
    162             if gcold:

<magic-timeit> in inner(_it, _timer)

TypeError: 'int' object is not iterable
```

Doubling the braces bypasses the issue:

```{python}
In [44]: %timeit s.intersection({{2}})
242 ns ± 23.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [45]: %timeit s & {{2}}
174 ns ± 22.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
