### ISSUE TITLE
ipython 6.2.1 tab completion crashes with python3.7.0a2

### ISSUE THREAD

**Issue by nartes** [ipython/ipython#10930]
```
Python 3.7.0a2+ (heads/master:bc8ac6b00e, Nov 30 2017, 22:14:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import multiException in thread Thread-38:
Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 265, in load_grammar
    return _loaded_grammars[path]
KeyError: '/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/python/grammar37.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 268, in load_grammar
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/python/grammar37.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 84, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 94, in _get_completions
    for c in completions:
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1791, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1831, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1998, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/IPython/core/completer.py", line 1348, in _jedi_matches
    text, namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/jedi/api/__init__.py", line 386, in __init__
    super(Interpreter, self).__init__(source, **kwds)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/jedi/api/__init__.py", line 110, in __init__
    self._grammar = parso.load_grammar()
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 283, in load_grammar
    return load_grammar(**kwargs)
  File "/home/nartes/Documents/current/cpython/tmp/install/lib/python3.7/site-packages/parso/grammar.py", line 275, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version None is currently not supported.
```

**Comment by nartes** [comment]
A problem has gone with parso 0.1.1.
