### ISSUE TITLE
jupyter notebook not starting - new Mini-conda install

### ISSUE THREAD

**Issue by jetojedno** [ipython/ipython#10989]
I have a new Miniconda install on openSUSE linux 42.3

I've installed jupyter and various other bits, and jupyter notebooks won't start without extra parameters:

```
> jupyter notebook --no-browser
Traceback (most recent call last):
  File "/home/admin/Anaconda3/envs/udacity-nd101/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/notebook/notebookapp.py", line 1507, in initialize
    self.init_webapp()
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/notebook/notebookapp.py", line 1297, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/admin/Anaconda3/envs/udacity-nd101/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

I've added:
```
c.NotebookApp.port = 8888
c.NotebookApp.ip = '127.0.0.1'
```
to ~/Anaconda3/envs/env-name/lib/python3.6/site-packages/jupyter_core/tests/dotipython_empty/profile_default/ipython_notebook_config.py and that didn't help.

It runs OK if started:
`
jupyter notebook --ip='127.0.01' --no-browser
`

Should I put these lines somewhere else or is this a defect?

**Comment by jetojedno** [comment]
```
> uname -a
Linux oxford 4.4.104-18.44-default #1 SMP Thu Jan 4 08:07:55 UTC 2018 (05a9de6) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jetojedno** [comment]
OK.  Wrong config files.

Added the settings to `~/.jupyter/jupyter_notebook_config.py` (after generating it) and it now works without extra command line parameters.

But ... there's still a defect somewhere.

**Comment by takluyver** [comment]
We try to defend against that - see `NotebookApp._default_ip()`. What do you get from:

```python
s = socket.socket()
s.bind(('localhost', 0))
```

**Comment by jetojedno** [comment]
In the conda environment
```
> import socket
> s = socket.socket()
> s.bind(('localhost', 0))
```
succeeds - no output.

**Comment by takluyver** [comment]
Yeah, that's what our code checks, and if it succeeds, it tries to bind the web server on localhost, which is what fails for you. I don't understand what's going wrong there. :-/

**Comment by jetojedno** [comment]
I have it working now :-) and if others aren't complaining (I'd expect quite a few reactions if it were widespread) then I think it's just one of those things - complex software which, in some circumstances, gets its knickers in a twist.  If I had to point a finger, it would be towards some component of the initialisation on install - this was all freshly installed packages.

I also had a transient problem with (newly installed) nb_conda which was resolved by the simple steps of exiting the conda environment & re-entering, then re-running the initialisation.

Thanks.  All good now (touch wood) :-)

**Comment by takluyver** [comment]
OK, glad it's working now.

**Comment by jkbr-19** [comment]
I get pretty much the same error message on Antergos. Runs fine when started with `jupyter notebook --ip='127.0.0.1'`
```
(base) jkbr:~/ $ conda info                                                                                          

     active environment : base
    active env location : /home/jkbr/miniconda3
            shell level : 1
       user config file : /home/jkbr/.condarc
 populated config files : /home/jkbr/.condarc
          conda version : 4.6.2
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : /home/jkbr/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jkbr/miniconda3/pkgs
                          /home/jkbr/.conda/pkgs
       envs directories : /home/jkbr/miniconda3/envs
                          /home/jkbr/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.7.2 Linux/4.20.8-arch1-1-ARCH antergos/19.2 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I noticed something interesting.
```
jkbr:~/ $ ssh jkbr@localhost                                                                                          
ssh: connect to host localhost port 22: Cannot assign requested address
# looks like it doesn't work
jkbr:~/ $ ssh jkbr@127.0.0.1                                                                                         
ssh: connect to host 127.0.0.1 port 22: Connection refused
# Seems like my firewall is doing its job
```
It seems to me that this issue doesn't have anything to do with jupyter or miniconda but `localhost` not being properly set on the system. This seems like something with basic knowledge about this kind of stuff should be able to fix pretty easily, however I'm not one of those people.

**Comment by jkbr-19** [comment]
I get pretty much the same error message on Antergos. Runs fine when started with `jupyter notebook --ip='127.0.0.1'`
```
(base) jkbr:~/ $ conda info                                                                                          

     active environment : base
    active env location : /home/jkbr/miniconda3
            shell level : 1
       user config file : /home/jkbr/.condarc
 populated config files : /home/jkbr/.condarc
          conda version : 4.6.2
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : /home/jkbr/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jkbr/miniconda3/pkgs
                          /home/jkbr/.conda/pkgs
       envs directories : /home/jkbr/miniconda3/envs
                          /home/jkbr/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.7.2 Linux/4.20.8-arch1-1-ARCH antergos/19.2 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I noticed something interesting.
```
jkbr:~/ $ ssh jkbr@localhost                                                                                          
ssh: connect to host localhost port 22: Cannot assign requested address
# looks like it doesn't work
jkbr:~/ $ ssh jkbr@127.0.0.1                                                                                         
ssh: connect to host 127.0.0.1 port 22: Connection refused
# Seems like my firewall is doing its job
```
It seems to me that this issue doesn't have anything to do with jupyter or miniconda but `localhost` not being properly set on the system. This seems like something with basic knowledge about this kind of stuff should be able to fix pretty easily, however I'm not one of those people.
