### ISSUE TITLE
Cannot start ipython after brand new installation

### ISSUE THREAD

**Issue by PaulPichaureau** [ipython/ipython#10981]
Hi,

I've just reinstalled completely Python3 on my computer. The first package I've installed is ipython, and I cannot start it. The error message is quite cryptic for me:

    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/bin/ipython3", line 7, in <module>
    from IPython import start_ipython
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-    packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/application.py", line 23, in <module>
      from traitlets.config.application import Application, catch_config_error
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 120, in <module>
      class Application(SingletonConfigurable):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 291, in Application
      def initialize(self, argv=None):
    TypeError: catch_config_error() missing 1 required positional argument: 'app'

I use Python 3.6.4 on MacOs 10.13.1 and I've installed ipython using pip3.

Thanks for any help!

**Comment by triyangle** [comment]
Getting same issue using Anaconda distribution on macOS 10.13.2

**Comment by alonho** [comment]
https://stackoverflow.com/questions/48248521/ipython3-catch-config-error-missing-1-required-positional-argument-app/48248712#48248712

This is happening because traitlets relies on a package called 'decorator' that was just updated from 4.1.2 to 4.2.0 and broken its backward compatibility.

If you're using a requirements file or pip, install decorator==4.1.2 before installing IPython.

**Comment by takluyver** [comment]
This should be fixed by decorator 4.2.1, which was released yesterday.
