### ISSUE TITLE
WXAgg support seems pretty proken

### ISSUE THREAD

**Issue by 2sn** [ipython/ipython#11040]
(does not crash in regular python3)

~>ipython3
Python 3.6.4 (default, Dec 28 2017, 16:19:09) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
<IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7f7cf7f3bba8>
Using matplotlib backend: WXAgg
Populating the interactive namespace from numpy and matplotlib

In [1]: plot([0,1])
Out[1]: [<matplotlib.lines.Line2D at 0x7f7c86f88cc0>]

In [2]:                                                                                                                         
Traceback (most recent call last):
  File "/home/alex/Python/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/alex/Python/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 463, in interact
    code = self.prompt_for_code()
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 376, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/home/alex/Python/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/home/alex/Python/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 102, in run
    self._inputhook_context.call_inputhook(ready)
  File "/home/alex/Python/lib/python3.6/site-packages/prompt_toolkit/eventloop/inputhook.py", line 74, in call_inputhook
    self.inputhook(self)
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 495, in inputhook
    self._inputhook(context)
  File "/home/alex/Python/lib/python3.6/site-packages/IPython/terminal/pt_inputhooks/wx.py", line 98, in inputhook_wx3
    assert wx.Thread_IsMain()
AttributeError: module 'wx' has no attribute 'Thread_IsMain'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.6/site-packages/matplotlib/_pylab_helpers.py", line 78, in destroy_all
    manager.destroy()
  File "/home/alex/Python/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py", line 1303, in destroy
    self.frame.Destroy()
  File "/home/alex/Python/lib/python3.6/site-packages/matplotlib/backends/backend_wx.py", line 1256, in Destroy
    if not self.IsBeingDeleted():
RuntimeError: wrapped C/C++ object of type FigureFrameWxAgg has been deleted
~>

**Comment by takluyver** [comment]
This looks like #10055; I'll close it and we can keep tracking it there.

It's waiting for someone to update it for the new version of wxPython. And to work out whether one hook can work for wx3 and wx4, or whether we should separate them.
