### ISSUE TITLE
 ipython nbconvert --to python 10\ Playing\ frame\ stream\ from\ video.ipynb

### ISSUE THREAD

**Issue by vijaypanchal** [ipython/ipython#11075]
[NbConvertApp] Using existing profile dir: u'/home/teksunlab/.config/ipython/profile_default'
[NbConvertApp] Converting notebook 10 Playing frame stream from video.ipynb to python
[NbConvertApp] Support files will be in 10 Playing frame stream from video_files/
Traceback (most recent call last):
  File "/usr/bin/ipython", line 6, in <module>
    start_ipython()
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 546, in launch_instance
    app.start()
  File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 358, in start
    return self.subapp.start()
  File "/usr/lib/python2.7/dist-packages/IPython/nbconvert/nbconvertapp.py", line 267, in start
    self.convert_notebooks()
  File "/usr/lib/python2.7/dist-packages/IPython/nbconvert/nbconvertapp.py", line 300, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python2.7/dist-packages/IPython/nbconvert/exporters/exporter.py", line 289, in from_filename
    return self.from_notebook_node(nbformat.read(f, 'json'), resources=resources,**kw)
  File "/usr/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 188, in read
    return reads(fp.read(), format, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 137, in reads
    return reads_json(s, **kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 90, in reads_json
    raise NBFormatError('Unsupported JSON nbformat version %s (supported version: %i)' % (nbf, 3))
NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by takluyver** [comment]
Sounds like you're trying to convert a newer format notebook with an old version of the code. Time to upgrade!

IPython was split up into several packages, most of which are now called Jupyter. Here's the page on how to install it: http://jupyter.org/install.html
