### ISSUE TITLE
Crash on __builtins__.__dict__.pop('zip')

### ISSUE THREAD

**Issue by vanillajonathan** [ipython/ipython#11095]
```
In [1]: __builtins__.__dict__.pop('zip')
Out[1]: zip

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 413, in run
    self._redraw()
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/renderer.py", line 436, in render
    extended_height=size.rows,
  File "/usr/lib/python3/dist-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/layout/containers.py", line 195, in _divide_heigths
    i = next(child_generator)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/utils.py", line 234, in take_using_weights
    for item_i, item, weight in zip(range(item_count), items, weights):
NameError: name 'zip' is not defined
```

System information
```python
{'commit_hash': 'b467d487e',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python3/dist-packages/IPython',
 'ipython_version': '5.5.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-13-generic-x86_64-with-Ubuntu-18.04-bionic',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.6.5 (default, Apr  1 2018, 05:46:30) \n[GCC 7.3.0]'}
```

**Comment by takluyver** [comment]
That's what I'd expect to happen. IPython is written in Python, and it depends on other packages that are written in Python. If you break Python by removing builtins, Python code stops working.
