### ISSUE TITLE
AttributeError: 'HistoryManager' object has no attribute 'log'

### ISSUE THREAD

**Issue by subbayya** [ipython/ipython#11169]
I was trying to use pyspark with the following command:

pyspark --master yarn --executor-memory 10G --executor-cores 5 --driver-cores 5 --driver-memory 10G --packages com.databricks:spark-csv_2.11:1.2.0 --jars /home/ssubbayya/spark-avro_2.11-3.0.0.jar

Traceback (most recent call last):
  File "/usr/anaconda/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/usr/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 306, in initialize
    self.init_shell()
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 322, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/usr/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.

py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 465, in __init__
    self.init_history()
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1586, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/usr/anaconda/lib/python2.7/site-packages/IPython/core/history.py", line 520, in __init__
    self.log.error("Failed to create history session in %s. History will not be saved.",
AttributeError: 'HistoryManager' object has no attribute 'log'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

**Comment by Carreau** [comment]
which version of IPython are you using ? Any particualr config ?
