### ISSUE TITLE
ipython output broken in emacs

### ISSUE THREAD

**Issue by altosaar** [ipython/ipython#11220]
Following https://ipython.readthedocs.io/en/stable/config/details.html?highlight=emacs 

I added the following to emacs' `init.el`:

```
(require 'python)
(setq
 python-shell-interpreter "ipython"
 python-shell-interpreter-args "--simple-prompt --classic --nosep"
)
```
Then if I open a file in emacs `~/tmp/test.py` with the contents:

```
print('test printing')
print('test bug)
```

And run it using `M-x run-python` then `M-x python-shell-send-buffer`,
the output is quite messy:

```
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
>>> Traceback (most recent call last):

  File "/usr/local/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-57ce0cd600e5>", line 1, in <module>
    import codecs, os;__pyfile = codecs.open('''/var/folders/qr/s_h2rhqj6kdg8qrj0zw2scnw0000gn/T/pyLbk6Vh''', encoding='''utf-8''');__code =
__pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/qr/s_h2rhqj6kdg8qrj0zw2scnw0000gn/T/pyLbk6Vh''');exec(compile(__code, '''/Users/jaan/tmp/test.py''', 'exec'));

  File "/Users/jaan/tmp/test.py", line 2
    print('test bug)
                    ^
SyntaxError: EOL while scanning string literal
```

Is there any way to clean up the output, especially the parts involving
`codecs.open('''/var/folders/qr/s_h2rhqj6kdg8qrj0zw2scnw0000gn/T/pyLbk6Vh'''`?

I'm using this version of emacs on OS X High Sierra: https://github.com/railwaycat/homebrew-emacsmacport

Thanks!

**Comment by aweinstein** [comment]
It seems that

```
(setq python-shell-interpreter-args "--simple-prompt")
```
fix the problem.
