### ISSUE TITLE
set_trace not working

### ISSUE THREAD

**Issue by axil** [ipython/ipython#11236]
In Jupyter notebook debugging is not working in this minimal example:

from bokeh.io import output_notebook, output_file, reset_output, show
output_notebook()
def f(doc):
    from IPython.core.debugger import Pdb; Pdb().set_trace()
show(f)

I expect it to open ipdb debug console. Instead it says, 

```
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=f34077de-eddd-4305-bd21-7d6eef95b065&bokeh-absolute-url=http://localhost:56057&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:56057', method='GET', uri='/autoload.js?bokeh-autoload-element=f34077de-eddd-4305-bd21-7d6eef95b065&bokeh-absolute-url=http://localhost:56057&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "d:\documents\python\thz_lab\env\lib\site-packages\bokeh\server\views\autoload_js_handler.py", line 26, in get
    session = yield self.get_session()
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "d:\documents\python\thz_lab\env\lib\site-packages\bokeh\server\views\session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "d:\documents\python\thz_lab\env\lib\site-packages\tornado\gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "d:\documents\python\thz_lab\env\lib\site-packages\bokeh\server\application_context.py", line 182, in create_session_if_needed
    self._application.initialize_document(doc)
  File "d:\documents\python\thz_lab\env\lib\site-packages\bokeh\application\application.py", line 169, in initialize_document
    h.modify_document(doc)
  File "d:\documents\python\thz_lab\env\lib\site-packages\bokeh\application\handlers\function.py", line 126, in modify_document
    self._func(doc)
  File "<ipython-input-3-64993cd62c27>", line 2, in f
    from IPython.core.debugger import Pdb; Pdb().set_trace()
  File "d:\utilities\development\python36-32\Lib\bdb.py", line 55, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "d:\utilities\development\python36-32\Lib\bdb.py", line 99, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=f34077de-eddd-4305-bd21-7d6eef95b065&bokeh-absolute-url=http://localhost:56057&resources=none (::1) 1471.08ms
```

I traced this issue down to ipython and the problem seems to be with ipython.

@minrk 's commit 3bc63510d5e22d8ddfbe2ab32e35c343d31dd421 fixes this, plz don't desert this branch (more-await-repl).

PS System info:
{'commit_hash': '84a4925',
 'commit_source': 'repository',
 'default_encoding': 'utf-8',
 'ipython_path': 'd:\\documents\\python\\ipython\\IPython',
 'ipython_version': '4.1.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Utilities\\Development\\Python\\python.EXE',
 'sys_platform': 'win32',
 'sys_version': '3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 '
                '32 bit (Intel)]'}

**Comment by axil** [comment]
Steps to workaround this problem (to enable debugging for embedded bokeh notebooks):
```
pip install -e git+https://github.com/minrk/ipython.git@aedb5d6d3a441dcdb7180ac9b5cc03f91329117b#egg=ipython
pip install -e git+https://github.com/minrk/ipykernel.git@d08f120988cfadeeedb25434101f86c51d382e35#egg=ipykernel
pip install tornado==5.0.2
```

`ipynernel` is necessary for the this branch of ipython to work.
`tornado` should be 5.0.2. Version 5.1 still shows this error even with the proper branches of ipython and ipykernel.

Result:

![image](https://user-images.githubusercontent.com/170910/43091012-368fb16e-8ed3-11e8-9d06-4c189e0cebae.png)

**Comment by anentropic** [comment]
I have the same issue in:
```
Python 3.7.3 (default, May 25 2019, 18:42:37)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
```

I import set_trace like `In [49]: from IPython.core.debugger import set_trace`

Later I call a function which calls `set_trace()`

I get the error:
```
  File "/Users/anentropic/.pyenv/versions/3.7.3/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/anentropic/.pyenv/versions/3.7.3/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

I would really like to be able to set a breakpoint from within code that I have entered in the IPython shell.
