### ISSUE TITLE
ipython directive seems to be broken

### ISSUE THREAD

**Issue by tacaswell** [ipython/ipython#11320]
Found this while trying to build the Matplotlib docs.  Can try to chase it down better tomorrow, but posting now in case I do not get back to it.

```
Exception occurred:
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 333, in process_input_line
    if self.IP.check_complete()[0] != 'incomplete':
TypeError: check_complete() missing 1 required positional argument: 'code'
The full traceback has been saved in /tmp/sphinx-err-ruydljl4.log, if you want to report the issue to the developers.

```

23:56 $ ipython --version
7.0.0.dev

<details>

```
23:51 $ cat /tmp/sphinx-err-ruydljl4.log
# Sphinx version: 1.8.0
# Python version: 3.8.0a0 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 97%] tutorials/advanced/path_tutorial
#   
#   reading sources... [ 97%] tutorials/advanced/patheffects_guide
#   
#   reading sources... [ 97%] tutorials/advanced/transforms_tutorial
#   
#   reading sources... [ 97%] tutorials/colors/colorbar_only
#   
#   reading sources... [ 97%] tutorials/colors/colormapnorms
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.11) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.graphviz (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx.ext.intersphinx (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (1.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   IPython.sphinxext.ipython_directive (unknown version) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py
#   numpydoc (0.8.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/numpydoc/__init__.py
#   sphinx_gallery.gen_gallery (0.2.0) from /home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx_gallery/gen_gallery.py
#   matplotlib.sphinxext.mathmpl (unknown version) from /home/tcaswell/source/p/matplotlib/lib/matplotlib/sphinxext/mathmpl.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /home/tcaswell/source/p/matplotlib/lib/matplotlib/sphinxext/plot_directive.py
#   sphinxext.custom_roles (unknown version) from /home/tcaswell/source/p/matplotlib/doc/sphinxext/custom_roles.py
#   sphinxext.github (unknown version) from /home/tcaswell/source/p/matplotlib/doc/sphinxext/github.py
#   sphinxext.math_symbol_table (unknown version) from /home/tcaswell/source/p/matplotlib/doc/sphinxext/math_symbol_table.py
#   sphinxext.mock_gui_toolkits (unknown version) from /home/tcaswell/source/p/matplotlib/doc/sphinxext/mock_gui_toolkits.py
#   sphinxext.skip_deprecated (unknown version) from /home/tcaswell/source/p/matplotlib/doc/sphinxext/skip_deprecated.py
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 915, in run
    rgxin, rgxout, promptin, promptout = self.setup()
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 875, in setup
    self.shell = EmbeddedSphinxShell(exec_lines)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 317, in __init__
    self.process_input_line(line, store_history=False)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 333, in process_input_line
    if self.IP.check_complete()[0] != 'incomplete':
TypeError: check_complete() missing 1 required positional argument: 'code'

```

</details>

**Comment by Carreau** [comment]
Thanks for being our test suite. 

See #11321

**Comment by Carreau** [comment]
BTW, the ipython_directive seem to `import matplotlib.pyplot as plt` and `import numpy as np` by default.
Any objection to changing the default ?
