### ISSUE TITLE
ipython and jupyternotebook unresponsive

### ISSUE THREAD

**Issue by jeffbaena** [ipython/ipython#11364]
Hi I have an issue with anaconda3 python.
 I have a server with ubuntu 16.04 and I was using jupyter notebooks on my local browser. Everything was fine. After some days of inactivity I could not open my jupyter notebooks anymore.
JUPYTER: Directory tree works fine, when I try to load a notebook it freezes, or sometimes load the code but freezes. On terminal I get " 304 GET /api/kernelspecs (127.0.0.1)" frozen, sometimes also other errors

IPYTHON: gets stuck with no output nor green input line. After a while (like 10 min or so) gives an error 

I have checked .db and they are empty I have tried to reinstall anaconda but things todn't change

I am really puzzled by what's going on.

Any help would be really appreciated,

Thanks,
Stefano 

[ipython logs.txt](https://github.com/ipython/ipython/files/2449787/ipython.logs.txt)
[jupyter_logs.txt](https://github.com/ipython/ipython/files/2449788/jupyter_logs.txt)

**Comment by jeffbaena** [comment]
Another example of logs:

  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 87, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 257, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/academic/ssavian/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 430, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 501, in __init__
    self.init_history()
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 1621, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 537, in __init__
    **traits)
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 229, in __init__
    self.init_db()
  File "<decorator-gen-15>", line 2, in init_db
  File "/home/academic/ssavian/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 87, in catch_corrupt_db
    return f(self, *a, **kw)
KeyboardInterrupt

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
