### ISSUE TITLE
ipython 7.0.1 and sphinx code-blocks

### ISSUE THREAD

**Issue by thequackdaddy** [ipython/ipython#11394]
I'm working on getting ipython 7 to work with statsmodel's docbuild. 

I think I stumbled across another problem that seems to have crept up. 

The docs have an rst file with this code:

```python

.. ipython:: python
   :suppress:

   import numpy as np
   np.set_printoptions(precision=4, suppress=True)

   from patsy.contrasts import ContrastMatrix

   def _name_levels(prefix, levels):
       return ["[%s%s]" % (prefix, level) for level in levels]

   class Simple(object):
       def _simple_contrast(self, levels):
           nlevels = len(levels)
           contr = -1./nlevels * np.ones((nlevels, nlevels-1))
           contr[1:][np.diag_indices(nlevels-1)] = (nlevels-1.)/nlevels
           return contr
       def code_with_intercept(self, levels):
           contrast = np.column_stack((np.ones(len(levels)),
                                       self._simple_contrast(levels)))
           return ContrastMatrix(contrast, _name_levels("Simp.", levels))
       def code_without_intercept(self, levels):
           contrast = self._simple_contrast(levels)
           return ContrastMatrix(contrast, _name_levels("Simp.", levels[:-1]))

```

The docbuild is failing on this with this...

```
>>>-------------------------------------------------------------------------
Exception in /home/peter/git/statsmodels/docs/source/contrasts.rst at block ending on line 38
Specify :okexcept: as an option in the ipython:: block to suppress this message
  File "<ipython-input-5-73d6e7795395>", line 1
    class Simple(object):    def _simple_contrast(self, levels):        nlevels = len(levels)
                               ^
SyntaxError: invalid syntax

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-0dec34385e1c> in <module>
----> 1 contr = -1./nlevels * np.ones((nlevels, nlevels-1))

NameError: name 'nlevels' is not defined
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-7176c07ecc42> in <module>
----> 1 contr[1:][np.diag_indices(nlevels-1)] = (nlevels-1.)/nlevels

NameError: name 'nlevels' is not defined
  File "<ipython-input-8-19eb420dec18>", line 1
    return contr
                ^
SyntaxError: 'return' outside function

  File "<ipython-input-10-3da959d515b0>", line 1
    return ContrastMatrix(contrast, _name_levels("Simp.", levels))
                                                                  ^
SyntaxError: 'return' outside function

  File "<ipython-input-12-a97eda370d11>", line 1
    return ContrastMatrix(contrast, _name_levels("Simp.", levels[:-1]))
                                                                       ^
SyntaxError: 'return' outside function

<<<-------------------------------------------------------------------------
```
It looks (and feels)  like ipython is submitting at the end of every line instead of waiting until the end of class block. I have no idea how to prove this, however. I'm happy to work on it.

**Comment by Carreau** [comment]
could you try with master ? There was a bug where IPython was eagerly evaluating that may have been fixed.

**Comment by thequackdaddy** [comment]
I pip installed git+https from master and got the same bug. 

I get this running `make html` from the docs folder. 

Happy to help debug, but I don't know really know how to make a minimal example.

**Comment by jorisvandenbossche** [comment]
This might be the same as https://github.com/ipython/ipython/issues/11362 ?

**Comment by thequackdaddy** [comment]
It really looks like it is... not sure how I missed that. I'll close this as a duplicate.
