### ISSUE TITLE
Parallel ipython kernels disk errors

### ISSUE THREAD

**Issue by MSeal** [ipython/ipython#11460]
I had an issue come up in papermill around parallel computing notebook execution (https://github.com/nteract/papermill/issues/239) and was hoping to brainstorm solutions here.

Basically 
```
#!/bin/bash
foo () {
    papermill 'foo.ipynb' "foo$1_out.ipynb"
}

for i in `seq 1 10`; do foo "$i" & done
```
or 
```
import papermill as pm
import multiprocessing as mp

foo_outs = ['foo{}_out'.format(n) for n in range(25)]

def run_nb(out_id):
    pm.execute_notebook('foo.ipynb', '{}.ipynb'.format(out_id))
    
pool = mp.Pool(4)
pool.map(run_nb, foo_outs)
pool.close()
pool.join()
```
causes a bunch of disk IO errors around sessions and history. In some races it locks up on session generations, though most of the time it's the onexit code complaining.

If this particular kernel message appears it will hang that thread or process indefinitely until papermill times out in launching the kernel.
```
[IPKernelApp] ERROR | Failed to create history session in /home/mseal/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/home/mseal/.py3local/lib/python3.5/site-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "<decorator-gen-22>", line 2, in new_session
  File "/home/mseal/.py3local/lib/python3.5/site-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "/home/mseal/.py3local/lib/python3.5/site-packages/IPython/core/history.py", line 570, in new_session
    self.session_number = cur.lastrowid
```

Overall papermill when using nbconvert engine generates a new kernel process for each execution and passes messages as a normal jupyter client. Today it does this to ensure execution occurs and is isolated from other actors. I was thinking there might be some insight into mechanisms to isolate sessions / parameterize the kernel in a way that it's protected from noisy neighbors. Or maybe I should consider looking into enabling a shared mode which uses existing kernels / resolves the kernel launch race separately. 

The nbconvert code which launches the kernel can be found here: https://github.com/jupyter/nbconvert/blob/1a7b848cedae10970f6df83268ef0898ba80d734/nbconvert/preprocessors/execute.py#L234

Thoughts?

**Comment by Carreau** [comment]
For the history database you can setup the config option to `--HistoryManager.hist_file=` to `:memory:` that should prevent any disk access and isolate kernels more. 

We can a likely add similar option for other stuff, but IPython is big so it will be every time we find something to fix.

**Comment by MSeal** [comment]
Ok thanks. I'll try making these style changes on the papermill side as an experimental feature and might come back to this thread for suggestions as I hit the next thing.
