### ISSUE TITLE
IPython crashes at launch

### ISSUE THREAD

**Issue by danlub** [ipython/ipython#11485]
Hi! I have the following error output when I launch IPython (below). I don't know what triggered it, because it stopped working ''randomly''. I've googled for a solution but I couldn't find any

My machine has Xubuntu 18.04 and I'm using Anaconda as my python distribution. I'll be happy to provide more info, since I have no clue about how to fix this.

This is the output of ` python -c "import IPython; print(IPython.sys_info())"`:
```python
{'commit_hash': '59a7834d2',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/daniel/anaconda3/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.1.1',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-38-generic-x86_64-with-debian-buster-sid',
 'sys_executable': '/home/daniel/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, '
                '12:34:16) \n'
                '[GCC 7.3.0]'}
```

Thanks in advance!

 ---
```
Python 3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 595, in _run_async
    self._redraw()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 444, in _redraw
    self.renderer.render(self, self.layout)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/renderer.py", line 557, in render
    if (self.style.invalidation_hash() != self._last_style_hash or
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/styles/style.py", line 372, in invalidation_hash
    return tuple(s.invalidation_hash() for s in self.styles)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/styles/style.py", line 372, in <genexpr>
    return tuple(s.invalidation_hash() for s in self.styles)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/styles/base.py", line 140, in invalidation_hash
    return (self.get_style() or self._dummy).invalidation_hash()
  File "/home/daniel/.local/lib/python3.6/site-packages/powerline/renderers/ipython/since_5.py", line 79, in invalidation_hash
    return super(PowerlinePromptStyle, self).invalidation_hash() + 1
TypeError: can only concatenate tuple (not "int") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 490, in mainloop
    self.interact()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 473, in interact
    code = self.prompt_for_code()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 402, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 733, in prompt
    return run_sync()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 722, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/daniel/anaconda3/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 654, in _run_async2
    assert not self._is_running
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by Carreau** [comment]
that seem to be an issue in the powerline extension, try to remove it.

**Comment by danlub** [comment]
> that seem to be an issue in the powerline extension, try to remove it.

That's possible, yes. None of this happened on my other installs, and the one that failed is the one with powerline.

I don't have access now, so I can't test if this will fix it, but it seems that your suggestion would do it. I'll update this when I can try

Thanks!

**Comment by danlub** [comment]
Yep, it was that. It's already reported in powerline/powerline/issues/1953.

Thanks for the help!
I'll close now
