### ISSUE TITLE
IPython crashes with message 'UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed'

### ISSUE THREAD

**Issue by wtorcaso** [ipython/ipython#11489]
In a Vagrant VM, hosted on a MacBook, run ipython

Then type Option-?  (option questionmark)

(That is not what I meant to do.  I have no idea if it is reasonable input or not)

The result is this traceback

In [1]: ??
The history saving thread hit an unexpected error (UnicodeEncodeError('utf-8', '\udcc3\udcb7', 0, 2, 'surrogates not allowed')).History will not be written to the database.
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django_extensions/management/commands/shell_plus.py", line 448, in handle
    shell()
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/django_extensions/management/commands/shell_plus.py", line 255, in run_ipython
    start_ipython(argv=ipython_arguments, user_ns=imported_objects)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 471, in interact
    self.run_cell(code, store_history=True)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2690, in run_cell
    cell_name = self.compile.cache(cell, self.execution_count)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/core/compilerop.py", line 129, in cache
    name = code_name(code, number)
  File "/home/vagrant/.virtualenvs/ousweb/lib/python3.6/site-packages/IPython/core/compilerop.py", line 58, in code_name
    hash_digest = hashlib.sha1(code.encode("utf-8")).hexdigest()
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by PaulKuin** [comment]
I think I have a similar issue: iPython on Mac-OS, Python-3.5. 

When using cut and paste from an editor, going from ctrl-c and ctrl-v to xterms, I sometimes type ctrl-v in the xterm, and instead of a paste a ? is put in the input buffer. Hitting return results in a crash as reported above. It is VERY annoying.  

I'm not sure if this is a recent ipython issue or only in the 3.5 python version.  

Just looking at the last lines in the error report, 

File "/sciencesoft/anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2660, in run_cell
    cell_name = self.compile.cache(cell, self.execution_count)
  File "/sciencesoft/anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/core/compilerop.py", line 129, in cache
    name = code_name(code, number)
  File "/sciencesoft/anaconda3/envs/astroconda/lib/python3.5/site-packages/IPython/core/compilerop.py", line 58, in code_name
    hash_digest = hashlib.md5(code.encode("utf-8")).hexdigest()
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce3' in position 0: surrogates not allowed

It seems to me that the last statement is not protected and causes the crash. 

I'm not familiar with this code, so if one of its developers can have another look at it, that would be super!
