### ISSUE TITLE
Ipython in sublime, TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by OpenWaygate** [ipython/ipython#11508]
I want to use Ipython in sublime with sublimeREPL, win 10, conda, python 3.6.7, ipython 7.1.1
this is my modified file of sublimeREPL in Sublime Text 3\Packages\SublimeREPL\config\Python\ipy_repl.py
```javascript {.line-numbers}
# https://gist.github.com/pe224/ec5d7effa26e8f736fa2f6bb8f515606
import os
import json
import socket
import threading

activate_this = os.environ.get("SUBLIMEREPL_ACTIVATE_THIS", None)
# turn off pager
os.environ['TERM'] = 'emacs'

if activate_this:
    with open(activate_this, "r") as f:
        exec(f.read(), {"__file__": activate_this})

try:
    import jupyter_console.app
    JUPYTER = True
except ImportError:
    JUPYTER = False

if not JUPYTER:
    try:
        import IPython
        IPYTHON = True
        version = IPython.version_info[0]
    except ImportError:
        # for virtualenvs w/o IPython
        import code
        code.InteractiveConsole().interact()

# Jupyter and IPython 4+
if JUPYTER or (IPYTHON and version > 3):
    from traitlets.config.loader import Config
# all other versions
else:
    from IPython.config.loader import Config

editor = "subl -w"

cfg = Config()
cfg.ZMQTerminalInteractiveShell.simple_prompt = True
cfg.InteractiveShell.readline_use = False
cfg.InteractiveShell.autoindent = True
cfg.InteractiveShell.colors = "NoColor"
cfg.InteractiveShell.editor = os.environ.get("SUBLIMEREPL_EDITOR", editor)

if JUPYTER:
    app = jupyter_console.app.ZMQTerminalIPythonApp(config=cfg, user_ns={})
elif IPYTHON:
    app = IPython.terminal.ipapp.TerminalIPythonApp(config=cfg, user_ns={})

app.initialize()

ac_port = int(os.environ.get("SUBLIMEREPL_AC_PORT", "0"))
ac_ip = os.environ.get("SUBLIMEREPL_AC_IP", "127.0.0.1")

if ac_port:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((ac_ip, ac_port))


def read_netstring(s):
    size = 0
    while True:
        ch = s.recv(1)
        if ch == b':':
            break
        size = size * 10 + int(ch)
    msg = b""
    while size != 0:
        msg += s.recv(size)
        size -= len(msg)
    ch = s.recv(1)
    assert ch == b','
    return msg


# def send_netstring(sock, msg):
#     payload = b"".join([str(len(msg)).encode("ascii"),
#                         b':', msg.encode("utf-8"), b','])
#     sock.sendall(payload)
def send_netstring(sock, msg):
    payload = b"".join([str(len(msg)).encode("ascii"),
                        b':', msg, b','])
    sock.sendall(payload)


def complete(shell, req):
    # Jupyter
    if JUPYTER:
        result = shell.Completer.complete_request(
            req['line'], req['cursor_pos'])
        return (req['line'], result['matches'])
    # Ipython 4
    elif IPYTHON and version > 3:
        return shell.complete(**req)
    # Ipython 1-3
    else:
        return []


def handle():
    while True:
        msg = read_netstring(s).decode("utf-8")
        try:
            req = json.loads(msg)
            result = complete(app.shell, req)
            res = json.dumps(result)
            send_netstring(s, res)
        except Exception:
            send_netstring(s, b"[]")


if ac_port:
    t = threading.Thread(target=handle)
    t.start()

app.start()

if ac_port:
    s.close()
```

Then I open Ipython in sublime with sublimeREPL, 
``` javascript {.line-numbers}
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.



In [1]: import tensorflow as tf

In [2]: tf.enable_eager_execution()

In [3]: a = tf.constant(1)
2018-11-25 16:57:18.037657: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2

In [4]: [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Python\envs\py37\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Python\envs\py37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Python\envs\py37\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Python\envs\py37\lib\site-packages\ipykernel\kernelbase.py", line 572, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "C:\Python\envs\py37\lib\site-packages\ipykernel\ipkernel.py", line 348, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "C:\Python\envs\py37\lib\site-packages\ipykernel\ipkernel.py", line 373, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "C:\Python\envs\py37\lib\site-packages\IPython\core\completer.py", line 485, in rectify_completions
    completions = list(completions)
  File "C:\Python\envs\py37\lib\site-packages\IPython\core\completer.py", line 1809, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "C:\Python\envs\py37\lib\site-packages\IPython\core\completer.py", line 1853, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "C:\Python\envs\py37\lib\site-packages\IPython\core\completer.py", line 1977, in _complete
    text = self.splitter.split_line(line_buffer, cursor_pos)
  File "C:\Python\envs\py37\lib\site-packages\IPython\core\completer.py", line 563, in split_line
    l = line if cursor_pos is None else line[:cursor_pos]
TypeError: 'NoneType' object is not subscriptable
```
It seems that every time this extra outpu about 'AVX AVX2' appears, the ipython will crash.
```javascript {.line-numbers}
In [3]: a = tf.constant(1)
2018-11-25 16:57:18.037657: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
```

**Comment by matthewgdv** [comment]
I'm getting the same issue (at least I think it's the same one) in Hydrogen on Atom. It pretty much happens constantly and the stack trace is:

    [IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): 
    File "C:\Python\envs\defaultenv\Lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell [33;1myield[m gen.maybe_future(handler(stream, idents, msg)) [36m | | | | -> {'header': {'username': 'matth', 'session': '00000000-0000-0000-0000-000000000000', 'msg_type': 'complete_request', 'msg_id': 'c...[m [36m | | | -> [b'dealer552366cd-77bb-4523-847f-052d06ab0100'][m [36m | | -> <zmq.eventloop.zmqstream.ZMQStream object at 0x0000020165FE64A8>[m [36m | -> <bound method Kernel.complete_request of <ipykernel.ipkernel.IPythonKernel object at 0x0000020165FE6A58>>[m [36m -> [m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\tornado\gen.py", line 735, in run value = future.result() [36m -> None[m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\tornado\gen.py", line 209, in wrapper yielded = [35;1mnext[m(result) [36m| -> [m [36m-> None[m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\ipykernel\kernelbase.py", line 580, in complete_request matches = [33;1myield[m gen.maybe_future(self.do_complete(code, cursor_pos)) [36m | | | -> 0[m [36m | | -> ''[m [36m | -> <ipykernel.ipkernel.IPythonKernel object at 0x0000020165FE6A58>[m [36m -> [m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\ipykernel\ipkernel.py", line 348, in do_complete [33;1mreturn[m self._experimental_do_complete(code, cursor_pos) [36m | | -> 0[m [36m | -> ''[m [36m -> <ipykernel.ipkernel.IPythonKernel object at 0x0000020165FE6A58>[m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\ipykernel\ipkernel.py", line 373, in _experimental_do_complete completions = [35;1mlist[m(_rectify_completions(code, raw_completions)) [36m | | -> [m [36m | -> ''[m [36m -> [m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\IPython\core\completer.py", line 485, in rectify_completions completions = [35;1mlist[m(completions) [36m| -> [m [36m-> [m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\IPython\core\completer.py", line 1816, in completions for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000): 
    File "C:\Python\envs\defaultenv\Lib\site-packages\IPython\core\completer.py", line 1860, in _completions full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column) 
    File "C:\Python\envs\defaultenv\Lib\site-packages\IPython\core\completer.py", line 1984, in _complete text = self.splitter.split_line(line_buffer, cursor_pos) [36m| | | -> 0[m [36m| | -> None[m [36m| -> <IPython.core.completer.IPCompleter object at 0x000002016604A0F0>[m [36m-> None[m 
    File "C:\Python\envs\defaultenv\Lib\site-packages\IPython\core\completer.py", line 563, in split_line l = line if cursor_pos is None else line[:cursor_pos] [36m | | | -> 0[m [36m | | -> None[m [36m | -> 0[m [36m -> None[m TypeError: 'NoneType' object is not subscriptable

**Comment by nscozzaro** [comment]
I get the same error, but in JupyterLab
![image](https://user-images.githubusercontent.com/15185105/73391301-aac07c80-42a5-11ea-8157-b580c6d75a1d.png)

**Comment by TheHubbit** [comment]
I ran into this issue in a different situation too and just created a pull request that adds a check for line_buffer before calling self.splitter.split_line().
