### ISSUE TITLE
autoreload fails with tensors

### ISSUE THREAD

**Issue by sanyam5** [ipython/ipython#11558]
Reproducing the bug
===============

hola.py
```
import torch

class Bhai:
    three_ones = torch.ones(3)

    pass
```

test.ipynb
```
In[1]:
%load_ext autoreload
%autoreload 2

In[2]:
from hola import *

In[3]:
# before executing this cell modify something minor (like adding a space) in `hola.py`
print("hello")
```

Before executing the third cell modify something minor (like adding a space) in `hola.py`. I get this error

```
[autoreload of ipyt failed: Traceback (most recent call last):
  File "/home/sanyam/miniconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/sanyam/miniconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 393, in superreload
    update_generic(old_obj, new_obj)
  File "/home/sanyam/miniconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 330, in update_generic
    update(a, b)
  File "/home/sanyam/miniconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 278, in update_class
    if old_obj == new_obj:
RuntimeError: bool value of Tensor with more than one value is ambiguous
]

```

**Comment by takluyver** [comment]
Autoreload is something of a brittle hack; it doesn't sit well with the way Python usually works, so it will probably always have issues in corner cases. But if you can figure  out a safe way to fix this one which is unlikely to break anything else, feel free to make a pull request.

**Comment by sanyam5** [comment]
Thanks. One way to handle it could be to explicity check if `==` returns `True` by `if (old_obj == new_obj) is True`. This solution will treat some essentially equal tensors as unequal. Now, I am not fully aware of how autoreload works but it seems that in that case a new tensor will be created. This would be a little bit efficient (compute and memory wise) but should not introduce any new bugs.

Is this solution acceptable? :)

**Comment by takluyver** [comment]
I think that's reasonable, at a glance. You've made the pull request against your own fork of IPython; don't forget to open it against this repository.

**Comment by sanyam5** [comment]
Thank you for pointing that out! I've now made a pull request against the main fork :)
