### ISSUE TITLE
Can't start in directory with file named array.py

### ISSUE THREAD

**Issue by anielsen001** [ipython/ipython#11566]
Running Ipython 7.2.0 with python 3.7.1 on Ubuntu 16.04 from the command line. if I have a file called array.py in the directory that I try to start ipython, ipython attempts to load the array package from this file instead of the system package. 

Steps to recreate:
1. create empty directory
`mkdir temp`
2. put a file called array.py in the directory
`touch temp/array.py`
3. switch to that directory and try to start ipython
`cd temp`
`ipython`

Is this because the CWD is put on the python path before ipython startup is complete?

Here is the crash result
```
apn@aria:~/temp$ touch array.py
apn@aria:~/temp$ ipython
Python 3.7.1 (default, Oct 27 2018, 17:16:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 595, in _run_async
    self._redraw()
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 444, in _redraw
    self.renderer.render(self, self.layout)
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/renderer.py", line 530, in render
    size = output.get_size()
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/output/vt100.py", line 429, in get_size
    rows, columns = _get_size(stdout.fileno())
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/output/vt100.py", line 364, in _get_size
    buf = array.array(b'h' if six.PY2 else u'h', [0, 0, 0, 0])
AttributeError: module 'array' has no attribute 'array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apn/sw/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/apn/sw/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/apn/sw/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/apn/sw/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/apn/sw/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 494, in mainloop
    self.interact()
  File "/home/apn/sw/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 477, in interact
    code = self.prompt_for_code()
  File "/home/apn/sw/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 406, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 733, in prompt
    return run_sync()
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 722, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/apn/sw/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 654, in _run_async2
    assert not self._is_running
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by anielsen001** [comment]
yes, I did. It was set to this:

```
apn@aria:~/temp/array$ echo $PYTHONPATH
:/opt/movidius/caffe/python
```
when I cleared it, ipython started without an issue.

**Comment by takluyver** [comment]
OK, that's expected, then. `array.py` shadows the standard library `array` module, which `prompt_toolkit`, a depdendency of IPython,  is using. Your PYTHONPATH adds the current working directory to be used for imports (the empty string before the first colon).

IPython also adds the current working directory to find importable modules, but it does that after it has started up, so modules like `array` will already have been imported from the correct location.
