### ISSUE TITLE
Small recursion limit immediately crashes

### ISSUE THREAD

**Issue by pganssle** [ipython/ipython#11576]
I seem to be able to consistently crash the interpreter by setting the recursion limit to 30, with IPython 7.2.0, Python 3.7.1 on Arch Linux:

```
$ ipython
Python 3.7.1 (default, Nov  1 2018, 15:09:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys

In [2]: sys.setrecursionlimit(30)
```

This crashes with the following Traceback:

<details>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 651, in _run_async2
    f = From(_run_async())
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 46, in From
    return ensure_future(obj)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 21, in ensure_future
    return _run_coroutine(future_or_coroutine)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 67, in _run_coroutine
    result_f = loop.create_future()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/base.py", line 107, in create_future
    return Future(loop=self)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 27, in __init__
    assert loop is None or isinstance(loop, EventLoop)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 494, in mainloop
    self.interact()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 477, in interact
    code = self.prompt_for_code()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 406, in prompt_for_code
    **self._extra_prompt_options())
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 733, in prompt
    return run_sync()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 722, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 654, in _run_async2
    assert not self._is_running
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Exception ignored in: <function Future.__del__ at 0x7f94230d76a8>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 48, in __del__
AttributeError: 'Future' object has no attribute '_exception'
</details>

It seems to have something to do with the implicit event loop in the async support.

**Comment by Carreau** [comment]
most likely also limited by Jedi that does use recursion quite a lot to inspect things. 
Not sure there is much we can do.

**Comment by pganssle** [comment]
@Carreau Well the problem is that it actually crashes IPython itself. It's a pretty weird edge case I'll grant you that, I think there are a few options to fixing it (if desirable):

1. Mock `sys.setrecursionlimit()` so that it's not possible to set it low enough that it would crash the main IPython process - Python itself does something like this: https://github.com/python/cpython/blob/ab67281e95de1a88c4379a75a547f19a8ba5ec30/Python/sysmodule.c#L777
2. See if it's possible to set the "low water mark" to a higher number in pure python without having to mock `sys.setrecursionlimit`.
3. Temporarily increase the recursion limit while calling IPython functions so that the REPL itself doesn't actually consume any of the stack depth

There may be structural changes to IPython that would obviate the problem, but I am not going to explore those because they're way out of proportion for fixing such a minor issue.

Possibly related is [bpo-25274](https://bugs.python.org/issue25274).
