### ISSUE TITLE
Using 'type()' in qtconsole results in TypeError

### ISSUE THREAD

**Issue by bathigpen** [ipython/ipython#11607]
ipykernel-5.1.0
IPython-7.2.0
qtconsole-4.4.3
tornado-5.1.1

both Linux and Mac  (Anaconda, version 2018.12, python 3.7)

In qtconsole, trying to use 'type()' results in a TypeError.  The error occurs immediately when entering 'type(', meaning as soon as I type the open-parenthesis character.  Possibly some sort of completion error?  Commenting out lines 863-868 of 'IPython/core/oinspect.py' removes the error.

Traceback follows:
```
Traceback (most recent call last):
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 593, in inspect_request
    content.get('detail_level', 0),
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 411, in do_inspect
    detail_level=detail_level
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 1765, in object_inspect_mime
    detail_level=detail_level
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/IPython/core/oinspect.py", line 600, in _get_info
    info = self._info(obj, oname=oname, info=info, detail_level=detail_level)
  File "/Users/localuser/anaconda3/lib/python3.7/site-packages/IPython/core/oinspect.py", line 863, in _info
    names = [sub.__name__ for sub in obj.__subclasses__()]
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

**Comment by Carreau** [comment]
Or just `type?` in plain IPython.

**Comment by Carreau** [comment]
see #11608
