### ISSUE TITLE
Jupyter doesn't recover web view of NotEbook

### ISSUE THREAD

**Issue by JavierRuano** [ipython/ipython#11605]
It is necessary to open the notebook in another browser, the browser, which i was using, cannot recover the web.
The notebook goes on running :-)

```
Traceback (most recent call last):
      File "C:\Users\Admin\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\tornado\web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbconvert\handlers.py", line 91, in get
        exporter = get_exporter(format, config=self.config, log=self.log)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbconvert\handlers.py", line 66, in get_exporter
        Exporter = get_exporter(format)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\nbconvert\exporters\base.py", line 110, in get_exporter
        % (name, ', '.join(get_export_names())))
    ValueError: Unknown exporter "ipynb", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
[E 23:07:54.390 NotebookApp] {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "es-ES,es;q=0.8,en-GB;q=0.5,en;q=0.3",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763",
      "Accept-Encoding": "gzip, deflate",
      "Host": "localhost:8888",
      "Connection": "Keep-Alive",
      "Cookie": "_xsrf=2|5790afa9|0d6043282581c90844742dab55ee16ac|1549893183; Webstorm-f904df39=ebe436ad-87e6-4b94-934d-660e827e99b1; username-localhost-8888=\"2|1:0|10:1550268542|23:username-localhost-8888|44:ZDRkNWE0OGJkYmVmNDQzMThkZTBmNGExZjg1MzZmMDU=|b06a8b10c24f12545ad2c93bc7a1784c36bc8805145d13541bf55ce475fb5c18\""
    }
[E 23:07:54.396 NotebookApp] 500 GET /nbconvert/ipynb/ObjectPreferences.ipynb?download=true (::1) 148.02ms referer=None
[E 23:07:59.401 NotebookApp] Uncaught exception GET /nbconvert/ipynb/ObjectPreferences.ipynb?download=true (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nbconvert/ipynb/ObjectPreferences.ipynb?download=true', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\Admin\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\tornado\web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbconvert\handlers.py", line 91, in get
        exporter = get_exporter(format, config=self.config, log=self.log)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\notebook\nbconvert\handlers.py", line 66, in get_exporter
        Exporter = get_exporter(format)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\nbconvert\exporters\base.py", line 110, in get_exporter
        % (name, ', '.join(get_export_names())))
    ValueError: Unknown exporter "ipynb", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
[E 23:07:59.409 NotebookApp] {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "es-ES,es;q=0.8,en-GB;q=0.5,en;q=0.3",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763",
      "Accept-Encoding": "gzip, deflate",
      "Host": "localhost:8888",
      "Connection": "Keep-Alive",
      "Cookie": "_xsrf=2|5790afa9|0d6043282581c90844742dab55ee16ac|1549893183; Webstorm-f904df39=ebe436ad-87e6-4b94-934d-660e827e99b1; username-localhost-8888=\"2|1:0|10:1550268542|23:username-localhost-8888|44:ZDRkNWE0OGJkYmVmNDQzMThkZTBmNGExZjg1MzZmMDU=|b06a8b10c24f12545ad2c93bc7a1784c36bc8805145d13541bf55ce475fb5c18\""
    }
```

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

**Comment by JavierRuano** [comment]
I felt that as unusual bug. Perhaps I should write it in tornado repository. Sorry.
