### ISSUE TITLE
PyQt5 event loop fails for PyQt >5.11 with No module named 'sip'

### ISSUE THREAD

**Issue by flutefreak7** [ipython/ipython#11612]
This is effectively a duplicate of a qtconsole issue: https://github.com/jupyter/qtconsole/issues/291

When I attempt to run a cell with `%gui qt` I get the following:

    Traceback (most recent call last):
      File "c:\python37\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
        ret = callback()
      File "c:\python37\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "c:\python37\lib\site-packages\ipykernel\kernelbase.py", line 306, in advance_eventloop
        eventloop(self)
      File "c:\python37\lib\site-packages\ipykernel\eventloops.py", line 129, in loop_qt5
        return loop_qt4(kernel)
      File "c:\python37\lib\site-packages\ipykernel\eventloops.py", line 116, in loop_qt4
        kernel.app = get_app_qt4([" "])
      File "c:\python37\lib\site-packages\IPython\lib\guisupport.py", line 114, in get_app_qt4
        from IPython.external.qt_for_kernel import QtGui
      File "c:\python37\lib\site-packages\IPython\external\qt_for_kernel.py", line 95, in <module>
        QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
      File "c:\python37\lib\site-packages\IPython\external\qt_loaders.py", line 309, in load_qt
        result = loaders[api]()
      File "c:\python37\lib\site-packages\IPython\external\qt_loaders.py", line 220, in import_pyqt5
        import sip
    ModuleNotFoundError: No module named 'sip'

As noted in the qtconsole issue, this is due to a backwards incompatibility: http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-11

The qtconsole PR is here: https://github.com/jupyter/qtconsole/issues/291

**Comment by flutefreak7** [comment]
This was my first PR ever! Woot!

**Comment by QuLogic** [comment]
Shouldn't this be closed by the above PR?

**Comment by ccordoba12** [comment]
Sure, it seems this was solved by PR #11613.
