### ISSUE TITLE
Infinite recursion when autoreloading a generic class

### ISSUE THREAD

**Issue by huzecong** [ipython/ipython#11619]
When using autoreload (`autoreload 2`) while a generic class is imported, it gives an error saying that autoreload failed due to exceeding maximum recursion depth. However, the class in question is still reloaded correctly.

The minimum working example is as follows. The code containing the generic class is stored in file `foo.py`:
```python
from typing import Generic, TypeVar

T = TypeVar('T')

class Foo(Generic[T]):
    def __init__(self, x: T) -> None:
        self.x = x
```

This is the IPython output. I have `%load_ext autoreload` and `%autoreload 2` stored in the startup script.
```
$ ipython
Python 3.6.3 (default, Mar 29 2018, 12:00:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from foo import Foo

In [2]: f = Foo[int](1)

In [3]: print(f.x)
1

In [4]: # at this point, change the __init__ code from 'self.x = x' to 'self.x = x * 2'
[autoreload of foo failed: Traceback (most recent call last):
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
RecursionError: maximum recursion depth exceeded
]

In [5]: f = Foo[int](1)

In [6]: print(f.x)
2
```

My system information is as follows:
```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '2e1cca5bc',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.3.0',
 'os_name': 'posix',
 'platform': 'Darwin-18.2.0-x86_64-i386-64bit',
 'sys_executable': '/Users/[redacted_user]/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 (default, Mar 29 2018, 12:00:21) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]'}
```

**Comment by ppmfloss** [comment]
Hi @huzecong, On my Debian 9 I am not able to reproduce this issue. Please see the interaction logs below. Can you please try with the latest version of IPython from github.

```shell
ppm@debian-9:~/ppm/python/ipython$ python3 -m IPython
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext autoreload                                                          

In [2]: %autoreload 2                                                                 

In [3]: from foo import Foo                                                           

In [4]: f = Foo[int](1)                                                               

In [5]: print(f.x)                                                                    
1

In [6]: # changed the code now from self.x = x to self.x = x * 2                      

In [7]: print(f.x)                                                                    
1

In [8]: # still works                                                                 

In [9]: f = Foo[int](1)                                                               

In [10]: print(f.x)                                                                   
2

In [11]: # now new code is automatically reloaded                                     

In [12]:  

```

**Comment by huzecong** [comment]
Hi @ppmfloss, thanks for the feedback! I've tried with the version from the master branch (`7.4.0-dev`), and tested on several different Python versions. The results are:
- Python 3.5.3: works fine.
- Python 3.6.0: works fine.
- Python 3.6.2: works fine.
- Python 3.6.3: the issue still exists.
- Python 3.6.4: the issue still exists.
- Python 3.7.0: works fine.

So it appears this only affects certain versions of Python. I did a search and my wild guess is that it could be related to Python bugs, for instance <https://github.com/python/typing/issues/506>. Not sure if you would plan to add workarounds to target Python versions, but I guess the better solution for me is to upgrade my Python installation.

**Comment by DSamuylov** [comment]
I have the same issue with Python 3.6.8 on my Mac.

**Comment by rohaldbUni** [comment]
Same
