### ISSUE TITLE
Kernel error in Jupyter notebook

### ISSUE THREAD

**Issue by Heloul** [ipython/ipython#11669]
Hello all, 
Jupyter notebook used to work normally for me untill this afternoon where I upgraded pandas version, and then python's version. I am not using anaconda so I do everything with 'pip'. 
Jupyter notebook opens normally but I have the following Kernel error : 

```
Traceback (most recent call last):
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
    self.start_restarter()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\jupyter_client\ioloop\manager.py", line 52, in start_restarter
    self._restarter.start()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\jupyter_client\ioloop\restarter.py", line 47, in start
    self._pcallback.start()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\ioloop.py", line 1209, in start
    self._schedule_next()
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\ioloop.py", line 1237, in _schedule_next
    self._update_next(self.io_loop.time())
  File "C:\Users\Hela\Documents\python\User\lib\site-packages\tornado\ioloop.py", line 1244, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
**TypeError: unsupported operand type(s) for *: 'ZMQIOLoop' and 'float'**
```

Thanks for your help !

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
