### ISSUE TITLE
Convert jupyter notebook to pdf via LaTex

### ISSUE THREAD

**Issue by dedalus94** [ipython/ipython#11686]
Hi, I am trying to convert a jupyter notebook into a pdf file. The result's just 12 pages while the notebook is much longer. No error is displayed, it just downloads the file with missing content. I have tried to run this code in the terminal:

 ipython nbconvert --to pdf Final_report.ipynb 

But I have no idea what the output means...

Shall I just assume that there is a problem with LaTex in the line mentioned in the output? 
```
dario@dario-SATELLITE-Radius-15-P50W-C-10P:~$ ipython nbconvert --to pdf Final_report.ipynb 
[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter nbconvert` in the future
[NbConvertApp] Converting notebook Final_report.ipynb to pdf
Traceback (most recent call last):
  File "/home/dario/.local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/dario/.local/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/dario/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/dario/.local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 351, in start
    return self.subapp.start()
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/dario/.local/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/dario/.local/lib/python2.7/site-packages/nbformat/__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "/home/dario/.local/lib/python2.7/site-packages/nbformat/__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "/home/dario/.local/lib/python2.7/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/home/dario/.local/lib/python2.7/site-packages/nbformat/reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
NotJSONError: Notebook does not appear to be JSON: u''...

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by dedalus94** [comment]
I solved the problem by converting to html first and then pdf. The file was maybe too long (100+ pages) because there was an executed cell containing a for loop which had generated many plots.

**Comment by Carreau** [comment]
Hum that is weird. Happy you solved it.

Closing. 

You may want to also ask into https://github.com/jupyter/nbconvert next time, and on the discourse forum (https://discourse.jupyter.org/)
