### ISSUE TITLE
Missing ship numpy testing decorator

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11709]
```
Traceback (most recent call last):
  File "/Users/mbussonnier/dev/cpython/test/bin/iptest", line 6, in <module>
    from IPython.testing.iptestcontroller import main
  File "/Users/mbussonnier/dev/cpython/test/lib/python3.8/site-packages/IPython/testing/iptestcontroller.py", line 23, in <module>
    from .iptest import (
  File "/Users/mbussonnier/dev/cpython/test/lib/python3.8/site-packages/IPython/testing/iptest.py", line 40, in <module>
    from IPython.external.decorators import KnownFailure, dec
ImportError: cannot import name 'dec' from 'IPython.external.decorators' (/Users/mbussonnier/dev/cpython/test/lib/python3.8/site-packages/IPython/external/decorators/__init__.py)
```

Seem like `dec` is not define ini out `_decorator.py` 

Appologies for shortness boarding a plane

**Comment by dhomeier** [comment]
I can confirm this for Python 3.7:
```
/sw/bin/python3.7 -B IPython/testing/iptest.py IPython
Traceback (most recent call last):
  File "IPython/testing/iptest.py", line 40, in <module>
    from IPython.external.decorators import KnownFailure, dec
ImportError: cannot import name 'dec' from 'IPython.external.decorators' (/scratch.noindex/fink.build/ipython-py37-7.5.0-1/ipython-7.5.0/build/lib/IPython/external/decorators/__init__.py)
```
also using the decorators fails with
```
Python 3.7.3 (default, May  5 2019, 04:25:55) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from IPython.testing import decorators as dec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.7/site-packages/IPython/testing/decorators.py", line 336, in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
NameError: name 'dec' is not defined
```
installing `numpy` resolves this, making it a dependency for the test suite as well as for using `IPython.testing` by outside applications.

**Comment by dhomeier** [comment]
Seems to be due to a252070 and related commits, which try to import `dec` from `numpy.testing` and on `ImportError` import the rest from `._decorators`, but leaving `dec` undefined.

Adding this line to [`external/decorators/__init__.py`](https://github.com/ipython/ipython/blob/master/IPython/external/decorators/__init__.py):
```
except ImportError:
    from ._decorators import *
    from ...testing import decorators as dec
```
enabled `from IPython.testing import decorators as dec` to work, but not `from IPython.external.decorators import KnownFailure, dec` - unless the former import was called first. I.e. `iptest.py` still fails...
