### ISSUE TITLE
Ctrl-C in page crash repl

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11721]
```
import numpy as np
np?
Ctrl-C
q  # to quit page
Ctrl-C # again
```

```
In [5]: numpy?
^C
KeyboardInterrupt escaped interact()


Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 498, in mainloop
    self.interact()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 481, in interact
    code = self.prompt_for_code()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 410, in prompt_for_code
    **self._extra_prompt_options())
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in prompt
    return run_sync()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 681, in run
    f = self.run_async(pre_run=pre_run)
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 527, in run_async
    assert not self._is_running, 'Application is already running.'
AssertionError: Application is already running.

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

^CException ignored in: <module 'threading' from '/Users/bussonniermatthias/anaconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by kmaork** [comment]
This seems to be resolved in the current version
