### ISSUE TITLE
Arm failures in test_embed.test_nest_embed

### ISSUE THREAD

**Issue by hroncok** [ipython/ipython#11754]
I constantly get this error on arm (armv7hl and aarch64):

```
..E............
======================================================================
ERROR: test that `IPython.embed()` is nestable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 509, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/ipython-7.5.0-1.fc31.noarch/usr/lib/python3.7/site-packages/IPython/testing/decorators.py", line 212, in skipper_func
    return f(*args, **kwargs)
  File "/builddir/build/BUILDROOT/ipython-7.5.0-1.fc31.noarch/usr/lib/python3.7/site-packages/IPython/terminal/tests/test_embed.py", line 76, in test_nest_embed
    child.expect(ipy_prompt)
  File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0xffffb067db70>
command: /usr/bin/python3
args: ['/usr/bin/python3', '-m', 'IPython', '--colors=nocolor']
buffer (last 100 chars): b''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 11509
child_fd: 10
closed: False
timeout: 5
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b']:')
----------------------------------------------------------------------
Ran 15 tests in 65.198s
FAILED (errors=1)
```

Does it simply mean the timeout is too low for a slow arm builder and should be increased, or does it actually mean something is broken?

(I'll investigate.)

**Comment by hroncok** [comment]
Increasing the timeout makes the test pass. Would you accept a PR that makes the time configurable via an environment variable?

**Comment by Carreau** [comment]
Yes, that shouldn't be an issue; you can even increase the default timeout.
