### ISSUE TITLE
AnsibleInventory - not working with vars section

### ISSUE THREAD

**Issue by jifox** [ipython/ipython#11762]
There will be an error with following valid Ansible yaml inventory file:

## Error inventory file - working with Ansible
```yaml
---
all:
  vars:
    is_develop: true

  # All linux server
  children:
    linux:

      hosts:
        scvbrsa01:
```
## Nornir - Parseable inventory file
```yaml
---
all:
  # vars:
  #  is_develop: true

  # All linux server
  children:
    linux:

      hosts:
        scvbrsa01:
```

## Nornir Version
```bash
ansible@ubuntu:~ $ pip list | grep nornir
nornir                       2.0.0               /home/ansible/nornir/nornir-workshop/src/nornir
```

The `vars:` section will raise an error:
```bash
ansible@ubuntu:~/nornir/test_nornir $ cd /home/ansible/nornir/test_nornir ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/ansible/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 39909 /home/ansible/nornir/test_nornir/test_nornir.py 
Traceback (most recent call last):
  File "/home/ansible/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/ansible/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/ansible/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ansible/nornir/test_nornir/test_nornir.py", line 5, in <module>
    nr = InitNornir(config_file="nornir_config.yml")
  File "/home/ansible/nornir/nornir-workshop/src/nornir/nornir/init_nornir.py", line 39, in InitNornir
    transform_function=transform_function, config=conf, **conf.inventory.options
  File "/home/ansible/nornir/nornir-workshop/src/nornir/nornir/core/deserializer/inventory.py", line 111, in deserialize
    deserialized = cls(*args, **kwargs)
  File "/home/ansible/nornir/nornir-workshop/src/nornir/nornir/plugins/inventory/ansible.py", line 251, in __init__
    hosts=host_vars, groups=group_vars, defaults=defaults, *args, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pydantic/main.py", line 190, in __init__
    self.__setstate__(self._process_values(data))
  File "/usr/local/lib/python3.6/dist-packages/pydantic/main.py", line 360, in _process_values
    return validate_model(self, input_data)
  File "/usr/local/lib/python3.6/dist-packages/pydantic/main.py", line 533, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
defaults -> is_develop
  extra fields not permitted (type=value_error.extra)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Carreau** [comment]
Hi there, thanks for your report, 

Unfortunately this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

You also seem to be searching for help for a project that _uses_ ipython; maybe [nornir](https://github.com/nornir-automation/nornir), pydantic or ansible. I've never heard of the first two until today so will not be able to help you much. 

Closing as there is not much actionable from my end, but feel free to keep commenting
