### ISSUE TITLE
raise StopIteration

### ISSUE THREAD

**Issue by hamedtorky** [ipython/ipython#11866]
When running ipython in terminal 

```bash

>> ipython
Traceback (most recent call last):
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 531, in _load_config_files
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hamed/.local/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/core/application.py", line 389, in initialize
    self.load_config_file()
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/core/application.py", line 254, in load_config_file
    path=self.config_file_paths
  File "<string>", line 2, in load_config_file
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/hamed/.local/lib/python3.7/site-packages/IPython/config/application.py", line 538, in load_config_file
    for config in self._load_config_files(filename, path=path, log=self.log):
RuntimeError: generator raised StopIteration

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```
but running with `sudo` it true

**Comment by Carreau** [comment]
There hasn't been a `IPython/config/application.py` for close to 5 years. 
Please upgrade.
