### ISSUE TITLE
Unable to launch ipython

### ISSUE THREAD

**Issue by jaib1** [ipython/ipython#11860]
I'm using a Windows10 PC. Tried launching ipython from anaconda, winpython, and after a direct install from pypi. Keep getting this same error (full traceback shown below):

```
Traceback (most recent call last):
  File "c:\users\jai\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jai\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jai\Python\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\users\jai\python\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\users\jai\python\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<c:\users\jai\python\lib\site-packages\decorator.py:decorator-gen-114>", line 2, in initialize
  File "c:\users\jai\python\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\jai\python\lib\site-packages\IPython\terminal\ipapp.py", line 317, in initialize
    self.init_shell()
  File "c:\users\jai\python\lib\site-packages\IPython\terminal\ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "c:\users\jai\python\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\users\jai\python\lib\site-packages\IPython\terminal\interactiveshell.py", line 459, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "c:\users\jai\python\lib\site-packages\IPython\core\interactiveshell.py", line 693, in __init__
    self.init_magics()
  File "c:\users\jai\python\lib\site-packages\IPython\terminal\interactiveshell.py", line 442, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "c:\users\jai\python\lib\site-packages\IPython\core\interactiveshell.py", line 2246, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "c:\users\jai\python\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "c:\users\jai\python\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "c:\users\jai\python\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "c:\users\jai\python\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\users\jai\python\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "c:\users\jai\python\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "c:\users\jai\python\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "c:\users\jai\python\lib\sre_parse.py", line 816, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "c:\users\jai\python\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "c:\users\jai\python\lib\sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "c:\users\jai\python\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 9
```

**Comment by Carreau** [comment]
What is the value of the `PATHEXT` environment variable ?

**Comment by jaib1** [comment]
```
C:\Users\Jai\Anaconda3\Library\bin;C:\Users\Jai\Anaconda3\condabin;C:\Users\Jai\Anaconda3\Scripts;C:\Users\Jai\Anaconda3;.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```
Anaconda3 still shows up here and in my path even after I've uninstalled

**Comment by Carreau** [comment]
PATHEXT should only contain extensions as far as I understand.

`C:\Users\Jai\Anaconda3\Library\bin`,`C:\Users\Jai\Anaconda3\condabin` and `C:\Users\Jai\Anaconda3\Scripts;C:\Users\Jai\Anaconda3` likely need to be in `PATH`, Not `PATHEXT`.

The error is due to the first `\U` in PATHEXT if my reading is correct.

I'm unsure how to change env variable in windows, but you likely need to fix this, by reseting `PATHEXT` to `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`

**Comment by jaib1** [comment]
great, thanks! I'll close this now. Do you know how the 'PATHEXT' variable got set with these values, out of curiosity?

**Comment by Carreau** [comment]
I'm not familiar enough with Windows. Happy it was solved. Enjoy your
coding.
