### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'filenames'

### ISSUE THREAD

**Issue by 0anton** [ipython/ipython#11875]
Hi,

I am trying to convert ipynb notebook to html using customized template, which stores png resources as external files. The template I use is following:

```
separate_image_html.tpl:

{%- extends 'full.tpl' -%}

{% block data_png scoped -%}
    <div class="output_png output_subarea {{ extra_class }}">
        <img src="{{ output.metadata.filenames['image/png'] | path2url }}">
    </div>
{%- endblock data_png %}

```

Command I use to convert the notebook:

`jupyter nbconvert --to=html --HTMLExporter.template_file=separate_image_html.tpl  ./matplotlib.ipynb
`

My environment is:

```
$ pip list | grep nbconvert
nbconvert                         5.6.0
            

$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '741169a00',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.7.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-51-generic-x86_64-with-debian-10.0',
 'sys_executable': '/usr/local/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.7.4 (default, Aug 14 2019, 12:09:51) \n[GCC 8.3.0]'}

``` 
 

The traceback I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 322, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jovyan/UpgradeReports/misc/separate_image_html.tpl", line 1, in top-level template code
    {%- extends 'full.tpl' -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/full.tpl", line 2, in top-level template code

    {% from 'mathjax.tpl' import mathjax %}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 1, in top-level template code
    {%- extends 'display_priority.tpl' -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in top-level template code
    {%- extends 'null.tpl' -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 26, in top-level template code
    {%- block body -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/full.tpl", line 99, in block "body"
    {{ super() }}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 28, in block "body"
    {%- block any_cell scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 31, in block "any_cell"
    {%- block codecell scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 6, in block "codecell"
    {{ super() }}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 41, in block "codecell"
    {%- block output_group -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 19, in block "output_group"
    {{ super() }}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 45, in block "output_group"
    {%- block outputs scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 47, in block "outputs"
    {%- block output scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 73, in block "output"
    {{ super() }}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 61, in block "output"
    {%- block display_data scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 62, in block "display_data"
    {%- block data_priority scoped -%}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 97, in block "data_priority"

    {{ super() }}
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 15, in block "data_priority"
    {%- block data_png -%}
  File "/home/jovyan/UpgradeReports/misc/separate_image_html.tpl", line 5, in block "data_png"
    <img src="{{ output.metadata.filenames['image/png'] | path2url }}">
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'filenames'

```

Notebook I'd like to convert is has the following sample python code:

```
%matplotlib inline 
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

plt.show()

```

This looks to me similar to #7746, but I don't have any suspicious metadata.

```
cat matplotlib.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "<removed for breavity>\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "%matplotlib inline \n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "# Data for plotting\n",
    "t = np.arange(0.0, 2.0, 0.01)\n",
    "s = 1 + np.sin(2 * np.pi * t)\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "ax.plot(t, s)\n",
    "\n",
    "ax.set(xlabel='time (s)', ylabel='voltage (mV)',\n",
    "       title='About as simple as it gets, folks')\n",
    "ax.grid()\n",
    "\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```

How can I create a template, which produces png images as external resources during conversion to html?

**Comment by 0anton** [comment]
Sorry, wrong assumption. 

Must specify preprocessor like:

jupyter nbconvert --execute --to=html --HTMLExporter.preprocessors=[\'nbconvert.preprocessors.ExtractOutputPreprocessor\'] --HTMLExporter.template_file=basic.tpl  ./matplotlib.ipynb
