### ISSUE TITLE
[TerminalIPythonApp] ERROR | Failed to open SQLite history

### ISSUE THREAD

**Issue by vict0rsch** [ipython/ipython#11893]
Here's how the error occurs ; I'm working on a slurm-managed shared cluster:

```
$ module load anaconda/3
$ source $CONDA_ACTIVATE
$ conda create --name 'clouds' python=3.6.4
[...]
$ conda install ipython
[... no error]
$ which ipython
/network/home/schmidtv/.conda/envs/clouds/bin/ipython # as expected
$ ipython
[TerminalIPythonApp] ERROR | Failed to open SQLite history /network/home/schmidtv/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | History file was moved to /network/home/schmidtv/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /network/home/schmidtv/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | History file was moved to /network/home/schmidtv/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /network/home/schmidtv/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | Failed to load history too many times, history will not be saved.
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sqlite3

In [2]: sqlite3.sqlite_version
Out[2]: '3.29.0'

In [3]: sqlite3.version
Out[3]: '2.6.0'

In [4]: import IPython

In [5]: print(IPython.sys_info())
{'commit_hash': 'c233c25ab',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/network/home/schmidtv/.conda/envs/clouds/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.8.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid',
 'sys_executable': '/network/home/schmidtv/.conda/envs/clouds/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) \n'
                '[GCC 7.2.0]'}
```

I'm aware of #9909 and #11407 but none help as it seems my sqlite dist is up to date

**Comment by andres-fernandez-leon** [comment]
I had the same problem in two different environments: AWS and a cluster. Both were related to LUSTRE file system. I solved them in two different ways.
Does your cluster employ LUSTRE??

**Comment by martijnkruiten** [comment]
We had the same issue and the culprit was that file locking was not working on our new NFS fileserver because `rpc-statd.service` was disabled. The output of `dmesg` was something like: `lockd: cannot monitor <client>`.

**Comment by ashkan-leo** [comment]
I also face this issue. I'm opening an ipython repl through Emacs. I get the following exceptiosn:
```python
[TerminalIPythonApp] ERROR | Failed to create history session in /Users/ashkanaleali/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/Users/ashkanaleali/w/fantasysports/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "</Users/ashkanaleali/w/fantasysports/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/decorator.py:decorator-gen-22>", line 2, in new_session
  File "/Users/ashkanaleali/w/fantasysports/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "/Users/ashkanaleali/w/fantasysports/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/IPython/core/history.py", line 570, in new_session
    self.session_number = cur.lastrowid
sqlite3.OperationalError: database is locked
Python 3.7.3 (default, Sep  5 2019, 17:14:41) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

```

**Comment by lisanhu** [comment]
Same issue here. I'm working on a university lab machine that uses lustre.

**Comment by i-chaochen** [comment]
Same issue in a slurm cluster.

**Comment by tonmoy-saikia** [comment]
I confirm this as well.  Working on a slurm cluster with home on nfs. 
changing the ipython-dir to a local disk works
Eg: ipython --ipython-dir=/tmp

**Comment by liwt31** [comment]
This seems to be an issue with the network file system. You can try the following C code to test if the `flock` system call works normally:
```
#include <stdio.h>
#include <sys/file.h>

int main(){
    int fd = open("test.db", O_RDWR | O_CREAT);
    fprintf(stderr, "Prepare Locking File: %d\n", fd);
    int res = flock(fd, LOCK_SH);
    fprintf(stderr, "Result: %d\n", res);
}
```
For me, the system call hangs forever, although it works perfectly fine for local disks.

My solution to the problem is reporting the issue to the cluster manager, who restarted the NFS, and then the problem is solved.

**Comment by perrymil** [comment]
Hi All, 

Databases don't work on lustre based file systems. Applications such as sqlite that require POSIX locking won't work on lustre. Such applications (like sqlite) are not supported on lustre.

**Comment by antofthy** [comment]
I've been battling this issue (Notebook/ipykernel locking up jupyter lab web server on start) on and off for 3 years!
Just was given a pointer from Jupyter forum, which pointed out the problem.

The solution being... [set SQLite history to memory](https://github.com/ipython/ipython/blob/3df473c58741eadf468cfb761ac9b7d9db576be4/IPython/core/history.py#L142-L159)

**Comment by Bigsealion** [comment]
I had the same problem, and after referring to the above reply, I used the following method to solve it, hoping to help people who had the same problem

This issue is related to the file system. Moving the `.ipython` folder to the drive with `python` might solve this problem

```
mv raw_absolute_path/.ipython new_absolute_path/.ipython 
ln -s new_absolute_path/.ipython raw_absolute_path/.ipython
```

**Comment by dhirschfeld** [comment]
I was googling for the solution when the `sqlite` db is on an Azure Files (SMB) share.

The answer which worked for me was setting `nobrl` on the `mountOption` as documented in:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/827#issue-348525426

**Comment by joshua-seals** [comment]
The above worked for me nobrl on azure StorageClass mountOptions in AKS.
