### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by Khushu06** [ipython/ipython#11895]
Now it shows me the error of dead kernel. Kindly help on this
Error: A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.
```
[I 10:33:32.182 NotebookApp] Loading IPython parallel extension
[I 10:33:32.292 NotebookApp] JupyterLab extension loaded from C:\Users\Khushboo.Girotra\anaconda3\lib\site-packages\jupyterlab
[I 10:33:32.292 NotebookApp] JupyterLab application directory is C:\Users\Khushboo.Girotra\anaconda3\share\jupyter\lab
[I 10:33:32.297 NotebookApp] Serving notebooks from local directory: C:\Users\Khushboo.Girotra
[I 10:33:32.298 NotebookApp] The Jupyter Notebook is running at:
[I 10:33:32.299 NotebookApp] http://localhost:8888/?token=8e24cc355a607b399fedca623643ddf1b2ebb428f69c39bc
[I 10:33:32.300 NotebookApp]  or http://127.0.0.1:8888/?token=8e24cc355a607b399fedca623643ddf1b2ebb428f69c39bc
[I 10:33:32.301 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:33:32.755 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Khushboo.Girotra/AppData/Roaming/jupyter/runtime/nbserver-8844-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=8e24cc355a607b399fedca623643ddf1b2ebb428f69c39bc
     or http://127.0.0.1:8888/?token=8e24cc355a607b399fedca623643ddf1b2ebb428f69c39bc
[W 10:33:50.064 NotebookApp] Notebook Documents/Analytics bootcamp/python_decision_trees/decision_trees/decision_trees.ipynb is not trusted
[I 10:33:53.885 NotebookApp] Kernel started: a869e91b-d19d-478e-b2a7-6fda11ce89f5
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Khushboo.Girotra\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<C:\Users\Khushboo.Girotra\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 530, in initialize
    self.write_connection_file()
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 227, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Khushboo.Girotra\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[I 10:33:59.591 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[IPKernelApp] ERROR | Failed to load connection file: 'C:\\Users\\Khushboo.Girotra\\AppData\\Roaming\\jupyter\\runtime\\kernel-a869e91b-d19d-478e-b2a7-6fda11ce89f5.json'
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 252, in init_connection_file
    self.load_connection_file()
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 569, in load_connection_file
    info = json.load(f)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[I 10:34:02.637 NotebookApp] KernelRestarter: restarting kernel (2/5), keep random ports
[IPKernelApp] ERROR | Failed to load connection file: 'C:\\Users\\Khushboo.Girotra\\AppData\\Roaming\\jupyter\\runtime\\kernel-a869e91b-d19d-478e-b2a7-6fda11ce89f5.json'
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 252, in init_connection_file
    self.load_connection_file()
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 569, in load_connection_file
    info = json.load(f)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[I 10:34:05.668 NotebookApp] KernelRestarter: restarting kernel (3/5), keep random ports
[IPKernelApp] ERROR | Failed to load connection file: 'C:\\Users\\Khushboo.Girotra\\AppData\\Roaming\\jupyter\\runtime\\kernel-a869e91b-d19d-478e-b2a7-6fda11ce89f5.json'
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 252, in init_connection_file
    self.load_connection_file()
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 569, in load_connection_file
    info = json.load(f)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[I 10:34:08.695 NotebookApp] KernelRestarter: restarting kernel (4/5), keep random ports
[IPKernelApp] ERROR | Failed to load connection file: 'C:\\Users\\Khushboo.Girotra\\AppData\\Roaming\\jupyter\\runtime\\kernel-a869e91b-d19d-478e-b2a7-6fda11ce89f5.json'
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 252, in init_connection_file
    self.load_connection_file()
  File "C:\Users\Khushboo.Girotra\lib\site-packages\jupyter_client\connect.py", line 569, in load_connection_file
    info = json.load(f)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Khushboo.Girotra\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Khushboo.Girotra\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[W 10:34:11.713 NotebookApp] KernelRestarter: restart failed
[W 10:34:11.714 NotebookApp] Kernel a869e91b-d19d-478e-b2a7-6fda11ce89f5 died, removing from map.
[W 10:34:54.178 NotebookApp] Timeout waiting for kernel_info reply from a869e91b-d19d-478e-b2a7-6fda11ce89f5
[E 10:34:54.181 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: a869e91b-d19d-478e-b2a7-6fda11ce89f5)
[W 10:34:55.240 NotebookApp] 404 GET /api/kernels/a869e91b-d19d-478e-b2a7-6fda11ce89f5/channels?session_id=fe921aa3776f48e79b7232347f66318f (::1): Kernel does not exist: a869e91b-d19d-478e-b2a7-6fda11ce89f5
[W 10:34:55.286 NotebookApp] 404 GET /api/kernels/a869e91b-d19d-478e-b2a7-6fda11ce89f5/channels?session_id=fe921aa3776f48e79b7232347f66318f (::1) 46.89ms referer=None
[W 10:34:57.395 NotebookApp] Replacing stale connection: a869e91b-d19d-478e-b2a7-6fda11ce89f5:fe92```

**Comment by Khushu06** [comment]
For reference:
Kerner json file :

{
 "argv": [
  "C:\\Users\\Khushboo.Girotra\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}

Versions:
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2

win32 installed!
