### ISSUE TITLE
jupyter notebook kernel error

### ISSUE THREAD

**Issue by PBR1123** [ipython/ipython#11903]
I am new to using jupyter notebook and I am having issues with r kernel.

Please tell me how to solve.
```
--------------------------------------
Traceback (most recent call last):
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\csbr\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\CSBR\\AppData\\Roaming\\jupyter\\runtime\\kernel-c0bb9c82-0e76-4888-985e-e91d380711f7.json'
```

**Comment by Heyuanfly** [comment]
You have to run  the cmd or powrshell  as administrator，then it will be ok.
