### ISSUE TITLE
greek later variable names \phi and \varphi have same content

### ISSUE THREAD

**Issue by PrometheusPi** [ipython/ipython#11918]
With the LaTeX like replacement in the ipython console it is possible to use greek letters as variable names as well. However, in contrast to e.g. `julia`, python/ipython maps `\varphi[tab]`
 and `\phi[tab]` to the same data. 

Python:
```python
φ = 12
ϕ = 2
print(φ) # returns 2
print(ϕ) # returns 2
```

e.g. Julia:
```julia
φ = 12
ϕ = 2
println(φ) # returns 12
println(ϕ) # returns 2
```

(Please be aware that depending on your font, \varphi and \phi, might look very similar)

Tested with:
```
Python 3.6.5
IPython 6.4.0
```

**Comment by dhirschfeld** [comment]
I didn't believe it, but I can confirm on my system using spyder;:
```python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

In [1]: ϕ = 2

In [2]: φ = 12

In [3]: print(ϕ)
12

In [4]: print(φ)
12
```

**Comment by dhirschfeld** [comment]
I think this is a *really* nasty silent failure - you could get the wrong answer and never even know it 😬

**Comment by PrometheusPi** [comment]
@dhirschfeld I agree, it is an extremely hard to track down bug.

**Comment by PrometheusPi** [comment]
I had a look at the following list: https://github.com/ipython/ipython/blob/01f51c04ba54b707dbf2305d697e2fe5a5d4de2b/IPython/core/latex_symbols.py

and `\phi`(ϕ), `\varphi`(φ), `\_phi`(ᵩ), and `\^phi`(ᵠ) point to the same data. `\Phi`(Φ) does not point to that data.

The same error occurs for `\delta`() and `\^delta`(ᵟ), etc. and even for any roman letter as e.g. `G`(G) and `\^G`(ᴳ).  It does not occur for `L`(L) and `\L`(Ł). 

I will adjust the title of this issue to better reflect the scope of the problem.

**Comment by PrometheusPi** [comment]
It is not only the same content, but actually the same identity:

```python
ϕ = 1
print("id phi:", id(ϕ))
print("phi =", ϕ)

φ=2
print("id varphi:", id(φ))
print("varphi =", φ)

print("id phi:", id(ϕ))
print("phi =", ϕ)
```
returns:
```
id phi: 4530017632
phi = 1
id varphi: 4530017664
varphi = 2
id phi: 4530017664
phi = 2
```

I will adjust the issue name accordingly.

**Comment by dhirschfeld** [comment]
I can confirm. Also verified that python does consider them different unicode characters:
```python
>>> 'φ'.encode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\u03c6' in position 0: ordinal not in range(128)
>>> 'ϕ'.encode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\u03d5' in position 0: ordinal not in range(128)
>>> ϕ
2
>>> φ
2
>>> φ = 1
>>> φ
1
>>> ϕ
1
>>>
```

Is this a Python bug??

**Comment by PrometheusPi** [comment]
It looks like it is actually a python bug (that becomes only relevant if one uses an ipython-like development system). Where would one report such a bug?

**Comment by PrometheusPi** [comment]
I reported  to bug on the python issue tracker. Is has the ID: `issue38612`. 
https://bugs.python.org/issue38612

**Comment by stevendaprano** [comment]
This is a documented feature of the language.

https://docs.python.org/3/reference/lexical_analysis.html#identifiers
