### ISSUE TITLE
%run magic command errors when combined with --matplotlib magic and changed backend

### ISSUE THREAD

**Issue by samvaughan** [ipython/ipython#11946]
Possibly related to #11941

I've been running various scripts from an iPython console using the %run magic command. When the script in question contains an error, I'm using the %matplotlib magic command (passed via the command line) and I've changed the matplotlib backend, the %run command fails with the following error: 

```
~/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in mpl_execfile(fname, *where, **kw)
    178         matplotlib.interactive(is_interactive)
    179         # make rendering call now, if the user tried to do it
 --> 180         if plt.draw_if_interactive.called:
    181             plt.draw()
    182             plt.draw_if_interactive.called = False

AttributeError: 'function' object has no attribute 'called'
```

## Minimal reproducible test case

I've made a script called ```tmp.py``` which contains the following code:
```
1 = 2
```
When run from the command line:

```
~: samvaughan$ ipython --matplotlib
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: MacOSX

In [1]: import matplotlib                                                                                                                                               

In [2]: matplotlib.use('Agg')                                                                                                                                           

In [3]: %run tmp.py                                                                                                                                                     
  File "/Users/samvaughan/tmp.py", line 2
    1 = 2
         ^
SyntaxError: can't assign to literal

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6ce6810515f9> in <module>
----> 1 get_ipython().run_line_magic('run', 'tmp.py')

~/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2312                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2313             with self.builtin_trap:
-> 2314                 result = fn(*args, **kwargs)
   2315             return result
   2316 

</Users/samvaughan/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-59> in run(self, parameter_s, runner, file_finder)

~/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    825                     else:
    826                         # regular execution
--> 827                         run()
    828 
    829             if 'i' in opts:

~/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py in run()
    811                         def run():
    812                             runner(filename, prog_ns, prog_ns,
--> 813                                     exit_ignore=exit_ignore)
    814 
    815                     if 't' in opts:

~/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in mpl_execfile(fname, *where, **kw)
    178         matplotlib.interactive(is_interactive)
    179         # make rendering call now, if the user tried to do it
--> 180         if plt.draw_if_interactive.called:
    181             plt.draw()
    182             plt.draw_if_interactive.called = False

AttributeError: 'function' object has no attribute 'called'

In [4]:              
```

Note that this also means that any variables/functions defined in the script aren't now available to use in the console. 

### Expected behaviour: 

ipython returns the python error:   
```
File "/Users/samvaughan/tmp.py", line 2
    1 = 2
         ^
SyntaxError: can't assign to literal
```

Running the same code _without_ using the ```--matplotlib``` command line argument or without changing matplotlib backend leads to expected behaviour: 

```
~: samvaughan$ ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib                                                                                                                                               

In [2]: matplotlib.use('Agg')                                                                                                                                           

In [3]: %run tmp.py                                                                                                                                                     
  File "/Users/samvaughan/tmp.py", line 2
    1 = 2
         ^
SyntaxError: can't assign to literal


In [4]:       
```

and 

```
~: samvaughan$ ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: MacOSX

In [1]: import matplotlib                                                                                                                                               

In [2]: %run tmp.py                                                                                                                                                     
  File "/Users/samvaughan/tmp.py", line 2
    1 = 2
         ^
SyntaxError: can't assign to literal


In [3]:          
```

This is ipython 7,7.0, MacOS Mojave 10.14.6, installed using anaconda:

```
~: samvaughan$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '741169a00',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/samvaughan/anaconda3/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.7.0',
 'os_name': 'posix',
 'platform': 'Darwin-18.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/samvaughan/anaconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.7.3 (default, Mar 27 2019, 16:54:48) \n'
                '[Clang 4.0.1 (tags/RELEASE_401/final)]'}
```

Thanks!

**Comment by Carreau** [comment]
can you try #11959 ?

**Comment by ZouLiSha** [comment]
without using the --matplotlib command line argument or without changing matplotlib backend?? how can i do?
