### ISSUE TITLE
Raise StopIteration  on python manage.py shell

### ISSUE THREAD

**Issue by Saqibzaidig** [ipython/ipython#11967]
```
C:\Users\SAQIBZAIDI\Django_1\mysite>PYTHON manage.py shell
Traceback (most recent call last):
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 531, in _load_config_files
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\shell.py", line 108, in handle
    return getattr(self, shell)(options)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\shell.py", line 42, in ipython
    start_ipython(argv=[])
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\terminal\ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\application.py", line 389, in initialize
    self.load_config_file()
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\application.py", line 254, in load_config_file
    path=self.config_file_paths
  File "<string>", line 2, in load_config_file
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\SAQIBZAIDI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\config\application.py", line 538, in load_config_file
    for config in self._load_config_files(filename, path=path, log=self.log):
RuntimeError: generator raised StopIteration

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by Saqibzaidig** [comment]
is this a bug or i'm doing something wrong?

**Comment by Carreau** [comment]
These message look like you are using at least a 2 year old version of IPython. 
please update. 

Manage.py seem to be a django thing as well so this might be a django bug. 

Thanks.

**Comment by svigne1** [comment]
I got this error when i was trying to open the django shell.
I uninstalled ipython & tried again. It worked for me
