### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'inputhook'

### ISSUE THREAD

**Issue by nschloe** [ipython/ipython#11962]
I updated all my Python packages this morning and IPython doesn't work anymore since then. Error:
```python
Traceback (most recent call last):
  File "/home/nschloe/.local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/nschloe/.local/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</home/nschloe/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-113>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/nschloe/.local/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/home/nschloe/.local/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/usr/lib/python3/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/nschloe/.local/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 464, in __init__
    self.init_prompt_toolkit_cli()
  File "/home/nschloe/.local/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 296, in init_prompt_toolkit_cli
    **self._extra_prompt_options())
TypeError: __init__() got an unexpected keyword argument 'inputhook'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by oboudry** [comment]
I just reinstalled jupyterlab using conda `conda install -c conda-forge jupyterlab` and am getting the exact same error when running ipython.

**Comment by Carreau** [comment]
Downgrade prompt_toolkit ? Seem like Prompt toolkit 3.0 was released yesterday.

**Comment by sgjholt** [comment]
@Carreau @nschloe Can confirm that downgrading to prompt_toolkit 2.0 solved the issue. I had exactly the same error installing a fresh version of iPython via anaconda.

**Comment by Carreau** [comment]
our `setup.py` already state that we are only compatible with prompt toolkit version 2. I'll check the conda recipe.

**Comment by Carreau** [comment]
Conda-forge should be updated to tell it that the latest IPython is not compatible with ptk 3.

Though the solver may still get you an older version of IPython w/ a new version of prompt toolkit.

**Comment by Carreau** [comment]
Master is compatible with PTK3 if necessary.

**Comment by suewonjp** [comment]
This same issue occurred when I used ipdb (version 0.12.2) on Windows Subsystem for Windows 1 with python 3.6.9.
I downgraded ipython to 7.9.0 and it worked fine.
I think ipdb doesn't work with ipython 7.10.0.

**Comment by Carreau** [comment]
for the ipdb issue please try #11979 I'll try to make a 7.10.1 on monday.

**Comment by snowman** [comment]
### downgrade prompt_toolkit package

```bash
# --upgrade option can be used as downgrade also ;)
$ pip3 install --upgrade --user prompt_toolkit==2.0.10
```

**Comment by lijunzh** [comment]
> downgrade prompt_toolkit package

In conda use the following command to downgrade:
```
conda install prompt_toolkit==2.0.10
```

**Comment by Carreau** [comment]
7.10.1 should have been released; you can also upgrade IPython. 

Also when downgrading use `<`, so that if there is a patch or minor release you can get it. 
```
$ pip3 install --upgrade --user 'prompt_toolkit<3'
```
