### ISSUE TITLE
ipython crashed at launch

### ISSUE THREAD

**Issue by Tom89757** [ipython/ipython#12002]
Hi! I have the following error output when I launch IPython using cmd on Windows 10. And it is confusing that I can launch it successfully using Anaconda. Thanks in advance.

This is the output of python `python -c "import IPython; print(IPython.sys_info())"`：
```
{'commit_hash': 'e508b6e4d',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': 'D:\\Python37\\lib\\site-packages\\IPython',
 'ipython_version': '7.10.1',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.18362-SP0',
 'sys_executable': 'D:\\Python37\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.7.5rc1 (tags/v3.7.5rc1:4082f600a5, Oct  1 2019, 20:28:14) '
                '[MSC v.1916 64 bit (AMD64)]'}
```

Below is the error output on cmd: 
```
C:\WINDOWS\system32>ipython
Traceback (most recent call last):
  File "d:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python37\Scripts\ipython.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "d:\python37\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "d:\python37\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<d:\python37\lib\site-packages\decorator.py:decorator-gen-114>", line 2, in initialize
  File "d:\python37\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\python37\lib\site-packages\IPython\terminal\ipapp.py", line 317, in initialize
    self.init_shell()
  File "d:\python37\lib\site-packages\IPython\terminal\ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "d:\python37\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "d:\python37\lib\site-packages\IPython\terminal\interactiveshell.py", line 513, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "d:\python37\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "d:\python37\lib\site-packages\IPython\terminal\interactiveshell.py", line 496, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "d:\python37\lib\site-packages\IPython\core\interactiveshell.py", line 2240, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "d:\python37\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "d:\python37\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "d:\python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "d:\python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "d:\python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "d:\python37\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "d:\python37\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "d:\python37\lib\sre_parse.py", line 813, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 6

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

Here is the output from Anaconda (I replace the real name with name): 
```
(base) PS C:\Users\name> ipython
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by Carreau** [comment]
What is the value of your `pathext` environment variable ? 

you might be able to get it via:
```
import os
print(os.environ['pathext'])
```

**Comment by Tom89757** [comment]
It's `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYM\`. Is it that I forget to add some environment variables？

**Comment by Carreau** [comment]
No, the problem is that it ends with a backslash. This is likely a mistake which triggers this issue. I would remove the \ .

**Comment by Tom89757** [comment]
It works ! Thanks so much for your help.
