### ISSUE TITLE
Ipython breaks out of user and starts using old system python files

### ISSUE THREAD

**Issue by flip111** [ipython/ipython#12058]
I installed jupyter with `pip install --user jupyter`, installation went fine. Then when i run `jupyter notebook i get`

```
[I 16:04:25.251 NotebookApp] Writing notebook server cookie secret to /home/flip111/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/home/flip111/.local/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/home/flip111/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/flip111/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</home/flip111/.local/lib/python3.8/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/flip111/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/flip111/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1720, in initialize
    self.init_webapp()
  File "/home/flip111/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1443, in init_webapp
    self.web_app = NotebookWebApplication(
  File "/home/flip111/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 153, in __init__
    settings = self.init_settings(
  File "/home/flip111/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 269, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/home/flip111/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1104, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 119, in <module>
    from IPython.utils import path as util_path
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/home/flip111/.local/lib/python3.8/site-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 15, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 218
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                               ^
SyntaxError: invalid syntax
```

On my system (ubuntu 16.04) there is python3.5, but i installed python3.8 from ppa which i would like to use. Seems that the python3.8 code starts to use old python3.5 code. Is there any way i can fix this on my end?

**Comment by Carreau** [comment]
can you test to `pip install pexpect` with your 3.8 ?  To make sure you get the right pip you can try `python3.8 -m pip install ...`

**Comment by flip111** [comment]
I get

> Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (4.0.1)

When i run `python3.8 -m pip install pexpect`

**Comment by Carreau** [comment]
Oh, hum, 

check your PATH and PYTHONPATH for `/usr/lib/python3/dist-packages/` and remove it when you are using Python 3.8; keep it when using 3.5 don't remove it by default you may break software update. 

Removing things from PATH/PYTHONPATH is [not straitforward](https://stackoverflow.com/questions/370047/what-is-the-most-elegant-way-to-remove-a-path-from-the-path-variable-in-bash);  I would recommend to not use a PPA for 3.8; and/or be really careful when modifying system python with Linux as the package manager uses Python as well. 

Instead I would suggest using anaconda, or something else that make a complete user-space Python install, especially if you want to be on the bleeding edge.

You might also be able to try a venv with `python3.8 -m venv` and alike ;  activating the env; it might tweak the PATH/PYTHONPATH correctly for you. 

Note, the issue is because `async` is becoming a full real keyword in 3.8

**Comment by flip111** [comment]
`PYTHONPATH` is not defined. `PATH` contains no reference to anything with python3

I was able to run jupyter from within a venv but it's a bit cumbersome because i have to navigate to the venv directory first and after lauching jupyter i can't open notebooks from another directory.

**Comment by Carreau** [comment]
Hum, you will to check `sys.path` with pure python, but I'm not quite sure how to fix that if you are using a PPA. It might just be that you can't have both 3.5 and 3.8 installed at the same time using APT.

**Comment by flip111** [comment]
They can be installed simultaneously because they don't have files with the same extraction path in their packages (otherwise apt would refuse to install them).

I check `sys.path` of python3.8 and indeed there is a path to `/usr/lib/python3/dist-packages` making use of python3.5 things. I don't know how the `sys.path` ended up looking like this or how i should modify this default.

By the way, i have a desktop computer with ubuntu 19.10 and when ubuntu 20.04 comes out i will reinstall the laptop. So that are two solutions for me to work around this problem, but i thought it would be a good idea to report the original problem.

**Comment by flip111** [comment]
@Carreau thanks for all the help. It suspect this is a bug upstream with ppa deadsnakes. I will make a bug report there. Jupyter runs well now if i start it like `python3.8 -m jupyter notebook`

**Comment by Carreau** [comment]
Thanks. Feel free to report back here (or link to another thread) to help
potential other users.

**Comment by flip111** [comment]
my temporary workaround is to edit the file `/usr/lib/python3.8/site.py` and comment out the part where `sitepackages.append()` is including the python 3.5 system libraries. `site.py` is beind build by applying this diff (so you know what to look for) https://github.com/deadsnakes/python3.8/blob/debian/3.8.1-1%2Bxenial3/debian/patches/distutils-install-layout.diff#L266-L268

**Comment by lykinsbd** [comment]
For future readers, I had the same issue, and it is due to not using the `--ignore-installed` flag when installing `ipython` in my non-system python.

```
ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 5, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python3.8/dist-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/ultratb.py", line 116, in <module>
    from IPython.utils import path as util_path
  File "/usr/local/lib/python3.8/dist-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/usr/local/lib/python3.8/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/local/lib/python3.8/dist-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                               ^
SyntaxError: invalid syntax
```

I was using a PPA installed Python 3.8 on a system with 3.6 as default, and getting the wrong version of `pexpect` out of the `dist-packages` for the system python.

Attempting to upgrade `pexpect` gave me the following:

```
sudo pip3 install pexpect
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (4.2.1)
```

I had to force with the `--ignore-installed` flag to get pip to install into the 3.8 location:

```
sudo python3.8 -m pip install --ignore-installed pexpect
Collecting pexpect
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 1.2 MB/s 
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Installing collected packages: ptyprocess, pexpect
Successfully installed pexpect-4.8.0 ptyprocess-0.6.0
```

After this `ipython` loaded fine.
