### ISSUE TITLE
ipython exclusively crashes 

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [ipython/ipython#12134]
ipython version - 7.12
python version - 3.6, 3.7, 3.8
ubuntu 18.04
ipython and all modules installed with pip in virtualenv
python compiled by myself with ./configure --prefix=path; make; make test; make install

Taceback does not mention any part of my code. When running my script: python script.py no errors occur.

Error is trigered by calling a class method. See line 181 in [here](https://github.com/7PintsOfCherryGarcia/JellyBelly/blob/master/python/belly_vector.py)  

traceback
```
Traceback (most recent call last):
File "MYPATH/lib/python3.8/site-packages/jedi/cache.py", line 109, in wrapper
return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/MYPATH/bin/ipython", line 10, in <module>
sys.exit(start_ipython())
File "/MYPATH/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
return launch_new_instance(argv=argv, **kwargs)
File "MYPATH/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
app.start()
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
self.shell.mainloop()
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 558, in mainloop
self.interact()
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 541, in interact
code = self.prompt_for_code()
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 467, in prompt_for_code
text = self.pt_app.prompt(
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 997, in prompt
return self.app.run()
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 810, in run
return loop.run_until_complete(self.run_async(pre_run=pre_run))
File "/home/jregalado/Software/myPython/snakes/python3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 777, in run_async
return await _run_async2()
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 765, in _run_async2
await self.cancel_and_wait_for_background_tasks()
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 862, in cancel_and_wait_for_background_tasks
await task
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
await coroutine(*a, **kw)
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
async for completion in self.completer.get_completions_async(
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
async for completion in completer.get_completions_async(
File "MYPATH/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
for item in self.get_completions(document, complete_event):
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 90, in get_completions
yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
File "MYPATH/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 100, in _get_completions
for c in completions:
File "MYPATH/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
completions = list(completions)
File "MYPATH/lib/python3.8/site-packages/IPython/core/completer.py", line 1815, in completions
for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
File "MYPATH/lib/python3.8/site-packages/IPython/core/completer.py", line 1872, in _completions
signature = _make_signature(jm)
File "MYPATH/lib/python3.8/site-packages/IPython/core/completer.py", line 989, in _make_signature
return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for p in completion.params) if f])
File "MYPATH/lib/python3.8/site-packages/jedi/cache.py", line 111, in wrapper
result = method(self, *args, **kwargs)
File "MYPATH/lib/python3.8/site-packages/jedi/api/classes.py", line 421, in params
warnings.warn(
DeprecationWarning: Deprecated since version 0.16.0. Use get_signatures()[...].params

If you suspect this is an IPython 7.12.0 bug, please report it at:
https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
   %config Application.verbose_crash=True
```

**Comment by tacaswell** [comment]
What version of `jedi` do you have installed?

**Comment by 7PintsOfCherryGarcia** [comment]
jedi==0.16.0

pip freeze:

backcall==0.1.0
decorator==4.4.1
ipython==7.12.0
ipython-genutils==0.2.0
jedi==0.16.0
joblib==0.14.1
numpy==1.18.1
parso==0.6.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.3
ptyprocess==0.6.0
Pygments==2.5.2
scikit-learn==0.22.1
scipy==1.4.1
six==1.14.0
sklearn==0.0
traitlets==4.3.3
wcwidth==0.1.8

**Comment by Carreau** [comment]
Hum, it might be a jedi issue. One should try to reproduce by using jedi directly.

You might want to try to purge jedi cache. See https://jedi.readthedocs.io/en/latest/docs/settings.html#filesystem-cache for where the cache is located.

**Comment by 7PintsOfCherryGarcia** [comment]
# Crash does not happen with jedi==0.14.1

After purging jedi's cache, ipython keeps crashing with same error.

To reproduce error:
In python >= 3.6  virtualenv:
   ```
   git clone --single-branch --branch dev https://github.com/7PintsOfCherryGarcia/JellyBelly.git
   cd JellyBelly/python
   python setup.py install
   cd ..
   ```
Start ipython session
   ```
   import JellyBelly
  #Error is triggered when trying to autocomplete
   a = JellyBelly.JELLYVECS("whatever you want")
   ```

**Comment by aiguofer** [comment]
This is related to #12102... find it weird that it's crashing though, shouldn't it just display the warning?

**Comment by aterenin** [comment]
Having the same issue, and using jedi==0.14.1 fixes it.

**Comment by jniediek** [comment]
I was having the same issue, for me using jedi version 0.18.0 fixed it.
