### ISSUE TITLE
Fabric's Run with watchers breaks IPython

### ISSUE THREAD

**Issue by Diego-MX** [ipython/ipython#12149]
I'm running Anaconda's Ipython v.7.8.0 , with Conda v.4.8.2 on Windows Powershell prompt. 

These are my first steps with Fabric commands to connect to a host and update a repo

```python
import os
from dotenv import load_dotenv
from invoke import Responder, run
from fabric import Connection, Config
from patchwork import files

load_dotenv()  
# SSH_HOST, SSH_USER, SSH_PASS, REPO_PASS, REPO_USER

REPO_URL = "local_server_gogs_repo_sorry_no_github"

#%% 
config = Config(overrides = {"sudo" : {"password": os.getenv("SSH_PASS")} })
ctxt = Connection(os.getenv("SSH_HOST"), config = config)   

code_dir   = "/opt/repos/the_dir"
code_dir2 = "/home/my_user/repos/the_dir" also breaks

git_password =  Responder(pattern=r"Password for .*", response=f"{os.getenv('REPO_PASS')}\n")
git_watchers = [Responder(pattern=r"Username for .*", response=f"{os.getenv('REPO_USER')}\n"),
    git_password ]

with ctxt.cd(code_dir2):
    fetch = ctxt.run(f"git fetch", pty=True, watchers=git_watchers)

with ctxt.cd(code_dir):  # More challenging because of Sudo. 
    fetch = ctxt.sudo(f"git fetch", pty=True, watchers=git_watchers, user="root")
```

The last two commands break iPython and close the program. 
I have tried the equivalent command with less, or even no watchers, passing the host+address in git fetch, or even non-securely host+password+address, with the same breaking result.  

On another path, I did run that command in Anaconda's Jupyter Notebook and finished successfully.  

What could it be?  Would you need more information from my side.  

Cheers from mexico. 

The traceback is shown here.  From what I get, this is mostly the application's code, and nothing from my code. 

```
Traceback (most recent call last):
  File "C:\...\anaconda3\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\...\anaconda3\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\...\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\...\anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\...\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 498, in mainloop
    self.interact()
  File "C:\...\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 481, in interact
    code = self.prompt_for_code()
  File "C:\...\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 410, in prompt_for_code
    **self._extra_prompt_options())
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 797, in prompt
    return run_sync()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 786, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 736, in run
    return run()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 710, in run
    return f.result()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\eventloop\future.py", line 151, in result
    raise self._exception
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\eventloop\coroutine.py", line 92, in step_next
    new_f = coroutine.throw(exc)
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 685, in _run_async2
    result = yield f
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\eventloop\coroutine.py", line 88, in step_next
    new_f = coroutine.send(None)
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 627, in _run_async
    self._request_absolute_cursor_position()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 791, in _request_absolute_cursor_position
    self.renderer.request_absolute_cursor_position()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\renderer.py", line 408, in request_absolute_cursor_position
    self._min_available_height = self.output.get_rows_below_cursor_position()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\output\win32.py", line 333, in get_rows_below_cursor_position
    info = self.get_win32_screen_buffer_info()
  File "C:\...\anaconda3\lib\site-packages\prompt_toolkit\output\win32.py", line 186, in get_win32_screen_buffer_info
    success = windll.kernel32.GetConsoleScreenBufferInfo(self.hconsole, byref(sbinfo))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Carreau** [comment]
I'm confused, how are you running this script ? And where is IPython involved in this ?

If you can try to update to IPython 7.12 or master.

**Comment by Diego-MX** [comment]
Well, two things are happenning here.  
Since I am running this on IPython, where it breaks (even after the update to Ipython 7.12), and not in Jupyter where it doesn't break, I thought this belonged here.

However.... after running it in regular Python console, I found that it also breaks there.  Thus becoming a non-Ipython issue.  

Thanks for the response, 
Best
