### ISSUE TITLE
Unhandled reference to child in utils._process_posix interrupt handler

### ISSUE THREAD

**Issue by bollwyvl** [ipython/ipython#12164]
In [packaging 7.13 for conda-forge, we observed the below failure on all aarch64/ppcle builds during `test_system_interrupt`. We've added a [test skip](https://github.com/conda-forge/ipython-feedstock/pull/97/files#diff-e178b687b10a71a3348107ae3154e44cR42) but wanted to leave a trail for future investigation.

```
Test group: utils

......................................................................S...SS...S..../home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/paths.py:60: UserWarning: IPython dir '/tmp/tmp15oo8dhv/tmprf9onc93/.ipython' is not a writable location, using a temp directory.

  " using a temp directory.".format(ipdir))

.S...........E..S..S.......................................................

======================================================================

ERROR: When interrupted in the way ipykernel interrupts IPython, the

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/utils/_process_posix.py", line 156, in system

    child = pexpect.spawn(self.sh, args=['-c', cmd])  # Vanilla Pexpect

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 205, in __init__

    self._spawn(command, args, preexec_fn, dimensions)

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 304, in _spawn

    cwd=self.cwd, **kwargs)

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 315, in _spawnpty

    return ptyprocess.PtyProcess.spawn(args, **kwargs)

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 309, in spawn

    exec_err_data = os.read(exec_err_pipe_read, 4096)

KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/utils/tests/test_process.py", line 154, in test_system_interrupt

    status = self.assert_interrupts(command)

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/utils/tests/test_process.py", line 136, in assert_interrupts

    result = command()

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/utils/tests/test_process.py", line 152, in command

    return system('%s -c "import time; time.sleep(5)"' % python)

  File "/home/conda/feedstock_root/build_artifacts/ipython_1582943933524/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/IPython/utils/_process_posix.py", line 172, in system

    child.sendline(chr(3))

UnboundLocalError: local variable 'child' referenced before assignment

----------------------------------------------------------------------

Ran 159 tests in 4.278s

FAILED (SKIP=7, errors=1)
```

**Comment by bollwyvl** [comment]
This also failed at least once on linux-x64:
```
______________________________________________________________________
Test suite completed for system with the following information:
IPython version: 7.13.0
IPython commit : d0b255042 (installation)
IPython package: ~/feedstock_root/build_artifacts/ipython_1583007419582/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/site-packages/IPython
Python version : 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) [GCC 7.3.0]
sys.executable : ~/feedstock_root/build_artifacts/ipython_1583007419582/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
Platform       : Linux-4.15.0-1069-azure-x86_64-with-centos-6.10-Final
```

**Comment by tornaria** [comment]
This seems a race condition in `IPython.utils._process_posix.system()`. Can be reproduced as:
```
$ python
Python 3.11.3 (main, May 18 2023, 16:04:06) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time, threading, IPython, _thread
>>> IPython.version_info
(8, 14, 0, '')
>>> from IPython.utils._process_posix import system
>>> def command(): return system('python -c "import time; time.sleep(5)"')
... 
>>> def interrupt(): time.sleep(0.0) ; _thread.interrupt_main()
... 
>>> threading.Thread(target=interrupt).start() ; result = command()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/IPython/utils/_process_posix.py", line 148, in system
    child = pexpect.spawn(self.sh, args=['-c', cmd])  # Vanilla Pexpect
                          ^^^^^^^
  File "/usr/lib/python3.11/site-packages/IPython/utils/_process_posix.py", line 55, in sh
    self._sh = pexpect.which(shell_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pexpect/utils.py", line 54, in which
    if os.path.dirname(filename) != '' and is_executable_file(filename):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pexpect/utils.py", line 26, in is_executable_file
    fpath = os.path.realpath(path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in command
  File "/usr/lib/python3.11/site-packages/IPython/utils/_process_posix.py", line 164, in system
    child.sendline(chr(3))
    ^^^^^
UnboundLocalError: cannot access local variable 'child' where it is not associated with a value
```

If one does `time.sleep(0.5)` as in the test, this is much harder to trigger, but it still may happen in a very loaded system. I came upon this on github CI for https://github.com/void-linux/void-packages/pull/44268, see:
https://github.com/void-linux/void-packages/actions/runs/5171305705/jobs/9314764960?pr=44268#step:7:1755

Apparently the interrupt hits the main thread before `pexpect.spawn(...)` finishes, thus the `child` variable is never bound.

There is a similar race condition in the test code itself, namely in `assert_interrupts()` there is this code:
```
        try:
            result = command()
        except KeyboardInterrupt:
            # Success!
            pass
        ...
        return result
```
but when the `KeyboardInterrupt` actually triggers here the `result` variable will not be bound  (maybe replace `pass` with `result=1` is reasonable here).

**Comment by tornaria** [comment]
Self contained test file:
```python
import time, threading, _thread
from IPython.utils._process_posix import system

def command():
    return system('python -c "import time; time.sleep(5)"')

def interrupt():
    time.sleep(0.0)
    _thread.interrupt_main()

threading.Thread(target=interrupt).start()
result = command()

print(f"{result = }")
```

I get the same failure with ipython 8.13.2 as with 8.14.0:
```
$ python test_race.py 
...
UnboundLocalError: cannot access local variable 'child' where it is not associated with a value
```

Suggested fix:
```diff
--- a/IPython/utils/_process_posix.py
+++ b/IPython/utils/_process_posix.py
@@ -136,6 +136,7 @@ def system(self, cmd):
         # record how far we've printed, so that next time we only print *new*
         # content from the buffer.
         out_size = 0
+        child = None
         try:
             # Since we're not really searching the buffer for text patterns, we
             # can set pexpect's search window to be tiny and it won't matter.
@@ -158,6 +159,13 @@ def system(self, cmd):
                 # Update the pointer to what we've already printed
                 out_size = len(child.before)
         except KeyboardInterrupt:
+
+            if child is None:
+                # the interrupt was received before pexpect.spawn()
+                # was done... recover as best as possible.
+                import signal
+                return -signal.SIGINT
+
             # We need to send ^C to the process.  The ascii code for '^C' is 3
             # (the character is known as ETX for 'End of Text', see
             # curses.ascii.ETX).
```

With this fix, the same test file gives:
```
$ python test_race.py 
result = -2
```
