### ISSUE TITLE
New matplotlib (3.2.0) breaks the test suite

### ISSUE THREAD

**Issue by itamarst** [ipython/ipython#12176]
Trying to reproduce matplotlib-y errors in #12168, I did `pip install --upgrade matplotlib`, and now I'm getting the same errors, e.g.:

```python
ERROR: Test color settings for latex_to_png.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/itamarst/Devel/ipython/venv/lib64/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/itamarst/Devel/ipython/IPython/testing/decorators.py", line 212, in skipper_func
    return f(*args, **kwargs)
  File "/home/itamarst/Devel/ipython/IPython/lib/tests/test_latextools.py", line 144, in test_latex_to_png_color
    default_value = latextools.latex_to_png(latex_string, wrap=False)
  File "/home/itamarst/Devel/ipython/IPython/lib/latextools.py", line 104, in latex_to_png
    bin_data = f(s, wrap, color, scale)
  File "/home/itamarst/Devel/ipython/IPython/lib/latextools.py", line 126, in latex_to_png_mpl
    mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
  File "/home/itamarst/Devel/ipython/venv/lib64/python3.7/site-packages/matplotlib/mathtext.py", line 3436, in to_png
    with open(filename, "wb") as file:
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

**Comment by itamarst** [comment]
I will try to fix in order to unblock my PR.

**Comment by tacaswell** [comment]
Is there a Matplotlib issue for this?  We should definitely fix this on the mpl side.  In the meantime, it would be better to exclude the broken version of Matplotlib.

**Comment by itamarst** [comment]
As discussed in the PR, there is an upstream issue and it'll be fixed in matplotlib 3.2.1.

**Comment by tacaswell** [comment]
Do you know what issue / PR fixed this?

**Comment by tacaswell** [comment]
found it: https://github.com/matplotlib/matplotlib/pull/16709

**Comment by kkirsche** [comment]
Should this issue be closed as the fix has been merged upstream?

**Comment by tacaswell** [comment]
Yes, this should be closed.  Thank you for noticing @kkirsche!
