### ISSUE TITLE
Unable to autoreload @dataclass(frozen=True)

### ISSUE THREAD

**Issue by Techcable** [ipython/ipython#12185]
I think you can bypass the FrozenInstanceError by directly invoking object.__setattr__

````
[autoreload of pitch_detection failed: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/usr/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/usr/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/usr/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 317, in update_class
    update_instances(old, new)
  File "/usr/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 280, in update_instances
    ref.__class__ = new
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field '__class__'
]
````

**Comment by Carreau** [comment]
Hummm... If you know what you are doing then we'll happily take a Pull Request.

**Comment by kvjrhall** [comment]
I have observed this in vscode, in particular.

Let us say that we have a frozen dataclass in some user-specified module `usermodule` (I haven't tested with any 3rd party packages) along with other code currently in development.

```
from dataclasses import dataclass

@dataclass
class some_frozen_class:
    a: int

def algorithm(a: int) -> int:
    return a + 2
```

In a notebook cell we have the following

```
from usermodule import algorithm

display(algorithm(2))
```

Next we modify algorithm (or any code in that python file)

```
from dataclasses import dataclass

@dataclass
class some_frozen_class:
    a: int

def algorithm(a: int) -> int:
    return a + 3   # a change
```

...and re-run the cell. I've been seeing two things: (1) the autoreload error as reported by @Techcable; and (2) the cell continues to run despite the error, with unpredictable behavior (i.e., code may or may not be changed, etc). Restarting the python interpreter results in the error disappearing and code running as expected for the first run.
