### ISSUE TITLE
Infinite loop when using ipdb on ipython 7.13+

### ISSUE THREAD

**Issue by werdeil** [ipython/ipython#12192]
I use pytest with appium and when I use ipdb.set_trace() I'm stuck in a loop:

```
Exception in thread Thread-21249:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 102, in in_thread
    line = self.pt_app.prompt()
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 986, in prompt
    return self.app.run()
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 788, in run
    return get_event_loop().run_until_complete(self.run_async(pre_run=pre_run))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-21249'.
```

As you can see I reached thread 21249 before managing to kill the process.

With the same code it works as expected on ipython 7.12, so I guess is it linked to https://github.com/ipython/ipython/pull/12141/

Am I the only one having this bug?

**Comment by zogzog** [comment]
I just discovered that same exact thing today.

**Comment by srggrs** [comment]
I can confirm that this happen to me as well:
```
python=3.6.10
ipython=7.13.0
ipdb=0.12.3
```

**Comment by igandhi** [comment]
I believe this is an issue in `7.13`. I was able to resolve this by downgrading to iPython `7.10.2`

**Comment by werdeil** [comment]
Any news on this? I tried python 7.17.0 and I still have the same issue...

**Comment by werdeil** [comment]
Tried with python 7.19.0 and I still have the issue, any news?

**Comment by werdeil** [comment]
While trying to provide a simple script to reproduce I found out a fix: I had the the issue in an environment with prompt-toolkit==3.0.2 and it is resolve by prompt-toolkit==3.0.8.

**Comment by delijati** [comment]
Yeah i still into the same issue. Welcome back to pre ipdb times ;(
