### ISSUE TITLE
history.py 'database is locked'

### ISSUE THREAD

**Issue by DanielGoldfarb** [ipython/ipython#12202]
I wish I could provide more detail about this issue, but posting what I have in the hopes that others may contribute additional information.

Both yesterday and today, while searching history, I've gotten then error `The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.`

After yesterday's error, the history database was trashed and no longer useful, but I was able to fix it by removing duplicate entries from the 'sessions' table.  **[SEE FULL DETAILS HERE](https://stackoverflow.com/questions/60837351/lost-ipython-history-database-locked).**

Today I got the error again, but this time after stopping and restarting ipython history was working fine again.  Here is the error text from today's thread crash:

    13: hist -l100 -g date
    In [14]: hist -l100 -g date  -f histfile.txt
    The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.
    In [15]: quit
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "/home/dino/anaconda3/lib/python3.7/site-packages/IPython/core/history.py", line 578, in end_session
        len(self.input_hist_parsed)-1, self.session_number))
    sqlite3.OperationalError: database is locked

After the above error, and restarting ipython, I was able to successfully run `hist -l100 -g date  -f histfile2.txt` and although the error occured upon `hist -l100 -g date  -f histfile.txt`, the file `histfile.txt` appears to have been written correctly.

Version Info:

    dino@DINO:~$ ipython
    Python 3.7.4 (default, Aug 13 2019, 20:35:49)
    Type 'copyright', 'credits' or 'license' for more information
    IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

    dino@DINO:~$ uname -a
    Linux DINO 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
    dino@DINO:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.2 LTS
    Release:        18.04
    Codename:       bionic

**Comment by Carreau** [comment]
> running WSL Ubuntu

That is probably the issue. IPython history uses sqlite which is finicky on NFS storage and similar, so issue on WSL does not surprise me as WSL try to make files transparently available both on windows and ubuntu.

Quick google search turns https://github.com/microsoft/WSL/issues/2395

Do you use IPython both in and out of WSL ? One thing you can try to use `c.HistoryManager.hist_file=<path>` to put the history file in a different place which potentially is accessible only from WSL.

If that does not work or is impractical we can try to add a workaround (they suggest putting a sleep(0.1) in above issue.

**Comment by DanielGoldfarb** [comment]
@Carreau 

>  microsoft/WSL#2395 

Nice find!  ... will read throught that thread in some detail later.  ... work predominantly in WSL; sometimes a separate Ubuntu boot (effectively a different machine), and sometimes macbook (literally a different machine).  All in all I don't expect this problem to bother me that much, but we'll see.  (Thinking about upgrading to WSL2 soon, although from what I've heard are the main changes WSL -> WSL2 ,i would expect that the same bug exists there as well).

**Comment by DanielGoldfarb** [comment]
> (Thinking about upgrading to WSL2 soon, although from what I've heard are the main changes WSL -> WSL2 ,i would expect that the same bug exists there as well).

I take it back (maybe) ... according to [this comment here](https://github.com/microsoft/WSL/issues/2395#issuecomment-568483792) upgrading to WSL2 very well may resolve the problem.

**Comment by 2sn** [comment]
I have a related error in a different situation:
```
~>ipython
[TerminalIPythonApp] ERROR | Failed to create history session in /home/alex/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/home/alex/Python/lib/python3.10/site-packages/IPython/core/history.py", line 543, in __init__
    self.new_session()
  File "/home/alex/Python/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/alex/Python/lib/python3.10/site-packages/IPython/core/history.py", line 58, in needs_sqlite
    return f(self, *a, **kw)
  File "/home/alex/Python/lib/python3.10/site-packages/IPython/core/history.py", line 568, in new_session
    cur = conn.execute("""INSERT INTO sessions VALUES (NULL, ?, NULL,
sqlite3.OperationalError: database is locked
Python 3.10.1 (main, Dec  7 2021, 12:35:08) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
```
This occurs when I run IPython in another session on the same computer that is currently busy (in my case, executing binary code in a f2py module), which is why I start a second session in the first place.  

Maybe the error could be caught and a quick note be displayed with less fanfare, or sqlite be replaces with a db that allows parallel transactions, or maybe history.pu could be adjusted to close transaction and unlock db when executing a command?

**Comment by Carreau** [comment]
I'm unsure what to do about that. It is likely that what we are doing is not thread safe, or that we are not locking the db, 
reviewing code I can't see any write location where we don't use the context manager, so this is weird.

Maybe it's #13406, but I doubt it, and it will likely take SO who can reproduce the issue to track it down, maybe track the timing around  each write operation as the default timeout is 5s ?

**Comment by DanielGoldfarb** [comment]
Fyi (as per my comment above) I did upgrade to **WSL2** at the beginning of August 2020 ... well over a year now, and I have ***not*** seen this problem since.  Also, I am very pleased with WSL2 in so many ways!  I would strongly recommend it to anyone using WSL1.

**Comment by prosoitos** [comment]
I am encountering the issue in Arch Linux:

> The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

past which (after some delay and a bunch of "Ret" to get ouf of the error message), I can keep on using IPython.

OS: Arch Linux 6.17.1
Python: 3.13.7
IPython: 9.5.0
