### ISSUE TITLE
Got Error in atexit._run_exitfuncs: during running futures.ThreadPoolExecutor

### ISSUE THREAD

**Issue by Eshan-Agarwal** [ipython/ipython#12257]
I am using below code to generate examples from datasets list, 

```py
with futures.ThreadPoolExecutor(max_workers=WORKER_COUNT_DATASETS) as tpool:
        builder_examples = tpool.map(generate_single_visualization, dataset_config_list)
```
here `generate_single_visualization` is some function which generate images and `dataset_config_list` is list of datasets passed. Everything runs fine but in last this error raises

WORKER_COUNT_DATASETS is 10

> Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/history.py", line 786, in writeout_cache
    self._writeout_input_cache(conn)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/history.py", line 770, in _writeout_input_cache
    (self.session_number,)+line)

For any help thanks

**Comment by Eshan-Agarwal** [comment]
Problem solved after updating Ipython to latest version `pip install ipython==7.13.0` previous version of Ipython is `5.5.0` in colab.
