### ISSUE TITLE
`oinspect.getdoc` and Python 3.9.0a6

### ISSUE THREAD

**Issue by frenzymadness** [ipython/ipython#12287]
Another problem with the version 3.9.0a6 is that `inspect.getdoc()` no longer returns docstring inherited from the type of the object or from parent class if it is a class if it is not defined in the object itself. See [this bug](https://bugs.python.org/issue40257) or [this changelog entry](https://docs.python.org/3.9/whatsnew/3.9.html#changes-in-the-python-api).

This change causes failure in [`test_getdoc` in `test_oinspect`](https://github.com/ipython/ipython/blob/master/IPython/core/tests/test_oinspect.py#L237).

**Comment by frenzymadness** [comment]
This is probably also the reason for failure of `IPython.core.tests.test_debugger.test_ipdb_magics`. See the part about docstrings where in `Got` there is `<no docstring>`:
```
======================================================================
FAIL: Doctest: IPython.core.tests.test_debugger.test_ipdb_magics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ipython-7.14.0-1.fc33.x86_64/usr/lib/python3.9/site-packages/IPython/testing/plugin/ipdoctest.py", line 268, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for test_ipdb_magics
  File "/builddir/build/BUILDROOT/ipython-7.14.0-1.fc33.x86_64/usr/lib/python3.9/site-packages/IPython/core/tests/test_debugger.py", line 75, in test_ipdb_magics
----------------------------------------------------------------------
File "/builddir/build/BUILDROOT/ipython-7.14.0-1.fc33.x86_64/usr/lib/python3.9/site-packages/IPython/core/tests/test_debugger.py", line 100, in test_ipdb_magics
Failed example:
    with PdbTestInput([
       'pdef example_function',
       'pdoc ExampleClass',
       'up',
       'down',
       'list',
       'pinfo a',
       'll',
       'continue',
    ]):
        trigger_ipdb()
Expected:
    --Return--
    None
    > <doctest ...>(3)trigger_ipdb()
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> pdef example_function
     example_function(x, y, z='hello')
     ipdb> pdoc ExampleClass
    Class docstring:
        Docstring for ExampleClass.
    Init docstring:
        Docstring for ExampleClass.__init__
    ipdb> up
    > <doctest ...>(11)<module>()
          7    'pinfo a',
          8    'll',
          9    'continue',
         10 ]):
    ---> 11     trigger_ipdb()
    <BLANKLINE>
    ipdb> down
    None
    > <doctest ...>(3)trigger_ipdb()
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> list
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> pinfo a
    Type:           ExampleClass
    String form:    ExampleClass()
    Namespace:      Local...
    Docstring:      Docstring for ExampleClass.
    Init docstring: Docstring for ExampleClass.__init__
    ipdb> ll
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> continue
Got:
    --Return--
    None
    > <doctest test_ipdb_magics[3]>(3)trigger_ipdb()
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> pdef example_function
     example_function(x, y, z='hello') ipdb> pdoc ExampleClass
    Class docstring:
        Docstring for ExampleClass.
    Init docstring:
        Docstring for ExampleClass.__init__
    ipdb> up
    > <doctest test_ipdb_magics[4]>(11)<module>()
          7    'pinfo a',
          8    'll',
          9    'continue',
         10 ]):
    ---> 11     trigger_ipdb()
    <BLANKLINE>
    ipdb> down
    None
    > <doctest test_ipdb_magics[3]>(3)trigger_ipdb()
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> list
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> pinfo a
    Type:            ExampleClass
    String form:     ExampleClass()
    Namespace:       Locals
    Docstring:       <no docstring>
    Class docstring: Docstring for ExampleClass.
    Init docstring:  Docstring for ExampleClass.__init__
    <BLANKLINE>
    ipdb> ll
          1 def trigger_ipdb():
          2    a = ExampleClass()
    ----> 3    debugger.Pdb().set_trace()
    <BLANKLINE>
    ipdb> continue
>>  raise self.failureException(self.format_failure(<_io.StringIO object at 0x7fcde86b4ee0>.getvalue()))
```

**Comment by tirkarthi** [comment]
The change was later reverted : https://bugs.python.org/issue40257#msg369279

**Comment by frenzymadness** [comment]
I can confirm that the latest IPython works very well with Python 3.9.0b5 we have in Fedora.
