### ISSUE TITLE
multiprocessing.Pool gets stuck indefinitely

### ISSUE THREAD

**Issue by jayaBalaR** [ipython/ipython#12396]
I am facing the same issue in Google colaboratory
multiprocessing.Pool gets stuck indefinitely and never returns. Please refer the screenshots below.
An issue has been raised on https://github.com/jupyter/notebook/issues/5261, but redirected here.
Please refer the screenshots below
![85009690-7e39ce00-b17c-11ea-86d6-fbf23021dfdc](https://user-images.githubusercontent.com/21074002/85047905-1d2bed80-b1b0-11ea-97ca-8ed3a51c690e.png)
![85009560-3d41b980-b17c-11ea-9013-a8ecafd5a232](https://user-images.githubusercontent.com/21074002/85047909-1ef5b100-b1b0-11ea-93b4-5cbcfd7f771b.png)
![85009599-50548980-b17c-11ea-9e74-05a029852380](https://user-images.githubusercontent.com/21074002/85047912-1f8e4780-b1b0-11ea-814b-9054ea79b6bc.png)

**Comment by Carreau** [comment]
That's even a pure Python issue at the normal REPL level:

```
$ python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(1, 2, 3)
KeyboardInterrupt
>>> from multiprocessing import Pool
>>>
>>> def f(x):
...     return x*x
...
>>> if __name__ == '__main__':
...     with Pool(5) as p:
...         print(p.map(f, [1, 2, 3]))
...
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
```

That is likely due to a change in mac os that forces python to use `.spawn()`  instead of `.fork()`. I opened https://bugs.python.org/issue41041 

You can workaround by calling once, early enough `multiprocessing.set_start_method('fork')`, though be careful this is unstable and can crash on macOS (send your complaints to Apple for this).

There is probably a way to pickle and send `__main__` in multiprocessing but I'm not too familiar with it.

**Comment by Carreau** [comment]
a workaround is to use `multiprocess` (to pip-install) instead of multiprocessing.

**Comment by jayaBalaR** [comment]
Okay thank you

**Comment by JorickvdHoeven** [comment]
I can confirm that this is an issue with python switching the default start_method from 'fork' to 'spawn'. In principle we should see this not impact Unix systems as this should be localized to MacOS and Windows, both of which default to 'spawn' in Python 3.8.

I haven't yet found a way to get iPython to play nice with the 'spawn' process starting but other users around the internet have had success with moving referenced methods to modules. 

Maybe there's a way that we can looking into reorganizing how iPython kernels interact with multiprocessing code to serve an interface to the spawning mechanism which is more friendly to it?

**Comment by Carreau** [comment]
Or we could depends on `multiprocess` on macos X and patch sys.module.

**Comment by JorickvdHoeven** [comment]
That would certainly be a work around however I would be wary of relying on a third party library if this library (https://pypi.org/project/multiprocess/) is the one you're referring to. Of course, I'm not super familiar with it so my cursory searching may mean that I've missed out on a lot of the Pathos goodness. 

You mention patching sys.module, what would you suggest patching in there? Would you suggest patching it back to process spawn "fork" with the associated possible issues discussed in https://bugs.python.org/issue41041 or are you referring to patching sys.module to change how the kernel executes multiprocessing code to behave more like the `multiprocess` module?

**Comment by krlng** [comment]
Up to now, `multiprocessing.set_start_method('fork')` worked for me quite well as a workarround, thanks @Carreau

**Comment by L-F-S** [comment]
I am having the same problem on a jupyter-notebook on windows.
using `multiprocessing.set_start_method('fork')` gives  the following error: 'ValueError: cannot find context for 'fork''

**Comment by kasyachitche** [comment]
> I am having the same problem on a jupyter-notebook on windows. using `multiprocessing.set_start_method('fork')` gives the following error: 'ValueError: cannot find context for 'fork''

Because there is the one [choice](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) on windows.
