### ISSUE TITLE
'nonlocal' misclassified as incomplete code

### ISSUE THREAD

**Issue by RJ722** [ipython/ipython#12408]
If I enter, line-by-line, a nonlocal statement in an inner function, ipython throws a syntax error, e.g.:

```
In [1]: def a():
   ...:     def b():
   ...:         nonlocal c
  File "<ipython-input-1-dbf568c371f7>", line 3
    nonlocal c
    ^
SyntaxError: no binding for nonlocal 'c' found
```

The following code runs fine on python interpreter (and if execured as a file):

```python
def a():
    def b():
        nonlocal c
        return c + 1
    c = 1
    b()
    return c

print(a())
```

This was originally reported by Chris Angelico as a bug in IDLE -- https://bugs.python.org/issue19335

I can successfully reproduce it on IPython 7.16.1. Here is the output of `python -c "import IPython; print(IPython.sys_info())"`:

```python
{'commit_hash': '2486838d9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/rahuljha/.virtualenvs/vulture/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.16.1',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/rahuljha/.virtualenvs/vulture/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.7.0b5 (v3.7.0b5:abb8802389, May 30 2018, 20:03:19) \n'
                '[Clang 6.0 (clang-600.0.57)]'}
```

**Comment by Carreau** [comment]
Well this is an issue with Python itself as `compile()` return a syntax error:
```
$ python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
SyntaxError: EOF while scanning triple-quoted string literal
>>> a = """
... def a():
...     def b():
...         nonlocal c
... """
>>> compile(a, '', 'exec')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "", line 4
SyntaxError: no binding for nonlocal 'c' found
```

So not sure we can do much.

**Comment by MrMino** [comment]
I'm afraid this isn't how `nonlocal` works. Python needs to know in advance which variable the `nonlocal` should bind to. Consider this:

```
def a():
    def b():
        def c():
             nonlocal d
```

Without `d` being declared anywhere, Python doesn't know to which scope this declaration refers to.

> The following code runs fine on python interpreter (and if execured as a file):

It also runs fine in IPython. I don't think there's any bug for us to fix here.

**Comment by RJ722** [comment]
> It also runs fine in IPython.

There might be a confusion here. I just tried this out: If you copy-paste the code, it works perfectly. However, if you enter it line-by-line, `SyntaxError` is raised as soon as it encounters `nonlocal`:

```
In [1]: def a():
   ...:     def b():
   ...:         nonlocal c
  Input In [1]
    nonlocal c
    ^
SyntaxError: no binding for nonlocal 'c' found
```

**Comment by MrMino** [comment]
Oh, I get it now. I was mentally stuck on why would you want to defer that error, because in my mind you have no way of fixing in the lines following - I forgot you would want to just add `c` in the `a` scope after finishing `b` definition.

**Comment by aryansk** [comment]
I’m working on a focused completeness-check fix for the line-by-line `nonlocal` case, with regression coverage to ensure IPython waits for the enclosing scope before declaring the input invalid. I’ll keep it narrow and step aside if there’s an active fix I missed.
