### ISSUE TITLE
ipykernel install throws ImportError: libsodium in a virtual environment

### ISSUE THREAD

**Issue by Isaacsh** [ipython/ipython#12409]
I'm following this [link](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments)

My conda info (summarized) is as follows:

```python
conda version : 4.7.11
python version : 3.7.1.final.0
platform : linux-64
```

I created a new virtual env by running

```python
conda create -n myenv python=3.7.* jupyter ipyparallel
```

Then I activate it by `conda activate myenv` and run this:

```python
python -m ipykernel install --user --name=myenv
```

which produces the following error:

```
Traceback (most recent call last):
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```

I checked inside Python console to see if I can import zmq, but it errored out:

```
(myenv) datascientist@e0a2ac9b9c6f:~$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/opt/oss/conda3/envs/myenv/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```

**Comment by Carreau** [comment]
This is likely an issue with zmq itself. 

Try to reinstall but using `-c conda-forge` to pull from the conda-forge channel.

**Comment by Isaacsh** [comment]
Reinstalling from `conda-forge` channel solved the issue. Thanks!
