### ISSUE TITLE
Autoreload fails when reloading frozen data classes

### ISSUE THREAD

**Issue by eehusky** [ipython/ipython#12411]
I have autoreload turned on and when reloading a data class with the frozen attribute enabled i get the following error.

```
[autoreload of MotionPlanner.TrajectoryGenerator failed: Traceback (most recent call last):
  File "C:\Users\sparky\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\sparky\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "C:\Users\sparky\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 347, in update_generic
    update(a, b)
  File "C:\Users\sparky\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_class
    update_instances(old, new)
  File "C:\Users\sparky\anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 280, in update_instances
    ref.__class__ = new
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field '__class__'
]
```

It appears that the module does in fact reload successfully if a re-run a cell (I am using IPython via JupyterLab)

```
{'commit_hash': '2922831ac',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Users\\sparky\\anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '7.15.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Users\\sparky\\anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit '
                '(AMD64)]'}
```

This is an example of the class definition.

```python
@dataclass(init=True, repr=True, eq=True, frozen=True, order=True)
class Constraints(object):
    q0: float
    q1: float
    v0: float
    v1: float
    j_max: float
    a_max: float
    v_max: float
    duration: float = None
```

It works eventually but figured it would be worth bringing it up.  I'm not 100% certain this is an IPython problem (could be Jupyter?).

**Comment by ottumm** [comment]
I am also running into this same issue using the ipython console in a terminal, so I do think it's an IPython Kernel issue and not a Jupyter issue.

**Comment by ottumm** [comment]
Also cross-linking https://github.com/ipython/ipython/issues/12185.
