### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by anand-jungade** [ipython/ipython#12424]
![image](https://user-images.githubusercontent.com/47827377/86519973-891f7e80-be5d-11ea-8c01-c7226eb88457.png)

**Comment by Carreau** [comment]
what is p1 ?

**Comment by anand-jungade** [comment]
p1 is a data frame (of pandas).

**Comment by Carreau** [comment]
You probably want to give more details about how you got it, what you did before, which verison of IPython, jedi, prompt_toolkit you have. 

Usually just asking for a dataframe shape does not crash for everybody, so I'll need more details.

**Comment by 10office** [comment]
I meet the error as well. How about this?

In [66]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start.py", line 106, in start.attach_ipython
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\IPython\__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\IPython\terminal\interactiveshell.py", line 566, in mainloop
    self.interact()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\IPython\terminal\interactiveshell.py", line 549, in interact
    code = self.prompt_for_code()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\IPython\terminal\interactiveshell.py", line 474, in prompt_for_code
    text = self.pt_app.prompt(
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1034, in prompt
    return self.app.run(
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 978, in run
    return loop.run_until_complete(
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\site-packages\prompt_toolkit\eventloop\inputhook.py", line 120, in select
    th.start()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

If you suspect this is an IPython 7.31.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Process Process-21:
Traceback (most recent call last):
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 2, in run
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
Process Process-20:466:2:
Traceback (most recent call last):
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 2, in save_file
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
BrokenPipeError: [WinError 232] The pipe is being closed
Process Process-20:468:
Traceback (most recent call last):
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 2, in execute
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
MemoryError
Process Process-20:467:
Traceback (most recent call last):
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 2, in monitor
  File "C:\app\TESTUS\python\python-3.8.10.amd64\lib\multiprocessing\managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
BrokenPipeError: [WinError 232] The pipe is being closed
