### ISSUE TITLE
"OSError: [Errno 9] Bad file descriptor" When try to Install the library in Python IDLE

### ISSUE THREAD

**Issue by smathimech** [ipython/ipython#12436]
I'm a beginner to the Python program. when I'm trying to install the "numby" library using windows command prompt. but I'm getting the following error.
 

so please help me to resolve this issue. 

![numpy error](https://user-images.githubusercontent.com/66507831/87312042-b0e9a300-c53d-11ea-943d-7edb5040e8a3.PNG)

**Comment by Carreau** [comment]
This is the bug tracker for IPython, it is not related to idle, or numpy. 

For data science environment I strongly recommend for you to install anaconda https://www.anaconda.com/products/individual#Downloads which will make the pain of installing most of the scientific ecosystem go away.

Closing as there is not much to do here, but feel free to keep commenting.

**Comment by AvAkanksh** [comment]
Even i am facing the same problem , even though i have installed the python using anaconda .


`C:\Users\avaka>pip install numpy
Traceback (most recent call last):
  File "C:\Users\avaka\anaconda3\Scripts\pip-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "C:\Users\avaka\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 114, in <module>
    from . import utils
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 27, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_vendor\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\avaka\anaconda3\lib\site-packages\pip\_vendor\requests\compat.py", line 65, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 973, in get_data
OSError: [Errno 9] Bad file descriptor`

**Comment by AvAkanksh** [comment]
it would better if  i send you the screenshot of the error
here go the screenshot of the error , please do help me !
![image](https://user-images.githubusercontent.com/49116510/88872004-e2998400-d236-11ea-87cc-acd8925c1e2e.png)

**Comment by AvAkanksh** [comment]
Basically i am getting the error for each an every package i want to install , its not about pip install <package >, but pip alone , just in case i perform any task using pip always ends up like this so please help me.

**Comment by Carreau** [comment]
Not an IPython issue.
