### ISSUE TITLE
autoreload fails silently upon syntax errors

### ISSUE THREAD

**Issue by sntgluca** [ipython/ipython#12446]
Dear all,
If this has already been discussed, apologies, I couldn't find it...

I am enjoying autoreload more and more in my development / prototyping days with JupyterLab :)

One major difficulty I experience is that, if I introduce syntax errors in the code to reload, (at least by default) I don't get any error messages when a cell tries to call the broken code.
It fails implicitly, which is less than ideal. I would prefer having the error output in my cell, this would make easier to catch the errors.

Of course there are other angles to look at the problem: I could double-check my code for instance, but this would be another point...

**Comment by Carreau** [comment]
Yes, you are right I came across this recently, having it fail with explicit error messages would be great.

**Comment by nicolaslazo** [comment]
Hi! I was checking the issues for the 8.0 release and found I couldn't reproduce this one but there's no linked PR. Shall I close it?

```
In [1]: %load_ext autoreload

In [2]: %autoreload 2

In [3]: import asdf

In [4]: asdf.asdfg()
Out[4]: 2

In [5]: """
   ...: Content of asdf.py is
   ...:     def asdfg():
   ...:         a=0
   ...:         a+=2
   ...:         return a
   ...:     
   ...: Is is then changed to
   ...:     def asdfg():
   ...:         a=0
   ...:         a++=2
   ...:         return a
   ...: """
[autoreload of asdf failed: Traceback (most recent call last):
  File "/home/user/repos/ipython/IPython/extensions/autoreload.py", line 257, in check
    superreload(m, reload, self.old_objects)
  File "/home/user/repos/ipython/IPython/extensions/autoreload.py", line 451, in superreload
    module = reload(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/swaves/repos/ipython/asdf.py", line 3
    a++=2
      ^
SyntaxError: invalid syntax
]
Out[5]: '\nContent of asdf.py is\n    def asdfg():\n        a=0\n        a+=2\n        return a\n    \nIs is then changed to\n    def asdfg():\n        a=0\n        a++=2\n        return a\n'
```
