### ISSUE TITLE
Error while importing sklearn.metrics as loss

### ISSUE THREAD

**Issue by AnuragAnalog** [ipython/ipython#12458]
```ipython3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: try: 
   ...:     assert 1/0 
   ...: except: 
   ...:     print("Cant divide with zero") 
   ...:                                                                
Cant divide with zero

In [2]: help(try)                                                      
  File "<ipython-input-2-0d04fc436cf0>", line 1
    help(try)
           ^
SyntaxError: invalid syntax


In [3]: help("try")                                                    


In [4]: import os                                                      

In [5]: os.system("du -h app.py")                                      
8.0K	app.py
Out[5]: 0

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
In [6]: import sklearn.metrics as loss                                 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset({('resolve_stars', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.6/dist-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/anurag/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 552, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 535, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 464, in prompt_for_code
    **self._extra_prompt_options())
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/shortcuts/prompt.py", line 986, in prompt
    return self.app.run()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 788, in run
    return get_event_loop().run_until_complete(self.run_async(pre_run=pre_run))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 772, in run_async
    return await _run_async2()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 760, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 840, in cancel_and_wait_for_background_tasks
    await task
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1684, in async_completer
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 90, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 100, in _get_completions
    for c in completions:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 1815, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 1872, in _completions
    signature = _make_signature(jm)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 989, in _make_signature
    return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for p in completion.params) if f])
  File "/usr/local/lib/python3.6/dist-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/classes.py", line 350, in params
    for n in signature.get_param_names(resolve_stars=True)
  File "/usr/local/lib/python3.6/dist-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/signature.py", line 89, in get_param_names
    params = process_params(params)
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/star_args.py", line 190, in process_params
    )), star_count=2):
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/star_args.py", line 115, in process_params
    kwarg_callables = list(_iter_nodes_for_param(p))
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/star_args.py", line 51, in _iter_nodes_for_param
    assert False
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Input cell 6 caused this exception
I don't know which error caused this, but when I type "import sklearn.metrics as loss", I get this exception and the Ipython shell is terminated automatically. What to do?

**Comment by Carreau** [comment]
1) you installation likely have a numpy problem. 
2) this was likely triggered when you pressed tab at some point as jedi is related to tab completion.

Try to a) update IPython you are 7 version behind, and to update jedi.
Also update numpy, sklearn, and Python to at least Python 3.7, IPython does not support 3.6 anymore.

**Comment by AnuragAnalog** [comment]
Thank you, I'll update the packages
