### ISSUE TITLE
ipython crashes on launch

### ISSUE THREAD

**Issue by nraiha** [ipython/ipython#12466]
Hi,

I installed ipython with `pip install ipython`
When I try to launch it I get `ModuleNotFoundError: No module named 'pydoc'.`

Python 3.8.5
pip 20.1.1
pydoc.py can be found at `/usr/local/lib/python3.10/pydoc.py`

`python -m IPython` does not work either.

Callstack:
```
Traceback (most recent call last):
  File "/home/nuutti/.local/bin/ipython", line 5, in <module>
    from IPython import start_ipython
  File "/home/nuutti/.local/lib/python3.8/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/home/nuutti/.local/lib/python3.8/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/nuutti/.local/lib/python3.8/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/nuutti/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 97, in <module>
    import pydoc
ModuleNotFoundError: No module named 'pydoc'
```

Seems that the pydoc.py found is from python 3.10 install. When ipython is installed via pip3.10 it works.

Can anyone advise me how to get pydoc.py to 3.8.5 or should I just use python 3.10? Python 3.8.5 is installed via packet manager

**Comment by MrMino** [comment]
Hi

If it's Python 3.8.5 that you are using, why is the library installed in "lib/python**3.10**/" ?
Looks to me like you have an issue with different commands being run under different environment sites - try to `pip uninstall ipython`, then `python -m pip install ipython` again.

**Comment by nraiha** [comment]
Hi.

The problems seems to be that the package manager installs python with --without-doc-strings switch. So I can fix this by installing python manually
