### ISSUE TITLE
About ipython open failure

### ISSUE THREAD

**Issue by thedevilsgrave** [ipython/ipython#12486]
```
error massage:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\gitee\cesium\Scripts\ipython3.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "e:\gitee\cesium\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "e:\gitee\cesium\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "e:\gitee\cesium\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "e:\gitee\cesium\lib\site-packages\IPython\terminal\ipapp.py", line 317, in initialize
    self.init_shell()
  File "e:\gitee\cesium\lib\site-packages\IPython\terminal\ipapp.py", line 333, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "e:\gitee\cesium\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "e:\gitee\cesium\lib\site-packages\IPython\terminal\interactiveshell.py", line 526, in __init__
    self.init_prompt_toolkit_cli()
  File "e:\gitee\cesium\lib\site-packages\IPython\terminal\interactiveshell.py", line 330, in init_prompt_toolkit_cli
    **self._extra_prompt_options())
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 458, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 738, in _create_application
    output=self._output,
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\application\application.py", line 266, in __init__
    self.output = output or session.output
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\application\current.py", line 65, in output
    self._output = create_output()
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\output\defaults.py", line 54, in create_output
    return cast(Output, Windows10_Output(stdout))
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\output\windows10.py", line 28, in __init__
    self.win32_output = Win32Output(stdout)
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\output\win32.py", line 101, in __init__
    info = self.get_win32_screen_buffer_info()
  File "e:\gitee\cesium\lib\site-packages\prompt_toolkit\output\win32.py", line 196, in get_win32_screen_buffer_info
    self.hconsole, byref(sbinfo)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
```

**Comment by Carreau** [comment]
try to update IPython and Prompt_Toolkit.
