### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor : whenever i try to install any python package.

### ISSUE THREAD

**Issue by ShlokKatare** [ipython/ipython#12505]
PROBLEM:
Anaconda Navigator does not run and the prompt gives the same error whenever i use conda or pip to install anything, PyCharm refuses to import any package because of the same error also in normal python interpreter pip install gives the same error.
So in short i cant run external packages on any of my python IDE as all of them while i install end up with the same error.

TRIED:
I tried re installing anaconda, python, pycharm several times yet it gives the same error, all the paths in the environmental variables are also set properly by default. 

REQUEST:
Please find a solution as i ws unable to find any solution also i need these packages for my projects I am kindof stuck here.

ERROR:

Microsoft Windows [Version 10.0.18362.1016]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\uk>pip3 install pandas
Traceback (most recent call last):
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\uk\AppData\Local\Programs\Python\Python38-32\Scripts\pip3.exe\__main__.py", line 9, in <module>
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\__init__.py", line 114, in <module>
    from . import utils
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\utils.py", line 27, in <module>
    from ._internal_utils import to_native_string
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "c:\users\uk\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\requests\compat.py", line 65, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 973, in get_data
OSError: [Errno 9] Bad file descriptor
![Untitled](https://user-images.githubusercontent.com/64885571/90857806-87286500-e3a2-11ea-9a37-b69fb243c079.jpg)

**Comment by Carreau** [comment]
That feel like a problem with pandas/pip/anaconda I don't see mentions of IPython anywhere in here.

You seem to have installed Python both using anaconda and the installer at Python.org, you likely don't want to do that.

**Comment by Sandeepbeast** [comment]
@ShlokKatare did you get solution for the OSerror problem?
I'm stuck with the same problem while installing any new lib
