### ISSUE TITLE
`with logging.disable('WARN')` wrecks IPython

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ipython/ipython#12713]
```python
import logging
with logging.disable('WARN'): pass
```
[demo.mp4](https://puu.sh/GSQEk/3f1d0e8607.mp4). Not reproduced if ran as script. Win10 x64, IPython 7.19.0, Python 3.7.7.

**Comment by AsafFisher** [comment]
`logging.disable` does not have context manager///

**Comment by OverLordGoldDragon** [comment]
Yes but IPython shouldn't respond the way it does.

**Comment by AsafFisher** [comment]
To me it does not happen are you sure your setup is not misconfigured check pip freeze and everything

**Comment by OverLordGoldDragon** [comment]
Installed latest 7.19.0 via Anaconda on Windows 10, still flooding a pure IPython terminal. Pressing any key duplicates below error message, and cannot interrupt, must kill terminal.

<details>
  <summary>img</summary>

![image](https://user-images.githubusercontent.com/16495490/102002493-7ff0e280-3d16-11eb-80c4-05f66f6271ed.png)

</details>

**Comment by Carreau** [comment]
No this is a "bug" in python, you are breaking AsyncIO.

And it's not the context manager its `disable("WARN")` that is wrong. disable takes int, not str you meant: `logging.disable(logging.WARN)`. Which will work.

```python
$ python foo.py
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/logging/__init__.py", line 1685, in isEnabledFor
    return self._cache[level]
KeyError: 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 17, in <module>
    asyncio.run(main())
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/runners.py", line 39, in run
    loop = events.new_event_loop()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/events.py", line 758, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/selector_events.py", line 59, in __init__
    logger.debug('Using selector: %s', selector.__class__.__name__)
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/logging/__init__.py", line 1421, in debug
    if self.isEnabledFor(DEBUG):
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/logging/__init__.py", line 1689, in isEnabledFor
    if self.manager.disable >= level:
TypeError: '>=' not supported between instances of 'str' and 'int'
Exception ignored in: <function BaseEventLoop.__del__ at 0x1038a65e0>
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/base_events.py", line 656, in __del__
    self.close()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/Users/bussonniermatthias/miniconda3/lib/python3.8/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
sys:1: RuntimeWarning: coroutine 'main' was never awaited
$ cat pytest.ini
```
```python
$ cat foo.py
import asyncio

async def count():
    print("One")
    await asyncio.sleep(1)
    print("Two")

async def main():
    await asyncio.gather(count(), count(), count())

import logging
logging.disable('WARN')

if __name__ == "__main__":
    import time
    s = time.perf_counter()
    asyncio.run(main())
    elapsed = time.perf_counter() - s
    print(f"{__file__} executed in {elapsed:0.2f} seconds.")
```

You may want to open a bug in CPython.

**Comment by OverLordGoldDragon** [comment]
[Made one](https://bugs.python.org/issue42644); I don't really follow what's breaking here (the workaround is clear though), so I'll leave it to them. Also your bottom code snippet still crashes IPython for me. I further noticed that running as script does ultimately kill IPython, but differently: 1) kernel restart works; 2) console isn't flooded with messages. If you think fix lies outside IPython, feel free close the Issue.

**Comment by Carreau** [comment]
> Also your bottom code snippet still crashes IPython for me.

Yes, the point of this code snippet is that it fails even outside of IPython; and there for that the error is not in IPython itself.

I'll follow up upstream.

**Comment by MrMino** [comment]
IIUC this has been resolved upstream.

In 3.9.1:

```py
In [1]: import logging
   ...: with logging.disable('WARN'): pass
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-bbe58e505dd2> in <module>
      1 import logging
----> 2 with logging.disable('WARN'): pass

AttributeError: __enter__
```
