### ISSUE TITLE
iPython 7.19.0 autocomplete breaks with jedi <=0.17.0 and parso >=0.8.0

### ISSUE THREAD

**Issue by GregDungca** [ipython/ipython#12747]
Tab complete results in no response with the specified combo of package versions installed. This is because jedi <=0.17.0 is incompatible with parso >= 0.8.0 even though its package requirements say otherwise. It was fixed in jedi here: https://github.com/davidhalter/jedi/commit/cf1b54cfe590cd320421ecf76930e661653d68bd

This affected many users at our company, and it took some effort to track down.

I'm not sure for cases like this whether we should update the version specifier for the dependency. It would be jedi>=0.17.1 in this case.

**Comment by Hex-Tron** [comment]
I have also same error after updating python3.8.5 Then I fresh install my Linux mint 
![jupter version](https://imgur.com/0gZMF0g.png)
-----
I Tried everything reinstall python to python3.9.1 and jupyter from pip
None seems to work
```[I 2020-12-30 10:07:29.404 ServerApp] Kernel started: bad34d2d-ab3e-4323-9625-0402bafbbc41
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/tmp/ipykernel/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/tmp/ipykernel/ipykernel/kernelbase.py", line 576, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/tmp/ipykernel/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/tmp/ipykernel/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/usr/local/lib/python3.8/dist-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

```

**Comment by paw-lu** [comment]
Was in the middle of debugging this
Thank you so much @GregDungca !

**Comment by paw-lu** [comment]
Actually autocomplete is also not working for me on a fresh install with 

```txt
jedi==0.18.0
parso==0.7.1
```

**Comment by GregDungca** [comment]
@paw-lu are you getting the errors described here? https://github.com/ipython/ipython/issues/12745

There's a separate issue right now with jedi 0.18.0.

**Comment by paw-lu** [comment]
Seems #12740 explains it. Jedi 0.18.0 has its own issues. [Downgrading to 0.17.2](https://github.com/ipython/ipython/issues/12740#issuecomment-751273584) is a temporary fix.

**Comment by paw-lu** [comment]
> @paw-lu are you getting the errors described here? #12745

Yeah I jumped the gun there! Separate issue on my end. Apologies!

**Comment by XingXingXudong** [comment]
Flow the #12745 and [this](https://github.com/ipython/ipython/issues/12745#issuecomment-752151883). The error is Fix.

**Comment by dangreenisrael** [comment]
Does anyone know why the version iPython isn't pinned? https://github.com/ipython/ipython/blob/21f8f14b18b4a8e4ed2277195a0270299baa9423/setup.py#L187

**Comment by paw-lu** [comment]
@dangreenisrael 
not sure on the actual reason, but #12751 was opened to pin the dependency on the `7.x` branch, which should fix this current issue.
