### ISSUE TITLE
Ipython gets stuck when I use the TAB key to complete and report an error

### ISSUE THREAD

**Issue by zhangyanyao** [ipython/ipython#12748]
$ ipython
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: impo
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.6/dist-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 817, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1684, in async_completer
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/usr/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/usr/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/usr/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by zgoda** [comment]
This is related to jedi 0.18, downgrading to 0.17.2 fixes this issue.

**Comment by tomp** [comment]
Downgrading jedi fixed this for me.  thank you!

**Comment by Lebhoryi** [comment]
my jedi is 0.18, and  `pip install jedi==0.17.2` it solved the question! thx!

**Comment by hueyyeng** [comment]
I hit this issue when setting up a brand new dev environment for Ubuntu with Win10 WSL2 and was wondering why pressing Tab resulted in the same error.

```bash
  File "/home/hueyyeng/.pyenv/versions/3.6.12/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/home/hueyyeng/.pyenv/versions/3.6.12/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/home/hueyyeng/.pyenv/versions/3.6.12/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/home/hueyyeng/.pyenv/versions/3.6.12/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
```

Downgrading jedi to 0.17.2 solves the issue when pressing Tab in IPython for autocompletion.

**Comment by k0al4** [comment]
Just lost the day because of that, but now it's fixed. Thanks!

**Comment by konflic** [comment]
This bug comes bundled with latest jupyter right now

**Comment by MrMino** [comment]
`pip install jed==0.17.2`

**Comment by Carreau** [comment]
#12793 fixes it. IPython master already had the changes.

**Comment by shepherdpp** [comment]
downgrading jedi from 0.18.0 to 0.17.2 solved the problem, thank you!

**Comment by charanjit-singh** [comment]
I think this issue is related to `custom Error Handlers`, Django in my case.

**Comment by howge** [comment]
> This is related to jedi 0.18, downgrading to 0.17.2 fixes this issue.

you saved me!  thanks  a lot
