### ISSUE TITLE
Shell crashes after code completion try, on Python 3.7 @ MacOs

### ISSUE THREAD

**Issue by onderezdi** [ipython/ipython#12756]
Getting crash after code completion.
Pyenv environment is Python 3.7 on MacOs 10.13.6 High Sierra

```
Traceback (most recent call last):
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 112, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 519, in handle
    shell()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/django_extensions/management/commands/shell_plus.py", line 314, in run_ipython
    start_ipython(argv=ipython_arguments, user_ns=imported_objects)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 475, in prompt_for_code
    **self._extra_prompt_options())
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 817, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/Users/onderezdi/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1684, in async_completer
    document, complete_event
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/Users/onderezdi/.pyenv/versions/venv37/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by harper357** [comment]
See #12740 for the fix of downgrading `jedi` or waiting for the next release.

**Comment by onderezdi** [comment]
possible duplication with https://github.com/ipython/ipython/issues/12740, closing issue for now.
