### ISSUE TITLE
Error after trying to autocomplete command

### ISSUE THREAD

**Issue by tomukio** [ipython/ipython#12760]
Hi, 
I'm getting the following error after trying to use autocomplete (for example np.[tab]). I don't get any suggestions and after I delete the line, followed by an enter then ipython breaks and the following message appears:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/paulix/.local/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run
    return loop.run_until_complete(
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

I'm using Ipython 7.19.0. I recently updated a bunch of python packages including ipython, I'm unsure if this has something to do.

**Comment by dimbuhdotsud4wUxso** [comment]
> Hi, 
> 
> I'm getting the following error after trying to use autocomplete (for example np.[tab]). I don't get any suggestions and after I delete the line, followed by an enter then ipython breaks and the following message appears:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
> 
>     yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
> 
>     for c in completions:
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
> 
>     completions = list(completions)
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
> 
>     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
> 
>     matched_text, matches, matches_origin, jedi_matches = self._complete(
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
> 
>     completions = self._jedi_matches(
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
> 
>     interpreter = jedi.Interpreter(
> 
>   File "/home/paulix/.local/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
> 
>     super().__init__(code, environment=environment,
> 
> TypeError: __init__() got an unexpected keyword argument 'column'
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/bin/ipython", line 8, in <module>
> 
>     sys.exit(start_ipython())
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
> 
>     return launch_new_instance(argv=argv, **kwargs)
> 
>   File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
> 
>     app.start()
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
> 
>     self.shell.mainloop()
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
> 
>     self.interact()
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
> 
>     code = self.prompt_for_code()
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
> 
>     text = self.pt_app.prompt(
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
> 
>     return self.app.run(set_exception_handler=set_exception_handler)
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run
> 
>     return loop.run_until_complete(
> 
>   File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
> 
>     return future.result()
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
> 
>     return await _run_async2()
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
> 
>     await self.cancel_and_wait_for_background_tasks()
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
> 
>     await task
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
> 
>     await coroutine(*a, **kw)
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
> 
>     async for completion in self.completer.get_completions_async(
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
> 
>     async for completion in completer.get_completions_async(
> 
>   File "/usr/local/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
> 
>     for item in self.get_completions(document, complete_event):
> 
>   File "/usr/local/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
> 
>     exc_type, exc_value, exc_tb = sys.exc_info()
> 
> NameError: name 'sys' is not defined
> 
> 
> 
> I'm using Ipython 7.19.0. I recently updated a bunch of python packages including ipython, I'm unsure if this has something to do.
> 
> 
> 
>
