### ISSUE TITLE
AssertionError: "Application is already running." when using ipdb with matplotlib

### ISSUE THREAD

**Issue by thomasbbrunner** [ipython/ipython#12782]
When running a simple script to create a plot with ipdb, the program crashed with AssertionError: "Application is already running."

## How to reproduce

Run the following script with ipdb3 (`ipdb3 bug.py`). Then press c to start execution of script.

Script file:
```
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
```

Output (shortened):
```
thomas@thisone:~/code/snippets$ ipdb3 ipdb_bug.py 
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
      1 
----> 2 import matplotlib.pyplot as plt
      3 

ipdb> c                                                                                                  
Start of script
End of script
The program finished and will be restarted
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
      1 
----> 2 import matplotlib.pyplot as plt
      3 

ipdb> Exception in thread Thread-36:                                                                     
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/debugger.py", line 102, in in_thread
    line = self.pt_app.prompt()
  File "/usr/lib/python3/dist-packages/prompt_toolkit/shortcuts/prompt.py", line 797, in prompt
    return run_sync()
  File "/usr/lib/python3/dist-packages/prompt_toolkit/shortcuts/prompt.py", line 786, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/application.py", line 736, in run
    return run()
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/application.py", line 709, in run
    run_until_complete(f, inputhook=inputhook)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/defaults.py", line 126, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/posix.py", line 67, in run_until_complete
    self._run_once(inputhook)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/posix.py", line 86, in _run_once
    self._inputhook_context.call_inputhook(ready, inputhook)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/inputhook.py", line 84, in call_inputhook
    inputhook(self)
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 576, in inputhook
    self._inputhook(context)
  File "/usr/lib/python3/dist-packages/IPython/terminal/pt_inputhooks/tk.py", line 88, in inputhook
    wait_using_filehandler()
  File "/usr/lib/python3/dist-packages/IPython/terminal/pt_inputhooks/tk.py", line 65, in wait_using_filehandler
    root.createfilehandler(inputhook_context.fileno(), _tkinter.READABLE, done)
RuntimeError: Calling Tcl from different apartment
Start of script
End of script
The program finished and will be restarted
```

## Why it happens

After finishing the execution of the program, ipdb automatically restarts the program (at least in my setup). If this happens, the second execution results in the AssertionError: "Application is already running." The program is then restarted in an endless loop and fills the terminal with error messages.

## Why it matters

pdb does not suffer from this bug. The program can be run many times without any problems (see output below).

```
thomas@thisone:~/code/snippets$ pdb3 ipdb_bug.py 
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
-> import matplotlib.pyplot as plt
(Pdb) c
Start of script
End of script
The program finished and will be restarted
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
-> import matplotlib.pyplot as plt
(Pdb) c
Start of script
End of script
The program finished and will be restarted
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
-> import matplotlib.pyplot as plt
(Pdb) c
Start of script
End of script
The program finished and will be restarted
> /home/thomas/code/snippets/ipdb_bug.py(2)<module>()
-> import matplotlib.pyplot as plt
(Pdb) 

```

Versions:
ubuntu 20.04
python: 3.8.5
ipython: 7.13.0
matplolib: 3.1.2

**Comment by Carreau** [comment]
@tacaswell ?

**Comment by thomasbbrunner** [comment]
I don't think this is a matplotlib problem. As stated above, this does not happen when using `pdb`.
