### ISSUE TITLE
Couldn't get model class object after import the model 

### ISSUE THREAD

**Issue by kathirraja** [ipython/ipython#12785]
I tried to import django models and simply tried type <mode_class_name> and enter then I got this following error

```
In [4]: from myapp.models import ModelClass

In [5]: ModelClass
Traceback (most recent call last):
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kathir/cardfind/cardfind/manage.py", line 22, in <module>
    main()
  File "/home/kathir/cardfind/cardfind/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 100, in handle
    return getattr(self, shell)(options)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 36, in ipython
    start_ipython(argv=[])
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 825, in run
    return loop.run_until_complete(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 792, in run_async
    return await _run_async2()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/kathir/anaconda3/envs/cf/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined
```

**Comment by douardda** [comment]
Same here (python 3.9.1, ipython 7.19.0 pip-installed in a venv).
This is a fit funky because the `sys` is actually imported in this `ptutils.py` module...

**Comment by kathirraja** [comment]
I just fixed it by importin sys and traceback module

**Comment by douardda** [comment]
But I guess the true problem happen before, in 

> I just fixed it by importing "sys" and "traceback" module

But why is this happening? the true problem is the mis-usage of `jedi.Interpreter` class. But in any case, these `sys` and `traceback` modules should already be imported at this point in the module, so why importing them again is needed? Who clears the global namespace in there?

**Comment by Carreau** [comment]
#12793 fixes it. IPython master already had the changes. 

It needed both new compatiblity with jedi and importing sys and tb in the 7.x branch.
