### ISSUE TITLE
sys.excinfo() but sys is not imported

### ISSUE THREAD

**Issue by guy4261** [ipython/ipython#12784]
https://github.com/ipython/ipython/blob/6a7c488093026577db0d5c5f21d2aea129e5b6c9/IPython/terminal/ptutils.py#L118

Just got a crash because of this (in the context of another exception).

```python
Traceback (most recent call last):
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grapaport/miniconda3/envs/py38/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 825, in run
    return loop.run_until_complete(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 792, in run_async
    return await _run_async2()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/Users/grapaport/miniconda3/envs/py38/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined
```

**Comment by guy4261** [comment]
My bad - seems like it's solved in the nightly build.
