### ISSUE TITLE
RuntimeError: generator raised StopIteration error while running ipython from terminal

### ISSUE THREAD

**Issue by alejandrozuleta** [ipython/ipython#12787]
When I try to run ipython command to open an interactive session this error is thrown.

```
(venva) [user@user-machine folder]$ ipython
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 553, in _load_config_files
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/venva/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/IPython/core/application.py", line 460, in initialize
    self.load_config_file()
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/IPython/core/application.py", line 316, in load_config_file
    Application.load_config_file(
  File "<decorator-gen-5>", line 2, in load_config_file
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/user/.pyenv/versions/venva/lib/python3.8/site-packages/traitlets/config/application.py", line 561, in load_config_file
    for config in self._load_config_files(filename, path=path, log=self.log,
RuntimeError: generator raised StopIteration

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```
OS: Manjaro
Python: 3.8.6
Ipython: 7.19.0

**Comment by alejandrozuleta** [comment]
I just figured out traitlets package version was 4.2.1 so upgrade it to 5.0.5 version and it works smoothly now.
