### ISSUE TITLE
IPython throws error on exitfuncs when the program is unsuspended in a different directory and the initial directory has been removed

### ISSUE THREAD

**Issue by PythonCoderAS** [ipython/ipython#12867]
If I were to suspend ipython, change directory, and bring ipython to foreground, and run exit, ipython will throw an exception as it is exiting.

```
...
❯ cd ..
❯ rm -rf ~/Manga/mangadex-dl/download
❯ fg
[1]  - 15305 continued  ipython
(pwd : ~/Manga/mangadex-dl/download)
In [5]: exit
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3802, in atexit_operations
    self.reset(new_session=False)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1421, in reset
    self.history_manager.reset(new_session)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/history.py", line 592, in reset
    self.dir_hist[:] = [os.getcwd()]
FileNotFoundError: [Errno 2] No such file or directory
(pwd now: ~/Manga/mangadex-dl)
```

**Comment by MrMino** [comment]
That is quite an edge case. I haven't really studied how Linux handles cases where curdir for a process gets deleted, but IMO IPython code should be shielded against the `FileNotFoundError`.

Note to self: Is there any way this could happen under Windows?

**Comment by PythonCoderAS** [comment]
> That is quite an edge case. I haven't really studied how Linux handles cases where curdir for a process gets deleted, but IMO IPython code should be shielded against the `FileNotFoundError`.
> 
> Note to self: Is there any way this could happen under Windows?

This cannot happen in Windows for two reasons.

1. Windows does not let you suspend console programs like Unix systems do.
2. Windows will not let you delete directories that a program is open in. For example, if I open a Windows Command Prompt, cd to a dir, and try deleting it, it'll throw errors until I close any open programs.

**Comment by MrMino** [comment]
I was pondering whether there's a way for this to become a race condition on windows when using `%cd`. Not sure how related it would be to this particular case, I'm just curious.

**Comment by christopherphan** [comment]
Another datapoint, which I offer in the hope that it will be helpful to you. I ran into this issue:

1) on MacOS
2) without having suspended iPython

I opened iPython in a terminal window in an empty directory, and then renamed the directory from another terminal window. When I tried to `exit` from iPython, I got this traceback:

```
Traceback (most recent call last):
  File "/Users/chris/Documents/prog_journal/.venv/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 699, in mainloop
    self._atexit_once()
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3744, in _atexit_once
    self.reset(new_session=False)
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1335, in reset
    self.history_manager.reset(new_session)
  File "/Users/chris/Documents/prog_journal/.venv/lib/python3.10/site-packages/IPython/core/history.py", line 620, in reset
    self.dir_hist[:] = [Path.cwd()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 993, in cwd
    return cls(cls._accessor.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by aryansk** [comment]
I reproduced the failure path here and have a focused fix with regression coverage for reset when the current working directory is gone. I’m preparing a draft PR against `main`.
