### ISSUE TITLE
`AttributeError: 'TypeError' object has no attribute 'tb_frame'` bug

### ISSUE THREAD

**Issue by chrisrytting** [ipython/ipython#12877]
I think I found an iPython bug when trying to use a google research language model to read a text file of prefixes and generate a text file of completions. I tihink it's a bug because none of my code is in the stack trace.
```
In [6]: model.predict(input_file='experiments/experiment/prefixes.txt', output_file
   ...: ='experiments/experiment/predictions.txt')

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 1
13, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_comple
ter)
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 1
26, in _get_completions
    for c in completions:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 438
, in _deduplicate_completions
    completions = list(completions)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 181
8, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeou
t/1000):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 186
2, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 203
0, in _complete
    cursor_pos, cursor_line, full_text)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/completer.py", line 137
4, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/__init__.py", line 726, in
__init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.6/dist-packages/IPython/__init__.py", line 126, in s
tart_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lo                                          │103  nav_gen_chris.py          start_obj.py              train_from_scratch.sh         │10025 step, tf_loss[0.00264650118][1247896]                                            
612 You can print a more detailed traceback right now with "%tb", or use "%debug"      │104  nav_gen_dw.py             start.py                  train_granular.sh             │10026 step, tf_loss[0.00378946098][1247897]                                            
613 to interactively debug it.                                                         │105  nav_gen_dw_UNIFORM2.py    start_wiki.py             training                      │10027 step, tf_loss[0.00152271334][1247898]                                            
614                                                                                    │106  nav_gen_dw_UNIFORM3.py    sub                       train_tasks.sh                │10028 step, tf_loss[0.00456751371][1247899]                                            
615 Extra-detailed tracebacks for bug-reporting purposes can be enabled via:           │107  nav_gen_dw_UNIFORM.py     sub1                      viz                           │10029 step, tf_loss[0.00244110567][1247900]                                            
616     %config Application.verbose_crash=True                                         │108  nav_gen.py                sub3nips                  viz.py                        │10030 step, tf_loss[0.00430229073][1247901]                                            
617                                                 cal/lib/python3.6/dist-packages/traitlets/config/application.py", li
ne 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ipapp.py", line 356
, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py
", line 563, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py
", line 546, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/interactiveshell.py
", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/shortcuts/prompt.py",
 line 1021, in prompt
    set_exception_handler=set_exception_handler, in_thread=in_thread
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/applicati
on.py", line 888, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/applicati
on.py", line 816, in run_async
    return await _run_async2()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/applicati
on.py", line 798, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/applicati
on.py", line 945, in cancel_and_wait_for_background_tasks
    await task
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1909
, in new_coroutine
    await coroutine(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 1739
, in async_completer
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py",
line 272, in get_completions_async
    document, complete_event
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py",
line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/usr/local/lib/python3.6/dist-packages/IPython/terminal/ptutils.py", line 1
16, in get_completions
    print_tb(e)
  File "/usr/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/usr/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/usr/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'
```

**Comment by MrMino** [comment]
Hi, I think this is the same error that #12793 addressed a while back. You have two options here: either upgrade Python to 3.7, so that lets you use the version that is not impacted by this bug, or, as a workaround, downgrade `jedi` library:

```
pip install jedi==0.17.2
```

I'm closing this, but if the above didn't help - feel free to reach out here, I'll reopen if it's something different.
