### ISSUE TITLE
input “import argparse” error occurred

### ISSUE THREAD

**Issue by leowang22** [ipython/ipython#12908]
In [1]: import argparse
Traceback (most recent call last):
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1021, in prompt
    set_exception_handler=set_exception_handler, in_thread=in_thread
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 888, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 798, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 945, in cancel_and_wait_for_background_tasks
    await task
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1739, in async_completer
    document, complete_event
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 272, in get_completions_async
    document, complete_event
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/wy/.espressif/python_env/idf4.2_py3.6_env/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/usr/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/usr/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/usr/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

**Comment by MrMino** [comment]
Hi. If you are running on Python 3.6, please downgrade Jedi `pip install jedi==0.17.2`, it should fix it.

This has been fixed for newer versions in #12793.
