### ISSUE TITLE
7.24.1: building documentation fails

### ISSUE THREAD

**Issue by kloczek** [ipython/ipython#13017]
```console
[tkloczko@barrel ipython-7.24.1]$ PYTHONPATH=$PWD/lub/build make -C docs html
make: Entering directory '/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs'
python3 autogen_api.py
Traceback (most recent call last):
  File "autogen_api.py", line 21, in <module>
    docwriter = ApiDocWriter(package,rst_extension='.rst')
  File "/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/sphinxext/apigen.py", line 128, in __init__
    self.package_name = package_name
  File "/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/sphinxext/apigen.py", line 151, in set_package_name
    self.root_module = import_module(package_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'IPython'
make: *** [Makefile:86: source/api/generated/gen.txt] Error 1
make: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs'
```
```console
PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/build/lib
+ sphinx-build -b man -d python-ipython docs/source .
Running Sphinx v4.0.2
Adding Tag: ipystable
Initializing GitHub plugin
WARNING: html_static_path entry '_static' is placed inside outdir
[autosummary] generating autosummary for: about/history.rst, about/index.rst, about/license_and_copyright.rst, api/index.rst, config/callbacks.rst, config/custommagics.rst, config/details.rst, config/eventloops.rst, config/extensions/autoreload.rst, config/extensions/index.rst, ..., whatsnew/version0.8.rst, whatsnew/version0.9.rst, whatsnew/version1.0.rst, whatsnew/version2.0.rst, whatsnew/version3.rst, whatsnew/version3_widget_migration.rst, whatsnew/version4.rst, whatsnew/version5.rst, whatsnew/version6.rst, whatsnew/version7.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://rpy2.github.io/doc/latest/html/objects.inv...
loading intersphinx inventory from https://jupyter-client.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jedi.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://traitlets.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://ipykernel.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://python-prompt-toolkit.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://ipywidgets.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://ipyparallel.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://pip.pypa.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 75 added, 0 changed, 0 removed
reading sources... [ 62%] sphinxext

>>>-------------------------------------------------------------------------
Exception in /home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/sphinxext.rst at block ending on line None
Specify :okexcept: as an option in the ipython:: block to suppress this message
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-b431797473b4> in <module>
----> 1 from matplotlib.pylab import *

ModuleNotFoundError: No module named 'matplotlib'
<<<-------------------------------------------------------------------------

/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/api/index.rst:12: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'docs/source/api/generated/gen.txt'.
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/options/index.rst:9: WARNING: toctree contains reference to nonexisting document 'config/options/terminal'
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/options/index.rst:9: WARNING: toctree contains reference to nonexisting document 'config/options/kernel'
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/shortcuts/index.rst:17: WARNING: Problems with "csv-table" directive path:
[Errno 2] No such file or directory: 'docs/source/config/shortcuts/single_filtered.csv'.

.. csv-table::
    :header: Shortcut,Filter,Description
    :widths: 30, 30, 100
    :delim: tab
    :file: single_filtered.csv
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/shortcuts/index.rst:27: WARNING: Problems with "csv-table" directive path:
[Errno 2] No such file or directory: 'docs/source/config/shortcuts/multi_filtered.csv'.

.. csv-table::
    :header: Shortcut,Filter,Description
    :widths: 30, 30, 100
    :delim: tab
    :file: multi_filtered.csv
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/interactive/magics.rst:23: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'docs/source/interactive/magics-generated.txt'.

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/build/lib/IPython/sphinxext/ipython_directive.py", line 570, in process_input
    raise RuntimeError('Non Expected exception in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected exception in `/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/sphinxext.rst` line None
The full traceback has been saved in /tmp/sphinx-err-htcs4t0j.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by Carreau** [comment]
I assume it's working on previous versions ? Are you building from the git repository, or sdist (tar.gz) ?
Is that to package on Fedora or similar ?

**Comment by kloczek** [comment]
I have no idea. I'm still working on package first time ipython as rpm package basing on fedora spec.
BTW. After add below patch which switches from distutils to setuptools (AFAIK docutils is now marked as legacy):
```patch
--- a/setup.py~ 2021-06-12 15:16:10.000000000 +0100
+++ b/setup.py  2021-06-12 15:20:27.829325513 +0100
@@ -65,7 +65,7 @@
 # update it when the contents of directories change.
 if os.path.exists('MANIFEST'): os.remove('MANIFEST')

-from distutils.core import setup
+from setuptools import setup

 # Our own imports
 from setupbase import target_update
```
is possible to generate documentation in some unified way like below (still with the same error)
```console
+ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
Adding Tag: ipystable
Initializing GitHub plugin
making output directory... done
[autosummary] generating autosummary for: about/history.rst, about/index.rst, about/license_and_copyright.rst, api/index.rst, config/callbacks.rst, config/custommagics.rst, config/details.rst, config/eventloops.rst, config/extensions/autoreload.rst, config/extensions/index.rst, ..., whatsnew/version0.8.rst, whatsnew/version0.9.rst, whatsnew/version1.0.rst, whatsnew/version2.0.rst, whatsnew/version3.rst, whatsnew/version3_widget_migration.rst, whatsnew/version4.rst, whatsnew/version5.rst, whatsnew/version6.rst, whatsnew/version7.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://rpy2.github.io/doc/latest/html/objects.inv...
loading intersphinx inventory from https://jupyter-client.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jedi.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://traitlets.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://ipykernel.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://python-prompt-toolkit.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://ipywidgets.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://ipyparallel.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://pip.pypa.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 75 added, 0 changed, 0 removed
reading sources... [ 62%] sphinxext

>>>-------------------------------------------------------------------------
Exception in /home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/sphinxext.rst at block ending on line None
Specify :okexcept: as an option in the ipython:: block to suppress this message
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-b431797473b4> in <module>
----> 1 from matplotlib.pylab import *

ModuleNotFoundError: No module named 'matplotlib'
<<<-------------------------------------------------------------------------

/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/api/index.rst:12: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'docs/source/api/generated/gen.txt'.
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/options/index.rst:9: WARNING: toctree contains reference to nonexisting document 'config/options/terminal'
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/options/index.rst:9: WARNING: toctree contains reference to nonexisting document 'config/options/kernel'
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/shortcuts/index.rst:17: WARNING: Problems with "csv-table" directive path:
[Errno 2] No such file or directory: 'docs/source/config/shortcuts/single_filtered.csv'.

.. csv-table::
    :header: Shortcut,Filter,Description
    :widths: 30, 30, 100
    :delim: tab
    :file: single_filtered.csv
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/config/shortcuts/index.rst:27: WARNING: Problems with "csv-table" directive path:
[Errno 2] No such file or directory: 'docs/source/config/shortcuts/multi_filtered.csv'.

.. csv-table::
    :header: Shortcut,Filter,Description
    :widths: 30, 30, 100
    :delim: tab
    :file: multi_filtered.csv
/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/interactive/magics.rst:23: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'docs/source/interactive/magics-generated.txt'.

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/IPython/sphinxext/ipython_directive.py", line 570, in process_input
    raise RuntimeError('Non Expected exception in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected exception in `/home/tkloczko/rpmbuild/BUILD/ipython-7.24.1/docs/source/sphinxext.rst` line None
The full traceback has been saved in /tmp/sphinx-err-g2w9oaob.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
error: Bad exit status from /var/tmp/rpm-tmp.pS85MF (%build)
```
In mean time I found that I have missing matplot module which is not easy to package and has some circular dependencies (generate matplot documentation requires ipython and to generate ipthon documentation looks like I need as well matplot)

**Comment by Carreau** [comment]
I'm quite astonished there is not already an RPM package for IPython, and yes the matplotlib <-> IPython circular dependency is annoying, though those dependencies should be optional, I'll see if we can have an option to build the docs w/o triggering those issues, though we are a bit understaffed.

You likely want a
```
make -C docs api autoconfig automagic autogen_shortcuts
```

Before `/usr/bin/python3 setup.py build_sphinx -b man`, this will generate a number of files, at least that removed issues with  some of the errors you have.

**Comment by kloczek** [comment]
> I'm quite astonished there is not already an RPM package for IPython, and yes the matplotlib <-> IPython circular dependency is annoying, though those dependencies should be optional, I'll see if we can have an option to build the docs w/o triggering those issues, though we are a bit understaffed.
> 
> You likely want a
> 
> ```
> make -C docs api autoconfig automagic autogen_shortcuts
> ```
> 
> Before `/usr/bin/python3 setup.py build_sphinx -b man`, this will generate a number of files, at least that removed issues with some of the errors you have.

I'm almost sure that it should be possible to code somehow to generate those files in setuptools build_sphinx command without using `make` and to have full build documentation procedure plugged under the setuptool framework 🤔

**Comment by MrMino** [comment]
@kloczek Just to be clear: have you done the `pip install -r docs/requirements.txt` first? That file contains `-e .[test]`, so it installs the repo in the editable mode. Installing `IPython` is a required step as far as I know.

**Comment by kloczek** [comment]
I still did not package `mathplot` (because some other missing build dependencies). Except that part I have all `[test]` build requirements as rpm packages.
