### ISSUE TITLE
File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket         context = ssl_options_to_context(ssl_options)

### ISSUE THREAD

**Issue by SaM885** [ipython/ipython#13038]
[E 10:31:35.627 NotebookApp] Exception in callback (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7f4215baed90>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 274, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 239, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 487, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 10:31:36.048 NotebookApp] Exception in callback (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7f4215baed90>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 274, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 239, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 487, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 10:31:36.050 NotebookApp] Exception in callback (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7f4215baed90>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 274, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 239, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 487, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 10:31:36.353 NotebookApp] Exception in callback (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7f4215baed90>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 274, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 239, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 487, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied

**Comment by SaM885** [comment]
i have try many time to solve error but it not solve , i have try all view ans , but it's not work at

**Comment by MrMino** [comment]
Hi @SaM885. This is an issue tracker for IPython, the project that provides a toolkit for interactive computing in Python. 

There's nothing in the traceback you provided that would denote the error as being related / relevant to IPython. Are you sure this is the right place for it?
