### ISSUE TITLE
`%gui qt` support for PyQt6

### ISSUE THREAD

**Issue by outofculture** [ipython/ipython#13058]
`%gui qt` in an environment with PyQt6 complains that no qt implementations are available.

```
In [1]: %gui qt
ERROR:root:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          False
    Tried to load:                                              ['pyqtdefault', 'pyside', 'pyqt5', 'pyside2']
```

I made a stab at implementing this locally, but I can say that just treating PyQt6 like PyQt5 is insufficient:

```
In [1]: %gui qt

In [2]: Traceback (most recent call last):
  File "/home/martin/.miniconda3/envs/qt6/bin/ipython", line 33, in <module>
    sys.exit(load_entry_point('ipython==8.0.0.dev0', 'console_scripts', 'ipython')())
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 604, in mainloop
    self.interact()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 587, in interact
    code = self.prompt_for_code()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 513, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/eventloop/inputhook.py", line 117, in select
    self.inputhook(InputHookContext(self._r, input_is_ready))
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/pt_inputhooks/qt.py", line 35, in inputhook
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
AttributeError: type object 'Qt' has no attribute 'AA_EnableHighDpiScaling'
```

That didn't seem too important for now, but just commenting out that line moves us to the next error:

```
In [1]: %gui qt

In [2]: Traceback (most recent call last):
  File "/home/martin/.miniconda3/envs/qt6/bin/ipython", line 33, in <module>
    sys.exit(load_entry_point('ipython==8.0.0.dev0', 'console_scripts', 'ipython')())
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 604, in mainloop
    self.interact()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 587, in interact
    code = self.prompt_for_code()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/interactiveshell.py", line 513, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/eventloop/inputhook.py", line 117, in select
    self.inputhook(InputHookContext(self._r, input_is_ready))
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/ipython-8.0.0.dev0-py3.9.egg/IPython/terminal/pt_inputhooks/qt.py", line 59, in inputhook
    QtCore.QSocketNotifier.Read)
AttributeError: type object 'QSocketNotifier' has no attribute 'Read'
```

`Read` was moved to `QtCore.QSocketNotifier.Type.Read`, which is fine, and leads us to the next error:

```
In [1]: %gui qt

In [2]: Traceback (most recent call last):
  File "/home/martin/.miniconda3/envs/qt6/bin/ipython", line 33, in <module>
    sys.exit(load_entry_point('ipython', 'console_scripts', 'ipython')())
  File "/home/martin/src/acq4/ipython/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/martin/src/acq4/ipython/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/martin/src/acq4/ipython/IPython/terminal/interactiveshell.py", line 604, in mainloop
    self.interact()
  File "/home/martin/src/acq4/ipython/IPython/terminal/interactiveshell.py", line 587, in interact
    code = self.prompt_for_code()
  File "/home/martin/src/acq4/ipython/IPython/terminal/interactiveshell.py", line 513, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/martin/.miniconda3/envs/qt6/lib/python3.9/site-packages/prompt_toolkit/eventloop/inputhook.py", line 117, in select
    self.inputhook(InputHookContext(self._r, input_is_ready))
  File "/home/martin/src/acq4/ipython/IPython/terminal/pt_inputhooks/qt.py", line 71, in inputhook
    event_loop.exec_()
AttributeError: 'QEventLoop' object has no attribute 'exec_'
```

That can be changed to a call to just plain `.exec()` and then things work! Sorta! My windows load and behave, but when I close all the gui windows and exit the shell, it completely locks itself up - not even `^z` or `^c` get through. `kill -15` works fine, but I didn't strace to find out what was up.

I don't have the wherewithal to fix the exit behavior and turn this into a real PR that still supports HiDPI and all the other Qt versions. https://github.com/outofculture/ipython/tree/qt6 has my attempt, messy though it is.

**Comment by MrMino** [comment]
Thanks @outofculture, for pushing it forward. Could you please create a PR with your implementation? That way it will be easier for others to take a look on this too.

**Comment by outofculture** [comment]
Totes! I didn't want to make a PR with known broken code, but if that's the preferred workflow then no problem.

**Comment by outofculture** [comment]
Oh, and if it helps, the code I'm using to make a gui is:

```python
import pyqtgraph as pg
pg.plot([0, 1, 1])
```

That should open a simple interactive line plot ( it requires pyqtgraph be installed, though ).

**Comment by MrMino** [comment]
Well, since I cannot guarantee that I can look at it any time soon, I want to lower the threshold for anyone who'd like to push this forward.

> Oh, and if it helps, the code I'm using to make a gui is:

I went ahead and put this into your PR description, just in case. Hope you don't mind :).
