### ISSUE TITLE
7.25.0: `ipywidgets` 7.6.3 man page build fails

### ISSUE THREAD

**Issue by kloczek** [ipython/ipython#13105]
I'm trying to build` ipywidgets` 7.6.3 diocumentation as man page and looks like it fails because ipython issue.
FYI: Build of the html in the same env is fine.
```console
[tkloczko@barrel ipywidgets-7.6.3]$ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.1.2
loading pickled environment... done
[autosummary] generating autosummary for: changelog.md, contributing.md, dev_docs.md, dev_install.md, dev_release.md, dev_testing.md, developer_docs.rst, embedding.md, examples/Layout Example.ipynb, examples/Layout Templates.ipynb, ..., examples/Widget Basics.ipynb, examples/Widget Custom.ipynb, examples/Widget Events.ipynb, examples/Widget List.ipynb, examples/Widget Low Level.ipynb, examples/Widget Styling.ipynb, index.rst, migration_guides.md, user_guide.rst, user_install.md
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... jupyterwidgets.1 { user_guide user_install examples/Using Interact examples/Widget Basics examples/Widget List examples/Output Widget examples/Widget Events examples/Widget Styling examples/Layout Templates examples/Widget Custom examples/Widget Low Level examples/Widget Asynchronous embedding contributing migration_guides changelog developer_docs dev_install dev_testing dev_docs dev_release } /home/tkloczko/rpmbuild/BUILD/ipywidgets-7.6.3/docs/source/developer_docs.rst:10: WARNING: unknown document: examples/Widget Basics.ipynb
failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 466, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: CodeAreaNode
The full traceback has been saved in /tmp/sphinx-err-rbbppw6_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@barrel ipywidgets-7.6.3]$ cat /tmp/sphinx-err-rbbppw6_.log
# Sphinx version: 4.1.2
# Python version: 3.8.11 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:
#   contributing
#   migration_guides
#   changelog
#   developer_docs
#   dev_install
#   dev_testing
#   dev_docs
#   dev_release
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.1.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.1.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.1.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (4.1.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   nbsphinx (0.8.7) from /usr/lib/python3.8/site-packages/nbsphinx.py
#   jupyter_sphinx (0.3.2) from /usr/lib/python3.8/site-packages/jupyter_sphinx/__init__.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /usr/lib/python3.8/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   recommonmark (0.7.1) from /usr/lib/python3.8/site-packages/recommonmark/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 177, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 39, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 7 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 472, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 466, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: CodeAreaNode
```

**Comment by Carreau** [comment]
I think that might not be in IPython itself. I've opened and issue on ipywidgets that points here see if there is anything we can do.
