### ISSUE TITLE
Strange crash of IPython 7.16.1 with Python 3.6.9

### ISSUE THREAD

**Issue by mlliarm** [ipython/ipython#13313]
## Description of the issue
I've installed the following version of IPython on my Lubuntu 18.04.?:

```
$ ipython --version
7.16.1
```

I run the following, and after calling the function `unique`, the IPython REPL crashed horribly.

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %config Application.verbose_crash=True

In [2]: dataT = [('abcd'), ('s4fad'), ('')]
   ...: dataF = [('23ds2'), ('hb 627jh=j ()')]

In [3]: dataT
Out[3]: ['abcd', 's4fad', '']

In [4]: dataF
Out[4]: ['23ds2', 'hb 627jh=j ()']

In [5]: def unique(string):
   ...:     # Assuming character set is ASCII (128 characters)
   ...:     if len(string) > 128:
   ...:         return False
   ...: 
   ...:     char_set = [False for _ in range(128)]
   ...:     for char in string:
   ...:         val = ord(char)
   ...:         if char_set[val]:
   ...:             # Char already found in string
   ...:             return False
   ...:         char_set[val] = True
   ...: 
   ...:     return True
   ...: 

In [6]: for str in dataT:
   ...:     print(unique(dataT))
   ...: 
---------------------------------------------------------------------------
---------------------------------------------------------------------------
TypeError             Python 3.6.9: /home/milia/.venvs/leetcode/bin/python3
                                                   Tue Nov 23 09:31:52 2021
A problem occurred executing Python code.  Here is the sequence of function
calls leading up to the error, with the most recent (innermost) call last.
~/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/ptutils.py in get_completions(self=<IPython.terminal.ptutils.IPythonPTCompleter object>, document=Document('uniqu', 5), complete_event=CompleteEvent(text_inserted=False, completion_requested=True))
```

## Expected behavior
According to the function that I found [here](https://github.com/careercup/CtCI-6th-Edition-Python/blob/e6bc732588601d0a98e5b1bc44d83644b910978d/Chapter1/1_Is%20Unique/IsUnique.py), the result should have been instead:

```
True
True
True
```

## Observed behavior
The following stacktrace when IPython crashed:

```
In [8]: dataT
Traceback (most recent call last):
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/jedi/api/__init__.py", line 729, in __init__
    super().__init__(code, environment=environment, project=project, **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/milia/.venvs/leetcode/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1021, in prompt
    set_exception_handler=set_exception_handler, in_thread=in_thread
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 891, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 815, in run_async
    return await _run_async2()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 797, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 1000, in cancel_and_wait_for_background_tasks
    await task
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1739, in async_completer
    document, complete_event
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 272, in get_completions_async
    document, complete_event
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/milia/.venvs/leetcode/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/usr/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/usr/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/usr/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

## Python version
```
$python3 --version
Python 3.6.9
```

## OS info
```
$sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

## Detailed stacktrace
I did the following suggestion when I opened the REPL in order to get a more verbose error message:

```
In [1]: %config Application.verbose_crash=True
```

You'll find the verbose error message at [this Github gist](https://gist.github.com/mlliarm/e2746e5e7de0e72106e6b51fd8ca130f).

Thanks.

**Comment by Carreau** [comment]
You want to pin jedi to an older version. As you are on Python 3.6 you do not get the latest IPython version that fixes those issues, and/or pin jedi.
