### ISSUE TITLE
autoreload gratuitous "object layout differs" error

### ISSUE THREAD

**Issue by sam-s** [ipython/ipython#13347]
I have a file `test.py` with the following code:
```python
import collections
class Cnt(collections.namedtuple("cnt",["c"])):
    def __str__(self):
        return f"<{self.__class__.__name__}/{self.c}>"
```
and a notebook with the following code:
```
In [1]:
%load_ext autoreload
%autoreload 2
import test as t
o = t.Cnt(c=7)
```
After I evaluate cell 1, I can do `print(o)` in another cell and it works.

However, if I `touch test.py` and re-eval the cell with `print(o)`, I get this:
```
<Cnt/7>
[autoreload of test failed: Traceback (most recent call last):
  File "/home/sds/.virtualenvs/myself/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/sds/.virtualenvs/myself/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/home/sds/.virtualenvs/myself/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/home/sds/.virtualenvs/myself/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 317, in update_class
    update_instances(old, new)
  File "/home/sds/.virtualenvs/myself/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 280, in update_instances
    ref.__class__ = new
TypeError: __class__ assignment: 'Cnt' object layout differs from 'Cnt'
]
```
otherwise it works just find, and the error disappears when I re-eval the cell again.

This does not happen with ordinary classes, nor with vanilla `namedtuple`s, but I *do* get this error with [`dataclass`](https://docs.python.org/3/library/dataclasses.html) classes.

**Comment by vsraptor** [comment]
similar here
```

class Link(tuple): ..............



[autoreload of prjs.link failed: Traceback (most recent call last):
  File "/my/py38/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 257, in check
    superreload(m, reload, self.old_objects)
  File "/my/py38/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 480, in superreload
    update_generic(old_obj, new_obj)
  File "/my/py38/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 377, in update_generic
    update(a, b)
  File "/my/py38/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 345, in update_class
    update_instances(old, new)
  File "/my/py38/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 303, in update_instances
    ref.__class__ = new
TypeError: __class__ assignment: 'Link' object layout differs from 'Link'
]

```

**Comment by sam-s** [comment]
Still present with python 3.10 and ```
IPython          : 8.10.0
ipykernel        : 6.21.2
ipywidgets       : 8.0.4
jupyter_client   : 8.0.3
jupyter_core     : 5.2.0
jupyter_server   : 2.3.0
jupyterlab       : not installed
nbclient         : 0.7.2
nbconvert        : 7.2.9
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : 5.4.0
traitlets        : 5.9.0
```

**Comment by coroa** [comment]
Seeing this also with [attrs](https://www.attrs.org/) classes on python 3.11

**Comment by sam-s** [comment]
Also present with JupyterLab 4.0.12 & Python 3.12.1

**Comment by sam-s** [comment]
Still present with 
```
Python 3.13.1
IPython 8.32.0
JupyterLab 4.3.5
```
