### ISSUE TITLE
Suggestion to horeload slots

### ISSUE THREAD

**Issue by sekkit** [ipython/ipython#13369]
to hotreload slots, firstly create a new slots object, copy the values to the object, and replace old slots with new.

**Comment by nlgranger** [comment]
Here is an MRE of this issue:

`a.py`:
```py
class A:
    __slots__ = ["a"]

    def __init__(self):
        self.a = 0

```

`slots.ipynb`:
```py
# %%
%load_ext autoreload
%autoreload 2

# %%
from draft.slots import A

a = A()
```

Edit a to b in `a.py` then rerun the last cell.

```
[autoreload of draft.slots failed: Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File ".venv/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File ".venv/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 397, in update_generic
    update(a, b)
  File ".venv/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 365, in update_class
    update_instances(old, new)
  File ".venv/lib/python3.12/site-packages/IPython/extensions/autoreload.py", line 323, in update_instances
    object.__setattr__(ref, "__class__", new)
TypeError: __class__ assignment: 'A' object layout differs from 'A'
]
```
