### ISSUE TITLE
prompt-toolkit crash fixed by redirecting to /dev/null

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [ipython/ipython#13384]
After installing ipython in a fresh virtual environment:

```
pyenv virtualenv 3.9.4 ipython-fresh-test
pyenv activate ipython-fresh-test
pip install -U pip wheel ipython
ipython --log-level=DEBUG
```

I get the following error stack on startup:

```
[TerminalIPythonApp] IPYTHONDIR set to: $HOME/.ipython
[TerminalIPythonApp] Using existing profile dir: '$HOME/.ipython/profile_default'
[TerminalIPythonApp] Searching path ['$HOME/.ipython/profile_default', '$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[TerminalIPythonApp] Attempting to load config file: ipython_config.py
[TerminalIPythonApp] Looking for ipython_config in /etc/ipython
[TerminalIPythonApp] Looking for ipython_config in /usr/local/etc/ipython
[TerminalIPythonApp] Looking for ipython_config in $HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/etc/ipython
[TerminalIPythonApp] Looking for ipython_config in $HOME/.ipython/profile_default
[TerminalIPythonApp] Loaded config file: $HOME/.ipython/profile_default/ipython_config.py
Python 3.9.4 (default, Sep 17 2021, 11:34:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

[TerminalIPythonApp] Loading IPython extensions...
[TerminalIPythonApp] Loading IPython extension: storemagic
[TerminalIPythonApp] Starting IPython's mainloop...

Traceback (most recent call last):
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.pyenv/versions/ipython-fresh-test/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 566, in mainloop
    self.interact()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 549, in interact
    code = self.prompt_for_code()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    text = self.pt_app.prompt(
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 890, in run
    return loop.run_until_complete(
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 815, in run_async
    return await _run_async2()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 791, in _run_async2
    result = await _run_async()
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 720, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "$HOME/.pyenv/versions/3.9.4/envs/ipython-fresh-test/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 173, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/asyncio/selector_events.py", line 336, in add_reader
    self._add_reader(fd, callback, *args)
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "$HOME/.pyenv/versions/3.9.4/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
OSError: [Errno 22] Invalid argument
```

If i'm not mistaken, this is an error with prompt-toolkit.

**Comment by MarcinKonowalczyk** [comment]
Here is the output of my `pip freeze`

```
backcall==0.2.0
decorator==5.1.0
ipython==7.30.1
jedi==0.18.1
matplotlib-inline==0.1.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.23
ptyprocess==0.7.0
Pygments==2.10.0
six==1.16.0
traitlets==5.1.1
wcwidth==0.2.5
```

**Comment by MarcinKonowalczyk** [comment]
so... this is curious...

I've gone on to test various versions of `prompt-toolkit` manually, and the problem seemed to persist. I've tried a few 2.0.x and few 3.0.x versions but i wanted to try all of them exhaustively. I've run `pip index versions prompt-toolkit` and wrote the following bash script:

```
#!/bin/bash
declare -a VERSIONS=(2.0.1 2.0.2 2.0.3 2.0.4 2.0.5 2.0.6 2.0.7 2.0.8 2.0.9 2.0.10 3.0.0 3.0.1 3.0.2 3.0.3 3.0.4 3.0.5 3.0.6 3.0.7 3.0.8 3.0.9 3.0.10 3.0.11 3.0.12 3.0.13 3.0.14 3.0.15 3.0.16 3.0.17 3.0.18 3.0.19 3.0.20 3.0.21 3.0.22 3.0.23 3.0.24)
for version in "${VERSIONS[@]}"; do
    pip install -q "prompt-toolkit==$version"
    ipython --log-level=DEBUG -c 'exit()' > /dev/null 2>&1
    echo "$version : exit code = $?"
done
```

upon which... everything worked fine(!). I've gone back to the terminal, installed the latest version of `prompt-toolkit` again, and everything still works fine. Best I can tell, the magic step which actually fixed it was redirecting the output to `/dev/null`. I do not have a good explanation as to why that would be the case.

**Comment by MarcinKonowalczyk** [comment]
I'm going to close the issue, but if anyone reproduces this behaviour, i'm sure it would be interesting to investigate.
