### ISSUE TITLE
doctest in IPython.core.display.Image requires network connection

### ISSUE THREAD

**Issue by mcepl** [ipython/ipython#13468]
Build environments for Linux/openSUSE (and not only, all Linux and non-Linux distributions are in the same boat) are disconnected from network.

This makes this doctest to fail:
```
[   80s] _______________ [ipdoctest] IPython.core.display.Image.__init__ ________________
[   80s] 873             Alternative text for the image, for use by screen readers.
[   80s] 874
[   80s] 875         Examples
[   80s] 876         --------
[   80s] 877         embedded image data, works in qtconsole and notebook
[   80s] 878         when passed positionally, the first arg can be any of raw image data,
[   80s] 879         a URL, or a filename from which to load image data.
[   80s] 880         The result is always embedding image data for inline images.
[   80s] 881
[   80s] 882         >>> Image('http://www.google.fr/images/srpr/logo3w.png')
[   80s] UNEXPECTED EXCEPTION: URLError(gaierror(-3, 'Temporary failure in name resolution'))
[   80s] Traceback (most recent call last):
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 1346, in do_open
[   80s]     h.request(req.get_method(), req.selector, req.data, headers,
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 1285, in request
[   80s]     self._send_request(method, url, body, headers, encode_chunked)
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 1331, in _send_request
[   80s]     self.endheaders(body, encode_chunked=encode_chunked)
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 1280, in endheaders
[   80s]     self._send_output(message_body, encode_chunked=encode_chunked)
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 1040, in _send_output
[   80s]     self.send(msg)
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 980, in send
[   80s]     self.connect()
[   80s]   File "/usr/lib64/python3.9/http/client.py", line 946, in connect
[   80s]     self.sock = self._create_connection(
[   80s]   File "/usr/lib64/python3.9/socket.py", line 823, in create_connection
[   80s]     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
[   80s]   File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
[   80s]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[   80s] socket.gaierror: [Errno -3] Temporary failure in name resolution
[   80s] During handling of the above exception, another exception occurred:
[   80s] Traceback (most recent call last):
[   80s]   File "/usr/lib64/python3.9/doctest.py", line 1334, in __run
[   80s]     exec(compile(example.source, filename, "single",
[   80s]   File "<doctest IPython.core.display.Image.__init__[0]>", line 1, in <module>
[   80s]   File "/home/abuild/rpmbuild/BUILD/ipython-8.0.0/IPython/core/display.py", line 952, in __init__
[   80s]     super(Image, self).__init__(data=data, url=url, filename=filename,
[   80s]   File "/home/abuild/rpmbuild/BUILD/ipython-8.0.0/IPython/core/display.py", line 327, in __init__
[   80s]     self.reload()
[   80s]   File "/home/abuild/rpmbuild/BUILD/ipython-8.0.0/IPython/core/display.py", line 987, in reload
[   80s]     super(Image,self).reload()
[   80s]   File "/home/abuild/rpmbuild/BUILD/ipython-8.0.0/IPython/core/display.py", line 357, in reload
[   80s]     response = urlopen(self.url)
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
[   80s]     return opener.open(url, data, timeout)
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 517, in open
[   80s]     response = self._open(req, data)
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 534, in _open
[   80s]     result = self._call_chain(self.handle_open, protocol, protocol +
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
[   80s]     result = func(*args)
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 1375, in http_open
[   80s]     return self.do_open(http.client.HTTPConnection, req)
[   80s]   File "/usr/lib64/python3.9/urllib/request.py", line 1349, in do_open
[   80s]     raise URLError(err)
[   80s] urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
[   80s] /home/abuild/rpmbuild/BUILD/ipython-8.0.0/IPython/core/display.py:882: UnexpectedException
```

I am not sure why this test fails and normal non-doc-tests for example in `IPython.core.tests.test_display` do not, but in order to make whole test suite pass I had to this ugly Linux-distributions-only hack:
```diff
---
 IPython/core/display.py |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- a/IPython/core/display.py
+++ b/IPython/core/display.py
@@ -879,7 +879,7 @@ class Image(DisplayObject):
         a URL, or a filename from which to load image data.
         The result is always embedding image data for inline images.
 
-        >>> Image('http://www.google.fr/images/srpr/logo3w.png')
+        >>> Image('http://www.google.fr/images/srpr/logo3w.png')  # doctest: +SKIP
         <IPython.core.display.Image object>
 
         >>> Image('/path/to/image.jpg')
```
Unfortunately it seems that pytest doesn’t any means how to mark doctests (see https://github.com/pytest-dev/pytest/issues/5794), and more sophisticated conditions in doctests mentioned in https://docs.pytest.org/en/latest/how-to/doctest.html#skipping-tests is exceedingly ugly.

**Comment by Carreau** [comment]
Do you want to send a PR with this as permanent patch ? Or do you think we should have a different proper fix  (option to skip, or monkeypatch the doctests/urllib  ?

**Comment by mcepl** [comment]
> Do you want to send a PR with this as permanent patch ? Or do you think we should have a different proper fix (option to skip, or monkeypatch the doctests/urllib ?

I don’t know. That unconditional skip seems like a nasty hack (and if there is an unconditional skip then you are much better with deleting the test altogether, but that’s wrong, on the network-connected machine it has a lot of sense) and pytest-dev/pytest#5794 has not been fulfilled.

So, I am not sure what is The Right Thing™ to do.

**Comment by Carreau** [comment]
I'll put a skip-doctest for now, I guess in the long run the doctests should have a way to monkeypatch urllib/Image to not make actual network call.

**Comment by MrMino** [comment]
@Carreau is firing up an HTTP server during tests considered valid, or should it monkey-patch the urllib?

**Comment by Carreau** [comment]
I think we better mock/monkey-patch, that way we can not only make sure we don't touch network at all, but we can also fail if unknown resources are being accessed, or if some resources are not accessed.
