### ISSUE TITLE
IPython crashes on metaclass with bad `__prepare__`

### ISSUE THREAD

**Issue by JelleZijlstra** [ipython/ipython#13481]
Running this code in IPython (8.0.1) causes a crash:
```
class X(type):
    def __prepare__(cls, *args, **kwargs):
        return []
class Y(metaclass=X):
    pass
```

It causes a long stack trace:

<details>

```
Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c06101dc01ef>", line 1, in <module>
    class Y(metaclass=X):
  File "<ipython-input-2-c06101dc01ef>", line 1, in Y
    class Y(metaclass=X):
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 793, in format_exception_as_a_whole
    if r.frame.f_locals.get("__tracebackhide__", 0) and i != lastrecord:
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 793, in format_exception_as_a_whole
    if r.frame.f_locals.get("__tracebackhide__", 0) and i != lastrecord:
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelle/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jelle/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/__main__.py", line 14, in <module>
    start_ipython()
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 793, in format_exception_as_a_whole
    if r.frame.f_locals.get("__tracebackhide__", 0) and i != lastrecord:
AttributeError: 'list' object has no attribute 'get'

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

</details>

The code is obviously badly broken, but it still shouldn't crash IPython.

**Comment by alexmojaki** [comment]
Released a new version (0.2.2) of `pure_eval` in https://github.com/alexmojaki/pure_eval/pull/12 which handles non-dict namespaces in frames. `pip install -U pure_eval` and try this again.

**Comment by JelleZijlstra** [comment]
Thanks, but IPython still crashes. The bug seems to be in IPython itself, not a dependency:
```
  File "/Users/jelle/py/venvs/venv310/lib/python3.10/site-packages/IPython/core/ultratb.py", line 793, in format_exception_as_a_whole
    if r.frame.f_locals.get("__tracebackhide__", 0) and i != lastrecord:
AttributeError: 'list' object has no attribute 'get'
```
This assumes f_locals is a Mapping, which isn't true in this case.

**Comment by alexmojaki** [comment]
Ah, I thought that there was a failure in pure_eval (which made the same assumption) that somehow wasn't in the traceback. So you would still need the upgraded pure_eval, but yes some independent code in IPython needs to handle this as well.
