### ISSUE TITLE
Typing ❌ into IPython Crashes on Enter

### ISSUE THREAD

**Issue by Redoubts** [ipython/ipython#13488]
I tried entering a string with '❌' directly into ipython console, and found the program crashed entirely. Oddly, I can put it in a file, reat it, and print it fine; but explicitly pasting or writing it into the terminal with a character picker causes the terminal to exit abruptly.

Reproduces on 7.29 and 8.0 

```
Traceback (most recent call last):
  File "./venv/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "./venv/lib/python3.8/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "./venv/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "./venv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "./venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "./venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "./venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "./venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2804, in _run_cell
    elif self.should_run_async(
  File "./venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2862, in should_run_async
    return _should_be_async(cell)
  File "./venv/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 151, in _should_be_async
    code = compile(
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 1: surrogates not allowed
```

**Comment by aroberge** [comment]
For what it's worth, using IPython 8.0.1 with Windows Terminal on Windows 10, results in a normal `SyntaxError`.
```
> ipython
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ❌
  Input In [1]
    ❌
    ^
SyntaxError: invalid character '❌' (U+274C)
```

**Comment by Redoubts** [comment]
Sorry, try putting it in a string.

**Comment by aroberge** [comment]
```
In [7]: "❌"
Out[7]: '❌'
```

**Comment by Carreau** [comment]
That works well here too : 
```
In [2]: "❌"
Out[2]: '❌'

In [3]: print("❌")
❌
```

It might be a 3.8 specific thing, and if it fails in `compile()` than it's likely a Python bug, can you try `compile("'❌'", ...)` directly in a pure python shell ? 

Or the encoding of your console is wrong ? We did clean up some python2/3 compatibility, it may have affected windows which sometime is not utf8, but then we'll need to bisect to find the problematic commit.

**Comment by Redoubts** [comment]
No issues with python & compile:

```
% python
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> compile("'❌'", "", "single")
<code object <module> at 0x7ffbf80f5df0, file "", line 1>
```

```
% python                                
Python 3.8.7 (default, Dec 22 2020, 16:05:35) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> compile("'❌'", "", "single")
<code object <module> at 0x7f3b08e28d40, file "", line 1>
>>> 
```

**Comment by MrMino** [comment]
I think it's related to the encoding of the input:
```
In [3]: "❌".encode('utf-8')
Out[3]: b'\xe2\x9d\x8c'
```

Your trace shows `\udce2'`. Could you please show what's the output of `env | grep LC` on your system?

**Comment by Redoubts** [comment]
`% env | grep LC`

LC_ALL=en_US.UTF-8

**Comment by MrMino** [comment]
Huh, that's suspiciously short. TIL there's a better way than `env → grep`:

Could you please try again, but use `locale` command this time?

**Comment by Redoubts** [comment]
```
% (darwin) locale                                       
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

```
% (linux) locale         
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
