### ISSUE TITLE
IPython crashes at start, but jupyter qtconsole works

### ISSUE THREAD

**Issue by UnaiSan** [ipython/ipython#13494]
In Windows 10, using python 3.8 and in a venv environment, I install jupyter. When I try to start ipython I get the following error message

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "C:\Users\sanmiguelu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sanmiguelu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sanmiguelu\Documents\python\venvs\.temp\Scripts\ipython.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\IPython\__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\IPython\terminal\ipapp.py", line 316, in start
    self.shell.mainloop()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\IPython\terminal\interactiveshell.py", line 611, in mainloop
    self.interact()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\IPython\terminal\interactiveshell.py", line 596, in interact
    code = self.prompt_for_code()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\IPython\terminal\interactiveshell.py", line 535, in prompt_for_code
    text = self.pt_app.prompt(
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1021, in prompt
    return self.app.run(
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\prompt_toolkit\application\application.py", line 930, in run
    return loop.run_until_complete(
  File "C:\Users\sanmiguelu\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\prompt_toolkit\application\application.py", line 849, in run_async
    return await _run_async2()
  File "c:\users\sanmiguelu\documents\python\venvs\.temp\lib\site-packages\prompt_toolkit\application\application.py", line 801, in _run_async2
    loop.add_signal_handler(
  File "C:\Users\sanmiguelu\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 536, in add_signal_handler
    raise NotImplementedError
NotImplementedError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by Kuju89** [comment]
I have the exact same error as UnaiSan. I just installed ipython and can't get it to work. How this could be fixed?

**Comment by PhilMacKay** [comment]
I just noticed the same issue. In my case it was solved by downgrading `prompt-toolkit` to a version below 3.0.25.
`pip install prompt-toolkit<3.0.25`

**Comment by UnaiSan** [comment]
They have updated propt-toolkit and now everything works fine. Thanks
