### ISSUE TITLE
IPython crashes on exception

### ISSUE THREAD

**Issue by Numerlor** [ipython/ipython#13525]
I've installed python3.10 from deadsnakes in an Ubuntu WSL environment, and installed IPython into that through pip.
Now almost every exception (not SyntaxErrors from what I've tried) crashes ipython with the following traceback:
<details>
 <summary> traceback </summary>

```py
numerlor@DESKTOP-K9CMQUF:/mnt/d/pycon$ ipython
Python 3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: raise Exception
Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-2aee0157c87b>", line 1, in <module>
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'Exception' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/numerlor/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```
</details>
With Application.verbose_crash=True, an another exception is added on top of that:
<details>
 <summary> verbose on traceback </summary>

```py
numerlor@DESKTOP-K9CMQUF:/mnt/d/pycon$ ipython
Python 3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %config Application.verbose_crash=True

In [2]: raise Exception
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1303, in is_dir
    return S_ISDIR(self.stat().st_mode)
AttributeError: 'str' object has no attribute 'stat'

Original exception was:
Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-2aee0157c87b>", line 1, in <module>
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'Exception' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numerlor/.local/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/numerlor/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/numerlor/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/numerlor/.local/lib/python3.10/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'
```
</details>

**Comment by Carreau** [comment]
From you r=error message line 58, we can see that your pygments seem to pre-date this commit https://github.com/pygments/pygments/commit/52c64b9ac314b09f20579a9e97b09322e4367a2f, which itself predate Pygments 2.4.0 which is our minimal requirements. 

https://github.com/ipython/ipython/blob/0f4a73c91db71cde174275337fc5e226acc9dd7d/setup.cfg#L41

So can you check first that pygments is recent enough ?

**Comment by Numerlor** [comment]
> From you r=error message line 58, we can see that your pygments seem to pre-date this commit [pygments/pygments@52c64b9](https://github.com/pygments/pygments/commit/52c64b9ac314b09f20579a9e97b09322e4367a2f), which itself predate Pygments 2.4.0 which is our minimal requirements.
> 
> https://github.com/ipython/ipython/blob/0f4a73c91db71cde174275337fc5e226acc9dd7d/setup.cfg#L41
> 
> So can you check first that pygments is recent enough ?

Ah, that seems to have fixed it, thanks. While I have no idea how it occurred when ipython was the first and only package I installed, it does not seem to be anything wrong with ipython.

The issue @lesteve mentioned persists but it doesn't seem to be related to the issue I had
