### ISSUE TITLE
IPython 8.1.0 claims to be compatible with Python 3.8, but isn't

### ISSUE THREAD

**Issue by arekfu** [ipython/ipython#13554]
Steps to reproduce:
```
$ python --version
Python 3.8.10
$ pip install ipython
$ ipython
Traceback (most recent call last):
  File "/path/to/venv/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/path/to/venv/lib/python3.8/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/path/to/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/path/to/venv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/path/to/venv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 619, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/path/to/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 529, in __init__
    self.init_virtualenv()
  File "/path/to/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 788, in init_virtualenv
    new_path = p.readlink()
AttributeError: 'PosixPath' object has no attribute 'readlink'

If you suspect this is an IPython 8.1.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

`PosixPath.readlink()` [was introduced in Python 3.9](https://docs.python.org/3/library/pathlib.html#pathlib.Path.readlink).

Thank you for looking into this.

**Comment by Mec-iS** [comment]
same problem here:
```
{'commit_hash': 'bd470fe8c',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '.venv/lib/python3.8/site-packages/IPython',
 'ipython_version': '8.1.0',
 'os_name': 'posix',
 'platform': 'Linux-5.13.0-30-generic-x86_64-with-glibc2.29',
 'sys_executable': '/home/lorenzo/code/.venv/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.8.10 (default, Nov 26 2021, 20:14:08) \n[GCC 9.3.0]'}

```

**Comment by olliemath** [comment]
Same same

**Comment by olliemath** [comment]
Can confirm
```bash
sed -i 's/p.readlink()/p._from_parts(os.readlink(p,))/g' interactiveshell.py
```
within my local venv fixed this for me

**Comment by adamdoupe** [comment]
I can also confirm this bug on Ubuntu 20.04.

You can reproduce by installing ipython in a venv (which is how I triggered it).

**Comment by cnobile2012** [comment]
I'm also getting this bug on ubuntu 20.04 on Python 3.8.10.
I also get the exact tracback.

**Comment by barlaensdoonn** [comment]
> Can confirm
> 
> ```shell
> sed -i 's/p.readlink()/p._from_parts(os.readlink(p,))/g' IPython/core/interactiveshell.py
> ```
> 
> within my local venv fixed this for me

worked for me in venv on Ubuntu 20.04, python 3.8.10. thx @olliemath!!

_for reference for anyone stuck here_: 
the above command needs to know where to find the `IPython` package directory, which should be in the `site-packages` directory for the venv in which it was installed.

to find this path, i ran this from within the activated venv (found in this very helpful [SO post](https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory)):
```
python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])
```
this output the absolute path to the venv's python `site-packages` dir, where `IPython` lives. I updated @olliemath 's command with the full path, and that fixed the issue:
```
sed -i 's/p.readlink()/p._from_parts(os.readlink(p,))/g' ~/gitbucket/infinityGAN/gainf/lib/python3.8/site-packages/IPython/core/interactiveshell.py
```

**Comment by MrMino** [comment]
From what I can see, this has been fixed in  #13557. @Carreau already merged a What's-New for 8.1.1, so it should get released soon.

**Comment by deepansh96** [comment]
For MacOS users, `sed -i` command might not work for you. [reason](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux)

What I did is I manually went to this path (note - I'm using a venv).
`venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py`

And I changed the line `p.readlink()` to `p._from_parts(os.readlink(p,))` and everything started working

**Comment by IVEWOR** [comment]
> For MacOS users, `sed -i` command might not work for you. [reason](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux)
> 
> What I did is I manually went to this path (note - I'm using a venv). `venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py`
> 
> And I changed the line `p.readlink()` to `p._from_parts(os.readlink(p,))` and everything started working

Working in linux as well.

**Comment by jotathebest** [comment]
> sed -i 's/p.readlink()/p._from_parts(os.readlink(p,))/g' ~/gitbucket/infinityGAN/gainf/lib/python3.8/site-packages/IPython/core/interactiveshell.py

this worked for me, thanks!

**Comment by Carreau** [comment]
Computer with all publishing credential died, it may take me a few days to
re-setup everything so don't expect a 8.1.1 soon unless someone else gets
to it.

**Comment by dgealow** [comment]
For anyone who wants a workaround for the next few days but doesn't want to muck around with source files and/or doesn't care about whatever other features/fixes 8.1 added, you can just downgrade to the previous version: `pip install ipython==8.0.1`

**Comment by tiffanyb** [comment]
confirmed bug if one creates a virtual environment and `pip install ipython`. ipython still works fine.

**Comment by SonyaEick** [comment]
> For MacOS users, `sed -i` command might not work for you. [reason](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux)
> 
> What I did is I manually went to this path (note - I'm using a venv). `venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py`
> 
> And I changed the line `p.readlink()` to `p._from_parts(os.readlink(p,))` and everything started working

This was the one for me! Thank you for sharing!
