### ISSUE TITLE
ipython3 crash: nested exceptions?

### ISSUE THREAD

**Issue by mazer-ai** [ipython/ipython#13586]
I just recently started getting seemingly random crashes - complete crash of the kernel, requring restart -- that appear to be related to exceptions occurring within the exception handler. The trigger appears completely random, but always starts with some sort of reasonable error at the console, followed by a long stack trace. Something like this, where the "Original exception" is my mistake:
```
Original exception was:
Traceback (most recent call last):
  File "/home/mazer/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-131-ddf36e5e5914>", line 1, in <cell line: 1>
  File "/home/mazer/src/taut/notebooks/jamie/graph-audio/debugger.py", line 238, in run_pipeline
    sup.title(f'sentence # {sampleno}')
NameError: name 'sup' is not defined
....
```
During handling of the above exception caused by my typo, another exception occurrs inside ipython:

```
Traceback (most recent call last):
  File "/home/mazer/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1979, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'
```
followed by along, inconsistent stack trace that always ends with:
```
  File "/home/mazer/.local/lib/python3.8/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/home/mazer/.local/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```
Just started getting this since I did a fresh update/install of the virtualenv I'm using.

Anybody seen this or have any ideas about what might be causing this?

Thanks,
Jamie

**Comment by mazer-ai** [comment]
Hi @Carreau I just swapped in the version of `ultratb.py` you pushed -- doesn't fix my particular issue (it did fix some of the others that were closed out). Here's a completely stack trace: ```In [5]: run_pipeline(gc2, params)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3.8/pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
AttributeError: 'str' object has no attribute 'stat'

Original exception was:
Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-024db4d4f4d5>", line 1, in <cell line: 1>
  File "/home/mazer/src/taut/notebooks/jamie/graph-audio/debugger.py", line 240, in run_pipeline
    show_ragsas_recon(gc, 'sas')
  File "/home/mazer/src/taut/notebooks/jamie/graph-audio/debugger.py", line 109, in show_ragsas_recon
    _cc = cc(x[-1], x[-2])
  File "/home/mazer/src/taut/decipher/vis.py", line 1300, in cc
    retval = np.corrcoef(a.flatten(), b.flatten())[0, 1]
  File "<__array_function__ internals>", line 5, in corrcoef
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2683, in corrcoef
    c = cov(x, y, rowvar, dtype=dtype)
  File "<__array_function__ internals>", line 5, in cov
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2477, in cov
    X = np.concatenate((X, y), axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 318592 and the array at index 1 has size 159296

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1979, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3301, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1981, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 805, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 723, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1979, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NotOneValueFound' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2900, in _run_cell
    return runner(coro)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3098, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3320, in run_ast_nodes
    self.showtraceback()
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1981, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 805, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 723, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1979, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NotOneValueFound' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mazer/src/taut/venv/bin/ipython3", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 653, in mainloop
    self.interact()
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 646, in interact
    self.run_cell(code, store_history=True)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
    result = self._run_cell(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2905, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1981, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 805, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/IPython/core/ultratb.py", line 723, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/home/mazer/src/taut/venv/lib/python3.8/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

Process Python exited abnormally with code 1
```

**Comment by Carreau** [comment]
Have yo tried updating stack_data and executing ?

**Comment by mazer-ai** [comment]
Starting to think my particular issue might actually be an emacs issue.
Seems to only come up when using `code-cells.el` (
https://github.com/astoff/code-cells.el) and appears to be version
dependent (latest checkout of code-cells.el causes problems, old version I
hacked doesn't). If you leave this open, I'll keep track of what happens
and update once I'm sure..
/jamie

**Comment by petergaultney** [comment]
An emacs issue? Are you running `ipython` inside emacs? 

I'm experiencing this issue and I'm an emacs user, but I'm running `ipython` directly from the shell and am not integrated with emacs in any way that I'm aware of.

**Comment by alexmojaki** [comment]
This looks like a duplicate of https://github.com/ipython/ipython/issues/13598. `pip install -U executing`, that should fix it.
