### ISSUE TITLE
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

### ISSUE THREAD

**Issue by alfredoPark-48** [ipython/ipython#13616]
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded' coming from line file "/home/.local/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 151.
`if not self._loaded`

**Comment by MrMino** [comment]
You'll have to give some more information than this. What's your OS? What's the version of IPython? What version of `prompt-toolkit` do you have installed`? When does this happen?

**Comment by glucksfall** [comment]
Same here. Fresh installed Ubuntu 20.04. `prompt-toolkit` version `2.0.10` and `ipython3` version `8.2.0`

Full trace
```
$ ipython3
Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 8, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.8/dist-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 648, in __init__
    self.init_prompt_toolkit_cli()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 437, in init_prompt_toolkit_cli
    history = PtkHistoryAdapter(self)
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 143, in __init__
    self._refresh()
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/interactiveshell.py", line 151, in _refresh
    if not self._loaded:
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

If you suspect this is an IPython 8.2.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by glucksfall** [comment]
Solution: Update `prompt-toolkit` (to `3.0.28`)

**Comment by alfredoPark-48** [comment]
Updating `prompt-toolkit` to version `3.0.28` fixed it.
