### ISSUE TITLE
Starting ipython immediately ends with an exception.

### ISSUE THREAD

**Issue by ItsDrike** [ipython/ipython#13611]
After updating the system, which included an update to the ipython package, trying to start ipython fails and raises an AttributeError complaining about accessing non-existent variable `_loaded` from `/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py` line 151.

Operating System: Arch Linux (kernel 5.16.6-arch1-1)
IPython installed through the package manager (pacman) with version: 8.2.0-1
Running `ipython --version` works and reports: 8.2.0

<details>

<summary>Attached Traceback</summary>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/usr/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/usr/lib/python3.10/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 648, in __init__
    self.init_prompt_toolkit_cli()
  File "/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 437, in init_prompt_toolkit_cli
    history = PtkHistoryAdapter(self)
  File "/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 143, in __init__
    self._refresh()
  File "/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 151, in _refresh
    if not self._loaded:
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

If you suspect this is an IPython 8.2.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

</details>

**Comment by ItsDrike** [comment]
Hm apparently, this was an issue with me having user pip dependency of `prompt_toolkit` which was outdated and took precedence over the correct system version of this dependency, managed by the package manager.

**Comment by MrMino** [comment]
My advice: use pyenv. Do not use system's interpreter for anything, especially not system's pip. You don't want to mix distribution-managed dependencies with the ones from PyPI, and that's what inadvertently will happen whenever you `pip install` packages to system's site.

Time spent fixing the inevitable crash is never worth the questionable convenience.
