### ISSUE TITLE
IPython has A IndentationError

### ISSUE THREAD

**Issue by ZxyNull0** [ipython/ipython#13649]
I just fuzz this project use oss-fuzz，and there is quickly find a crash，the infomation as followers：
```
 === Uncaught Python exception: ===
IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)
Traceback (most recent call last):
  File "fuzz_inputsplitter.py", line 28, in TestOneInput
  File "IPython/core/inputsplitter.py", line 481, in push_accepts_more
  File "IPython/core/inputsplitter.py", line 505, in get_indent_spaces
  File "IPython/core/inputsplitter.py", line 146, in find_next_indent
  File "IPython/core/inputsplitter.py", line 129, in partial_tokens
  File "tokenize.py", line 512, in _tokenize

==15== ERROR: libFuzzer: fuzz target exited
    #0 0x7f4227337f84 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:31:3
    #1 0x7f42272ddf58 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x7f42272c398c in fuzzer::Fuzzer::ExitCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:250:3
    #3 0x7f42270a88d6  (/lib/x86_64-linux-gnu/libc.so.6+0x468d6)
    #4 0x7f42270a8a8f in exit (/lib/x86_64-linux-gnu/libc.so.6+0x46a8f)
    #5 0x7f422674bdf8 in Py_Exit /tmp/Python-3.8.3/Python/pylifecycle.c:2299:5
    #6 0x7f4226750c0b in handle_system_exit /tmp/Python-3.8.3/Python/pythonrun.c:658:9
    #7 0x7f4226750c0b in _PyErr_PrintEx /tmp/Python-3.8.3/Python/pythonrun.c:668:5
    #8 0x55c45504975a  (/out/fuzz_inputsplitter.pkg+0x375a)
    #9 0x55c455049aac  (/out/fuzz_inputsplitter.pkg+0x3aac)
    #10 0x7f42270860b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #11 0x55c4550484d9  (/out/fuzz_inputsplitter.pkg+0x24d9)

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::ExitCallback()
SUMMARY: libFuzzer: fuzz target exited
MS: 2 ShuffleBytes-ChangeBinInt-; base unit: a48b9a4c9148ade92802192a182b0a332d294908
0xb7,0x8a,0x9,0x9,0xb7,0x8f,0xb7,0x8a,0x9,0x8,
\267\212\011\011\267\217\267\212\011\010
artifact_prefix='./'; Test unit written to ./crash-9ea37d6247357db2a662c42d1bf9effa840cc672
Base64: t4oJCbePt4oJCA==
```
Seems like there is an indentation error

**Comment by Carreau** [comment]
Can you provide the content of `fuzz_inputsplitter.py` and maybe the input that created teh crash, that would help.

**Comment by ZxyNull0** [comment]
The fuzzer is provided by the oss-fuzz.
[fuzz_inputsplitter.py](https://github.com/google/oss-fuzz/blob/master/projects/ipython/fuzz_inputsplitter.py)

**Comment by Carreau** [comment]
Thanks !
