### ISSUE TITLE
SyntaxError when trying to install a kernel

### ISSUE THREAD

**Issue by ObliviousMonkey** [ipython/ipython#13681]
I'm on MacOS 12.3.1 using MiniConda.

I've created an env with `conda create --name ipy2 python=2.7.18 ipykernel`

When I try to create a kernel with this env, I'm met with a syntax error:

```py
conda activate ipy2
python -m ipykernel install --user --name=iPy2
```
which produces:
```
Traceback (most recent call last):
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/runpy.py", line 111, in _get_module_details
    _import_(mod_name)  # Do not catch exceptions initializing package
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/ipykernel/_init_.py", line 2, in <module>
    from .connect import *
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/IPython/_init_.py", line 48, in <module>
    from .core.application import Application
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/traitlets/config/_init_.py", line 6, in <module>
    from .application import *
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/Users/USER_NAME/opt/anaconda3/envs/awake/lib/python2.7/site-packages/decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax
```

How can I solve this?

**Comment by MrMino** [comment]
You are trying to run that kernel on python 2. Make sure you are using `ipykernel` version that actually supports that (if there is one that does - I haven't checked).
