### ISSUE TITLE
ImportError: cannot import name 'wcwidth' from 'wcwidth' (unknown location)

### ISSUE THREAD

**Issue by tetoNidan** [ipython/ipython#13809]
Manjaro 

Python 3.10.7

$ whereis wcwidth
wcwidth: /usr/share/man/man3/wcwidth.3.gz /usr/share/man/man3p/wcwidth.3p.gz

$ which wcwidth
which: no wcwidth in (/home/myuser13al/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)

Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    from IPython import start_ipython
  File "/usr/lib/python3.10/site-packages/IPython/__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "/usr/lib/python3.10/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 31, in <module>
    from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/buffer.py", line 32, in <module>
    from .application.run_in_terminal import run_in_terminal
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/run_in_terminal.py", line 8, in <module>
    from prompt_toolkit.eventloop import run_in_executor_with_context
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/eventloop/__init__.py", line 2, in <module>
    from .inputhook import (
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/eventloop/inputhook.py", line 34, in <module>
    from prompt_toolkit.utils import is_windows
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/utils.py", line 19, in <module>
    from wcwidth import wcwidth
ImportError: cannot import name 'wcwidth' from 'wcwidth' (unknown location)

I updated pip,  uninstalled and reinstalled ipython. Made sure I has wcwidth installed. if there is anything else I can provide that can help let me know. Thanks and sorry I broke your fine program!

**Comment by tetoNidan** [comment]
I forcced pip to reinstall wcwidth and ipython is working again.

pip install --force-reinstall wcwidtn

This issue is resolved and can be closed.

**Comment by AJR07** [comment]
Hasn't been closed for some reason LOL
