### ISSUE TITLE
Regression in autoreload with metaclasses in IPython 8.5+

### ISSUE THREAD

**Issue by kortsi** [ipython/ipython#13830]
Given a simple file with one class and a metaclass for it (`klass.py`):

````
class MetaKlass(type):
    pass

class Klass(metaclass=MetaKlass):
    pass
````

In IPython 8.5 and 8.6 with autoreload an error can be produced like this:

````
Python 3.10.0 (default, Oct 21 2021, 15:52:07) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: from metaklass import *

[ins] In [2]: Klass()
Out[2]: <metaklass.Klass at 0x7fe4362ab1f0>
````

At this point, make a little change to the file to trigger autoreload. Then:

````
[ins] In [3]: Klass()
[autoreload of metaklass failed: Traceback (most recent call last):
  File "..../lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 261, in check
    superreload(m, reload, self.old_objects)
  File "..../lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 484, in superreload
    update_generic(old_obj, new_obj)
  File "..../lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 381, in update_generic
    update(a, b)
  File "..../lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 349, in update_class
    update_instances(old, new)
  File "..../lib/python3.10/site-packages/IPython/extensions/autoreload.py", line 307, in update_instances
    object.__setattr__(ref, "__class__", new)
TypeError: can't apply this __setattr__ to MetaKlass object
]
Out[3]: <metaklass.Klass at 0x7fe4362ab340>
````

With 8.4 there is no such problem:

````
Python 3.10.0 (default, Oct 21 2021, 15:52:07) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: from metaklass import *

[ins] In [2]: Klass()
Out[2]: <metaklass.Klass at 0x7f38e200e290>
````

Again, make a little change.

````
[ins] In [3]: Klass()
Out[3]: <metaklass.Klass at 0x7f38e200d780>
````

I believe this commit has introduced the regression:

https://github.com/ipython/ipython/commit/8eef757fc63a17f34a14920ec21a038fbeb67d46

**Comment by kortsi** [comment]
The first fix coming to my mind would be something like this (did not test):

````
    for ref in refs:
        if type(ref) is old:
            if ref.__setattr__ != object.__setattr__:
                # setattr has been overridden
                object.__setattr__(ref, "__class__", new)
            else:
                ref.__class__ = new
````

That would work both for classes with a metaclass or classes having `__setattr__` overridden, but not with classes having both I guess? I wonder what would be the proper way to fix this.

**Comment by vultix** [comment]
I'm running into this, is there any workaround?

**Comment by yut23** [comment]
This appears to have been resolved by the new deduperreload system in 9.0. For older versions, or if you have a scenario where that doesn't work, this fixes it for all the cases I've tested:
```diff
diff --git a/IPython/extensions/autoreload.py b/IPython/extensions/autoreload.py
index 39ac6d52d..0fe0823eb 100644
--- a/IPython/extensions/autoreload.py
+++ b/IPython/extensions/autoreload.py
@@ -328,7 +328,11 @@ class definition and update their __class__ to point to the new class
 
     for ref in refs:
         if type(ref) is old:
-            object.__setattr__(ref, "__class__", new)
+            try:
+                ref.__class__ = new
+            except AttributeError:
+                # this catches e.g. dataclasses.FrozenInstanceError
+                object.__setattr__(ref, "__class__", new)
 
 
 def update_class(old, new):
```
