### ISSUE TITLE
KeyError: 'ipython_dir'

### ISSUE THREAD

**Issue by UgoPelissier** [ipython/ipython#13832]
Hi everyone,

My computer shut down while running a simple code on Spyder. Ever since it has restarted, it seems that '/Users/fp/.ipython' has not been found anymore.

To be more specific, I run:

```ipython3```

And I get the following error message:

```
Traceback (most recent call last):
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'ipython_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fp/opt/anaconda3/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/core/application.py", line 458, in initialize
    self.init_profile_dir()
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/core/application.py", line 362, in init_profile_dir
    p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/core/application.py", line 174, in _ipython_dir_default
    d = get_ipython_dir()
  File "/Users/fp/opt/anaconda3/lib/python3.9/site-packages/IPython/paths.py", line 70, in get_ipython_dir
    os.makedirs(ipdir, exist_ok=True)
  File "/Users/fp/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/fp/.ipython'
```

I checked and indeed I do not have a ```/Users/fp/.ipython``` folder. On the contrary, I still have a ```/Users/fp/.jupyter``` folder for example.

```
ipython3 --version   
7.31.1

conda --version
conda 22.9.0

python3 --version
Python 3.9.13
```
Anyone could help me with that?

Thank you

**Comment by krassowski** [comment]
Can you create the `/Users/fp/.ipython` folder manually? The line `os.makedirs(ipdir, exist_ok=True)` is trying to do so but fails for some reason. Some possibilities include the `/Users/fp/` being read-only (but this should have been picked up earlier), or the disk not having sufficient space.

**Comment by UgoPelissier** [comment]
I tried but I could not create a hidden folder at root.

Instead, I created ```/Users/fp/ipython```, put inside this folder all the files from another ```ipython``` folder I had on another machine, and I changed the directory that is being searched inside ```path.py``` from ```.ipython``` to ```ipython```.

It is working fine now.

Thank's for taking the time to answer and trying to help. I will close the issue.
