### ISSUE TITLE
Problem with IPyhon 8.0 and upper to 8.5 (Jupyter case)

### ISSUE THREAD

**Issue by ManPython** [ipython/ipython#13867]
There is problem:
https://www.pythonfixing.com/2022/07/fixed-ipython-passwd-not-able-to-import.html
Soo.. on 8.5 not working, working on 8.0 
`from IPython.lib import passwd`
 But on 8.0 exist problem with this:
```
 NotebookApp] KernelRestarter: restarting kernel (5/5), new random ports
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/traitlets/config/application.py", line 991, in launch_instance
    app.initialize(argv)
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 665, in initialize
    self.init_sockets()
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 309, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 246, in _bind_socket
    return self._try_bind_socket(s, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 222, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/usr/home/eaforex/venvp311/lib/python3.11/site-packages/zmq/sugar/socket.py", line 232, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation not permitted
[W   NotebookApp] KernelRestarter: restart failed

```
On 8.0 upper problem not exist.. thats funny : )

**Comment by ManPython** [comment]
This same problem with  ipython-7.34.0 on Python 378 as 311
