### ISSUE TITLE
LimitOverrunError: Separator is not found, and chunk exceed the limit

### ISSUE THREAD

**Issue by garlandz-db** [ipython/ipython#14005]
I verified that IPython==7.32.0 works fine for the curl command
```
curl -X GET \
     "https://datasets-server.huggingface.co/first-rows?dataset=tatsu-lab%2Falpaca&config=tatsu-lab--alpaca&split=train"
```
but not in IPython==8.10.0 and instead get this error

```
Task exception was never retrieved
future: <Task finished name='Task-342' coro=<ScriptMagics.shebang.<locals>._handle_stream() done, defined at /Users/garland.zhang/mambaforge/envs/testenv/lib/python3.10/site-packages/IPython/core/magics/script.py:211> exception=ValueError('Separator is not found, and chunk exceed the limit')>
Traceback (most recent call last):
  File "/Users/garland.zhang/mambaforge/envs/testenv/lib/python3.10/asyncio/streams.py", line 524, in readline
    line = await self.readuntil(sep)
  File "/Users/garland.zhang/mambaforge/envs/testenv/lib/python3.10/asyncio/streams.py", line 602, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/garland.zhang/mambaforge/envs/testenv/lib/python3.10/site-packages/IPython/core/magics/script.py", line 213, in _handle_stream
    line = (await stream.readline()).decode("utf8", errors="replace")
  File "/Users/garland.zhang/mambaforge/envs/testenv/lib/python3.10/asyncio/streams.py", line 533, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit

```

**Comment by jasongrout-db** [comment]
For me:

IPython 7.33.0 works fine.

<details><summary>IPython 8.0.1 does not work</summary>

```
In [3]: import IPython
   ...: 
   ...: IPython.__version__
Out[3]: '8.0.1'

In [4]: %%sh
   ...: curl -X GET "https://datasets-server.huggingface.co/first-rows?dataset=tatsu-lab%2Falpaca&config=tatsu-lab--alpaca&split=train"
   ...: 
   ...: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  102k  100  102k    0     0   156k      0 --:--:-- --:--:-- --:--:--  157k
Task exception was never retrieved
future: <Task finished name='Task-411' coro=<ScriptMagics.shebang.<locals>._handle_stream() done, defined at /private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.ZswAqZOz/env/lib/python3.10/site-packages/IPython/core/magics/script.py:211> exception=ValueError('Separator is not found, and chunk exceed the limit')>
Traceback (most recent call last):
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.ZswAqZOz/env/lib/python3.10/asyncio/streams.py", line 524, in readline
    line = await self.readuntil(sep)
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.ZswAqZOz/env/lib/python3.10/asyncio/streams.py", line 602, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.ZswAqZOz/env/lib/python3.10/site-packages/IPython/core/magics/script.py", line 213, in _handle_stream
    line = (await stream.readline()).decode("utf8")
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.ZswAqZOz/env/lib/python3.10/asyncio/streams.py", line 533, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit
```
</details>

<details><summary>IPython 8.12.0 does not work (but better error message)</summary

```
In [4]: import IPython; IPython.__version__
Out[4]: '8.12.0'

In [5]: %%sh
   ...: curl -X GET "https://datasets-server.huggingface.co/first-rows?dataset=tatsu-lab%2Falpaca&config=tatsu-lab--alpaca&split=train"
   ...: 
   ...: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  102k  100  102k    0     0   152k      0 --:--:-- --:--:-- --:--:--  153k
Task exception was never retrieved
future: <Task finished name='Task-281' coro=<ScriptMagics.shebang.<locals>._handle_stream() done, defined at /private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.h9hWJWVB/env/lib/python3.11/site-packages/IPython/core/magics/script.py:211> exception=ValueError('Separator is not found, and chunk exceed the limit')>
Traceback (most recent call last):
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.h9hWJWVB/env/lib/python3.11/asyncio/streams.py", line 545, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.h9hWJWVB/env/lib/python3.11/asyncio/streams.py", line 623, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.h9hWJWVB/env/lib/python3.11/site-packages/IPython/core/magics/script.py", line 213, in _handle_stream
    line = (await stream.readline()).decode("utf8", errors="replace")
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/64/mpb2_6_x4sj7xgbvc61p9nsh0000gp/T/tmpenv.h9hWJWVB/env/lib/python3.11/asyncio/streams.py", line 554, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit
```
</details>

**Comment by jasongrout** [comment]
I bisected this issue down to commit ce820924d81ff15f711a5ad1ce2d6e2868d22039 in https://github.com/ipython/ipython/pull/12639

**Comment by garlandz-db** [comment]
Thanks for the root causing! I was thinking a quick fix would just simply increase the buffer limit. However maybe the right fix is to do something similar to curl. Instead of throwing an error when the chunk is larger than the buffer, keep storing it in memory until we reach a separator in a later chunk (or we OOM). This doesn't seem like a quick fix as that would require updating how readline works https://github.com/python/cpython/blob/fd512d76456b65c529a5bc58d8cfe73e4a10de7a/Lib/asyncio/streams.py#L540

**Comment by garlandz-db** [comment]
solution proposal: make a patch and instead of reading by line, we try continuously reading until a separator is found or the buffer is full. We would have to update [this line](https://github.com/ipython/ipython/blob/main/IPython/core/magics/script.py#L213) and instead of readline we use the [readuntil method](https://github.com/python/cpython/blob/fd512d76456b65c529a5bc58d8cfe73e4a10de7a/Lib/asyncio/streams.py#L549) which readline also uses under the hood.

**Comment by jasongrout** [comment]
> we use the [readuntil method](https://github.com/python/cpython/blob/fd512d76456b65c529a5bc58d8cfe73e4a10de7a/Lib/asyncio/streams.py#L549) which readline also uses under the hood.

And if readuntil returns a limit error, then use `read()` to get a chunk from the buffer, then call `readuntil()` again, like this pseudocode?

```
while True:
    try:
        chunk = stream.readuntil('\n')
    except LimitOverrunError:
        chunk = stream.read(stream.limit)
    process(chunk)
```

**Comment by garlandz-db** [comment]
im going to test this to confirm but that should be about it. we basically take `readline()` but handle the `LimitOverrunError`  differently. E.g.; we'll go from
```
async def readline(self):
        sep = b'\n'
        seplen = len(sep)
        try:
            line = await self.readuntil(sep)
        except exceptions.IncompleteReadError as e:
            return e.partial
        except exceptions.LimitOverrunError as e:
            if self._buffer.startswith(sep, e.consumed):
                del self._buffer[:e.consumed + seplen]
            else:
                self._buffer.clear()
            self._maybe_resume_transport()
            raise ValueError(e.args[0])
        return line
```

to
```
async def readWithoutLimit(self):
        sep = b'\n'
        seplen = len(sep)
        try:
            return self.readuntil(sep)
        except exceptions.IncompleteReadError as e:
            return e.partial
        except exceptions.LimitOverrunError as e:
            return await self.read(e.consumed)
```

and in IPython %%script we replace [this line](https://github.com/ipython/ipython/blob/9c07131ad450854fd265895e0b79cc0b89ef72d4/IPython/core/magics/script.py#L213) with

```
chunk = (await stream.readWithoutLimit()).decode("utf8", errors="replace")
```
with some renaming. does that make sense?

**Comment by jasongrout** [comment]
Sounds good, though `readWithoutLimit` is still reading with a limit. Maybe it should be called something like `readline_chunk` or `readchunk`, or something that indicates that it will return a chunk or segment of data, but only up to the next newline?

**Comment by garlandz-db** [comment]
ive got [a PR](https://github.com/ipython/ipython/pull/14019) @jasongrout  please review it when you can!

**Comment by jasongrout** [comment]
The PR (#14019) was merged. Thanks again!
