### ISSUE TITLE
IPython.start_ipython can only be started once

### ISSUE THREAD

**Issue by Yinameah** [ipython/ipython#14106]
I have an application with another kind of main loop, and I sometimes want to jump in a IPython session.

So I use `start_ipython(ns=some_dict)`. This block the main program while the user is using ipython pre-sorted data. 
When the user type quit, I'm back in the main program, which is nice, but any further attempt to launch the interpreter result in failure : 
```
Loading history failed
Traceback (most recent call last):
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/prompt_toolkit/buffer.py", line 422, in load_history_done
    f.result()
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/prompt_toolkit/buffer.py", line 410, in load_history
    async for item in self.history.load():
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/prompt_toolkit/history.py", line 59, in load
    self._loaded_strings = list(self.load_history_strings())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 175, in load_history_strings
    for __, ___, cell in self.shell.history_manager.get_tail(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_tail'

Unhandled exception in event loop:
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/prompt_toolkit/buffer.py", line 410, in load_history
    async for item in self.history.load():
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/prompt_toolkit/history.py", line 59, in load
    self._loaded_strings = list(self.load_history_strings())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aurelien/.local/share/virtualenvs/pygris/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 175, in load_history_strings
    for __, ___, cell in self.shell.history_manager.get_tail(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception 'NoneType' object has no attribute 'get_tail'
Press ENTER to continue...
```
and after that the shell is unusable, it only repeat the same error over and over.

**Minimal code to reproduce**

```
import IPython

IPython.start_ipython()
IPython.start_ipython()
```

maybe there is another way to "reconnect" to the last process, (but I could not find anything in the docs), or something is not cleaned and it's kind of a bug....

Would appreciate very much any help if I'm doing this wrong, or happy to provide further infos if this seems like a bug.

**Comment by swaroopsarma** [comment]
May be its old and i just came across this. STarting from ipython 8.16 , the mainloop has been made not to be callable again. They clear the history manager by calling _atexit_once. 
If you want to overcome this you may try this out. 

import IPython

def start_ip():
    ip = IPython.terminal.ipapp.TerminalIPythonApp()
    ip.initialize()
    # this is to avoid assert **_xterm_term_title_saved** 
    #ip.shell.init_term_title()
    if ip.shell.history_manager is None:
        ip.shell.history_manager = IPython.core.history.HistoryManager(shell=ip.shell)
    ip.start()
    # this is to rewrite flag, in case you need history manager to be cleared every time
    #ip.shell._atexit_once_called = False

**Comment by Yinameah** [comment]
Whoo, totally missed this answer. I'm currently doing things differently but I'm sure the tip will be useful in the future. Thanks
