### ISSUE TITLE
error with jupyter_notebook_config.json file

### ISSUE THREAD

**Issue by BioVictory** [ipython/ipython#14113]
**Hi, I face this error with my jupyter_notebook_config.json file, when I use "jupyter notebook"** 

Exception while loading config file /data/Wu_Feizhen/wfz05/.jupyter/jupyter_notebook_config.json
    Traceback (most recent call last):
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 858, in _load_config_files
        config = loader.load_config()
                 ^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/loader.py", line 576, in load_config
        dct = self._read_file_as_dict()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/loader.py", line 582, in _read_file_as_dict
        return json.load(f)
               ^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 293, in load
        return loads(fp.read(),
               ^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 3 column 13 (char 33)
Traceback (most recent call last):
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 991, in launch_instance
    app.initialize(argv)
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/notebookapp.py", line 2169, in initialize
    self.init_server_extension_config()
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/notebookapp.py", line 2026, in init_server_extension_config
    section = manager.get(self.config_file_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/services/config/manager.py", line 25, in get
    recursive_update(config, cm.get(section_name))
                             ^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/config_manager.py", line 100, in get
    recursive_update(data, json.load(f))
                           ^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 13 (char 33)

**then I run "jupyter notebook --debug", I got this,**
Searching ['/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/etc/jupyter', '/data/Wu_Feizhen/wfz05/.jupyter', '/data/Wu_Feizhen/wfz05/.local/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 21:29:21.651 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_config in /data/Wu_Feizhen/wfz05/.local/etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_config in /data/Wu_Feizhen/wfz05/.jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_config in /data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_notebook_config in /data/Wu_Feizhen/wfz05/.local/etc/jupyter
[D 21:29:21.651 NotebookApp] Looking for jupyter_notebook_config in /data/Wu_Feizhen/wfz05/.jupyter
[D 21:29:21.652 NotebookApp] Loaded config file: /data/Wu_Feizhen/wfz05/.jupyter/jupyter_notebook_config.py
[E 21:29:21.652 NotebookApp] Exception while loading config file /data/Wu_Feizhen/wfz05/.jupyter/jupyter_notebook_config.json
    Traceback (most recent call last):
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 858, in _load_config_files
        config = loader.load_config()
                 ^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/loader.py", line 576, in load_config
        dct = self._read_file_as_dict()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/loader.py", line 582, in _read_file_as_dict
        return json.load(f)
               ^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 293, in load
        return loads(fp.read(),
               ^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 3 column 13 (char 33)
[D 21:29:21.653 NotebookApp] Looking for jupyter_notebook_config in /data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/etc/jupyter
[D 21:29:21.653 NotebookApp] Raising open file limit: soft 1024->4096; hard 4096->4096
[D 21:29:21.673 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 21:29:21.673 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 21:29:21.673 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/data/Wu_Feizhen/wfz05/.local/etc/jupyter/jupyter_notebook_config.json
[D 21:29:21.673 NotebookApp] Paths used for configuration of jupyter_notebook_config: 
    	/data/Wu_Feizhen/wfz05/.jupyter/jupyter_notebook_config.json
Traceback (most recent call last):
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 991, in launch_instance
    app.initialize(argv)
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/notebookapp.py", line 2169, in initialize
    self.init_server_extension_config()
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/notebookapp.py", line 2026, in init_server_extension_config
    section = manager.get(self.config_file_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/services/config/manager.py", line 25, in get
    recursive_update(config, cm.get(section_name))
                             ^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/site-packages/notebook/config_manager.py", line 100, in get
    recursive_update(data, json.load(f))
                           ^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Wu_Feizhen/wfz05/anaconda3/envs/jupyter_R/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 13 (char 33)

**please anyone can help me with this issue, many thanks！**

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
