### ISSUE TITLE
Incompatibility with prompt_toolkit 3.0.39 and 3.0.40

### ISSUE THREAD

**Issue by beenje** [ipython/ipython#14255]
Hi!

I just updated ipython to 8.18.0 in one of my env and got the following error:

```
]# ipython
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.0 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "/opt/conda/envs/ipython/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
             ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/IPython/__init__.py", line 129, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/IPython/terminal/ipapp.py", line 317, in start
    self.shell.mainloop()
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 887, in mainloop
    self.interact()
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 872, in interact
    code = self.prompt_for_code()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ipython/lib/python3.12/site-packages/IPython/terminal/interactiveshell.py", line 813, in prompt_for_code
    text = self.pt_app.prompt(
           ^^^^^^^^^^^^^^^^^^^
TypeError: PromptSession.prompt() got an unexpected keyword argument 'inputhook'
```

I can reproduce it by creating the following env: `mamba create -y -n ipython ipython prompt_toolkit=3.0.39`

Updating `prompt_toolkit` to 3.0.41 fixes the issue.
Did https://github.com/ipython/ipython/pull/14241 make `ipython` incompatible with `prompt_toolkit` < 3.0.40?
The min version should be bumped in setup.cfg in that case.

**Comment by Carreau** [comment]
Yeah quite possible, i can't publish a fix before monday, but we likely should update pyproject.toml to pin to latest prompt toolkit, i'll try to restore compatibility for older versions later.

**Comment by Carreau** [comment]
See #14257, from my test it is also incompatible with 3.0.40, so I'll pin to 3.0.40+, 

In general fell free to send PRs, I'll merge and release in the next few hours.

**Comment by beenje** [comment]
Thanks!
