### ISSUE TITLE
Unexpected exception formatting exception in Python 3.13.0a3

### ISSUE THREAD

**Issue by nickovs** [ipython/ipython#14303]
I appreciate that Python 3.13 is still in alpha, but some incompatibility seems to have been introduced with the way that exception data is produced that causes `ipython`'s pretty execution formatting to fail, cause the raising of a separate "Unexpected exception formatting exception".

## Steps to reproduce

1) Build Python 3.13.0a3 from source and install it somewhere.
2) Create a venv using the new Python 3.13 interpreter.
3) Build the latest master branch of [`parso`](https://github.com/davidhalter/parso) from source and install it into the venv.
4) Install `ipython` using `pip`.
5) Run `ipython` in a way that triggers an exception (such as `ipython -c 'print(1/0)'`)

## Expected result

`ipython` should print a nicely formatted exception. For instance, on Python 3.12 the result is:

```
(venv_3.12) nicko@testvm ~ % ipython -c 'print(1/0)'                
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[1], line 1
----> 1 print(1/0)

ZeroDivisionError: division by zero
```

## Actual result

It appears that `ipython`, or possibly the `executing` library, is choking on the stack data and generates an `Unexpected exception formatting exception` message:

```
(venv_3.13) nicko@testvm ~ % ipython -c 'print(1/0)'
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-1-2fc232d1511a>", line 1, in <module>
    print(1/0)
          ~^~
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        etype, value, tb, tb_offset=tb_offset
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, etype, evalue, etb, tb_offset, number_of_lines_of_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, etype, value, tb, tb_offset, number_of_lines_of_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                           tb_offset)
                                                           ^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1063, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1160, in get_records
    res = list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
          ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/stack_data/core.py", line 597, in stack_data
    yield from collapse_repeated(
    ...<4 lines>...
    )
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/stack_data/utils.py", line 83, in collapse_repeated
    yield from map(mapper, original_group)
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/stack_data/core.py", line 587, in mapper
    return cls(f, options)
           ~~~^^^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/stack_data/core.py", line 551, in __init__
    self.executing = Source.executing(frame_or_tb)
                     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/executing/executing.py", line 283, in executing
    assert_(new_stmts <= stmts)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/nvansomeren/python_tests/venv_3.13/lib/python3.13/site-packages/executing/executing.py", line 80, in assert_
    raise AssertionError(str(message))
AssertionError
```

**Comment by Carreau** [comment]
I think we'll need @alexmojaki on this one as this is in [`executing`](https://github.com/alexmojaki/executing).

**Comment by nickovs** [comment]
For others running into this problem, it has been fixed in the [3.13 branch](https://github.com/alexmojaki/executing/tree/3.13) of `executing` and after installing that from source exception formatting works fine.

**Comment by Carreau** [comment]
Thanks for the heads up, I might update CI to install from that branch.
