### ISSUE TITLE
IPython 8.22 should require traitlets 5.13

### ISSUE THREAD

**Issue by krassowski** [ipython/ipython#14352]
https://github.com/ipython/ipython/pull/14324 introduced dependency on traitlets [v5.13.0](https://github.com/ipython/traitlets/releases/tag/v5.13.0), but the pin in pyproject is only on >5:

https://github.com/ipython/ipython/blob/1f25c79734b1053f2abef2912e6bf5db404b6f63/pyproject.toml#L34

```python
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/ipykernel_launcher.py", line 16, in <module>
    from ipykernel import kernelapp as app
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 21, in <module>
    from IPython.core.application import (  # type:ignore[attr-defined]
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 326, in <module>
    class InteractiveShell(SingletonConfigurable):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 331, in InteractiveShell
    ast_transformers: List[ast.NodeTransformer] = List(
  File "/srv/conda/envs/notebook/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/srv/conda/envs/notebook/lib/python3.10/typing.py", line 1345, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
  File "/srv/conda/envs/notebook/lib/python3.10/typing.py", line 228, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'traitlets.traitlets.List'> is not a generic class
```

**Comment by Carreau** [comment]
That, or `from __future__ import annotations` I guess.
