### ISSUE TITLE
No required version of typing_extensions is causing `ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' `

### ISSUE THREAD

**Issue by r00ta** [ipython/ipython#14380]
There are no version requirements on `typing_extensions`
https://github.com/ipython/ipython/blob/b9c597dfd0b29469ad32344f85b97b9ef83085f0/pyproject.toml#L35

but actually you are importing
```
from typing_extensions import TypeAliasType
```
here https://github.com/ipython/ipython/blob/b9c597dfd0b29469ad32344f85b97b9ef83085f0/IPython/core/guarded_eval.py#L40

and `TypeAliasType` has been added only in 4.6 https://github.com/python/typing_extensions/commit/09c1ed49509d3c0a963e5bfed50e4b941954810c. 

This means that if a system has already `typing_extensions` at version 4.4.0 (for example, on Ubuntu Jammy the deb package `python3-typing-extensions` is at version 4.4.0) `pip` will assume that 4.4.0 is ok, but you would end up with 
```
Traceback (most recent call last):
  File "/work/maas/bin/py", line 5, in <module>
    from IPython import start_ipython
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 48, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/core/completer.py", line 219, in <module>
    from IPython.core.guarded_eval import guarded_eval, EvaluationContext
  File "/work/maas/.ve/lib/python3.10/site-packages/IPython/core/guarded_eval.py", line 40, in <module>
    from typing_extensions import TypeAliasType
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)
```

Tested on 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by krassowski** [comment]
Thanks! I opened https://github.com/ipython/ipython/pull/14381.
