### ISSUE TITLE
Exception on rendering empty pipeline

### ISSUE THREAD

**Issue by stefansimik** [ipython/ipython#14568]
Hi guys, 
this issue is very very simple.

`ipython` simply fails on exception, when simple Pipeline is rendered.

![Image](https://github.com/user-attachments/assets/4dc0664a-be19-4351-a4a0-7c02ccc6ba0a)

This runs perfectly fine in normal `python`, it fails only in `ipython`.

## Reproduce

Very simple: put this code into new notebook and run:

```python
# This code fails - EMPTY pipeline is rendered

from sklearn.pipeline import Pipeline

# Create pipeline
pipeline = Pipeline(steps=[])
pipeline
```

It is important to note, that problem is in rendering, not the code itself, because this code runs fine (without rendering pipeline on last line):

```python
# This code works - pipeline is NOT rendered

from sklearn.pipeline import Pipeline

# Create pipeline
pipeline = Pipeline(steps=[])
```

As soon, as the pipeline is filled with some content (transformer), rendering works fine again. So the main problem is rendering the empty pipeline.

```python
# This code works - pipeline is not empty

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

def remove_columns(x): 
    return x.drop(columns=['a', 'b'])  

# Create pipeline
pipeline = Pipeline(steps=[
    ('remove_columns', FunctionTransformer(remove_columns)),    
])

pipeline
```

## Expected behavior

No exception should be thrown and empty Pipeline should by displayed.

**Comment by Carreau** [comment]
I think this is an upstream problem in sklearn; you can trigger the issue in the normal Python repr by building a html_repr manually:

```python
$ python
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.pipeline import Pipeline
>>> pipeline = Pipeline(steps=[])
>>> pipeline
Pipeline(steps=[])
>>> from sklearn.utils._estimator_html_repr import estimator_html_repr
>>> estimator_html_repr(pipeline)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bussonniermatthias/miniconda3/envs/arm64/lib/python3.12/site-packages/sklearn/utils/_estimator_html_repr.py", line 348, in estimator_html_repr
    check_is_fitted(estimator)
  File "/Users/bussonniermatthias/miniconda3/envs/arm64/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1660, in check_is_fitted
    if not _is_fitted(estimator, attributes, all_or_any):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniconda3/envs/arm64/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1579, in _is_fitted
    return estimator.__sklearn_is_fitted__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniconda3/envs/arm64/lib/python3.12/site-packages/sklearn/pipeline.py", line 1096, in __sklearn_is_fitted__
    check_is_fitted(self.steps[-1][1])
                    ~~~~~~~~~~^^^^
IndexError: list index out of range
```

sklearn likeley register this as a hook in IPython to be automatically triggered when displaying an object.

**Comment by Carreau** [comment]
I've opened an issue upstream:

https://github.com/scikit-learn/scikit-learn/issues/30197

**Comment by Carreau** [comment]
Closing as this is now fixed upstream. 

Thanks for the time you took to fist go in JupyterLab, then here, then in sklearn.
