### ISSUE TITLE
IPython completer generate wrong regexp

### ISSUE THREAD

**Issue by Amarchuk** [ipython/ipython#5638]
Try to get completions for next code:
In[1]: x=[1,2,3]
In[2]: x[1:-1]<tab>

And you will get the following traceback:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\ipython-1.2.0-py2.7.egg\IPython\core\completer.py", line 901, in complete
    self.matches.extend(matcher(text))
  File "C:\Python27\lib\site-packages\ipython-1.2.0-py2.7.egg\IPython\core\completer.py", line 584, in file_matches
    m0 = self.clean_glob(text.replace('\',''))
  File "C:\Python27\lib\site-packages\ipython-1.2.0-py2.7.egg\IPython\core\completer.py", line 524, in _clean_glob_win32
    for f in self.glob("%s*" % text)]
  File "C:\Python27\lib\glob.py", line 27, in glob
    return list(iglob(pathname))
  File "C:\Python27\lib\glob.py", line 44, in iglob
    for name in glob1(os.curdir, basename):
  File "C:\Python27\lib\glob.py", line 78, in glob1
 return fnmatch.filter(names, pattern)
  File "C:\Python27\lib\fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "C:\Python27\lib\re.py", line 190, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range

That's because completer.py runs function _clean_glob_win32 and uses fnmatch.py inside, which uses translate(text) function and this function produces wrong regexp (in which '-' sign used not for range) in attempt to get appropriate files. For this case it will be: 'x[1:-1].*\Z(?ms)'

**Comment by Carreau** [comment]
This seem to have been fixed for a while. Closing. Thanks
