### ISSUE TITLE
nbconvert citations broken?

### ISSUE THREAD

**Issue by JohnGriffiths** [ipython/ipython#5953]
In nbconvert-examples/citations when I type 'ipython nbconvert' I am now getting the following error:

Traceback (most recent call last):
  File "/home/brain/anaconda/bin/ipython", line 5, in <module>
    start_ipython()
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 564, in launch_instance
    app.start()
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
    self.convert_notebooks()
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename
    return self.from_notebook_node(nbformat.read(f, 'json'), resources=resources, **kw)
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 215, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/brain/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/brain/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brain/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/sphinx.tplx", line 377, in <module>
    ((( output.latex | strip_math_space )))
TemplateAssertionError: no filter named 'strip_math_space'

**Comment by takluyver** [comment]
I've just updated this example, and it seems to be working OK.
