### ISSUE TITLE
ipython notebook does not launch (after anaconda installation)

### ISSUE THREAD

**Issue by timothydmorton** [ipython/ipython#5976]
My specs:

```
mal:~$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '681fd77',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/u/tdm/anaconda/lib/python2.7/site-packages/IPython',
 'ipython_version': '2.1.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-431.17.1.el6.x86_64-x86_64-with-redhat-6.5-Pisa',
 'sys_executable': '/u/tdm/anaconda/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.7 |Anaconda 2.0.0 (64-bit)| (default, Jun  2 2014, 12:34:02) \n[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]'}
```

I was running ipython notebook with no problem on my Linux machine until yesterday.  Then I installed the anaconda distribution, and ipython breaks at launch with the below error message.  I tried rebooting the machine, and same error.  Any suggestions would be appreciated.

```
mal:~$ ipython notebook
2014-06-11 12:28:34.890 [NotebookApp] Created profile dir: u'/u/tdm/.ipython/profile_default'
2014-06-11 12:28:34.918 [NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/u/tdm/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 745, in initialize
    self.init_webapp()
  File "/u/tdm/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 632, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/tornado/tcpserver.py", line 117, in listen
    sockets = bind_sockets(port, address=address)
  File "/u/tdm/anaconda/lib/python2.7/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "/u/tdm/anaconda/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by a4mohit** [comment]
Facing the same issue. Does not work with --ip parameter also.
Any updates on this?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
