### ISSUE TITLE
Issue with Ipython Notebook Installation.

### ISSUE THREAD

**Issue by forwardcjj** [ipython/ipython#6165]
Hi, 
      I met this problem when install ipython notebook. try to follow the #4264 , but still not work.  @minrk @takluyver 

Could any friend offer a help? Thanks in advance.

Regards,  

```
2014-07-18 12:23:05.363 [NotebookApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 286, in wrapper
result = method(self, args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 66, in post
model = sm.create_session(name=name, path=path, kernel_id=kernel_id)
File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 75, in create_session
return self.save_session(session_id, name=name, path=path, kernel_id=kernel_id)
File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 103, in save_session
return self.get_session(session_id=session_id)
File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 134, in get_session
self.cursor.execute(query, list(kwargs.values()))
OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '����������������������������������������������������������������������������❳'
ERROR:tornado.application:Uncaught exception POST /api/sessions (::1)
HTTPRequest(protocol='http', host='localhost:8891', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1', headers={'Content-Length': '49', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8891', 'Accept': 'application/json, text/javascript, */; q=0.01', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130917 Firefox/17.0', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://localhost:8891/notebooks/Untitled2.ipynb', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1346, in when_complete
callback()
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1367, in execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2523, in wrapper
return method(self, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 301, in wrapper
self.finish(json.dumps(reply))
File "/usr/local/lib/python2.7/json/__init.py", line 243, in dumps
return _default_encoder.encode(obj)
File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 995: invalid start byte
ERROR:tornado.access:{
"Content-Length": "49",
"Accept-Language": "en-US,en;q=0.5",
"Accept-Encoding": "gzip, deflate",
"Connection": "keep-alive",
"Accept": "application/json, text/javascript, /; q=0.01",
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130917 Firefox/17.0",
"Host": "localhost:8891",
"X-Requested-With": "XMLHttpRequest",
"Pragma": "no-cache",
"Cache-Control": "no-cache",
"Referer": "http://localhost:8891/notebooks/Untitled2.ipynb",
"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
}
```

**Comment by aronwc** [comment]
@vrujbr I have the same problem. Can you please elaborate on your fix? 
Another complicating factor for me is that I have [Python 2.6 and 2.7 installed](https://github.com/h2oai/h2o/wiki/Installing-python-2.7-on-centos-6.3.-Follow-this-sequence-exactly-for-centos-machine-only), since CentOS requires 2.6 for yum

```sh
$ python -c 'import IPython; print(IPython.sys_info())'
{'commit_hash': 'b11c1c3',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '2.4.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-358.el6.x86_64-x86_64-with-centos-6.4-Final',
 'sys_executable': '/usr/local/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Apr 16 2014, 15:38:13) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]'}

$ sqlite3 -version
3.6.20


$ python -V
Python 2.7.6

```

**Comment by geffy** [comment]
Get the same problem.
Using python from scl (2.7.5) and virtualenv helps.

**Comment by chnwentao** [comment]
Get the same problem ， Using
 jupyter --version
4.2.1
sqlite3 -version
3.11.1 
/python -V
Python 2.7.1

python -c 'import IPython; print(IPython.sys_info())'
{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32_1-16-0-0_virtio-x86_64-with-redhat-4.3-Final',
 'sys_platform': 'linux2',
 'sys_version': '2.7.1 (r271:86832, Mar 12 2011, 16:42:00) \n[GCC 3.4.5 20051201 (Red Hat 3.4.5-2)]'}

bf/jupyter notebook --port=8899 --ip=cp01-xuchao08.epc.baidu.com --no-browser
[I 18:36:03.472 NotebookApp] Loaded server extension jupyter_nbextensions_configurator
[I 18:36:03.514 NotebookApp] JupyterLab alpha preview extension loaded from /home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/jupyterlab
[I 18:36:03.516 NotebookApp] Serving notebooks from local directory: /home/guowentao01
[I 18:36:03.516 NotebookApp] 0 active kernels
[I 18:36:03.516 NotebookApp] The Jupyter Notebook is running at: https://cp01-xuchao08.epc.baidu.com:8899/
[I 18:36:03.516 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
z[I 18:36:20.850 NotebookApp] 302 GET / (172.20.140.42) 1.04ms
[I 18:36:20.858 NotebookApp] 302 GET /tree? (172.20.140.42) 1.75ms
[I 18:36:29.205 NotebookApp] 302 GET /notebooks/bf_test.ipynb (172.20.140.42) 2.25ms
[I 18:36:33.719 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fbf_test.ipynb (172.20.140.42) 3.66ms
[W 18:36:34.545 NotebookApp] Notebook bf_test.ipynb is not trusted
[I 18:36:34.792 NotebookApp] Kernel started: c41b647a-670a-42e4-870f-944fda52dd62
[E 18:36:34.794 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 81, in create_session
        self.save_session(session_id, path=path, name=name, type=type, kernel_id=kernel_id)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 125, in save_session
        return self.get_session(session_id=session_id)
      File "/home/guowentao01/app/bigflow_python/python_runtime/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 156, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xfd\x80\x81\xa3\xf8\xa0\x80\xb1\xfd\x80\x80\xb6\xf8\x90\x80\xb7\xfd\xa0\x80\xad\xfc\x80\x80\xb7\xfb\x90\x81\xa1\xfc\xa0\x80\xb4\xfd\x80\x81\xa5\xfe\x80\x80\xad\xfc\x80\x80\xb7\xfb\x90\x81\xa6\xfd\x80\x80\xb9\xf9\xa0\x80\xb4\xf8\x90\x81\xa4\xfc\xa0\x80\xb5\xf9\x80\x81\xa4\xfc\xa0\x80\xb6'"

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
