### ISSUE TITLE
 Failure of ipynb to PDF conversion

### ISSUE THREAD

**Issue by takatsugukosugi** [ipython/ipython#6263]
Hi.
I use python notebook. 
I want to convert .ipynb to HTML and PDF.
So, I put this command lines.
```
% ipython nbconvert hoge.ipynb
```
I successed conversion of ipynb to html and got hoge.html.

But, I failed conversion of ipynb to PDF.
```
% ipython nbconvert hoge.ipynb --to latex --post PDF 
```
Do you have any good ideas?
```
[NbConvertApp] Using existing profile dir: u'/Users/TK/.ipython/profile_default'
[NbConvertApp] Converting notebook hoge.ipynb to latex
[NbConvertApp] Support files will be in hoge_files/
[NbConvertApp] Loaded template article.tplx
[NbConvertApp] Writing 16195 bytes to hoge.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'hoge.tex']
Traceback (most recent call last):
  File "/Users/TK/.virtualenvs/test1/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/config/application.py", line 564, in launch_instance
    app.start()
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
    self.convert_notebooks()
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 311, in convert_notebooks
    self.postprocessor(write_resultes)
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/postprocessors/base.py", line 28, in __call__
    self.postprocess(input)
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/postprocessors/pdf.py", line 140, in postprocess
    cont = self.run_latex(filename)
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/postprocessors/pdf.py", line 104, in run_latex
    self.latex_count, log_error)
  File "/Users/TK/.virtualenvs/test1/lib/python2.7/site-packages/IPython/nbconvert/postprocessors/pdf.py", line 84, in run_command
    p = subprocess.Popen(command, stdout=stdout, stdin=null)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
```
My OS environment is
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.2
BuildVersion:	13C64

My pip list is 
% pip list
backports.ssl-match-hostname (3.4.0.2)
certifi (14.05.14)
gnureadline (6.3.3)
ipython (2.1.0)
Jinja2 (2.7.3)
MarkupSafe (0.23)
matplotlib (1.3.1)
nose (1.3.3)
numpy (1.8.1)
pandas (0.14.1)
pip (1.5.6)
Pygments (1.6)
pyparsing (2.0.2)
python-dateutil (2.2)
pytz (2014.4)
pyzmq (14.3.1)
scipy (0.14.0)
setuptools (3.6)
six (1.7.3)
tornado (4.0)
wsgiref (0.1.2)

My Python version is
% Python --version
Python 2.7.8
```

**Comment by takluyver** [comment]
I'm closing this issue as it's not clear that there's anything for us to do. @AnneTheAgile's patch has been merged, so hopefully the error messages are more informative now.

**Comment by pylang** [comment]
I am confirming I had a similar issue on Windows using IPython 3.0, and this solution resolved my problem.  That is, installing latex (using miktex-2.9.5105) allowed me to "print to pdf" from the dropdown menu.  The output file looks great so far.  Thanks.
