### ISSUE TITLE
notebook crashes on startup

### ISSUE THREAD

**Issue by kdere** [ipython/ipython#6355]
I am using Python 2.7.6 and Ipython 2.2.0
on another computer, I am using IPython 2.1.0 and notebooks work fine

when starting up a notebook I get 

```
chianti/test> npython
2014-08-25 15:31:43.321 [NotebookApp] Using existing profile dir: u'/home/ken/.ipython/profile_notebook'
2014-08-25 15:31:43.331 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 320, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 315, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/usr/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib/python2.7/site-packages/tornado/tcpserver.py", line 116, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/site-packages/tornado/netutil.py", line 89, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address
```

**Comment by ellisonbg** [comment]
@kdere did you get this figured out?

**Comment by kdere** [comment]
with IPython 2.1 I don't have to specify an ip address
with IPython 2.2 and 2.3 I need to specify --ip=127.0.0.1

**Comment by minrk** [comment]
@kdere what do you get if you try:

```python
import socket
s = socket.socket()
s.bind(('localhost', 0))
```

**Comment by kdere** [comment]
running IPython 2.3.0
if I have already set --ip=127.0.0.0 those commands work - well, they don't throw off error messages
if not, I get the message that
port 8888 is already in use, try another random port
