### ISSUE TITLE
Multiple encoding failures in 2.2.0 unit tests on Python 3.4 / Ubuntu 12.04

### ISSUE THREAD

**Issue by andrewclegg** [ipython/ipython#6372]
One in utils:

```
ERROR: IPython.utils.tests.test_path.test_ensure_dir_exists
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/tests/test_path.py", line 607, in test_ensure_dir_exists
    path.ensure_dir_exists(d) # create it
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/path.py", line 579, in ensure_dir_exists
    if not os.path.exists(path):
  File "/usr/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2202' in position 17: ordinal not in range(256)
```

And a whole bunch in html:

```
ERROR: test_checkpoint_subdir (IPython.html.services.notebooks.tests.test_nbmanager.TestFileNotebookManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/notebooks/tests/test_nbmanager.py", line 64, in test_checkpoint_subdir
    os.mkdir(os.path.join(td, subd))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2202' in position 21: ordinal not in range(256)

======================================================================
ERROR: test_copy_notebook (IPython.html.services.notebooks.tests.test_nbmanager.TestNotebookManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/notebooks/tests/test_nbmanager.py", line 270, in test_copy_notebook
    orig = nm.create_notebook({'name' : name}, path=path)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/notebooks/nbmanager.py", line 207, in create_notebook
    model = self.save_notebook(model, model['name'], model['path'])
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/notebooks/filenbmanager.py", line 288, in save_notebook
    if self.notebook_exists(name, path) and not self.list_checkpoints(name, path):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/notebooks/filenbmanager.py", line 170, in notebook_exists
    return os.path.isfile(nbpath)
  File "/usr/lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u221a' in position 24: ordinal not in range(256)

======================================================================
ERROR: test_check_nbextension (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: install_nbextension when ipython_dir doesn't exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_create_nbextensions (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_nbextension (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_symlink (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_symlink_bad (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_tar (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_url (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_install_zip (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_overwrite_dir (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_overwrite_file (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_quiet (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_single_dir (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_single_file (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_skip_old_file (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

======================================================================
ERROR: test_update_file (IPython.html.tests.test_nbextensions.TestInstallNBExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 67, in setUp
    touch(fullpath)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/tests/test_nbextensions.py", line 39, in touch
    open(file, 'a').close()
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0192' in position 17: ordinal not in range(256)

----------------------------------------------------------------------
Ran 103 tests in 28.011s

FAILED (errors=18)
```

I checked on master (4dcc51a) -- same problems.

Some system info:

```
IPython version: 2.2.0
IPython commit : d87a8cd (installation)
IPython package: /usr/local/lib/python3.4/dist-packages/IPython
Python version : 3.4.1 (default, May 25 2014, 22:33:14) [GCC 4.6.3]
sys.executable : /usr/bin/python3.4
Platform       : Linux-3.2.0-23-generic-x86_64-with-Ubuntu-12.04-precise

Tools and libraries available at test time:
   curses cython jinja2 matplotlib numpy oct2py pexpect pygments requests rpy2 sphinx sqlite3 tornado zmq

Tools and libraries NOT available at test time:
   casperjs pymongo qt
```

Can be reproduced by installing Snake Charmer snake-charmer-devs/snake-charmer@5ef69edb44 and just running `iptest3 --all -j`.

**Comment by Carreau** [comment]
Closing as inactive.
