### ISSUE TITLE
Failure to launch notebook but --ip=127.0.0.1 doesn't work

### ISSUE THREAD

**Issue by Acomfort** [ipython/ipython#6381]
Hi I'm having trouble launching notebook.  I've tried the usual solution to add --pi=127.0.0.1 but I get the same error mesage (below) regardless.  I'm using Debian Wheezy armHF os.  Thanks in advance for your help!
Allen

[NotebookApp] Using existing profile dir: u'/home/debian/.config/ipython/profile_default'
[NotebookApp] Serving notebooks from /
Traceback (most recent call last):
  File "/usr/bin/ipython", line 8, in <module>
    launch_new_instance()
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/terminal/ipapp.py", line 388, in launch_new_instance
    app.initialize()
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 84, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/terminal/ipapp.py", line 313, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 84, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/core/application.py", line 325, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/terminal/ipapp.py", line 308, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 84, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 420, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 84, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 359, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 84, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/html/notebook/notebookapp.py", line 539, in initialize
    self.init_webapp()
  File "/usr/lib/python2.7/dist-packages/IPython/frontend/html/notebook/notebookapp.py", line 457, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 103, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 268, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by ellisonbg** [comment]
@Acomfort did you ever this this figured out?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
