### ISSUE TITLE
nbconvert AttributeError: LooseVersion - cannot convert to html

### ISSUE THREAD

**Issue by aswolf** [ipython/ipython#6478]
Hello,

I am just getting started with ipython notebooks and I have been extremely impressed. Unfortunately, I cannot get nbconvert to work when converting to html. It works fine for converting to markdown, latex, rst, and python. But, when trying html (or slides), I get the following error:
AttributeError: LooseVersion instance has no attribute 'version'

For background, I am running Mac OS 10.9.4 and am using the most current anaconda install (2.0.1). The full traceback is copied below. Note that this same exact file works fine for converting to all the other formats.

I have also tried updating conda, ipython, ipython-notebook, and ipython-qtconsole all using conda. Only ipython-qtconsole needed updating and it made no difference to all the described behaviors above.
 
 I really appreciate any help you can give.

Best,
Aaron

PS: I was just informed that this is the right repo to post this issue to (previous post: https://github.com/ipython/nbviewer/issues/346#issuecomment-55645707)

aswolfdisplay:software-carpentry-lessons aswolf$ ipython nbconvert testNotes.ipynb 
[NbConvertApp] Using existing profile dir: u'/Users/aswolf/.ipython/profile_default'
[NbConvertApp] Converting notebook testNotes.ipynb to html
[NbConvertApp] Support files will be in testNotes_files/
[NbConvertApp] Loaded template full.tpl
Traceback (most recent call last):
File "/Users/aswolf/anaconda/bin/ipython", line 6, in 
sys.exit(start_ipython())
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/init.py", line 120, in start_ipython
return launch_new_instance(argv=argv, **kwargs)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 564, in launch_instance
app.start()
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
return self.subapp.start()
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
self.convert_notebooks()
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks
output, resources = exporter.from_filename(notebook_filename, resources=resources)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename
return self.from_notebook_node(nbformat.read(f, 'json'), resources=resources, **kw)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 215, in from_notebook_node
output = self.template.render(nb=nb_copy, resources=resources)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 2, in top-level template code
{% from 'mathjax.tpl' import mathjax %}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 1, in top-level template code
{%- extends 'display_priority.tpl' -%}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in top-level template code
{%- extends 'null.tpl' -%}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 26, in top-level template code
{%- block body -%}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 63, in block "body"
{{ super() }}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 29, in block "body"
{%- block any_cell scoped -%}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 76, in block "any_cell"
{%- block headingcell scoped-%}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 79, in block "headingcell"
{{ ("#" * cell.level + cell.source) | replace('\n', ' ') | markdown2html | strip_files_prefix | add_anchor }}
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/filters/markdown.py", line 76, in markdown2html
if not verify_node(node):
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/nbconvert/filters/markdown.py", line 139, in _verify_node
return check_version(out.lstrip('v'), '0.9.12')
File "/Users/aswolf/anaconda/lib/python2.7/site-packages/IPython/utils/version.py", line 33, in check_version
return LooseVersion(v) >= LooseVersion(check)
File "/Users/aswolf/anaconda/lib/python2.7/distutils/version.py", line 296, in __cmp
return cmp(self.version, other.version)
AttributeError: LooseVersion instance has no attribute 'version'

If you suspect this is an IPython bug, please report it at:
https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
c.Application.verbose_crash=True

**Comment by Carreau** [comment]
Closing this as nothing we can do. 

Node should not be needed anymore now also. 

Thanks,
