### ISSUE TITLE
security scan causing ERROR:tornado.general:Uncaught exception

### ISSUE THREAD

**Issue by catimossi** [ipython/ipython#6574]
Running notebook server on mac os x 10.6.8. Recently updated platform with enpkg --update-all

Our organization conducts security scans periodically. The most recent triggered this stack trace from the notebook server:

```
myhost:Shared user$ WARNING:tornado.general:SSL Error on 7 ('131.243.64.212', 47569): [Errno 1] _ssl.c:507: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
ERROR:tornado.general:Uncaught exception
Traceback (most recent call last):
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/http1connection.py", line 674, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/gen.py", line 617, in run
    value = future.result()
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/gen.py", line 620, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/http1connection.py", line 165, in _read_message
    io_loop=self.stream.io_loop)
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/gen.py", line 617, in run
    value = future.result()
  File "/Users/catimossi/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
SSLError: [Errno 1] _ssl.c:507: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
```

**Comment by Carreau** [comment]
closing as inactive.
