### ISSUE TITLE
UnicodeEncodeError when trying ipcluster start (windows, python 2.7, non-ascii characters in user name)

### ISSUE THREAD

**Issue by mmagnuski** [ipython/ipython#7289]
I am getting UnicodeEncodeError when trying to start ipcluster.
I am using python 2.7, ipython 2.3.1, windows 8.
Opening ipython notebook works ok, only `ipcluster start` produces errors.

The error:
```python
D:\DATA
λ ipcluster start
2014-12-23 15:37:20.788 [IPClusterStart] Using existing profile dir: u'C:\\Users\\Miku\u015b\\.ipython\\profile_default'
2014-12-23 15:37:20.803 [IPClusterStart] Removing pid file: C:\Users\Mikuś\.ipython\profile_default\pid\ipcluster.pid
2014-12-23 15:37:20.805 [IPClusterStart] Starting ipcluster with [daemon=False]
2014-12-23 15:37:20.812 [IPClusterStart] Creating pid file: C:\Users\Mikuś\.ipython\profile_default\pid\ipcluster.pid
2014-12-23 15:37:20.815 [IPClusterStart] Starting Controller with LocalControllerLauncher
2014-12-23 15:37:20.816 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\ipclusterapp.py", line 525, in start_controller
    self.controller_launcher.start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 356, in start
    return super(LocalControllerLauncher, self).start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 277, in start
    cwd=self.work_dir
  File "D:\Python\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 98: ordinal not in range(128)
ERROR:tornado.general:Error in delayed callback
Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\zmq\eventloop\ioloop.py", line 69, in _run
    self.callback()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\ipclusterapp.py", line 525, in start_controller
    self.controller_launcher.start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 356, in start
    return super(LocalControllerLauncher, self).start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 277, in start
    cwd=self.work_dir
  File "D:\Python\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 98: ordinal not in range(128)
2014-12-23 15:37:21.819 [IPClusterStart] Starting 4 Engines with LocalEngineSetLauncher
2014-12-23 15:37:21.822 [IPClusterStart] ERROR | Engine start failed
Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\ipclusterapp.py", line 352, in start_engines

    self.engine_launcher.start(self.n)
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 401, in start
    d = el.start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 277, in start
    cwd=self.work_dir
  File "D:\Python\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 94: ordinal not in range(128)
ERROR:tornado.general:Error in delayed callback
Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\zmq\eventloop\ioloop.py", line 69, in _run
    self.callback()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\ipclusterapp.py", line 352, in start_engines

    self.engine_launcher.start(self.n)
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 401, in start
    d = el.start()
  File "D:\Python\Anaconda\lib\site-packages\IPython\parallel\apps\launcher.py", line 277, in start
    cwd=self.work_dir
  File "D:\Python\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 94: ordinal not in range(128)
```

**Comment by minrk** [comment]
Python 2 on Windows is *very* bad at unicode. If you have a non-ascii username on Windows, I strongly recommend you use Python 3, if possible. The number of issues in Python 2 with unicode on Windows are not manageable.

**Comment by mmagnuski** [comment]
I noticed that :) I get this kind of errors very frequently. But IPython is the first reason to actually push me to using Python 3. :)
