### ISSUE TITLE
ipython nbconvert cannot be run from within a notebook

### ISSUE THREAD

**Issue by npyoung** [ipython/ipython#7294]
I'm trying to take advantage of shell magic in a notebook to call nbconvert on that notebook (or even a different notebook) with the following line.

    !ipython nbconvert my_notebook.ipynb --to latex --post pdf

I use a notebook that runs on a remote server, so this would save me having to pop open a terminal, cd around, and reform the command whenever I want to generate a slideshow/pdf/report. But I always get the error below.

```
[NbConvertApp] Using existing profile dir: u'/home/me/.ipython/profile_default'
[NbConvertApp] Converting notebook my_notebook.ipynb to latex
[NbConvertApp] Support files will be in my_notebook_files/
[NbConvertApp] Loaded template article.tplx
pandoc: HOME: getAppUserDataDirectory: does not exist (no environment variable)
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 9, in <module>
    load_entry_point('ipython==2.3.1', 'console_scripts', 'ipython')()
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 564, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
    self.convert_notebooks()
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename
    return self.from_notebook_node(nbformat.read(f, 'json'), resources=resources, **kw)
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 215, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/article.tplx", line 8, in top-level template code
    ((* extends cell_style *))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/style_ipython.tplx", line 52, in top-level template code
    ((( text | add_prompts(first='{\color{' ~ prompt_color ~ '}' ~ prompt ~ '[{\\color{' ~ prompt_color ~ '}' ~ prompt_number ~ '}]:} ', cont=indention) )))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/base.tplx", line 180, in top-level template code
    ((*- block figure scoped -*))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/skeleton/display_priority.tplx", line 5, in top-level template code
    ((*- extends 'null.tplx' -*))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/skeleton/null.tplx", line 30, in top-level template code
    ((*- block body -*))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/base.tplx", line 122, in block "body"
    ((( super() )))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/skeleton/null.tplx", line 33, in block "body"
    ((*- block any_cell scoped -*))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/skeleton/null.tplx", line 80, in block "any_cell"
    ((*- block headingcell scoped-*))
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/exporters/../templates/latex/base.tplx", line 204, in block "headingcell"
    {((( cell.source | replace('\n', ' ') | citation2latex | strip_files_prefix | markdown2latex )))}
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/filters/markdown.py", line 65, in markdown2latex
    return pandoc(source, 'markdown', 'latex')
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/utils/pandoc.py", line 63, in pandoc
    check_pandoc_version()
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/utils/pandoc.py", line 104, in check_pandoc_version
    v = get_pandoc_version()
  File "/usr/local/lib/python2.7/site-packages/IPython/nbconvert/utils/pandoc.py", line 90, in get_pandoc_version
    out = subprocess.check_output( ['pandoc', '-v'], universal_newlines=True)
  File "/usr/local/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['pandoc', '-v']' returned non-zero exit status 1
```

I'm then asked to report this if I think this is a bug, as I am dutifully doing here.

I've checked and there doesn't appear to be a permissions issue. I can do `pandoc -v` in the terminal just fine, and I can also run the nbconvert command successfully from the command line.

System info:
```
{'commit_hash': '1c0eb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '2.3.1',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-24-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/usr/local/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.2 (default, Nov  6 2011, 16:20:41) \n[GCC 4.4.3]'}
```

**Comment by ellisonbg** [comment]
I think this is an issue with the installation or ipython or pandoc. Can you look into that angle?

**Comment by npyoung** [comment]
**Solved**. It had to do with when the notebook server gets started, not permissions. The notebook gets started by an upstart script that runs before the $HOME gets set, thus the complaint about `HOME: getAppUserDataDirectory: does not exist (no environment variable)`. Seems like a pandoc issue, not IPython.
