### ISSUE TITLE
Notebook conversion to LaTeX/pdf fails with nbconvert

### ISSUE THREAD

**Issue by fonnesbeck** [ipython/ipython#7421]
Using the current IPython master, I am unable to export notebooks either to LaTeX using nbconvert or to pdf via the export menu item. In the former, I receive an AttributeError:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/IPython/html/nbconvert/handlers.py", line 81, in get
        exporter = get_exporter(format, config=self.config, log=self.log)
      File "/usr/local/lib/python3.4/site-packages/IPython/html/nbconvert/handlers.py", line 59, in get_exporter
        from IPython.nbconvert.exporters.export import exporter_map
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
        from .exporters import *
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
        from .export import *
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/exporters/export.py", line 13, in <module>
        from .templateexporter import TemplateExporter
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 30, in <module>
        from IPython.nbconvert import filters
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
        from .markdown import *
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/filters/markdown.py", line 79, in <module>
        class MathBlockLexer(mistune.BlockLexer):
      File "/usr/local/lib/python3.4/site-packages/IPython/nbconvert/filters/markdown.py", line 80, in MathBlockLexer
        default_rules = ['block_math', 'latex_environment'] + mistune.BlockLexer.default_rules
    AttributeError: type object 'BlockLexer' has no attribute 'default_rules'

Whereas, using the notebook export menu item for pdf export, I get a `500 : Internal Server Error`, with no messages in the console.

For your reference, [here is the notebook I am attempting to export](https://gist.github.com/ae5f3469f3781f8604c4).

Running 3.0.0-dev on Python 3.4.2 on OS X 10.10.2.

**Comment by ellisonbg** [comment]
We will look at this before 3.0. Thanks.

**Comment by fonnesbeck** [comment]
Following #7369, installing mistune fixes the nbconvert to LaTeX issue, but exporting to pdf from the notebook still fails.

**Comment by takluyver** [comment]
You need to update mistune. See #7135.
