### ISSUE TITLE
ERROR:tornado.access:500 GET

### ISSUE THREAD

**Issue by demirpiton** [ipython/ipython#7536]
Hi,

When i enter "ipython notebook" command i recieve the error message below
How can i solve this problem i have no idea.

2015-01-22 18:36:16.816 [NotebookApp] Using existing profile dir: u'C:\\Users\\G\xfcn Bat\u0131m\u0131\\.ipython\\profile_default'
2015-01-22 18:36:16.841 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-01-22 18:36:16.915 [NotebookApp] Serving notebooks from local directory: C:\Users\Gün Batımı\Anaconda
2015-01-22 18:36:16.917 [NotebookApp] 0 active kernels
2015-01-22 18:36:16.917 [NotebookApp] The IPython Notebook is running at: http://localhost:8888/
2015-01-22 18:36:16.918 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
ERROR:tornado.application:Uncaught exception GET /static/style/style.min.css?v=7775081fa91df3822d16b2087bc2c8dd (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/static/style/style.min.css?v=7775081fa91df3822d16b2087
bc2c8dd', version='HTTP/1.1', remote_ip='::1', headers={'Connection': 'Keep-Alive', 'Accept-Language': 'tr-TR', 'Accept-Encoding': '
gzip, deflate', 'Referer': 'http://localhost:8888/tree', 'Host': 'localhost:8888', 'Accept': 'text/css, */*', 'User-Agent': 'Mozilla
/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko'})
Traceback (most recent call last):
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\tornado\web.py", line 1334, in _execute
    result = yield result
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\tornado\gen.py", line 628, in run
    value = future.result()
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\tornado\concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\tornado\gen.py", line 175, in wrapper
    yielded = next(result)
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\tornado\web.py", line 2108, in get
    absolute_path = self.get_absolute_path(self.root, self.path)
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 386, in get_absolute_path
    abspath = os.path.abspath(filefind(path, roots))
  File "C:\Users\G³n Bat²m²\Anaconda\lib\site-packages\IPython\utils\path.py", line 170, in filefind
    testname = expand_path(os.path.join(path, filename))
  File "C:\Users\G³n Bat²m²\Anaconda\lib\ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 8: ordinal not in range(128)
ERROR:tornado.access:{
  "Accept-Language": "tr-TR",
  "Accept-Encoding": "gzip, deflate",
  "Connection": "Keep-Alive",
  "Accept": "text/css, */*",
  "User-Agent": "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko",
  "Host": "localhost:8888",
  "Referer": "http://localhost:8888/tree"
}

**Comment by takluyver** [comment]
Are you using Python 2 or 3? If you're on Windows with a non-ascii username, please upgrade to Python 3; we've mostly stopped trying to fix these kinds of issues on Python 2.

**Comment by demirpiton** [comment]
Thanks, i use Python2

**Comment by takluyver** [comment]
OK, closing this as it's not going to get fixed with Python 2.

**Comment by demirpiton** [comment]
i installed Anaconda3. All problems solved. Thanks takluvyer.

**Comment by takluyver** [comment]
You're welcome, glad it's working again.

**Comment by demirpiton** [comment]
i’m glad to be here.






Kimden: Thomas Kluyver
Gönderme tarihi: ‎22‎ ‎Ocak‎ ‎2015‎ ‎Perşembe ‎22‎:‎11
Kime: ipython/ipython
Bilgi: Gün Batımı





You're welcome, glad it's working again.
