### ISSUE TITLE
IPython Crash

### ISSUE THREAD

**Issue by jonsariaatmadja** [ipython/ipython#7594]
Hi,

I've been using Anaconda's IPython Notebook for some time, but ever since I installed Kaspersky Internet Protection for my Mac it no longer works and comes up with the error:

```
Last login: Mon Jan 26 01:54:14 on ttys001

# user at user-MacBook-Air.local in ~ [2:19:39]
$ /Users/user/anaconda/bin/ipython_mac.command ; exit;
2015-01-26 02:19:40.128 [NotebookApp] Using existing profile dir: u'/Users/user/.ipython/profile_default'
2015-01-26 02:19:40.134 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/Users/user/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/Users/user/anaconda/lib/python2.7/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/user/anaconda/lib/python2.7/site-packages/tornado/netutil.py", line 106, in bind_sockets
    0, flags)):
gaierror: [Errno 8] nodename nor servname provided, or not known

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

I've uninstalled Kaspersky and reinstalled Anaconda and still come up with the same error. Help please.

Best,
Jon

**Comment by Carreau** [comment]
Can you:
 - show the content of `/Users/user/anaconda/bin/ipython_mac.command` (see if anaconda give some specific flag, but [I guess not](https://github.com/conda/conda-recipes/blob/master/ipython-notebook/ipython_mac.command))

Can you try:

 - getting rid of `~/.ipython/profile_default` (in case config is borked) 
 - Try running ipython command line dirrectly (`$ ipython notebook`) , potentially with `--debug` ?
 - pass ip flag  (`$ ipython notebook --ip=127.0.0.1`)
 - pass ip flag with localhost  (`$ ipython notebook --ip=localhost`)

**Comment by jonsariaatmadja** [comment]
Hi Matthias,

Here is the result of my ipython_mac.command:

Last login: Mon Jan 26 08:36:15 on ttys000
Jonathans-MacBook-Air:~ jonathansariaatmadja$ /Users/jonathansariaatmadja/anaconda/bin/ipython_mac.command ; exit;
2015-01-26 08:47:30.979 [NotebookApp] Using existing profile dir: u'/Users/jonathansariaatmadja/.ipython/profile_default'
2015-01-26 08:47:30.985 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/Users/jonathansariaatmadja/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/jonathansariaatmadja/anaconda/lib/python2.7/site-packages/tornado/netutil.py", line 106, in bind_sockets
    0, flags)):
gaierror: [Errno 8] nodename nor servname provided, or not known

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org<mailto:ipython-dev@scipy.org>

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

logout

[Process completed]

I will try the four next steps later today and revert back to you. Thanks for your help!

Best,
Jon
On Jan 26, 2015, at 2:38 AM, Matthias Bussonnier <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you:

  *   show the content of /Users/user/anaconda/bin/ipython_mac.command (see if anaconda give some specific flag, but I guess not<https://github.com/conda/conda-recipes/blob/master/ipython-notebook/ipython_mac.command>)

Can you try:

  *   getting rid of ~/.ipython/profile_default (in case config is borked)
  *   Try running ipython command line dirrectly ($ ipython notebook) , potentially with --debug ?
  *   pass ip flag ($ ipython notebook --ip=127.0.0.1)
  *   pass ip flag with localhost ($ ipython notebook --ip=localhost)

**Comment by Carreau** [comment]
Well I actually wanted to the content of the `/Users/user/anaconda/bin/ipython_mac.command` file, not its execution, as you already gave it ; Just to know with what command was IPython invocated.

**Comment by jonsariaatmadja** [comment]
Hi Mat,

I've tried the remaining steps and got it to work with

  *   pass ip flag ($ ipython notebook --ip=127.0.0.1)

Is there any problems using this command though? Since the URL is now http://127.0.0.1:8888/notebooks/ instead of localhost:8888.

Thanks,
Jon
On Jan 26, 2015, at 1:53 PM, Matthias Bussonnier <notifications@github.com<mailto:notifications@github.com>> wrote:


Well I actually wanted to the content of the /Users/user/anaconda/bin/ipython_mac.command file, not its execution, as you already gave it ; Just to know with what command was IPython invocated.

**Comment by Carreau** [comment]
No, there shouldn't be any problem. Strange that your computer does not resolve `localhost` to `127.0.0.1` it should be completely equivalent, but you don't have the only setup that have weird behavior. We did our best to accomodate most cases, but we always come up with configuratin with either localhost by default, or, 127.0.0.1 by default do not work...

In `~/.ipython/profile_default/ipython_notebook_config.py` you can add `c.NotebookApp.ip='127.0.0.1'`

It should already exists as `# c.NotebookApp.ip = 'localhost'`, just uncomment and change localhost to 127.0.0.1, and IPython should work without passing the flag.

**Comment by takluyver** [comment]
Sigh. So Sophos blocks websocket connections to 127.0.0.1, but allows them to the name `localhost`, and Kaspersky blocks localhost at some othe level but works with 127.0.0.1.

Aren't computers fun?

**Comment by Carreau** [comment]
`::1` man, `::1` once OSes start to support ipv6 :-)

**Comment by takluyver** [comment]
I thought ~all OSes have ipv6 support at this point? But Firefox doesn't appear to recognise `http://::1:8889/` as a URL.

**Comment by takluyver** [comment]
It appears you write it as `http://[::1]:8889/`, but still no joy.

**Comment by Carreau** [comment]
ipv6 literal should be enclosed by branckets, so would be `http://[::1]:8889/` I guess, but not sure for port number.

THe OS part was a joke.

**Comment by Carreau** [comment]
Seem to need a flag on chrome at least.

**Comment by takluyver** [comment]
It works on Firefox, but at least on Debian, there's a separate name `ip6-localhost` for localhost on ipv6, so the default server configuration is only listening on ipv4. Launching with `ipython notebook --ip=ip6-localhost` worked. Ubuntu and Mac appear to configure things so that `localhost` works over both ipv4 and ipv6.

**Comment by takluyver** [comment]
Anyway, closing this issue since we don't know of a proper fix (well, not one we can implement), and I think we've experienced more users running into problems with 127.0.0.1 than we have with localhost.

**Comment by jonsariaatmadja** [comment]
Funny that I can't seem to find the file ipython_notebook_config.py... maybe this is the problem after all?

Best,
J
On Jan 26, 2015, at 3:54 PM, Matthias Bussonnier <notifications@github.com<mailto:notifications@github.com>> wrote:


No, there shouldn't be any problem. Strange that your computer does not resolve localhost to 127.0.0.1 it should be completely equivalent, but you don't have the only setup that have weird behavior. We did our best to accomodate most cases, but we always come up with configuratin with either localhost by default, or, 127.0.0.1 by default do not work...

In ~/.ipython/profile_default/ipython_notebook_config.py you can add c.NotebookApp.ip='127.0.0.1'

It should already exists as # c.NotebookApp.ip = 'localhost', just uncomment and change localhost to 127.0.0.1, and IPython should work without passing the flag.

**Comment by takluyver** [comment]
No, that's not a problem - we don't create the config files unless you explicitly ask for them. `ipython profile create` should write them (with all the values commented out).
