### ISSUE TITLE
Bug report - Install IPython 2.4.0

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#7658]
Hi, 
I don't know this bug why was caused by, so I just want to report it after upgrading IPython:

C:\Windows\system32>pip install ipython -U
Collecting ipython from https://pypi.python.org/packages/2.7/i/ipython/ipython-2.4.0-py2-none-any.wh
l#md5=afb24ced30860ba8fe8d332255578de1
  Downloading ipython-2.4.0-py2-none-any.whl (2.8MB)
    100% |################################| 2.8MB 90kB/s eta 0:00:01
Requirement already up-to-date: pyreadline>=2.0 in c:\pyx\lib\site-packages (from ipython)
Installing collected packages: ipython
  Found existing installation: ipython 2.3.1
    Uninstalling ipython-2.3.1:
      Successfully uninstalled ipython-2.3.1

  Exception:
  Traceback (most recent call last):
    File "C:\PYX\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "C:\PYX\lib\site-packages\pip\commands\install.py", line 347, in run
      root=options.root_path,
    File "C:\PYX\lib\site-packages\pip\req\req_set.py", line 560, in install
      requirement.commit_uninstall()
    File "C:\PYX\lib\site-packages\pip\req\req_install.py", line 677, in commit_uninstall
      self.uninstalled.commit()
    File "C:\PYX\lib\site-packages\pip\req\req_uninstall.py", line 153, in commit
      rmtree(self.save_dir)
    File "C:\PYX\lib\site-packages\pip\utils\__init__.py", line 58, in rmtree
      onerror=rmtree_errorhandler)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "C:\PYX\lib\shutil.py", line 256, in rmtree
      onerror(os.rmdir, path, sys.exc_info())
    File "C:\PYX\lib\site-packages\pip\utils\__init__.py", line 70, in rmtree_errorhandler
      func(path)
  WindowsError: [Error 145] The directory is not empty: 'c:\\users\\myexpe~1\\appdata\\local\\temp\\
pip-87xgyd-uninstall\\pyx\\lib\\site-packages\\ipython\\nbconvert\\templates'

Thanks.

**Comment by minrk** [comment]
What files do you see still in that templates directory? It's unlikely that this is an IPython issue, since it's pip trying to remove files that presumably pip itself wrote. Did you perhaps add any nbconvert templates while using IPython?

**Comment by takluyver** [comment]
Sounds like a pip problem, to me. I don't see any problem going from 2.3.0 to 2.4.0 in a virtualenv on Linux.

**Comment by Carreau** [comment]
We are on IPython 4.0 now, and we haven't seen this issue since then, Closing, thanks.
