### ISSUE TITLE
Widget back-end to front-end flood causes front-end to back-end messages to mute.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython#7704]
I'm working on a notebook that illustrates the problem.

**Comment by jdfreder** [comment]
I'm debugging this now...

**Comment by jdfreder** [comment]
http://nbviewer.ipython.org/gist/jdfreder/7051ca96984863d13dd7 shows the bug.

**Comment by jdfreder** [comment]
Last hundred lines of the error that appears in the console:
```
ValueError: Invalid Signature: '<IDS|MSG>'
[C 12:39:14.172 NotebookApp] Malformed message: ['{"username":"jon","msg_type":"comm_msg","msg_id":"8c52a368-cf60-4e53-8fa1-ac7476a48bfa","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:14.170650"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"D08CC74CDFDA44D48EB1ACDA019DC304","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.3365256151038446},"method":"update"},"comm_id":"4f71fa2785b24a508dd8f7e2f3546aae"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:15.433 NotebookApp] Malformed message: ['comm-4f71fa2785b24a508dd8f7e2f3546aae', 'kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', '<IDS|MSG>', '<IDS|MSG>', '3197098343e836a96f355647b9507e711af343c795e143a28d2732710d6521c9', '{"username":"jon","msg_type":"comm_msg","msg_id":"29a49b1a-4604-423e-83dc-55c14a2f96c5","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.432514"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"EDAE27C762A142FF8E5BDC62CE5F300C","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.29149119968404813},"method":"update"},"comm_id":"4f71fa2785b24a508dd8f7e2f3546aae"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 828, in deserialize
        raise ValueError("Duplicate Signature: %r" % signature)
    ValueError: Duplicate Signature: '<IDS|MSG>'
[C 12:39:15.434 NotebookApp] Malformed message: ['17b686ee24802bacae7a74d10d9d491848822b0e593028c87bab6240d0279d7b', '{"username":"jon","msg_type":"status","msg_id":"9155037f-a913-481b-a567-16a04329290d","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.432870"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"23097AB0BF8F4A1E9AFD1E86C27DF62F","version":"5.0","msg_type":"comm_msg"}', '{}', '{"execution_state":"busy"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:15.726 NotebookApp] Malformed message: ['kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', '<IDS|MSG>', 'e043403e7da9911d25cd78e5ff52cd6d133d29155380373c2ecb8adc56280ae2', '{"username":"jon","msg_type":"status","msg_id":"7eca2dad-4817-4add-a275-54ca034a9396","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.725349"}', 'comm-a6809312543d4837b56001e5ea85a58b', '<IDS|MSG>', '8358b8d272953ad901aa42fac8e3ebbc5496fce964f0ab8b0e9e70e0ab39a00e', '{"username":"jon","msg_type":"comm_msg","msg_id":"1d4c04aa-ae39-4808-8fa1-73d03dad337e","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.725609"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"84FA65534F524014814ED3B52790D0D5","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.4589496027490575},"method":"update"},"comm_id":"a6809312543d4837b56001e5ea85a58b"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 832, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'e043403e7da9911d25cd78e5ff52cd6d133d29155380373c2ecb8adc56280ae2'
[C 12:39:15.728 NotebookApp] Malformed message: ['{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"84FA65534F524014814ED3B52790D0D5","version":"5.0","msg_type":"comm_msg"}', '{}', '{"execution_state":"busy"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:15.815 NotebookApp] Malformed message: ['comm-4f71fa2785b24a508dd8f7e2f3546aae', 'kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', '<IDS|MSG>', '<IDS|MSG>', 'ab6b6e1a0222b15fce43700deecf627ecbda7e4a0a6cb0e890eb71680926718d', 'b5e6d65a4e195a1fa3eb07e290681377014636cca724723fdab76c2f95eff241', '{"username":"jon","msg_type":"status","msg_id":"7f356d1a-f02b-4d50-a079-b7ee61cbd19b","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.814469"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"3396645B4DB0448FB43A23A7A8889DAF","version":"5.0","msg_type":"comm_msg"}', '{}', '{"execution_state":"busy"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 828, in deserialize
        raise ValueError("Duplicate Signature: %r" % signature)
    ValueError: Duplicate Signature: '<IDS|MSG>'
[C 12:39:15.815 NotebookApp] Malformed message: ['{"username":"jon","msg_type":"comm_msg","msg_id":"a7877b3c-19e1-4bc8-a9ed-4da69cd483bd","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.814211"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"BA32DD732222429B88410CD0F3CC4961","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.7069598272074822},"method":"update"},"comm_id":"4f71fa2785b24a508dd8f7e2f3546aae"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:15.817 NotebookApp] Malformed message: ['comm-e509321d3e1b4016a4975f1a6484cc37', '<IDS|MSG>', 'kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', '<IDS|MSG>', 'c20d839ca1cfc168004a1a833a66fee1d5406f0c33f35e5537206651aa69c981', '{"username":"jon","msg_type":"status","msg_id":"c0932063-2136-4c67-943a-32cd2717473d","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.817060"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"3396645B4DB0448FB43A23A7A8889DAF","version":"5.0","msg_type":"comm_msg"}', '{}', '{"execution_state":"idle"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 832, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status'
[C 12:39:15.818 NotebookApp] Malformed message: ['e484ab2a19b0518cc7cd933627fa2d6224481a36d8c1d1917de3a1e29a1e8e85', '{"username":"jon","msg_type":"comm_msg","msg_id":"8297c8b8-90ef-4f8d-9247-fc06d5a949c2","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:15.816087"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"3396645B4DB0448FB43A23A7A8889DAF","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.518205375124356},"method":"update"},"comm_id":"e509321d3e1b4016a4975f1a6484cc37"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:16.262 NotebookApp] Malformed message: ['kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', 'comm-a600727dfd204a52a98c1081a2b3309a', '<IDS|MSG>', '<IDS|MSG>', 'ff5850bb471ff2d429f91e66037c7bba2df69048e1a450d2c59c162b1085ccf3', '3eb30b99da95a319817646bfcf96eb63cc511af495571e4a0044dd1c9c863455', '{"username":"jon","msg_type":"comm_msg","msg_id":"332537bb-365f-459a-bdb3-71cc09f15798","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:16.262325"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"9B68CA5157904515B798E20A58A61189","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.28154363257418025},"method":"update"},"comm_id":"a600727dfd204a52a98c1081a2b3309a"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 828, in deserialize
        raise ValueError("Duplicate Signature: %r" % signature)
    ValueError: Duplicate Signature: '<IDS|MSG>'
[C 12:39:16.263 NotebookApp] Malformed message: ['{"username":"jon","msg_type":"status","msg_id":"15153f0c-9617-4fab-ac6e-023d9ec4be7d","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:16.261915"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"9B68CA5157904515B798E20A58A61189","version":"5.0","msg_type":"comm_msg"}', '{}', '{"execution_state":"idle"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
[C 12:39:36.042 NotebookApp] Malformed message: ['kernel.c3efc571-4ebf-4212-b65e-82a11c031e22.status', '<IDS|MSG>', 'f411fff8c5d5d982d6a6bf2b184f02468203e0f84ec6f04a8605a514a000d7a4', '{"username":"jon","msg_type":"status","msg_id":"f1fa3df3-660c-4e2d-96c9-eaadc6223c3b","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:36.041574"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"D1E70B4B1FC04A189F903D6B42A98718","version":"5.0","msg_type":"comm_msg"}', 'comm-e509321d3e1b4016a4975f1a6484cc37', '<IDS|MSG>', 'a3f1779a63e07cdddf5fea0ea72115d6c356dc1d70729bd1ad732471c3819b1a', '{"username":"jon","msg_type":"comm_msg","msg_id":"09aa19ab-1002-463e-89e0-f9debb7a8542","version":"5.0","session":"06a2d2c2-4f3b-4a0b-a9f2-8b39c257b25b","date":"2015-02-06T12:39:36.041857"}', '{"username":"username","session":"A723160B719E488689F3926228F2DA56","msg_id":"D1E70B4B1FC04A189F903D6B42A98718","version":"5.0","msg_type":"comm_msg"}', '{}', '{"data":{"state":{"value":0.6587747187902503},"method":"update"},"comm_id":"e509321d3e1b4016a4975f1a6484cc37"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 150, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 832, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'f411fff8c5d5d982d6a6bf2b184f02468203e0f84ec6f04a8605a514a000d7a4'
[C 12:39:36.043 NotebookApp] Malformed message: ['{}', '{"execution_state":"idle"}']
    Traceback (most recent call last):
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 166, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/jon/ipython/IPython/html/base/zmqhandlers.py", line 149, in _reserialize_reply
        idents, msg_list = self.session.feed_identities(msg_list)
      File "/Users/jon/ipython/IPython/kernel/zmq/session.py", line 756, in feed_identities
        idx = msg_list.index(DELIM)
    ValueError: '<IDS|MSG>' is not in list
```

**Comment by jdfreder** [comment]
Duplicate of #7411.
