### ISSUE TITLE
jinja2 failure during ipython nbconvert to HTML

### ISSUE THREAD

**Issue by deprecated** [ipython/ipython#7746]
One of my ipython notebooks triggers the following error when converting to HTML with `ipython nbconvert`: 
```
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 136, in <module>
    {%- if 'metadata' in output and 'width' in output.metadata.get('png', {}) %}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'get'
```
The offending file is [here](https://www.dropbox.com/s/zmfgx3sf3h479zz/Strong%20line%20ratios.ipynb?dl=0). 

My system info is:
```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '1c0eb68',
 'commit_source': 'installation',
 'default_encoding': 'US-ASCII',
 'ipython_path': '/Users/will/anaconda/lib/python3.3/site-packages/IPython',
 'ipython_version': '2.3.1',
 'os_name': 'posix',
 'platform': 'Darwin-14.1.0-x86_64-i386-64bit',
 'sys_executable': '/Users/will/anaconda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.3.5 |Anaconda 2.1.0 (x86_64)| (default, Sep  2 2014, 13:57:31) \n[GCC 4.2.1 (Apple Inc. build 5577)]'}
```
The full traceback is as follows: 
```
$ ipython nbconvert Strong\ line\ ratios.ipynb 
[NbConvertApp] Using existing profile dir: '/Users/will/.ipython/profile_default'
/Users/will/anaconda/lib/python3.3/importlib/_bootstrap.py:313: UserWarning: Module argparse was already imported from /Users/will/anaconda/lib/python3.3/argparse.py, but /Users/will/anaconda/lib/python3.3/site-packages is being added to sys.path
  return f(*args, **kwds)
[NbConvertApp] Converting notebook Strong line ratios.ipynb to html
[NbConvertApp] Support files will be in Strong line ratios_files/
[NbConvertApp] Loaded template full.tpl
Traceback (most recent call last):
  File "/Users/will/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/config/application.py", line 564, in launch_instance
    app.start()
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
    self.convert_notebooks()
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename
    return self.from_notebook_node(nbformat.read(f, 'json'), resources=resources, **kw)
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 215, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Users/will/anaconda/lib/python3.3/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/will/anaconda/lib/python3.3/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/will/anaconda/lib/python3.3/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 2, in <module>
    {% from 'mathjax.tpl' import mathjax %}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 1, in <module>
    {%- extends 'display_priority.tpl' -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in <module>
    {%- extends 'null.tpl' -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 26, in <module>
    {%- block body -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 63, in <module>
    {{ super() }}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 29, in <module>
    {%- block any_cell scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 31, in <module>
    {%- block codecell scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 6, in <module>
    {{ super() }}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 37, in <module>
    {%- block output_group -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 19, in <module>
    {{ super() }}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 39, in <module>
    {%- block outputs scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 41, in <module>
    {%- block output scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 59, in <module>
    {{ super() }}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 55, in <module>
    {%- block display_data scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line 56, in <module>
    {%- block data_priority scoped -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 92, in <module>
    {{ super() }}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 17, in <module>
    {%- block data_png -%}
  File "/Users/will/anaconda/lib/python3.3/site-packages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 136, in <module>
    {%- if 'metadata' in output and 'width' in output.metadata.get('png', {}) %}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'get'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

**Comment by takluyver** [comment]
Line 180 in the notebook: `"metadata": null,`. I'm pretty sure that should make the notebook invalid. Not sure how it got caused.

**Comment by deprecated** [comment]
Actually, the problem has resolved itself after I updated my conda environment from py33 to py34
```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'd87a8cd',
 'commit_source': 'installation',
 'default_encoding': 'US-ASCII',
 'ipython_path': '/Users/will/anaconda/envs/py34/lib/python3.4/site-packages/IPython',
 'ipython_version': '2.2.0',
 'os_name': 'posix',
 'platform': 'Darwin-14.1.0-x86_64-i386-64bit',
 'sys_executable': '/Users/will/anaconda/envs/py34/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.4.1 |Anaconda 2.1.0 (x86_64)| (default, Sep 10 2014, '
                '17:24:09) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}
```
The conversion now works fine, even though it is an older version of ipython.   So I'll close the issue since it seems to have just been a combination of particular versions of python and ipython, combined with some weirdness in my file.

**Comment by deprecated** [comment]
Ignore my last comment - that was a different file.  Changing to py34 made no difference.  But removing all the `"metadata" null` lines from the file did do the trick.  I've no idea how they got there - I haven't edited the file outside of the web interface.  Anyway, thanks very much for your help.

**Comment by takluyver** [comment]
Hmmm, but when I try converting it using IPython master, it fails again - different traceback, but probably the same issue.

How did you create this notebook? Was it in a stable version of IPython, a dev version, or some other notebook authoring tool? If there are invalid notebooks out there, we'd like to work out where they come from, and whether we need to handle them.

```
[NbConvertApp] ERROR | Notebook JSON is not valid v3: None is not of type 'object'

Failed validating 'type' in schema['properties']['metadata']:
    {'additionalProperties': True,
     'description': 'Cell output metadata.',
     'type': 'object'}

On instance['metadata']:
    None
Traceback (most recent call last):
  File "/home/takluyver/.local/bin/ipython", line 5, in <module>
    start_ipython()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 261, in start
    self.convert_notebooks()
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 300, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 153, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/__init__.py", line 133, in read
    return reads(fp.read(), as_version, **kwargs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/__init__.py", line 69, in reads
    nb = convert(nb, as_version)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/converter.py", line 46, in convert
    converted = convert_function(nb)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 56, in upgrade
    cells.append(upgrade_cell(cell))
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 92, in upgrade_cell
    cell.outputs = upgrade_outputs(cell.outputs)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 221, in upgrade_outputs
    return [upgrade_output(op) for op in outputs]
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 221, in <listcomp>
    return [upgrade_output(op) for op in outputs]
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 179, in upgrade_output
    to_mime_key(output.metadata)
  File "/home/takluyver/.local/lib/python3.4/site-packages/IPython/nbformat/v4/convert.py", line 145, in to_mime_key
    if alias in d:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by deprecated** [comment]
File was originally created in whatever was the default set of packages in the anaconda distribution of February 2014.  I've no idea how to reproduce that environment now

**Comment by takluyver** [comment]
OK, but it probably had a stable released version of IPython. @minrk , I wouldn't add support for this yet, but we should make a mental note of it - if we see more of this, we might need to handle it when reading v3 notebooks.

**Comment by deprecated** [comment]
I just resaved the notebook from my current environment and it seems fine (no instances of `null,` in the entire file).

**Comment by minrk** [comment]
Thanks, we'll keep an eye out for this in the future. We should consider including handling of this in the v3->v4 upgrade process. I'm not sure how it could be caused, though.
