### ISSUE TITLE
Issue with latest corrupt database. Cannot access or create any ipython notebooks.

### ISSUE THREAD

**Issue by erccarls** [ipython/ipython#7795]
Getting the attached error.  I am using the latest pull from github. Not sure what happened, but all of the sudden I could not access or create any ipynb's.  I have tried deleting the sqlite history as well as other notebook profiles.  Also tried reinstalling ipython (via pip). I have not been able to find anything via google that helps. 

Please advise.

[E 01:01:14.129 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/carlson/ipython/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/carlson/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/home/carlson/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/home/carlson/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 175, in wrapper
        yielded = next(result)
      File "/home/carlson/ipython/IPython/html/services/contents/handlers.py", line 126, in get
        path=path, type=type, format=format, content=content,
      File "/home/carlson/ipython/IPython/html/services/contents/filemanager.py", line 347, in get
        model = self._notebook_model(path, content=content)
      File "/home/carlson/ipython/IPython/html/services/contents/filemanager.py", line 307, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/home/carlson/ipython/IPython/html/services/contents/manager.py", line 444, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/home/carlson/ipython/IPython/nbformat/sign.py", line 222, in check_signature
        if self.db is None:
      File "/home/carlson/ipython/IPython/utils/traitlets.py", line 412, in __get__
        value = method()
      File "/home/carlson/ipython/IPython/nbformat/sign.py", line 129, in _db_default
        self.init_db(db)
      File "/home/carlson/ipython/IPython/nbformat/sign.py", line 141, in init_db
        )""")
    DatabaseError: database disk image is malformed
[E 01:01:14.131 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.8", 
      "Accept-Encoding": "gzip, deflate, sdch", 
      "Connection": "keep-alive", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36", 
      "Host": "***************:10000", 
      "X-Requested-With": "XMLHttpRequest", 
      "Cache-Control": "max-age=0", 
      "Referer": "***********************", 
    }
[E 01:01:14.131 NotebookApp] 500 GET /api/contents/Binning.ipynb?type=notebook&_=1424077272685 (67.180.133.234) 146.91ms referer=https://**************:10000/notebooks/Binning.ipynb

**Comment by erccarls** [comment]
Resolved by deleting .ipython/profile_default/security/nbsignatures.db

**Comment by takluyver** [comment]
We should possibly have some code to handle failures like this, as we
already do for the history database. A corrupted history database will be
renamed and a new one created automatically, with a warning printed. That
might work here too.
