### ISSUE TITLE
Unknown error with no read permissions

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#7848]
If you do not have read permission on a notebook (e.g., it has `-rw-------` and you are not the owner) and you try to open it, rather than saying permission denied, you get an error that implies there's something wrong with the notebook format:

![image](https://cloud.githubusercontent.com/assets/83444/6356023/53956f6e-bc0f-11e4-884b-aea89261a9e2.png)

In the notebook server, there is an unhandled permission denied traceback:

```
[E 11:09:31.650 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/jhamrick/project/tools/ipython/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/Users/jhamrick/project/tools/ipython/IPython/html/services/contents/handlers.py", line 126, in get
        path=path, type=type, format=format, content=content,
      File "/Users/jhamrick/project/tools/ipython/IPython/html/services/contents/filemanager.py", line 347, in get
        model = self._notebook_model(path, content=content)
      File "/Users/jhamrick/project/tools/ipython/IPython/html/services/contents/filemanager.py", line 306, in _notebook_model
        nb = self._read_notebook(os_path, as_version=4)
      File "/Users/jhamrick/project/tools/ipython/IPython/html/services/contents/fileio.py", line 104, in _read_notebook
        with self.open(os_path, 'r', encoding='utf-8') as f:
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/Users/jhamrick/project/tools/ipython/IPython/html/services/contents/fileio.py", line 49, in open
        with io.open(os_path, *args, **kwargs) as f:
    IOError: [Errno 13] Permission denied: '/Users/jhamrick/project/ipynb/Untitled9.ipynb'
```

Perhaps it would be possible to return a more informative generic error message, like just the last line of the traceback or something along those lines?

**Comment by minrk** [comment]
There already is a check for this to turn it into a better message, but it only checks for OSErrors, and I only tested it on Python 3, where IOError is a subclass of OSError. Should be fixed by #7852. I'll see if I can find a test that runs reliably that would catch this.
