### ISSUE TITLE
importing IPython.nbconvert.utils.pandoc imports whole nbconvert 

### ISSUE THREAD

**Issue by JanSchulz** [ipython/ipython#7859]
I'm trying to reuse the ipython wrapper for pandoc, but importing pandoc imports the whole of the nbconvert modules:

```python
Traceback (most recent call last):
  File "C:/data/external/knitpy/knitpy.py", line 251, in <module>
    print(main("testfiles\\hello.pymd"))
  File "C:/data/external/knitpy/knitpy.py", line 246, in main
    from IPython.nbconvert.utils.pandoc import pandoc
  File "c:\data\external\ipython\IPython\nbconvert\__init__.py", line 3, in <module>
    from .exporters import *
  File "c:\data\external\ipython\IPython\nbconvert\exporters\__init__.py", line 1, in <module>
    from .export import *
  File "c:\data\external\ipython\IPython\nbconvert\exporters\export.py", line 13, in <module>
    from .templateexporter import TemplateExporter
  File "c:\data\external\ipython\IPython\nbconvert\exporters\templateexporter.py", line 30, in <module>
    from IPython.nbconvert import filters
  File "c:\data\external\ipython\IPython\nbconvert\filters\__init__.py", line 6, in <module>
    from .markdown import *
  File "c:\data\external\ipython\IPython\nbconvert\filters\markdown.py", line 18, in <module>
    from pygments import highlight
ImportError: No module named pygments
```

I'm not sure if you even want to support such a code reuse, but if you want to allow it, it would be nice to do it in a way which does not import the whole nbconvert modules at the same time. :-)

This is master from a few days ago :-)

**Comment by minrk** [comment]
utils in nbconvert are only meant for use inside nbconvert, so I don't think there's any problem with the behavior here.

**Comment by mgaitan** [comment]
hey @JanSchulz . if you just want a pandoc wrapper you could try this package https://pypi.python.org/pypi/pypandoc/ .

**Comment by takluyver** [comment]
Closing as I don't think this kind of reuse is something we're aiming for at present.

**Comment by JanSchulz** [comment]
ok, fair enough, the pandoc wrapper looks small enough to copy or use pypandoc (@mgaitan: thanks!).

If this (reuse of nbconver.util.pandoc) is not something you support: do you support reusing `MultiKernelManager`, `KernelSpecManager`, `LoggingConfigurable` and `BaseIPythonApplication`?

I'm currently building a knitr/rmarkdown clone and I'm using IPython as a backed (-> kernels to execte the code in `pymarkdown` documents) and my main app is a `BaseIPythonApplication`.

**Comment by minrk** [comment]
> do you support reusing MultiKernelManager, KernelSpecManager, LoggingConfigurable and/or BaseIPythonApplication?

Yes, those are all public APIs except BaseIPythonApplication. I probably wouldn't use BaseIPythonApplication outside IPython. The more generic base class is `IPython.config.Application`.
