### ISSUE TITLE
nbconvert prompts 'ImportError: No module named 'mistune''

### ISSUE THREAD

**Issue by chrisalbon** [ipython/ipython#7936]
Using a conda installed ipython3 with a py3 instances, converting a notebook to html or markdown triggers a Server Error 500, "ImportError: No module named 'mistune'"

```
(py3k)Christophers-MacBook-Pro:code_py chrisralbon$ ipython nbconvert --to markdown pandas_selecting_rows_on_conditions.ipynb

Traceback (most recent call last):
  File "/Users/chrisralbon/anaconda/envs/py3k/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/config/application.py", line 402, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/exporters/export.py", line 13, in <module>
    from .templateexporter import TemplateExporter
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 30, in <module>
    from IPython.nbconvert import filters
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/nbconvert/filters/markdown.py", line 17, in <module>
    import mistune
ImportError: No module named 'mistune'
```

**Comment by takluyver** [comment]
Mistune is required for converting to HTML, but it shouldn't be necessary to convert to markdown. That's probably an oversight.

**Comment by nehalecky** [comment]
I hit the same error upon upgrading to 3.0 (via pip), and am able to reproduce when simply by calling from command line as:
```bash
$ ipython nbconvert
```
Produces traceback:

```python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin//ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 402, in initialize_subcommand
    subapp = import_item(subapp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/exporters/export.py", line 13, in <module>
    from .templateexporter import TemplateExporter
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 30, in <module>
    from IPython.nbconvert import filters
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/filters/markdown.py", line 17, in <module>
    import mistune
ImportError: No module named mistune
```

Installing mistune seems to have corrected the issue:
```bash
$ sudo pip install mistune
```

If there is anything else I can help with, please let me know. I much appreciate all the hard work! :bow:

**Comment by Carreau** [comment]
Yeah, but basically we import it unconditionally when importing filter. By the point where mistune is needed (to define filter that might be used in conversion) you are not even yet aware that you will only convert to markdown.

I'm not sure the effort of lazy-import is worth it.

**Comment by nehalecky** [comment]
@Carreau, thanks and I agree—it's not that important, and is easily remedied. I see now that mistune was added as a dependency between 2.4.1 and 3.0.0 in: 4173cdb48bf4dbfe63d67d172064f0d1980559b4.

Still, I don't understand why this wouldn't have been managed in the pip upgrade command?

```bash
$ sudo pip install -U ipython
```

Or does that not update dependency changes?

**Comment by minrk** [comment]
@nehalecky IPython has optional dependencies, via the setuptools `extras_require` facility. The package `ipython` doesn't depend on anything, but `ipython[notebook]` or `ipython[all]` can be used to pull in the optional dependencies that optional parts of IPython depend on.
