### ISSUE TITLE
Notebook doesn't start when invalid locale

### ISSUE THREAD

**Issue by GaelVaroquaux** [ipython/ipython#7975]
While teaching a workshop, a user had an invalid value as a locale. The user was a non technical user, an unable to understand what a locale was. I don't know how this problem appeared. But as a result the IPython notebook doesn't start (full traceback below).

The problem boils down to the fact that when locale environment variables contain invalid values, docutils.io does not import.

One way to avoid the problem would be to check for invalid values at the start of IPython notebook and override them as follows:
<pre>
import locale
try:
    locale.getdefaultlocale()
except ValueError:
    os.environ['LC_ALL'] = "C"
</pre>
This would fix the problem for these users who are currently unable to use the IPython notebook.

**Full traceback**
<pre>
10-4-204-92:~ katja$ ipython notebook

Traceback (most recent call last):

  File "/Users/katja/anaconda/bin/ipython", line 6, in <module>

    sys.exit(start_ipython())

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython

    return launch_new_instance(argv=argv, **kwargs)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance

    app.initialize(argv)

  File "<string>", line 2, in initialize

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error

    return method(app, *args, **kwargs)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize

    super(TerminalIPythonApp, self).initialize(argv)

  File "<string>", line 2, in initialize

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error

    return method(app, *args, **kwargs)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize

    self.parse_command_line(argv)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line

    return super(TerminalIPythonApp, self).parse_command_line(argv)

  File "<string>", line 2, in parse_command_line

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error

    return method(app, *args, **kwargs)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line

    return self.initialize_subcommand(subc, subargv)

  File "<string>", line 2, in initialize_subcommand

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error

    return method(app, *args, **kwargs)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 406, in initialize_subcommand

    subapp = import_item(subapp)

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item

    module = __import__(package, fromlist=[obj])

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 81, in <module>

    from IPython.consoleapp import IPythonConsoleApp

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/consoleapp.py", line 43, in <module>

    from IPython.kernel.zmq.kernelapp import (

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/kernelapp.py", line 54, in <module>

    from .ipkernel import Kernel

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/ipkernel.py", line 40, in <module>

    from .zmqshell import ZMQInteractiveShell

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/zmqshell.py", line 36, in <module>

    from IPython.core.payloadpage import install_payload_page

  File "/Users/katja/anaconda/lib/python2.7/site-packages/IPython/core/payloadpage.py", line 24, in <module>

    from docutils.core import publish_string

  File "/Users/katja/anaconda/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>

    from docutils import frontend, io, utils, readers, writers

  File "/Users/katja/anaconda/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>

    import docutils.utils

  File "/Users/katja/anaconda/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>

    import docutils.io

  File "/Users/katja/anaconda/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>

    from docutils.utils.error_reporting import locale_encoding, ErrorString,
ErrorOutput

  File "/Users/katja/anaconda/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>

    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]

  File "/Users/katja/anaconda/lib/python2.7/locale.py", line 543, in getdefaultlocale

    return _parse_localename(localename)

  File "/Users/katja/anaconda/lib/python2.7/locale.py", line 475, in _parse_localename

    raise ValueError, 'unknown locale: %s' % localename

ValueError: unknown locale: UTF-8
</pre>

**Comment by minrk** [comment]
Sorry this fell through the cracks. We no longer import docutils, and an invalid locale no longer seems to prevent launch.
