### ISSUE TITLE
ipython notebook stopped working

### ISSUE THREAD

**Issue by abell25** [ipython/ipython#8094]
Hi, I have been using ipython notebook without issue for a few months.  But since about a week ago as soon as I issue a command like 1+1 it just hangs.  Here is the console output from logging in, selecting a notebook, and executing 1+1:

tony@tony-M51AC:~/.ipython/profile_nbserver$ ipython notebook
2015-03-19 19:15:39.853 [NotebookApp] Using existing profile dir: u'/home/tony/.ipython/profile_default'
2015-03-19 19:15:39.859 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-03-19 19:15:39.866 [NotebookApp] Serving notebooks from local directory: /home/tony/code/python/notebooks
2015-03-19 19:15:39.866 [NotebookApp] 0 active kernels 
2015-03-19 19:15:39.866 [NotebookApp] The IPython Notebook is running at: https://127.0.0.1:53209/
2015-03-19 19:15:39.866 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
INFO:tornado.access:302 GET / (127.0.0.1) 1.27ms
INFO:tornado.access:302 POST /login?next=%2F (127.0.0.1) 3.65ms
2015-03-19 19:16:26.042 [NotebookApp] Saving notebook at /OttoGroup.ipynb
INFO:tornado.access:302 GET / (127.0.0.1) 0.78ms
2015-03-19 19:17:01.525 [NotebookApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 336, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 65, in post
    kernel_id = km.start_kernel(path=path)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/services/kernels/kernelmanager.py", line 90, in start_kernel
    kernel_id = super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/multikernelmanager.py", line 116, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py", line 219, in start_kernel
    self._connect_control_socket()
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py", line 179, in _connect_control_socket
    self._control_socket = self.connect_control()
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 552, in connect_control
    return self._create_connected_socket('control', identity=identity)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py", line 529, in _create_connected_socket
    sock.connect(url)
  File "socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4264)
ZMQError: Invalid argument
ERROR:tornado.access:{
  "Origin": "https://127.0.0.1:53209", 
  "Content-Length": "49", 
  "Accept-Language": "en-US,en;q=0.8", 
  "Accept-Encoding": "gzip, deflate", 
  "Connection": "keep-alive", 
  "Accept": "application/json, text/javascript, */*; q=0.01", 
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36", 
  "Host": "127.0.0.1:53209", 
  "X-Requested-With": "XMLHttpRequest", 
  "Cookie": "username-127-0-0-1-53209=\"2|1:0|10:1426810575|24:username-127-0-0-1-53209|48:MmViMTBkMWYtMjI2Ni00NGM5LTkzNmEtMTZjNjUxNjhjMTdi|4b190ce9b6859b933d2c7c941a52b47d147b50557e8333e7ca12a4143e7a7542\"", 
  "Referer": "https://127.0.0.1:53209/notebooks/OttoGroup.ipynb", 
  "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
}
ERROR:tornado.access:500 POST /api/sessions (127.0.0.1) 12.24ms referer=https://127.0.0.1:53209/notebooks/OttoGroup.ipynb
2015-03-19 19:19:02.048 [NotebookApp] Saving notebook at /OttoGroup.ipynb

**Comment by takluyver** [comment]
Can you stick a `print(url)` in `/home/tony/anaconda/lib/python2.7/site-packages/IPython/kernel/connect.py` just above line 529, and see what it's trying to connect to?

**Comment by abell25** [comment]
it printed this: tcp://:52453

**Comment by abell25** [comment]
I am wondering if some upgrades I had done recently could have caused this problem.  I had set up a ec2 instance with the same set-up (without the recent random ipython library upgrades) and it is still working fine.. Is there some way i can just do a fresh reinstall of everything?

**Comment by takluyver** [comment]
Is there anything in your config files? Try making a blank profile `ipython profile create foo` and running the notebook with it `ipython notebook --profile foo`.

@minrk , I followed this back a bit, and it looks like it's ending up in `IPython.utils.localinterfaces` - do you have an idea how it could go wrong?

**Comment by abell25** [comment]
`ipython profile create foo` also throws an exception:

tony@tony-M51AC:~$ ipython notebook --profile foo
2015-03-19 22:04:41.657 [NotebookApp] Using existing profile dir: u'/home/tony/.ipython/profile_foo'
2015-03-19 22:04:41.661 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/home/tony/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/home/tony/anaconda/lib/python2.7/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/tony/anaconda/lib/python2.7/site-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/home/tony/anaconda/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by minrk** [comment]
What do you get from `type ipython`? It doesn't make sense that `ipython profile create` would start the notebook.

**Comment by abell25** [comment]
typeing `type ipython` output:

ipython is hashed (/home/tony/anaconda/bin/ipython)

**Comment by abell25** [comment]
I just tried ipython profile create foo32 and it jenerated the default config files.
When I type `ipython notebook --profile foo32` it throw an error again:

tony@tony-M51AC:~/ec2$ ipython notebook --profile foo32
2015-03-20 20:23:40.155 [NotebookApp] Using existing profile dir: u'/home/tony/.ipython/profile_foo32'
2015-03-20 20:23:40.160 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/home/tony/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/home/tony/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/home/tony/anaconda/lib/python2.7/site-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/tony/anaconda/lib/python2.7/site-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/home/tony/anaconda/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

**Comment by Carreau** [comment]
Has this been resolved ?

**Comment by abell25** [comment]
I believe I re-installed my conda distribution and the problem went away.
