### ISSUE TITLE
Console crashes when interrupted during execution

### ISSUE THREAD

**Issue by cactaur** [ipython/ipython#8105]
After updating to IPython 3.0, there was a bug in IPython console where interruptions during execution cause the kernel and console to crash. A simple way of reproducing this bug is by running:

    $ ipython console
    In [1]: for i in range(1000000000):
        ...:      pass
        ...:

and then pressing Ctrl-C to interrupt. It results in:

    In [1]: for i in range(1000000000):
        ...:      pass
        ...:
    ^CTraceback (most recent call last):
      File "/usr/custom/Anaconda-2.0.1/bin/ipython", line 6, in <module>
        sys.exit(start_ipython())
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
        return launch_new_instance(argv=argv, **kwargs)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
        app.start()
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
        return self.subapp.start()
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 371, in start
        self.shell.mainloop()
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/console/interactiveshell.py", line 407, in mainloop
        self.interact(display_banner=display_banner)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/console/interactiveshell.py", line 568, in interact
        self.run_cell(source_raw)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/console/interactiveshell.py", line 168, in run_cell
        self.handle_input_request(msg_id, timeout=0.05)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/terminal/console/interactiveshell.py", line 373, in handle_input_request
        req = self.client.stdin_channel.get_msg(timeout=timeout)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython/kernel/blocking/channels.py", line 50, in get_msg
        ready = self.socket.poll(timeout)
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/zmq/sugar/socket.py", line 448, in poll
        evts = dict(p.poll(timeout))
      File "/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
      File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1586)
      File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2016)
        raise ZMQError(errno)
    ZMQError: Interrupted system call

    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org

    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.

    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        %config Application.verbose_crash=True

This does not seem to occur with the basic ipython without separate kernel support. When I attach an ipython console to an ipython notebook kernel, interruption only crashes the console while the notebook kernel remains active.

I am running IPython 3.0 through Anaconda on CentOS 6.6 and python 2.7. More system information is as follows:

    $ python -c "import IPython; print(IPython.sys_info())"
    {'commit_hash': u'f75fda4',
     'commit_source': 'installation',
     'default_encoding': 'UTF-8',
     'ipython_path': '/usr/custom/Anaconda-2.0.1/lib/python2.7/site-packages/IPython',
     'ipython_version': '3.0.0',
     'os_name': 'posix',
     'platform': 'Linux-2.6.32-504.8.1.el6.x86_64-x86_64-with-centos-6.6-Final',
     'sys_executable': '/usr/custom/Anaconda-2.0.1/bin/python',
     'sys_platform': 'linux2',
     'sys_version': '2.7.9 |Anaconda 2.0.1 (64-bit)| (default, Dec 15 2014, 10:33:51) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}

I hope that information is adequate! Thanks!

**Comment by takluyver** [comment]
#8108 fixes it for me, but I want to get clarification on whether the fix is in the best place.
