### ISSUE TITLE
`IPython` won't install from the repo

### ISSUE THREAD

**Issue by dabliss** [ipython/ipython#8157]
Hi all,

When trying to install `IPython` from the Git repo (the tip of the master branch), I get the following error:

    $ sudo python setup.py install
    running install
    running build
    running build_py
    running jsversion
    running css
    rebuilding css and sourcemaps failed (not a problem)
    invoke is required to rebuild css (pip install invoke)
    checking package data
    Traceback (most recent call last):
      File "setup.py", line 342, in <module>
        main()
      File "setup.py", line 339, in main
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/daniel/ipython/setupbase.py", line 757, in run
        command.run(self)
      File "/home/daniel/ipython/setupbase.py", line 233, in run
        check_package_data(self.package_data)
      File "/home/daniel/ipython/setupbase.py", line 223, in check_package_data
        assert os.path.exists(path), "Missing package data: %s" % path
    AssertionError: Missing package data: IPython/html/static/components/backbone/backbone-min.js

See also my [post on StackOverflow](http://stackoverflow.com/questions/29286152/ipython-unreadable-notebook-unsupported-json-nbformat-version-4-supported-ver) regarding another installation problem.

**Comment by takluyver** [comment]
That looks like you haven't pulled in the git submodules. But we're in the middle of reorganising code, so this isn't a very good time to install from master.

**Comment by Carreau** [comment]
Clone with the --recursive flag, or `python setup.py submodule` to set up the submodules. You should then probably checkout the 3.x branch.
