### ISSUE TITLE
IPython cannot be started

### ISSUE THREAD

**Issue by beojan** [ipython/ipython#8182]
IPython from git cannot be started:

`ipython notebook` gives the output

```
/usr/local/lib/python3.4/dist-packages/IPython/kernel/__init__.py:10: UserWarning: The `IPython.kernel` package has been deprecated. You should import from ipython_kernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated. "
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/local/lib/python3.4/dist-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 574, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 306, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 385, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 301, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 474, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 405, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/notebookapp.py", line 62, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/kernels/kernelmanager.py", line 14, in <module>
    from IPython.kernel.multikernelmanager import MultiKernelManager
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/__init__.py", line 27, in <module>
    from ipython_kernel import comm, inprocess
ImportError: No module named 'ipython_kernel'
```

**Comment by Carreau** [comment]
As we announce a few day back on the mailing list, twitter and other places, don't use master for the next few weeks, we are splitting it in many repo.

**Comment by rsmith31415** [comment]
@Carreau 

I had to recreate a virtual environment yesterday using master to test a pull request. It is working okay, but now I wonder what I should do given your warning.

**Comment by minrk** [comment]
Editable installs (`pip install -e`) still work just fine, because the split packages are in the repo directory, and thus still on sys.path. What won't work are regular installs (`pip install` or `python setup.py install`), which copy IPython into site-packages, but won't copy the nascent sibling packages.

**Comment by rsmith31415** [comment]
@minrk Excellent. Great work.

**Comment by Carreau** [comment]
You can also checkout an older commit or the 3.x branch.

**Comment by rsmith31415** [comment]
@Carreau As long as master is working for editable installs, I think that's good enough. I think the problem was that I ran something like `git fetch origin pull/#id/head:pr-something` after very drastic changes were made and then the environment didn't work at all.

**Comment by beojan** [comment]
In that case, can you add a message to that effect in large text at the top
of README.md?

Sincerely,
Beojan Stanislaus
