### ISSUE TITLE
[Test Report Only] Does anyone know what error caused in this IPTEST?

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8197]
Hi all,

I've just installed new python 3.4.3 into my computer and some dependencies to use with IPython. I tested it and here is the result:

```
C:\Python3\Scripts>iptest

Test group: kernel
.........................S..............................................K.K.S.....S.S........................SS......
----------------------------------------------------------------------
Ran 117 tests in 27.332s

OK (KNOWNFAIL=2, SKIP=6)

Test group: kernel.inprocess
........
----------------------------------------------------------------------
Ran 8 tests in 4.511s

OK

Test group: config
...............................................................................
----------------------------------------------------------------------
Ran 79 tests in 0.141s

OK

Test group: core
...................................................K................S...................................................
........................................................................................................................
...........S................S.....................SSSS.
KeyboardInterrupt
...SS..........................................S.S............S........SSSSSS...........................................
............SS....S........................Out[11]: True
..........S.........K......SS...........
----------------------------------------------------------------------
Ran 498 tests in 23.071s

OK (KNOWNFAIL=2, SKIP=24)

Test group: extensions
...
----------------------------------------------------------------------
Ran 3 tests in 0.031s

OK

Test group: lib
...............................Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\loader.py", line 252, in generate
    for test in g():
  File "C:\Python3\lib\site-packages\IPython\testing\decorators.py", line 230, in skipper_gen
    raise nose.SkipTest(get_msg(f,msg))
unittest.case.SkipTest: Skipping test: test_latex_to_png_dvipng_runs. This test runs only if command 'latex' is installe
d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 210, in run
    self.setUp()
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 271, in setUp
    if not self:
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 86, in __bool__
    test = next(self.test_generator)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\loader.py", line 262, in generate
    address=test_address(generator))
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\failure.py", line 22, in __init__
    log.debug("A failure! %s %s %s", exc_class, exc_val, format_tb(tb))
  File "C:\Python3\lib\traceback.py", line 93, in format_tb
    return format_list(extract_tb(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 106, in extract_tb
    return list(_extract_tb_iter(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "C:\Python3\lib\linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Python3\lib\tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "C:\Python3\lib\unittest\result.py", line 184, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb)
  File "C:\Python3\lib\traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "C:\Python3\lib\traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "C:\Python3\lib\traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "C:\Python3\lib\linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Python3\lib\tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 190, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err)
TypeError: _exc_info_to_string() missing 1 required positional argument: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python3\lib\site-packages\IPython\testing\iptest.py", line 515, in run_iptest
    TestProgram(argv=argv, addplugins=plugins)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 121, in __init__
    **extra_args)
  File "C:\Python3\lib\unittest\main.py", line 93, in __init__
    self.runTests()
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 62, in run
    test(result)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 215, in run
    result.addError(self, self._exc_info())
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 64, in addError
    exc_info = self._exc_info_to_string(err)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "C:\Python3\lib\unittest\result.py", line 179, in _exc_info_to_string
    if exctype is test.failureException:
AttributeError: 'NoneType' object has no attribute 'failureException'

Test group: terminal
..S........SSSSS....
----------------------------------------------------------------------
Ran 20 tests in 4.797s

OK (SKIP=6)

Test group: testing
....................S...S.....................S...
----------------------------------------------------------------------
Ran 50 tests in 6.446s

OK (SKIP=3)

Test group: utils
................................................................................................S.......................
......SS.SS.S....................S.........SS......S........S..S..S.....................................................
........................................................S.................S.............................................
.........................
----------------------------------------------------------------------
Ran 385 tests in 3.208s

OK (SKIP=15)

Test group: nbformat
C:\Python3\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
.................................................................................................C:\Python3\lib\site-pac
kages\IPython\nbformat\validator.py:147: UserWarning: No schema for validating v2 notebooks
  warnings.warn("No schema for validating v%s notebooks" % version, UserWarning)
........................
----------------------------------------------------------------------
Ran 121 tests in 1.985s

OK

Test group: qt
................
----------------------------------------------------------------------
Ran 16 tests in 1.256s

OK

Test group: html
:0: FutureWarning: IPython widgets are experimental and may change in the future.
SSSSSS...................................C:\Python3\lib\site-packages\IPython\nbformat\validator.py:147: UserWarning: No
 schema for validating v2 notebooks
  warnings.warn("No schema for validating v%s notebooks" % version, UserWarning)
....................S.S...S..........................................................................←[2K
----------------------------------------------------------------------
Ran 194 tests in 32.932s

OK (SKIP=11)

Test group: nbconvert
S........SS...SS.SSSSSSS.SSSSSSSS..SSC:\Python3\lib\site-packages\IPython\nbformat\validator.py:147: UserWarning: No sch
ema for validating v2 notebooks
  warnings.warn("No schema for validating v%s notebooks" % version, UserWarning)
...SS.SSS..SS.SSSS...SS.SSSS.......S.................................SSSS.................................S....SS.......
......SS.......S.SS
----------------------------------------------------------------------
Ran 176 tests in 41.167s

OK (SKIP=52)

Test group: autoreload
...
----------------------------------------------------------------------
Ran 3 tests in 7.046s

OK

Test group: parallel ----------------------------------------- NOT RUN
______________________________________________________________________
Test suite completed for system with the following information:
IPython version: 3.0.0
IPython commit : f75fda4 (installation)
IPython package: C:\Python3\lib\site-packages\IPython
Python version : 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
sys.executable : C:\Python3\python.exe
Platform       : Windows-8-6.2.9200

Tools and libraries available at test time:
   jinja2 jsonschema matplotlib mistune numpy pygments pymongo qt requests sphinx sqlite3 tornado zmq

Tools and libraries NOT available at test time:
   casperjs curses pexpect phantomjs slimerjs terminado

Status: ERROR - 1 out of 14 test groups failed (lib). Took 204.753s.

You may wish to rerun these, with:
  iptest lib


C:\Python3\Scripts>iptest lib

Test group: lib
...............................Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\loader.py", line 252, in generate
    for test in g():
  File "C:\Python3\lib\site-packages\IPython\testing\decorators.py", line 230, in skipper_gen
    raise nose.SkipTest(get_msg(f,msg))
unittest.case.SkipTest: Skipping test: test_latex_to_png_dvipng_runs. This test runs only if command 'latex' is installe
d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 210, in run
    self.setUp()
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 271, in setUp
    if not self:
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 86, in __bool__
    test = next(self.test_generator)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\loader.py", line 262, in generate
    address=test_address(generator))
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\failure.py", line 22, in __init__
    log.debug("A failure! %s %s %s", exc_class, exc_val, format_tb(tb))
  File "C:\Python3\lib\traceback.py", line 93, in format_tb
    return format_list(extract_tb(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 106, in extract_tb
    return list(_extract_tb_iter(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "C:\Python3\lib\linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Python3\lib\tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "C:\Python3\lib\unittest\result.py", line 184, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb)
  File "C:\Python3\lib\traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "C:\Python3\lib\traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "C:\Python3\lib\traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "C:\Python3\lib\traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "C:\Python3\lib\linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "C:\Python3\lib\linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Python3\lib\tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 190, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err)
TypeError: _exc_info_to_string() missing 1 required positional argument: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python3\lib\site-packages\IPython\testing\iptest.py", line 515, in run_iptest
    TestProgram(argv=argv, addplugins=plugins)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 121, in __init__
    **extra_args)
  File "C:\Python3\lib\unittest\main.py", line 93, in __init__
    self.runTests()
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\core.py", line 62, in run
    test(result)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 225, in run
    test(orig)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\suite.py", line 215, in run
    result.addError(self, self._exc_info())
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 64, in addError
    exc_info = self._exc_info_to_string(err)
  File "C:\Python3\lib\site-packages\nose-1.3.4-py3.4.egg\nose\result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "C:\Python3\lib\unittest\result.py", line 179, in _exc_info_to_string
    if exctype is test.failureException:
AttributeError: 'NoneType' object has no attribute 'failureException'

______________________________________________________________________
Test suite completed for system with the following information:
IPython version: 3.0.0
IPython commit : f75fda4 (installation)
IPython package: C:\Python3\lib\site-packages\IPython
Python version : 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
sys.executable : C:\Python3\python.exe
Platform       : Windows-8-6.2.9200

Tools and libraries available at test time:
   jinja2 jsonschema matplotlib mistune numpy pygments pymongo qt requests sphinx sqlite3 tornado zmq

Tools and libraries NOT available at test time:
   casperjs curses pexpect phantomjs slimerjs terminado

Status: ERROR - 1 out of 1 test groups failed (lib). Took 3.694s.

You may wish to rerun these, with:
  iptest lib


C:\Python3\Scripts>_

```

Is this error critical, does it affect IPython functionality?

Kind regards

Trung Nguyen

**Comment by takluyver** [comment]
Yes, I do - Python 3.4.3 made a small change to the tokenize module which caused some problems for us. I filed [an issue](http://bugs.python.org/issue23615) and it should be fixed when 3.4.4 comes out. So far we've only heard of the error occurring when running the tests, not in actual use, so we're not especially concerned about fixing it.

**Comment by brannerchinese** [comment]
Are we speaking about the error

    open() takes 1 positional argument but 2 were given

? I've encountered it while following https://github.com/jakevdp/sklearn_pycon2015, as soon as matplotlib is first called within a notebook.

**Comment by takluyver** [comment]
Yep, that's the one. *sigh*

I'm at PyCon, I'll try to get an estimate of when 3.4.4 might be out.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
