### ISSUE TITLE
TemplateNotFound error when extending builtin LaTeX template

### ISSUE THREAD

**Issue by flying-sheep** [ipython/ipython#8198]
```console
$ ipython nbconvert test.ipynb --to=latex --template=with_bib.tplx
```

fails:

```pytb
[NbConvertApp] Using existing profile dir: '~/.ipython/profile_default'
[NbConvertApp] Converting notebook diffusionmap.ipynb to latex
[NbConvertApp] Support files will be in diffusionmap_files/
[NbConvertApp] Loaded template with_bib.tplx
Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/usr/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/usr/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 261, in start
    self.convert_notebooks()
  File "/usr/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 300, in convert_notebooks
    output, resources = exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 153, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/nbconvert/exporters/latex.py", line 96, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3.4/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 214, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "./with_bib.tplx", line 1, in <module>
    ((*- extends 'latex/article.tplx' -*))
jinja2.exceptions.TemplateNotFound: latex/article.tplx
```

whereas `with_bib.tplx` contains:

```jinja
((*- extends 'latex/article.tplx' -*))

((* block bibliography *))
\bibliographystyle{unsrt}
\bibliography{bibliography}
((* endblock bibliography *))
```

and

```python
from IPython.nbconvert import TemplateExporter
'latex/article.tplx' in TemplateExporter().environment.loader.list_templates()
```

is `True`

**Comment by Carreau** [comment]
Can you just try `((*- extends 'article.tplx' -*))` ? Extending `'latex/article.tplx'` might try to actually load `latex/latex/article.tplx`

**Comment by flying-sheep** [comment]
this works, thanks!

AFAIK the docs don’t say that, though.
