### ISSUE TITLE
jupyter_client tries to import module parentpoller, actually in ipython_kernel

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#8201]
This is Big Split related. Traceback looks like this:

```
Traceback (most recent call last):
  File "c:\jenkins\workspace\windows-py3.4\IPython\html\base\handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "c:\jenkins\workspace\windows-py3.4\IPython\html\services\kernels\handlers.py", line 41, in post
    kernel_id = km.start_kernel(kernel_name=model['name'])
  File "c:\jenkins\workspace\windows-py3.4\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "c:\jenkins\workspace\windows-py3.4\jupyter_client\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\jenkins\workspace\windows-py3.4\jupyter_client\manager.py", line 240, in start_kernel
    **kw)
  File "c:\jenkins\workspace\windows-py3.4\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\jenkins\workspace\windows-py3.4\jupyter_client\launcher.py", line 178, in launch_kernel
    from jupyter_client.parentpoller import ParentPollerWindows
ImportError: No module named 'jupyter_client.parentpoller'
```

The module `parentpoller` is part of `ipython_kernel`.

**Comment by minrk** [comment]
:+1: I was just about to start working on splitting some of the entangling of client and kernel.
