### ISSUE TITLE
Upgrade to IPython resulted in all notebooks reporting error.

### ISSUE THREAD

**Issue by rcoridan** [ipython/ipython#8294]
I updated my IPython Notebook to the latest version and now none of my notebooks open.  I get the same error report for each one.  They all worked with the previous version of IPython Notebook (v. 3.0?)

"An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details."

[Update] It doesn't allow any notebooks to be created, not just opening old versions. 
Error message: "Unexpected error while saving file: Untitled.ipynb database disk image is malformed"

As it worked before the upgrade, and doesn't now, I'm not sure what the issue could be other than with the installation itself.

Server Log:
[E 09:03:40.129 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 407, in __get__
        value = obj._trait_values[self.name]
    KeyError: 'db'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/html/services/contents/handlers.py", line 126, in get
        path=path, type=type, format=format, content=content,
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/html/services/contents/filemanager.py", line 347, in get
        model = self._notebook_model(path, content=content)
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/html/services/contents/filemanager.py", line 307, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/html/services/contents/manager.py", line 447, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/nbformat/sign.py", line 221, in check_signature
        if self.db is None:
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 412, in __get__
        value = method()
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/nbformat/sign.py", line 128, in _db_default
        self.init_db(db)
      File "/Users/coridan/anaconda/lib/python3.4/site-packages/IPython/nbformat/sign.py", line 140, in init_db
        )""")
    sqlite3.DatabaseError: database disk image is malformed
[E 09:03:40.155 NotebookApp] {
      "Host": "localhost:8889",
      "Cookie": "org.cups.sid=92f07a9aeb014a91d90debd430509cee",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.8",
      "X-Requested-With": "XMLHttpRequest",
      "Accept-Encoding": "gzip, deflate, sdch",
      "Referer": "http://localhost:8889/notebooks/Untitled0.ipynb",
      "Accept": "application/json, text/javascript, */*; q=0.01"
    }
[E 09:03:40.156 NotebookApp] 500 GET /api/contents/Untitled0.ipynb?type=notebook&_=1428595418718 (::1) 98.51ms referer=http://localhost:8889/notebooks/Untitled0.ipynb

**Comment by rcoridan** [comment]
I found this earlier report of a similar problem: https://github.com/ipython/ipython/issues/2097/

However, moving the history.sqlite file did not correct my issue as it did for the referenced report.

**Comment by takluyver** [comment]
Different database - try moving `~/.ipython/profile_default/security/nbsignatures.db`.

**Comment by rcoridan** [comment]
Thanks for the response.  This worked to fix my issue.  Thanks!

**Comment by BarnetteME1** [comment]
Moving this `~/.ipython/profile_default/security/nbsignatures.db` file did not solve my problems. I actually found it in '~/Library/Jupyter/nbsignatures.db`. This solved the problem for me.

**Comment by starsk62** [comment]
I have the same problem...

![untitled](https://cloud.githubusercontent.com/assets/4258792/12063116/66391a10-afa9-11e5-8f74-7c1b1e827f1b.jpg)
