### ISSUE TITLE
Can't open a terminal

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8309]
In some situations on my Jupyterhub deployment, I can't open a terminal page. It tries to go to that page, but it doesn't open it so just comes right back to the dashboard with a flicker. When this happens I see the following traceback:

```
[E 2015-04-12 09:57:29.921 localuser handlers:374] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python3.4/dist-packages/IPython/html/terminal/api_handlers.py", line 18, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "/usr/local/lib/python3.4/dist-packages/terminado/management.py", line 304, in new_named_terminal
        term = self.new_terminal()
      File "/usr/local/lib/python3.4/dist-packages/terminado/management.py", line 161, in new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
      File "/usr/local/lib/python3.4/dist-packages/ptyprocess/ptyprocess.py", line 203, in spawn
        'executable: %s.' % command)
    FileNotFoundError: The command was not found or was not executable: .
[E 2015-04-12 09:57:29.922 localuser log:46] {
      "Referer": "https://dirac1.calpoly.edu/user/localuser/tree/home/localuser",
      "X-Forwarded-Port": "80",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "0",
      "Host": "dirac1.calpoly.edu",
      "Connection": "close",
      "X-Real-Ip": "129.65.101.140",
      "X-Nginx-Proxy": "true",
      "X-Forwarded-For": "129.65.101.140,129.65.23.43",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Cookie": "I have removed this content...",
      "X-Forwarded-Proto": "http",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.8,gl;q=0.6,sq;q=0.4",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
      "Origin": "https://dirac1.calpoly.edu"
    }
```

**Comment by minrk** [comment]
That looks like the command it's trying to run is an empty string, which is rightly failing. Can you tell what the value `$SHELL` is?

By the way, you can stop opening notebook issues on ipython/ipython, the new repo is up: https://github.com/jupyter/jupyter_notebook

**Comment by ellisonbg** [comment]
Opened as: https://github.com/jupyter/jupyter_notebook/issues/4
