### ISSUE TITLE
[IPython3] dont work, crashed

### ISSUE THREAD

**Issue by 230v** [ipython/ipython#8337]
```
➜  ~  ipython3 %debug
Traceback (most recent call last):
  File "/usr/bin/ipython3", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 320, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/core/application.py", line 375, in initialize
    self.init_profile_dir()
  File "/usr/lib/python3.4/site-packages/IPython/core/application.py", line 282, in init_profile_dir
    p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 230, in find_profile_dir_by_name
    return cls(location=profile_dir, config=config)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 86, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 565, in __init__
    setattr(self, key, value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 445, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 602, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 68, in _location_changed
    self.check_dirs()
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 159, in check_dirs
    self.check_static_dir()
  File "/usr/lib/python3.4/site-packages/IPython/core/profiledir.py", line 144, in check_static_dir
    from IPython.html import DEFAULT_STATIC_FILES_PATH
ImportError: No module named 'IPython.html'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

**Comment by minrk** [comment]
How did you install IPython?

**Comment by keithwoj** [comment]
Installed IPython on Linux Mint 17.1 Cinnamon using the instructions given in http://ipython.org/ipython-doc/stable/install/install.html.

(1) git clone  --recursive https://github.com/ipython/ipython.git
(2) cd ipython
(3) sudo python setup.py install

Then tried running an IPython notebook or IPython or iptest and received the following message each time:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 47, in <module>
    from .core.application import Application
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named traitlets.config.application

Any help is appreciated!

**Comment by minrk** [comment]
For running from master right now, while the dependencies have not yet been released, you will need to install with:

    pip install -e . -r requirements.txt

**Comment by keithwoj** [comment]
Thanks minrk, I had tried "pip install -e" but did not add the flag with the requirements.txt. It works now at the command line and I can use it.

**Comment by minrk** [comment]
It's a temporary measure while we haven't yet released the dependencies. It won't be necessary anymore once they are out, hopefully in a few weeks time.

**Comment by vvagias** [comment]
@minrk  You rock! Thanks for the tip it worked and I'm up and running. I never would have guessed to run pip like that. Learned something new :)

**Comment by naught101** [comment]
Hrm, has this changed recently? I just tried it, and I'm getting:

```{python}
In [9]: from traitlets.config.application import Application, catch_config_error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/naught101/miniconda3/envs/science/lib/python3.4/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-9-6a9731af4b98> in <module>()
----> 1 from traitlets.config.application import Application, catch_config_error

ImportError: No module named 'traitlets.config'; 'traitlets' is not a package
```

I used `pip install --upgrade -e . -r requirements.txt`, which succeeded. `requirements.txt` contains:

```
-e git+https://github.com/ipython/traitlets.git#egg=traitlets
```

and after importing the module I get:

```{python}
In [12]: print(dir(traitlets))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__warningregistry__', 'absolute_import', 'warn']
```

**Comment by mahdiiix** [comment]
I installed ipython3 with apt-get and when I running that on bash it gives me :
`Traceback (most recent call last):
  File "/usr/bin/ipython3", line 4, in <module>
    from IPython import start_ipython
ImportError: No module named 'IPython'
`
