### ISSUE TITLE
pager horizontal split freezes the qtconsole

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8344]
IPython QtConsole 3.0.0
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by takluyver** [comment]
It doesn't freeze for me on master, but I do see a traceback:

```
Traceback (most recent call last):
  File "/home/takluyver/.local/lib/python3.4/site-packages/jupyter_qtconsole/console/mainwindow.py", line 531, in <lambda>
    triggered=lambda: self.set_paging_active_frontend('hsplit'))
  File "/home/takluyver/.local/lib/python3.4/site-packages/jupyter_qtconsole/console/mainwindow.py", line 788, in set_paging_active_frontend
    self.active_frontend._set_paging(paging)
  File "/home/takluyver/.local/lib/python3.4/site-packages/jupyter_qtconsole/console/console_widget.py", line 1969, in _set_paging
    --paging=vsplit is used.""")
NotImplementedError: can only switch if --paging=hsplit or
                    --paging=vsplit is used.
```

**Comment by Carreau** [comment]
Hi, 

The qtconsole has been moved to https://github.com/jupyter/qtconsole, and this issue had no activity for quite some time. If this is still relevant I would suggest this issue to be reopen on the above cited repository. 

This will allow us to keep the number of IPython issues smaller and focussed on IPython. As currently there is an extremely high number of opened issues , it make it really hard to find if a problem is actually known, or going to be worked one. 

Feel free to reopen if need, for the time being I'm going to close this. 

Thanks.
