### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'current'

### ISSUE THREAD

**Issue by jorgehatccrma** [ipython/ipython#8374]
I'm attempting to start an `ipython notebook` in a remote server, inside a virtual environment, but I get the following error:

```shell
$ ipython notebook -no-browser --port=8000 --ip=0.0.0.0 --log-level=DEBUG

[D 11:33:42.180 NotebookApp] Config changed:
[D 11:33:42.180 NotebookApp] {'NotebookApp': {'ip': u'0.0.0.0', 'log_level': u'DEBUG', 'port': 8000, 'open_browser': False}}
[D 11:33:42.181 NotebookApp] IPYTHONDIR set to: /user/j/jorgeh/.ipython
[D 11:33:42.181 NotebookApp] Using existing profile dir: u'/user/j/jorgeh/.ipython/profile_default'
[D 11:33:42.182 NotebookApp] Searching path [u'/user/j/jorgeh/research/vEnv2', u'/user/j/jorgeh/.ipython/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[D 11:33:42.182 NotebookApp] Attempting to load config file: ipython_config.py
VIRTUAL_ENV -> /user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages
[D 11:33:42.184 NotebookApp] Loaded config file: /user/j/jorgeh/.ipython/profile_default/ipython_config.py
[D 11:33:42.184 NotebookApp] Attempting to load config file: ipython_notebook_config.py
[D 11:33:42.185 NotebookApp] Loaded config file: /user/j/jorgeh/.ipython/profile_default/ipython_notebook_config.py
[D 11:33:42.186 NotebookApp] Config changed:
[D 11:33:42.186 NotebookApp] {'NotebookApp': {'ip': u'0.0.0.0', 'verbose_crash': True, 'log_level': u'DEBUG', 'port': 8000, 'open_browser': False}}
[D 11:33:42.189 NotebookApp] searching for local mathjax in [u'/user/j/jorgeh/.ipython/nbextensions', '/user/j/jorgeh/research/vEnv2/share/jupyter/nbextensions', '/usr/local/share/jupyter/nbextensions', '/usr/share/jupyter/nbextensions']
[D 11:33:42.190 NotebookApp] searching for local mathjax in [u'/user/j/jorgeh/.ipython/profile_default/static', '/user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages/IPython/html/static']
[I 11:33:42.190 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[W 11:33:42.224 NotebookApp] Terminals not available (error was No module named terminado)
[I 11:33:42.224 NotebookApp] Serving notebooks from local directory: /user/j/jorgeh/research/vEnv2
[I 11:33:42.224 NotebookApp] 0 active kernels
[I 11:33:42.224 NotebookApp] The IPython Notebook is running at: http://0.0.0.0:8000/
[I 11:33:42.224 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/user/j/jorgeh/research/vEnv2/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/user/j/jorgeh/research/vEnv2/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 1092, in start
    self.io_loop = ioloop.IOLoop.current()
AttributeError: type object 'IOLoop' has no attribute 'current'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

I've read #7689, and updated relevant packages, but no luck so far. Unlike in that issue, in my case I don't need/have `ipython-sql`

This is the output of `pip freeze` (the list was too long, so I left what I assume was interesting, but let me know if you need more info):

```shell
AGTk==3.2
apicaro==1.0
astroid==1.2.1
async==0.6.1
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
Bajjer==0.2.5
Beaker==1.5.4
BeautifulSoup==3.2.1
beautifulsoup4==4.3.2
blivet==0.23.9
boto==2.34.0
Brlapi==0.6.0
bunch==1.0.1
bzr==2.6.0
CairoSVG==0.5
certifi==14.5.14
chardet==2.0.1
Cheetah==2.4.4
common==1.2
configobj==4.7.2
cssselect==0.9.1
cupshelpers==1.0
Cython==0.21.1
decorator==3.4.0
DecoratorTools==1.8
di==0.3
dispatcher==1.0
Django==1.6.10
dropbox==1.6
duplicity==0.6.25
ecdsa==0.11
egenix-mx-base==3.2.5
empy==3.3.2
ethtool==0.9
fail2ban==0.9.0
fedpkg==1.19
fedup==0.9.0
feedparser==5.1.3
Flask==0.10.1
fontforge==1.0
fonttools==2.4
foolscap==0.6.4
fpconst==0.7.3
fros==1.0
Genshi==0.7
gitdb==0.5.4
GitPython==0.3.2rc1
glusterfs-api==3.5.3
GnuPGInterface==0.3.2
gps==3.9
gresistor==0.0.1
gwebsockets==0.3
html5lib==0.999
httplib2==0.7.7
iniparse==0.4
initial-setup==0.3.10.1
ipaddr==2.1.10
IPy==0.75
ipython==3.1.0
itsdangerous==0.23
iwlib==1.2
javapackages==1.0.0
Jinja2==2.7.3
jsonschema==2.4.0
kitchen==1.1.1
kiwi==1.9.38
langtable==0.0.27
lockfile==0.9.1
logilab-common==0.62.1
lxml==3.3.6
M2Crypto==0.21.1
Magic-file-extensions==0.2
Mako==1.0.0
Markdown==2.3.1
MarkupSafe==0.18
matplotlib==1.3.1
mercurial==2.8.1
mglob==0.4
mwclient==0.7.1
myhdl==0.8.1
nose==1.3.0
ntplib==0.3.1
Numeric==24.2
numexpr==2.2.2
numpy==1.8.2
offtrac==0.1.0
oggconvert==0.3.3
openpyxl==1.7.0
ordereddict==1.1
packagedb-cli==2.8.1
pandas==0.10.0
papyon==0.5.6
paramiko==1.15.1
Paste==1.7.5.1
pdfshuffler==0.6.0
pexpect==3.1
Pillow==2.2.1
policycoreutils-default-encoding==0.1
pretty==0.1
Printrun==2014.1.26
protobuf==2.5.0
PsychoPy==1.80.1
pyalsa==1.0.26
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycups==1.9.65
pycurl==7.19.3
pygame===1.9.1release
pyglet==1.2a1
Pygments==1.6
pygobject==3.10.2
pygpgme==0.3
pyinotify==0.9.4
pykickstart==1.99.48
pyliblo==0.9.1
pyliblzma==0.5.3
pylint==1.3.1
PyOpenGL==3.1.0b2
pyOpenSSL==0.13.1
PyPAM==0.5.0
pyparsing==2.0.3
pyparted==3.9
pyPdf==1.13
pyserial==2.7
pysmbc==1.0.13
python-augeas==0.5.0
python-bugzilla==1.2.0
python-cloudfiles==1.7.10
python-dateutil==1.5
python-fedora==0.3.36
python-ldap==2.4.17
python-linux-procfs==0.4.6
python-meh==0.27
python-nss==0.16.0
python-xlib==0.15rc1
pytz===2012d
pyusb==1.0.0a3
pyxattr==0.5.1
pyxdg==0.25
pyzmq==13.0.2
regex==2015.3.18
reportlab==3.1.8
requests==1.2.3
rpkg==1.28
rpm-python==4.11.3
rsa==3.1.1
scdate==1.10.7
schedutils==0.4
scipy==0.12.1
scservices==0.111.1
scservices.dbus==0.111.1
seobject==0.1
sepolicy==1.1
setroubleshoot==1.1
simplegeneric==0.8
simplejson==3.5.3
six==1.9.0
slip==0.6.0
slip.dbus==0.6.0
slip.gtk==0.6.0
smmap==0.8.1
SOAPpy==0.11.6
spambayes==1.1b1
SSSDConfig==1.11.7
stevedore==0.12
tables==3.0.0
Tempita==0.5.1
tepache==1.2
tornado==4.1
tuna==0.11.1
Twisted-Core==12.2.0
Twisted-Web==12.2.0
uniconvertor==2.0
Unidecode==0.4.16
urlgrabber==3.10.1
urllib3==1.8.2
virtualenv==12.0.7
virtualenv-clone==0.2.4
virtualenvcontext==0.1.6
virtualenvwrapper==4.3.1
Werkzeug==0.9.4
wxPython==2.8.12.0
wxPython-common==2.8.12.0
xgflib==1.0
yum-langpacks==0.4.5
yum-metadata-parser==1.1.4
zope.event==4.0.3
zope.interface==4.1.1
ZSI==2.1a1
```

**Comment by takluyver** [comment]
@minrk suggested upgrading pyzmq and seeing if that helps.

**Comment by jorgehatccrma** [comment]
_Short answer:_

I solved my problem by creating a new `virtualenv` only with the minimum essential packages.

_Longer answer:_

The `virtualenv` I was working on originally was created with the `--system-site-packages` option. For some reason, when trying to update `pyzmq` it would download version 14, but it would keep using the previous version. 

As mentioned before, I created a new `virtualenv` with the default `--no-site-packages` option, and then installed `ipython` and the required dependencies only. By doing that I was able to run the notebook server. Btw, the `pyzmq` version installed this was was `14.6.0`, so probably @minrk was right.

Thanks!

**Comment by imsrgadich** [comment]
yes, @minrk was right. It does help upgrading pyzmq.

**Comment by SteliosStefanatos** [comment]
Just wanted to report I got the same issue after doing `conda update --all` today. The update involved 3-4 packages, including `tornado` which was updated to ver. `5.0` from ver. `4.5.3`. After downgrading to `4.5.3`, Jupyter opened as normal.

**Comment by Jorge-S** [comment]
Want to chime in that downgrading `tornado` from version `5.0 `to ver `4.5.3` like @SteliosStefanatos did made Jupyter work as normal.

**Comment by mayest** [comment]
Same issue immediately after updating to tornado version 5.0. Solved by using the suggestion by @minrk to update pyzmq. No need to downgrade tornado.

**Comment by hungrybear88** [comment]
run 
conda install  tornado=4.5.3

**Comment by AIGyan** [comment]
I found the solution from https://github.com/jupyter/notebook/issues/3407
