### ISSUE TITLE
Error starting up IPython with SublimeREPL

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8379]
Hi, 

I've set path to python folder and start IPython via SublimeREPL>Python>IPython...
However, the start-up was failed and here is the error:

```
WARNING: Unexpected error discovering local network interfaces: unknown encoding: idna
Traceback (most recent call last):
  File "C:\MyProggies\Sublime\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 52, in <module>
    embedded_shell.initialize()
  File "<string>", line 2, in initialize
  File "C:\Python3\lib\site-packages\IPython\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python3\lib\site-packages\IPython\terminal\ipapp.py", line 332, in initialize
    self.init_shell()
  File "C:\Python3\lib\site-packages\IPython\terminal\console\app.py", line 107, in init_shell
    IPythonConsoleApp.initialize(self)
  File "C:\Python3\lib\site-packages\IPython\consoleapp.py", line 342, in initialize
    self.init_kernel_manager()
  File "C:\Python3\lib\site-packages\IPython\consoleapp.py", line 298, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "C:\Python3\lib\site-packages\IPython\kernel\manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "C:\Python3\lib\site-packages\IPython\kernel\connect.py", line 492, in write_connection_file
    signature_scheme=self.session.signature_scheme,
  File "C:\Python3\lib\site-packages\IPython\kernel\connect.py", line 104, in write_connection_file
    sock.bind(('', 0))
LookupError: unknown encoding: idna

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True


***Repl Closed***WARNING: Unexpected error discovering local network interfaces: unknown encoding: idna
Traceback (most recent call last):
  File "C:\MyProggies\Sublime\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 52, in <module>
    embedded_shell.initialize()
  File "<string>", line 2, in initialize
  File "C:\Python3\lib\site-packages\IPython\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python3\lib\site-packages\IPython\terminal\ipapp.py", line 332, in initialize
    self.init_shell()
  File "C:\Python3\lib\site-packages\IPython\terminal\console\app.py", line 107, in init_shell
    IPythonConsoleApp.initialize(self)
  File "C:\Python3\lib\site-packages\IPython\consoleapp.py", line 342, in initialize
    self.init_kernel_manager()
  File "C:\Python3\lib\site-packages\IPython\consoleapp.py", line 298, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "C:\Python3\lib\site-packages\IPython\kernel\manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "C:\Python3\lib\site-packages\IPython\kernel\connect.py", line 492, in write_connection_file
    signature_scheme=self.session.signature_scheme,
  File "C:\Python3\lib\site-packages\IPython\kernel\connect.py", line 104, in write_connection_file
    sock.bind(('', 0))
LookupError: unknown encoding: idna

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True


***Repl Closed***


```

I have no idea what caused the problem.

Thank you

Kind regards

Steven

**Comment by koenvb** [comment]
Googling around a bit gives me that this could be related to some python path problem?

* Does ipython works properly when using the command line so not using the sublime REPL?
  * What is the version of ipython in your Sublime REPL?
  * What is the version of ipython in your normal terminal window?

Eg. On mac os if I use the SublimeREPL it falls back to the Apple python version.
If I use ipython in my terminal I get the Anaconda python version.

So I assume you will have to setup some settings for SublimeREPL so it takes
the correct python interpreter.

Some hint maybe:

http://stackoverflow.com/questions/20861176/how-do-i-setup-sublimerepl-with-anacondas-interpreter

**Comment by duytrung** [comment]
hi Koenvb,

There is no problem with starting via commandline or via qt GUI. It worked fine. 

I did not setup anything from sublimeREPL, just install from package installer.

I've updated to the latest ipython via anaconda "conda" package manager. Let me try the instruction for awhile. Thank you in advanced. 

Kind regards

Steven

**Comment by koenvb** [comment]
As mentioned in https://github.com/ipython/ipython/issues/8381 I would advise to also check the SublimeREPL project git to get some help as it seems more linked to the combination of sublime and ipython. Not really an ipython issue

**Comment by takluyver** [comment]
Closing as it seems unlikely to be an IPython bug. Feel free to use comments for troubleshooting.
