### ISSUE TITLE
Notebook Checkpointing failed after playing with file permissions

### ISSUE THREAD

**Issue by koenvb** [ipython/ipython#8380]
```
The version of the notebook server is 3.1.0-cbccb68 and is running on:
Python 2.7.9 |Anaconda 2.1.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
[GCC 4.2.1 (Apple Inc. build 5577)]
```

While researching about this issue https://github.com/ipython/ipython/issues/8368
I managed to get my notebook in a state where the checkpointing function fails.

Looking in the console I find this:

```
[E 14:22:58.388 NotebookApp] 500 POST /api/contents/dev/ipython_learn/test.ipynb/checkpoints (::1) 2.43ms referer=http://localhost:8888/notebooks/dev/ipython_learn/test.ipynb
[I 14:24:21.552 NotebookApp] Saving file at /dev/ipython_learn/test.ipynb
[E 14:24:22.342 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "//anaconda/lib/python2.7/site-packages/IPython/html/services/contents/handlers.py", line 280, in post
        checkpoint = yield gen.maybe_future(cm.create_checkpoint(path))
      File "//anaconda/lib/python2.7/site-packages/IPython/html/services/contents/manager.py", line 459, in create_checkpoint
        return self.checkpoints.create_checkpoint(self, path)
      File "//anaconda/lib/python2.7/site-packages/IPython/html/services/contents/filecheckpoints.py", line 55, in create_checkpoint
        self._copy(src_path, dest_path)
      File "//anaconda/lib/python2.7/site-packages/IPython/html/services/contents/fileio.py", line 81, in _copy
        shutil.copyfile(src, dest)
      File "//anaconda/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 13] Permission denied: u'/Users/koen/dev/ipython_learn/.ipynb_checkpoints/test-checkpoint.ipynb'
```

This seems to be related to the new saving mechanism mentioned in
- https://github.com/ipython/ipython/issues/8323
- https://github.com/ipython/ipython/issues/8322

**Comment by takluyver** [comment]
I don't think this is related to atomic save - it looks like it's failing to copy the checkpoint.

**Comment by koenvb** [comment]
Any idea why this would happen? 
Would be good to tell the user then that the notebook content does not get saved at all...
There is no mention of read only so user could assume that everything is kind of ok?

Only way to fix it is to copy the notebook into a new one and use that one.

**Comment by takluyver** [comment]
I imagine that it would happen if you made the `.ipynb_checkpoints/` directory, or the relevant checkpoint file within that, read only, but it was still able to write to the regular file.  In that case, I think it should actually save OK - even if the UI reports that it's failing, the failure should be after it has saved to the regular file.

If that is what's happened, I think it can only come about if the user has deliberately messed with those permissions, so I don't think it's something we need to worry about too much.
