### ISSUE TITLE
cannot start qtconsole on osx

### ISSUE THREAD

**Issue by lixiangalwh** [ipython/ipython#8384]
when i type "ipython qtconsole", i got the following error:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 409, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/qtconsoleapp.py", line 360, in initialize
    self.init_qt_elements()
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/qtconsoleapp.py", line 265, in init_qt_elements
    local_kernel=local_kernel)
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/rich_ipython_widget.py", line 39, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/ipython_widget.py", line 118, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/frontend_widget.py", line 169, in __init__
    self._highlighter = FrontendHighlighter(self, lexer=self.lexer)
  File "/usr/local/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 412, in __get__
    value = method()
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/frontend_widget.py", line 125, in _lexer_default
    return lexer_class()
  File "/usr/local/lib/python2.7/site-packages/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/usr/local/lib/python2.7/site-packages/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/usr/local/lib/python2.7/site-packages/pygments/lexer.py", line 504, in _process_state
    token = cls._process_token(tdef[1])
  File "/usr/local/lib/python2.7/site-packages/pygments/lexer.py", line 433, in _process_token
    'token type must be simple type or callable, not %r' % (token,)
AssertionError: token type must be simple type or callable, not Token.Literal.String

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

any help is appreciated. or tell me how to get more information about this error.

**Comment by minrk** [comment]
what platform and IPython version? Do you have any config? What pygments version?

**Comment by lixiangalwh** [comment]
Python 2.7.9 (default, Apr 26 2015, 07:13:39) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython
>>> IPython.__version__
'3.1.0'
>>> import pygments
>>> pygments.__version__
'2.0.2'

OS: OS X 10.9.5

i don't have any config.

but i once tried to setup pyqt in virtualenvwrapper.  i just create a link of pyqt to the virtual environment.  I don't know whether this would affect.
