### ISSUE TITLE
WARNING: Readline services not available or not loade

### ISSUE THREAD

**Issue by zhoufank** [ipython/ipython#8385]
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 52, in <module>
    embedded_shell.initialize()
  File "<string>", line 2, in initialize
  File "D:\Python27\lib\site-packages\IPython\config\application.py", line 75, in catch_config_error
    return method(app, _args, *_kwargs)
  File "D:\Python27\lib\site-packages\IPython\terminal\ipapp.py", line 332, in initialize
    self.init_shell()
  File "D:\Python27\lib\site-packages\IPython\terminal\console\app.py", line 114, in init_shell
    client=self.kernel_client,
  File "D:\Python27\lib\site-packages\IPython\config\configurable.py", line 337, in instance
    inst = cls(_args, *_kwargs)
  File "D:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 524, in **init**
    self.init_completer()
  File "D:\Python27\lib\site-packages\IPython\terminal\console\interactiveshell.py", line 129, in init_completer
    self.Completer = ZMQCompleter(self, self.client, config=self.config)
  File "D:\Python27\lib\site-packages\IPython\terminal\console\completer.py", line 37, in **init**
    self.readline.set_completer_delims('\r\n')
AttributeError: 'module' object has no attribute 'set_completer_delims'

**Comment by koenvb** [comment]
Does ipython works properly when using the command line so not using the sublime REPL?
What is the version of ipython in your Sublime REPL?
What is the version of ipython in your normal terminal window?
Eg. On mac os if I use the SublimeREPL it falls back to the Apple python version.
If I use ipython in my terminal I get the Anaconda python version.

So I assume you will have to setup some settings for SublimeREPL so it takes
the correct python interpreter.

Some hint maybe:

http://stackoverflow.com/questions/20861176/how-do-i-setup-sublimerepl-with-anacondas-interpreter

**Comment by takluyver** [comment]
What is `self.readline` if you stick a print statement in before the error?

**Comment by Carreau** [comment]
Closing as IPython does not use readline anymore. 

Thanks!
