### ISSUE TITLE
ipython notebook run forever with long input or output in code cell

### ISSUE THREAD

**Issue by andycjw** [ipython/ipython#8412]
the cell will run without output, if the code cell is given a big input or output, e.g.

```
for i in xrange(100000): 
   print i
```

or paste a long string with with len > 100000, and it'll run forever

and this is the output from interrrupt

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/IPython/kernel/zmq/ipkernel.py", line 181, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2801, in run_cell
    cell = self.input_transformer_manager.transform_cell(raw_cell)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/inputsplitter.py", line 597, in transform_cell
    self.push(cell)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/inputsplitter.py", line 641, in push
    out = self.push_line(line)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/inputsplitter.py", line 664, in push_line
    line = transformer.push(line)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/inputtransformer.py", line 92, in push
    return self.func(line)

  File "/usr/local/lib/python2.7/dist-packages/IPython/core/inputtransformer.py", line 350, in help_end
    m = _help_end_re.search(line)

KeyboardInterrupt

below is version info:

The version of the notebook server is 3.1.0-cbccb68 and is running on:
Python 2.7.2 (default, Jun 12 2011, 14:24:46) [MSC v.1500 64 bit (AMD64)]

Current Kernel Information:

Python 2.7.2 (default, Jun 12 2011, 14:24:46) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

**Comment by Carreau** [comment]
Closing as JupyterLab should handle long output better, and because there is not more we can do on IPython side about this. 

Thanks !
