### ISSUE TITLE
IOError / Disconnect when connecting to remote kernel via ssh

### ISSUE THREAD

**Issue by schober-ch** [ipython/ipython#8486]
Hi,

I encountered an issue when connecting to a ipython kernel (from a running ipython qtconsole) on a server via ssh (as in: https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh):

Connecting works fine first, but if some commands with a left parenthesis "(" is entered, the connection is closed. The full traceback is at the end of my post. Example:
```python
data = np.array([1,1,1]) # works
len(data) # fails
```
After the disconnect it is possible to reconnect and continue from the point before the command.

I googled a bit and found a recent open issue on the same problem in the spyder-ide, but I think it might be better adressed here (https://github.com/spyder-ide/spyder/issues/2429). The server is a Debian Jessie, the client a Arch Linux, resulting in somehow different ipython versions (see below). Could this be the reason? As Jessie just got released, this version of ipython will be quite common for a while. 

I quickly tried to get a dev checkout of ipython running in a virtualenv on the server, but then I got some import errors even after pip installing the dependencies (from traitlets.config.application import Application, catch_config_error ImportError: No module named config.application). If a test with the most recent version would help, I can try to fix that, but most likely not before Monday.
 
Python version info client:
```
{'commit_hash': u'cbccb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.0.4-2-ARCH-x86_64-with-glibc2.2.5',
 'sys_executable': '/usr/bin/python2',
 'sys_platform': 'linux2',
 'sys_version': '2.7.9 (default, Dec 11 2014, 04:42:00) \n[GCC 4.9.2]'}

python2-tornado 4.1.0-2
```

Python version info server:
```
{'commit_hash': 'be0cc2b',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python2.7/dist-packages/IPython',
 'ipython_version': '2.3.0',
 'os_name': 'posix',
 'platform': 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.0',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.8 (default, Oct 18 2014, 12:50:18) \n[GCC 4.9.1]'}

python-tornado 3.2.2-1.1
```

Full traceback on client:
```pytb
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/threaded.py", line 88, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 852, in deserialize
    return adapt(message)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 367, in adapt
    return adapter(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 70, in __call__
    return handler(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 295, in inspect_reply
    new_content['name'] = content['oname']
KeyError: 'oname'
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/threaded.py", line 88, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 852, in deserialize
    return adapt(message)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 367, in adapt
    return adapter(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 70, in __call__
    return handler(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 295, in inspect_reply
    new_content['name'] = content['oname']
KeyError: 'oname'
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 840, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/threaded.py", line 88, in _handle_recv
    msg = self.session.deserialize(smsg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 852, in deserialize
    return adapt(message)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 367, in adapt
    return adapter(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 70, in __call__
    return handler(msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 295, in inspect_reply
    new_content['name'] = content['oname']
KeyError: 'oname'
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f43106e5f70>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 568, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/threaded.py", line 79, in thread_send
    self.session.send(self.stream, msg)
  File "/usr/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 664, in send
    stream.send_multipart(to_send, copy=copy)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 256, in send_multipart
    self.on_send(callback)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 222, in on_send
    self._check_closed()
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _check_closed
    raise IOError("Stream is closed")
IOError: Stream is closed
```

**Comment by Carreau** [comment]
This seem to have been fix [9 days ago](https://github.com/ipython/ipython/commit/c1630c47ba8a879ae6ce6a913bb4326ff28108fc#diff-a86465ab2465a39b55ccd493b33ae9f2) you just want to try the branch 3.x instead of master. Master now have IPtyhon splitted in ~10 repos.

**Comment by Carreau** [comment]
Assuming this is fixed. Closing, feel free to reopen.
