### ISSUE TITLE
Unicode decode error when pressing Tab+Shift for tooltip in ipython notebook 3.1

### ISSUE THREAD

**Issue by mmagnuski** [ipython/ipython#8543]
Hey,
I am getting unicode decode error when asking for tooltip (`Tab` + `Shift`).
I am on windows 8 and yes - I have non-ascii characters in my username AND python 2.7.
I understand that you prefer to answer to this kind of reports by urging users to move to python 3, but in my case the tooltip works when I first open the notebook, only then, some time later, stops working.

The error shows in console, not in the notebook, so although I've had the problem for some time only recently have I noticed the error. It says:
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "D:\Python\Anaconda\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Python\Anaconda\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 420, in inspect_request
    content.get('detail_level', 0))
  File "D:\Python\Anaconda\lib\site-packages\IPython\kernel\zmq\ipkernel.py", line 253, in do_inspect
    info = self.shell.object_inspect(name)
  File "D:\Python\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 1585, in object_inspect
    detail_level=detail_level
  File "D:\Python\Anaconda\lib\site-packages\IPython\core\oinspect.py", line 749, in info
    out['file'] = compress_user(fname)
  File "D:\Python\Anaconda\lib\site-packages\IPython\utils\path.py", line 88, in compress_user
    if path.startswith(home):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 13: ordinal not in range(128)
```

**Comment by takluyver** [comment]
Sorry, but I am going to urge you to move to Python 3 ;-). If it's an intermittent failure, that makes it all the more difficult to debug.

**Comment by mmagnuski** [comment]
Well, ok, probably it's high time I moved to python 3. I've had enough Unicode Adventures. :smile:

**Comment by takluyver** [comment]
Cool, good luck!
