### ISSUE TITLE
Exception while starting local engines in parallel cluster

### ISSUE THREAD

**Issue by peter-ch** [ipython/ipython#8611]
I have a parallel cluster config with 3 SSH nodes, one of which is localhost. The cluster starts if I don't use localhost to start engines on it, but if I include it, I get this:

```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fadb10f6488>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/apps/ipclusterapp.py", line 332, in start_engines
    self.engine_launcher.start(self.n)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/apps/launcher.py", line 779, in start
    d = el.start(user=user, hostname=host)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/apps/launcher.py", line 634, in start
    self.send_files()
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/apps/launcher.py", line 602, in send_files
    self._send_file(local_file, remote_file)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/apps/launcher.py", line 592, in _send_file
    [self.location, 'mkdir', '-p', '--', remote_dir]
  File "/usr/lib/python3.4/subprocess.py", line 616, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['ssh', '-tt', 'localhost', 'mkdir', '-p', '--', '.ipython/profile_cluster1/security']' returned non-zero exit status 255
```

**Comment by peter-ch** [comment]
It wasn't a problem in IPython, forget it.
