### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by dbl001** [ipython/ipython#8621]
Does anyone know why I might be getting this error:

SSL: WRONG_VERSION_NUMBER

David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ ipython --version
3.2.0

David-Laxers-MacBook-Pro:pycon-pandas-tutorial davidlaxer$ conda --version
conda 3.14.1
David-Laxers-MacBook-Pro:pycon-pandas-tutorial davidlaxer$ python --version
Python 2.7.10 :: Anaconda 2.3.0 (x86_64)
D

David-Laxers-MacBook-Pro:~ davidlaxer$ ipython notebook --profile=nbserver
[I 19:08:00.252 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 19:08:00.317 NotebookApp] Serving notebooks from local directory: /Users/davidlaxer
[I 19:08:00.317 NotebookApp] 0 active kernels 
[I 19:08:00.317 NotebookApp] The IPython Notebook is running at: https://127.0.0.1:9999/
[I 19:08:00.317 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:08:25.637 NotebookApp] Writing notebook-signing key to /Users/davidlaxer/.ipython/profile_nbserver/security/notebook_secret
[W 19:08:25.645 NotebookApp] Notebook pycon-pandas-tutorial/Exercises-1.ipynb is not trusted
[I 19:08:27.843 NotebookApp] Kernel started: d34339cc-4141-49f9-aa53-1ba050f2dc5d
[I 19:10:27.956 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[W 19:10:27.960 NotebookApp] Saving untrusted notebook pycon-pandas-tutorial/Exercises-1.ipynb
[I 22:02:42.201 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[I 22:04:45.950 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb

[W 22:08:36.100 NotebookApp] Notebook pycon-pandas-tutorial/Exercises-2.ipynb is not trusted
[I 22:08:37.503 NotebookApp] Kernel started: fb7d4b59-fcf4-4cfe-8190-739ef1928337
[I 22:08:43.914 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-2.ipynb
[I 22:17:20.994 NotebookApp] Using existing profile dir: u'/Users/davidlaxer/.ipython/profile_nbserver'
[I 22:17:29.264 NotebookApp] Using existing profile dir: u'/Users/davidlaxer/.ipython/profile_default'
[I 22:18:03.976 NotebookApp] Kernel shutdown: d34339cc-4141-49f9-aa53-1ba050f2dc5d
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/parentpoller.py", line 35, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getppid'
[I 22:18:05.629 NotebookApp] Kernel shutdown: fb7d4b59-fcf4-4cfe-8190-739ef1928337
[I 22:18:17.514 NotebookApp] Kernel started: e81bf8cd-72ea-40e1-87e8-330cd884ff90
[I 22:23:04.151 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[W 22:23:12.272 NotebookApp] Notebook pydata-book/ch02.ipynb is not trusted
[I 22:23:18.682 NotebookApp] Kernel started: 82d56f4e-a231-4553-843c-321d3673a5f9
[I 22:23:53.647 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[I 22:26:00.713 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[I 22:35:37.189 NotebookApp] 302 GET /notebooks/pydata-book/ch02.ipynb (127.0.0.1) 1.48ms
[I 22:35:43.163 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fpydata-book%2Fch02.ipynb (127.0.0.1) 1.14ms
[W 22:36:55.811 NotebookApp] SSL Error on 50 ('127.0.0.1', 60661): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.812 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.815 NotebookApp] SSL Error on 50 ('127.0.0.1', 60662): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.815 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.821 NotebookApp] SSL Error on 50 ('127.0.0.1', 60663): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.822 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.846 NotebookApp] SSL Error on 50 ('127.0.0.1', 60664): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.848 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.859 NotebookApp] SSL Error on 50 ('127.0.0.1', 60665): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.875 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.876 NotebookApp] SSL Error on 50 ('127.0.0.1', 60666): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.877 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[I 22:37:48.686 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[W 00:55:23.190 NotebookApp] error on read
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 644, in _handle_read
        pos = self._read_to_buffer_loop()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 614, in _read_to_buffer_loop
        if self._read_to_buffer() == 0:
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 726, in _read_to_buffer
        chunk = self.read_from_fd()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 1419, in read_from_fd
        chunk = self.socket.read(self.read_chunk_size)
      File "/Users/davidlaxer/anaconda/lib/python2.7/ssl.py", line 621, in read
        v = self._sslobj.read(len or 1024)
    SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1752)
[E 00:55:23.224 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1752)
[I 00:55:41.421 NotebookApp] 302 GET /notebooks/pydata-book/ch02.ipynb (127.0.0.1) 4.10ms
[I 00:55:47.229 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fpydata-book%2Fch02.ipynb (127.0.0.1) 1.99ms
[I 00:56:44.181 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[W 08:22:47.934 NotebookApp] SSL Error on 6 ('127.0.0.1', 56430): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.942 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:22:47.956 NotebookApp] SSL Error on 6 ('127.0.0.1', 56431): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.957 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:22:47.963 NotebookApp] SSL Error on 6 ('127.0.0.1', 56432): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.963 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.477 NotebookApp] SSL Error on 6 ('127.0.0.1', 56478): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.478 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.483 NotebookApp] SSL Error on 6 ('127.0.0.1', 56479): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.484 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.489 NotebookApp] SSL Error on 6 ('127.0.0.1', 56480): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.490 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.923 NotebookApp] SSL Error on 6 ('127.0.0.1', 56482): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.924 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.928 NotebookApp] SSL Error on 6 ('127.0.0.1', 56483): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.929 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:24:33.937 NotebookApp] SSL Error on 6 ('127.0.0.1', 56484): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:24:33.938 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
E 08:24:33.938 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()

**Comment by minrk** [comment]
Are you making HTTP requests to an HTTPS server?

**Comment by dbl001** [comment]
[I 14:23:53.493 NotebookApp] 302 GET / (127.0.0.1) 10.08ms
[I 14:23:53.514 NotebookApp] 302 GET /tree (127.0.0.1) 5.44ms
[I 14:23:53.998 NotebookApp] 302 GET / (127.0.0.1) 0.46ms
[I 14:23:54.006 NotebookApp] 302 GET /tree (127.0.0.1) 0.73ms
[I 14:24:00.154 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 3.15ms
[I 14:24:40.985 NotebookApp] Kernel shutdown: e81bf8cd-72ea-40e1-87e8-330cd884ff90
[I 14:24:42.402 NotebookApp] Kernel shutdown: 82d56f4e-a231-4553-843c-321d3673a5f9
[I 14:24:52.926 NotebookApp] Kernel started: 9dd77d58-a3c1-470b-a7d3-e9393447f66f


In Chrome the notebook works but I get a red-line through HTTPS:




In Safari, which is also using HTTPS, the notebook can’t connect to the kernel:

**Comment by minrk** [comment]
> In Safari, which is also using HTTPS, the notebook can’t connect to the kernel

This is a limitation of Safari. It will not allow ssl websocket connections with self-signed certificates. To use a self-signed cert with Safari, you need to add it to your Keychain to make it a fully trusted cert.

**Comment by dbl001** [comment]
Ok.  I’ll try it.

Any ideas on this:

https://github.com/ipython/ipython/issues/8612 <https://github.com/ipython/ipython/issues/8612>

**Comment by ksens** [comment]
I had the same error 
```
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
```

Problem was that I was trying to access the notebook through `http` when I should have been trying with `https`. Same as what @minrk was suggesting in the first response to this post.

**Comment by hhsieh** [comment]
I have the same issue, but neither http:// nor https:// works for me.

**Comment by hhsieh** [comment]
It's solved now. It's just about proceeding to enter a password. https:// works.

**Comment by gabefair** [comment]
The real issue is that http isn't redirecting to https automatically

**Comment by Goblin80** [comment]
Don't use port 80 if you are going to use https.

**Comment by devpatat** [comment]
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:720)
Facing the issue on deploying apache server with django in email backend smtp

**Comment by ubani** [comment]
Are you serving imap via 993 as suggested here https://github.com/modoboa/modoboa/issues/1134 ?

**Comment by altimmons** [comment]
Having the error. Connecting to HTTP.  But connecting through a corporate proxy.  Perhaps thats it.

**Comment by matanster** [comment]
Same problem on Chrome. Not sure I discern anything specific in the browser console though.

**Comment by akmalick** [comment]
> Are you making HTTP requests to an HTTPS server?

In my case it was the exact opposite.
My local instance of Jira was already up and running at http://localhost:8080/
and I was trying to make a rest get call to 'https://localhost:8080/rest/api/2/issue/'+jiraId+'?fields=status'.

**Comment by prasang0607** [comment]
> The real issue is that http isn't redirecting to https automatically

@gabefair You can use nginx to automatically redirect request to **https**. Here is how you can do it on ubuntu.

Install nginx:
`$ sudo apt -y install nginx`

Check if nginx is active and running:
`$ sudo systemctl status nginx`

If it is not enabled or running, execute these two commands:
```
$ sudo systemctl enable nginx
$ sudo systemctl start nginx
```

Navigate to below directory:
`$ cd /etc/nginx/sites-available`

Edit the default file there, remove everything from it, and paste the below content:
```
server {
    listen 80;
    return 301 https://$host$request_uri;
}
```

Restart nginx:
`$ sudo systemctl restart nginx`

Now any request coming over http(port 80) will be redirected to https(port 443) version.

**Comment by vinjana** [comment]
> Having the error. Connecting to HTTP. But connecting through a corporate proxy. Perhaps thats it.

That was it for me. My HTTPS_PROXY/https_proxy variables were set to "http**s**://..." but should have been "http://..." because our corporate proxy doesn't work with HTTPS.
