### ISSUE TITLE
nbconvert --to slides raises AttributeError: slideshow

### ISSUE THREAD

**Issue by vshkolyar** [ipython/ipython#8635]
ipython version: 3.2.0  
pandoc version: 1.15.0.6  

`ipython nbconvert notebook_name.ipynb --to slides` raises an exception.

Stack trace:
```
Traceback (most recent call last):
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 278, in start
    self.convert_notebooks()
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 401, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 372, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 324, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 156, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 208, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 127, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 281, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/nbconvert/preprocessors/revealhelp.py", line 56, in preprocess
    if nb.cells[index + i].metadata.slideshow.slide_type in ['slide', 'subslide']:
  File "/Users/vs791j/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/utils/ipstruct.py", line 149, in __getattr__
    raise AttributeError(key)
AttributeError: slideshow
```

**Comment by takluyver** [comment]
I think this will be fixed in v4 by jupyter/nbconvert#36 - @damianavila @bollwyvl , can you confirm that it was the same bug that that was fixing?

**Comment by damianavila** [comment]
Should have been fixed by https://github.com/jupyter/nbconvert/pull/58

**Comment by takluyver** [comment]
Thanks.
