### ISSUE TITLE
testsuite aborts under python3.4 in release of 

### ISSUE THREAD

**Issue by idella** [ipython/ipython#8639]
Output of failing;

```bash
Test group: parallel
............................................................................................................................................................S....S....S..S......................................SSSSSSSSSSSSSS............................K...........K.......................
----------------------------------------------------------------------
Ran 286 tests in 68.841s

OK (KNOWNFAIL=2, SKIP=18)

Test group: kernel
..............................................................................S.........................................
----------------------------------------------------------------------
Ran 120 tests in 30.404s

OK (SKIP=1)

Test group: kernel.inprocess
........
----------------------------------------------------------------------
Ran 8 tests in 3.209s

OK

Test group: config
................................................................................
----------------------------------------------------------------------
Ran 80 tests in 0.119s

OK

Test group: core
..................................................................S......................................................................................................................................................................................S................S........................S.
KeyboardInterrupt
....S............................................S............S.................................................................................................................................S...........
----------------------------------------------------------------------
Ran 497 tests in 31.214s

OK (SKIP=8)

Test group: extensions
...
----------------------------------------------------------------------
Ran 3 tests in 0.020s

OK

Test group: lib
................................Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/loader.py", line 252, in generate
    for test in g():
  File "/mnt/gen2/TmpDir/portage/dev-python/ipython-3.2.1/work/ipython-3.2.1-python3_4/build/test/lib/IPython/testing/decorators.py", line 230, in skipper_gen
    raise nose.SkipTest(get_msg(f,msg))
unittest.case.SkipTest: Skipping test: test_latex_to_png_dvipng_runs. This test runs only if command 'latex' is installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 271, in setUp
    if not self:
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 86, in __bool__
    test = next(self.test_generator)
  File "/usr/lib64/python3.4/site-packages/nose/loader.py", line 262, in generate
    address=test_address(generator))
  File "/usr/lib64/python3.4/site-packages/nose/failure.py", line 22, in __init__
    log.debug("A failure! %s %s %s", exc_class, exc_val, format_tb(tb))
  File "/usr/lib64/python3.4/traceback.py", line 93, in format_tb
    return format_list(extract_tb(tb, limit=limit))
  File "/usr/lib64/python3.4/traceback.py", line 106, in extract_tb
    return list(_extract_tb_iter(tb, limit=limit))
  File "/usr/lib64/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python3.4/linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python3.4/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python3.4/linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib64/python3.4/tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "/usr/lib64/python3.4/unittest/result.py", line 184, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb)
  File "/usr/lib64/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib64/python3.4/traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "/usr/lib64/python3.4/traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "/usr/lib64/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python3.4/linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python3.4/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python3.4/linecache.py", line 126, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib64/python3.4/tokenize.py", line 438, in open
    buffer = _builtin_open(filename, 'rb')
TypeError: open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "/usr/lib64/python3.4/site-packages/nose/result.py", line 190, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err)
TypeError: _exc_info_to_string() missing 1 required positional argument: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/gen2/TmpDir/portage/dev-python/ipython-3.2.1/work/ipython-3.2.1-python3_4/build/test/lib/IPython/testing/iptest.py", line 515, in run_iptest
    TestProgram(argv=argv, addplugins=plugins)
  File "/usr/lib64/python3.4/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib64/python3.4/unittest/main.py", line 93, in __init__
    self.runTests()
  File "/usr/lib64/python3.4/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/usr/lib64/python3.4/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 215, in run
    result.addError(self, self._exc_info())
  File "/usr/lib64/python3.4/site-packages/nose/proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "/usr/lib64/python3.4/site-packages/nose/result.py", line 64, in addError
    exc_info = self._exc_info_to_string(err)
  File "/usr/lib64/python3.4/site-packages/nose/result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "/usr/lib64/python3.4/unittest/result.py", line 179, in _exc_info_to_string
    if exctype is test.failureException:
AttributeError: 'NoneType' object has no attribute 'failureException'

Test suite completed for system with the following information:
IPython version: 3.2.1
IPython commit : 2d95975 (installation)
IPython package: /mnt/gen2/TmpDir/portage/dev-python/ipython-3.2.1/work/ipython-3.2.1-python3_4/build/test/lib/IPython
Python version : 3.4.3 (default, Apr 11 2015, 16:00:07) [GCC 4.9.2]
sys.executable : /usr/bin/python3.4
Platform       : Linux-3.19.3-tuxonice-x86_64-AMD_Athlon-tm-_II_X4_645_Processor-with-gentoo-2.2

Tools and libraries available at test time:
   curses jinja2 jsonschema matplotlib mistune numpy pexpect pygments pymongo qt requests sphinx sqlite3 terminado tornado zmq

Tools and libraries NOT available at test time:
   casperjs phantomjs slimerjs

Status: ERROR - 1 out of 15 test groups failed (lib). Took 310.909s.

You may wish to rerun these, with:
```

I hope this supplies enough info, otherwise just ask for further output. You can see the issue is with the state of the installed modules of python; nose and unittests. There is no list of culprit failed tests.  The whole suite passes fine under pythons 2.7, 3.3 .

**Comment by takluyver** [comment]
Known issue with Python 3.4.3 specifically, should be fixed when 3.4.4 comes out.

**Comment by idella** [comment]
ok thx

**Comment by Carreau** [comment]
Closing as there is nothing we can do and it will resolve itself with time. 

Thanks.
