### ISSUE TITLE
Dict key completion with bytes keys raises

### ISSUE THREAD

**Issue by ischwabacher** [ipython/ipython#8647]
Dict key tab completion raises when trying to complete a prefix of a bytes literal that is a valid key in the dict, as below.  This issue persists after `pip install --upgrade ipython`.

``` python
Python 3.4.3 (default, Mar  3 2015, 10:49:33) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: foo = {b'spam': True, 'ham': False}

In [2]: foo['s<TAB>
%%script             %%system             %store               set                  stat+tlrc.BRIK.gz    str                  symptoms.csv
%%sh                 %save                %sx                  setattr              stat+tlrc.HEAD       sum                  
%%svg                %sc                  %system              slice                staticmethod         sun_et_al_seeds.txt  
%%sx                 %set_env             scripts/             sorted               stims/               super                

In [2]: foo['h<TAB>
%%html    %hist     %history  ham       hasattr   hash      help      hex       

In [2]: foo[b'h<TAB>
%%html    %hist     %history  hasattr   hash      help      hex       

In [2]: foo[b's<TAB>Traceback (most recent call last):
  File "/home/schwabacher/lib/python3.4/site-packages/IPython/core/completer.py", line 1092, in complete
    self.matches.extend(matcher(text))
  File "/home/schwabacher/lib/python3.4/site-packages/IPython/core/completer.py", line 917, in dict_key_matches
    closing_quote, token_offset, matches = match_dict_keys(keys, prefix, self.splitter.delims)
  File "/home/schwabacher/lib/python3.4/site-packages/IPython/core/completer.py", line 449, in match_dict_keys
    rem_repr = repr(rem + '"')
TypeError: can't concat bytes to str

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True


%%script             %%system             %store               set                  stat+tlrc.BRIK.gz    str                  symptoms.csv
%%sh                 %save                %sx                  setattr              stat+tlrc.HEAD       sum                  
%%svg                %sc                  %system              slice                staticmethod         sun_et_al_seeds.txt  
%%sx                 %set_env             scripts/             sorted               stims/               super                
```

**Comment by Carreau** [comment]
Marking as 6.0.
