### ISSUE TITLE
RPi pip install ipython[all] fails

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8660]
RPi pip install ipython[all] fails:

```
Downloading/unpacking appnope (from ipython[all])
  Downloading appnope-0.1.0.tar.gz
  Running setup.py egg_info for package appnope
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/appnope/setup.py", line 17, in <module>
        raise ValueError("Only meant for install on OS X >= 10.9")
    ValueError: Only meant for install on OS X >= 10.9
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/appnope/setup.py", line 17, in <module>

    raise ValueError("Only meant for install on OS X >= 10.9")

ValueError: Only meant for install on OS X >= 10.9

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/appnope
Storing complete log in /root/.pip/pip.log
```

**Comment by denfromufa** [comment]
RPi = Raspberry Pi 2 Model B with Raspbian installed on it

**Comment by denfromufa** [comment]
the full command used in terminal:

```
sudo pip install ipython[all] --upgrade
```

full output:

```
pi@raspberrypi ~ $ sudo pip install ipython[all] --upgrade
Requirement already up-to-date: ipython[all] in /usr/local/lib/python2.7/dist-packages
  Installing extra requirements: 'all'
Requirement already up-to-date: decorator in /usr/local/lib/python2.7/dist-packages (from ipython[all])
Requirement already up-to-date: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython[all])
Requirement already up-to-date: simplegeneric>0.8 in /usr/lib/python2.7/dist-packages (from ipython[all])
Requirement already up-to-date: traitlets in /usr/local/lib/python2.7/dist-packages (from ipython[all])
Requirement already up-to-date: pexpect in /usr/local/lib/python2.7/dist-packages (from ipython[all])
Downloading/unpacking nbformat (from ipython[all])
  Downloading nbformat-4.0.0.tar.gz (106Kb): 106Kb downloaded
  Running setup.py egg_info for package nbformat
    
    warning: no previously-included files found matching 'docs/#*'
    warning: no directories found matching 'examples'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    no previously-included directories found matching 'docs/dist'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
Downloading/unpacking appnope (from ipython[all])
  Downloading appnope-0.1.0.tar.gz
  Running setup.py egg_info for package appnope
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/appnope/setup.py", line 17, in <module>
        raise ValueError("Only meant for install on OS X >= 10.9")
    ValueError: Only meant for install on OS X >= 10.9
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/appnope/setup.py", line 17, in <module>

    raise ValueError("Only meant for install on OS X >= 10.9")

ValueError: Only meant for install on OS X >= 10.9

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/appnope
Storing complete log in /root/.pip/pip.log
pi@raspberrypi ~ $ 

```

**Comment by takluyver** [comment]
What version of pip do you have? Also, have you installed a development version of IPython at some point? Because I can't see appnope anywhere in the dependencies of the stable version.

**Comment by denfromufa** [comment]
When I forced `pip install ipython[all]==3.2.1` the installation completed
successfully.

**Comment by arsturges** [comment]
I saw this issue when I tried `$ pip install "ipython[all]"` with pip==1.3.1. When I upgraded to pip==1.5.6, it completed.

**Comment by denfromufa** [comment]
Yes, I had old pip version.

**Comment by takluyver** [comment]
OK, it sounds like this is just due to older versions of pip. Anyone else seeing this: please make sure your pip is up to date.
