### ISSUE TITLE
ipython parallel doesn't works with cython modules

### ISSUE THREAD

**Issue by mhooreman** [ipython/ipython#8708]
Hello,

It seems that load_balanced_view cannot work with cython modules.

The code is displayed below, as well as the execution result (with some stack trace replaced by [...]). As you can see, the "cython" is simple python in the example, except that it is piximported.

The main file imports both plib and clib (pyximport).

Performing a map with a load_balanced_view to a method of an object of plib raises the following error:_pickle.PicklingError: Can't pickle <cyfunction Toto.run at 0x7f23be7fbf60>: it's not found as clib.run.

It seems that's a pickle problem, even if dill is used.

Previously, I did parallel processing using the multiprocessing.pool, and I didn't had the issue.

I'm using dill for serialization (Client().direct_view().use_dill()), with Python 3.4.0 on Ubuntu 14.04 LTS and iPython 3.2.1. My scipy stack is updated weekly using pip.

Best regards.

```
$ cat clib.pyx
import time
class Toto():
    def run(self, x):
        time.sleep(x)

$ cat plib.py
import time
class Toto():
    def run(self, x):
        time.sleep(x)

$ cat proof.py
#!/usr/bin/env python3
import pyximport
pyximport.install()
import clib
import plib
from IPython.parallel import Client
c = Client()
cToto = clib.Toto()
pToto = plib.Toto()
c.direct_view().use_dill()
b = c.load_balanced_view()
b.block = True
print("Running with pure python")
b.map(pToto.run, range(1, 5))
print("Running with cython")
b.map(cToto.run, range(1, 5))

$ ./proof.py
Running with pure python
Running with cython
Traceback (most recent call last):
  File "/usr/lib/python3.4/pickle.py", line 272, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: 'module' object has no attribute 'run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/pickle.py", line 909, in save_global
    obj2 = _getattribute(module, name, allow_qualname=self.proto >= 4)
  File "/usr/lib/python3.4/pickle.py", line 275, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'run' on <module 'clib' (<pyximport.pyximport.PyxLoader object at 0x7fcac4cd27b8>)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./proof.py", line 20, in <module>
    b.map(cToto.run, range(1, 5))
  File "<string>", line 2, in map
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 55, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 40, in save_ids
    ret = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 1123, in map
    return pf.map(*sequences)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/remotefunction.py", line 271, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/remotefunction.py", line 78, in sync_view_results
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/remotefunction.py", line 243, in __call__
    ar = view.apply(f, *args)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 222, in apply
    return self._really_apply(f, args, kwargs)
  File "<string>", line 2, in _really_apply
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 52, in sync_results
    return f(self, *args, **kwargs)
  File "<string>", line 2, in _really_apply
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 40, in save_ids
    ret = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/view.py", line 1050, in _really_apply
    metadata=metadata)
  File "/usr/local/lib/python3.4/dist-packages/IPython/parallel/client/client.py", line 1276, in send_apply_request
    item_threshold=self.session.item_threshold,
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/zmq/serialize.py", line 142, in pack_apply_message
    arg_bufs = flatten(serialize_object(arg, buffer_threshold, item_threshold) for arg in args)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/data.py", line 30, in flatten
    return [x for subseq in seq for x in subseq]
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/data.py", line 30, in <listcomp>
    return [x for subseq in seq for x in subseq]
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/zmq/serialize.py", line 142, in <genexpr>
    arg_bufs = flatten(serialize_object(arg, buffer_threshold, item_threshold) for arg in args)
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/zmq/serialize.py", line 89, in serialize_object
    buffers.insert(0, pickle.dumps(cobj, PICKLE_PROTOCOL))
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 192, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 186, in dump
    pik.dump(obj)
  File "/usr/lib/python3.4/pickle.py", line 410, in dump
    self.save(obj)
  File "/usr/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 893, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/usr/lib/python3.4/pickle.py", line 601, in save_reduce
    save(args)
  File "/usr/lib/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 727, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 508, in save
    self.save_global(obj, rv)
  File "/usr/lib/python3.4/pickle.py", line 913, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <cyfunction Toto.run at 0x7fcac2144f60>: it's not found as clib.run
```

**Comment by minrk** [comment]
What happens if you make sure pyximport is set up on the engines as well:

    %px import pyximport; pyximport.install()

and then try?

**Comment by mhooreman** [comment]
Thanks minrk.

I've tried the following in proofs.py (I'm not within ipython environment, so magics are not available).

It doesn't works.

Best regards.

    c = Client()
    with c[:].sync_imports():
        import pyximport; pyximport.install()
        import clib
    cToto = clib.Toto()
    [...]

**Comment by minrk** [comment]
I don't think that example will result in calling `pyximport.install()`. `sync_imports` only syncs the actual imports, not any other code in the context.

**Comment by mhooreman** [comment]
Thanks.

My code doen't uses ipython, but runs on a standard python interpreter.

Do you know how to implement the suggestion you made in pure python? Sorry, I'm quite new to ipython.

Best regards.

**Comment by mgab** [comment]
Either running the scripts using IPython magics to import and initialize the pyximport module in the nodes or without using them, I still get the `PicklingError`

    from __future__ import print_function
    from IPython.parallel import Client
    c = Client()
    dv = c[:]
    ### Import and start pyximport WITHOUT IPython magics ###
    with dv.sync_imports(local=True):
        import pyximport;
    pyximport.install()
    dv.apply(pyximport.install)
    ### Import and start pyximport WITH IPython magics ###
    # %px import pyximport; pyximport.install()
    ###  ---  ###
    with dv.sync_imports(local=True):
        import plib
        import clib
    cToto = clib.Toto()
    pToto = plib.Toto()
    c.direct_view().use_dill()
    b = c.load_balanced_view()


    b.block = True
    print("Running with pure python")
    b.map(pToto.run, range(1, 5))
    print("Running with cython")
    b.map(cToto.run, range(1, 5))

**Comment by mhooreman** [comment]
Hello,

Thanks mgab. So, is it confirmed that there is an issue?

2015-08-28 11:00 GMT+02:00 mgab <notifications@github.com>:

> Either running the scripts using IPython magics to import and initialize
> the pyximport module in the nodes or without using them, I still get the
> PicklingError
>
> from __future__ import print_function
> from IPython.parallel import Client
> c = Client()
> dv = c[:]
> ### Import and start pyximport WITHOUT IPython magics ###
> with dv.sync_imports(local=True):
>     import pyximport;
> pyximport.install()
> dv.apply(pyximport.install)
> ### Import and start pyximport WITH IPython magics ###
> # %px import pyximport; pyximport.install()
> ###  ---  ###
> with dv.sync_imports(local=True):
>     import plib
>     import clib
> cToto = clib.Toto()
> pToto = plib.Toto()
> c.direct_view().use_dill()
> b = c.load_balanced_view()
>
>
> b.block = True
> print("Running with pure python")
> b.map(pToto.run, range(1, 5))
> print("Running with cython")
> b.map(cToto.run, range(1, 5))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8708#issuecomment-135693812>.
>



-- 

Michaël Hooremanmichael@hooreman.be - http://www.hooreman.be

**Comment by Freedomtowin** [comment]
Hello,

For anyone interested in whether or not ipp.Reference can be used in a directView map, yes it can. Just make a list comprehension of ipp.References to pass with the map.
