### ISSUE TITLE
IPython crash with "print '\x'"

### ISSUE THREAD

**Issue by AaronParsons** [ipython/ipython#8711]
typing:

    >>> print '\x'

causes IPython to crash:

```python
Traceback (most recent call last):
  File "/opt/local/bin/ipython", line 6, in <module>
    start_ipython()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 545, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 362, in start
    self.shell.mainloop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 436, in mainloop
    self.interact(display_banner=display_banner)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 555, in interact
    self.run_cell(source_raw, store_history=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2651, in run_cell
    self.showsyntaxerror()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1755, in showsyntaxerror
    stb = self.SyntaxTB.structured_traceback(etype, value, [])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1201, in structured_traceback
    if isinstance(value.filename, py3compat.string_types) \
AttributeError: 'exceptions.ValueError' object has no attribute 'filename'
```

**Comment by minrk** [comment]
I get:

```python
In [1]: print '\x'
ValueError: invalid \x escape
```

What version of IPython do you have (`ipython --version`)?

**Comment by nxzwt** [comment]
In [6]: print '\x'
ValueError: invalid \x escape

using ipython on windows 7
using chrome

**Comment by AaronParsons** [comment]
I get the error with IPython version 1.2.0 on OSX 10.9.3.

On Friday, August 14, 2015, nxzwt <notifications@github.com> wrote:

> In [6]: print '\x'
> ValueError: invalid \x escape
>
> using ipython on windows 7
> using chrome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8711#issuecomment-131048995>.
>


-- 
Aaron Parsons

510-406-4322 (cell)
Campbell Hall 523, UCB

**Comment by minrk** [comment]
@AaronParsons current IPython is 4.0. Apparently the bug has been fixed since 1.x.
