### ISSUE TITLE
Can not run IPython notebook with IPython 4

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8737]
Here is the log:

'''

C:\Users\eep1>ipython notebook
Traceback (most recent call last):
  File "c:\Python3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python3\Scripts\ipython.exe\__main__.py", line 9, in <module>
  File "c:\Python3\lib\site-packages\IPython\__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\Python3\lib\site-packages\IPython\terminal\ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\Python3\lib\site-packages\IPython\core\application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "c:\Python3\lib\site-packages\IPython\terminal\ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\Python3\lib\site-packages\traitlets\config\application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "c:\Python3\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named 'notebook'

C:\Users\eep1>pip list
alabaster (0.7.6)
anaconda-client (1.0.1)
argcomplete (0.9.0)
astropy (1.0.4)
Babel (2.0)
backports.ssl-match-hostname (3.4.0.2)
bcolz (0.10.0)
beautifulsoup4 (4.4.0)
bitarray (0.8.1)
blaze (0.8.2)
blosc (1.2.7)
blz (0.6.2)
bokeh (0.9.2)
boto (2.38.0)
certifi (2015.4.28)
cffi (1.1.2)
click (4.1)
click-plugins (1.0)
cligj (0.3.0)
clyent (0.4.0)
colorama (0.3.3)
conda (3.16.0)
conda-build (1.16.0)
conda-env (2.4.1)
configobj (5.0.6)
cryptography (1.0)
Cython (0.23)
cytoolz (0.7.3)
datashape (0.4.6)
decorator (4.0.2)
Django (1.8.3)
docutils (0.12)
fastcache (1.0.2)
Fiona (1.6.1)
flake8 (2.4.1)
Flask (0.10.1)
funcsigs (0.4)
future (0.15.0)
GDAL (2.0.0)
greenlet (0.4.7)
h5py (2.5.0)
html5lib (0.999999)
idlex (1.12)
idna (2.0)
ipython (4.0.0)
ipython-genutils (0.1.0)
itsdangerous (0.24)
jdcal (1.0)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
Kivy (1.9.0)
llvmlite (0.6.0)
llvmpy (0.12.7)
lxml (3.4.4)
mahotas (1.4.0)
Markdown (2.6.2)
MarkupSafe (0.23)
matplotlib (1.4.3)
mccabe (0.3.1)
menuinst (1.0.4)
mistune (0.7)
mock (1.3.0)
multipledispatch (0.4.8)
netCDF4 (1.1.9)
networkx (1.10)
nltk (3.0.4)
nose (1.3.7)
numba (0.20.0)
numexpr (2.4.3)
numpy (1.9.2)
odo (0.3.3)
openpyxl (2.2.4)
pandas (0.16.2)
path.py (7.6)
patsy (0.4.0)
pbr (1.5.0)
pep8 (1.6.2)
pickleshare (0.5)
Pillow (2.9.0)
pip (7.1.0)
ply (3.6)
psutil (3.1.1)
py (1.4.30)
pyasn1 (0.1.8)
pycares (0.7.0)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflake (0.1.9)
pyflakes (0.9.2)
Pygments (2.0.2)
PyICU (1.9.2)
pymongo (3.0.3)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyreadline (2.0)
pystache (0.5.4)
pytest (2.7.2)
python-dateutil (2.4.2)
pytz (2015.4)
pywin32 (219)
PyYAML (3.11)
pyzmq (14.7.0)
requests (2.7.0)
rope-py3k (0.9.4-1)
runipy (0.1.3)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scipy (0.16.0)
setuptools (18.1)
simplegeneric (0.8.1)
simplejson (3.8.0)
six (1.9.0)
snowballstemmer (1.2.0)
sockjs-tornado (1.0.1)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.7)
spyder (2.3.5.2)
SQLAlchemy (1.0.8)
statsmodels (0.6.1)
sympy (0.7.6)
tables (3.2.1)
toolz (0.7.4)
tornado (4.2.1)
traitlets (4.0.0)
ujson (1.33)
virtualenv (13.1.0)
Werkzeug (0.10.4)
wheel (0.24.0)
xlrd (0.9.4)
XlsxWriter (0.7.3)
xlwings (0.3.6)

C:\Users\eep1>
'''
Kind regards

**Comment by jenshnielsen** [comment]
Try installing jupyter http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/

**Comment by duytrung** [comment]
Hi there, is IPython 4 the same as Jupyter or different? I haven't touch the IPython for a month so I'm not aware changes. Thanks!

**Comment by takluyver** [comment]
For v4, we've split IPython up into *Jupyter*, which includes the notebook, and IPython, which is the backend to execute Python code. See the Jupyter install docs here: http://jupyter.readthedocs.org/en/latest/install.html
