### ISSUE TITLE
'ValueError: certfile "~/.ipython/mycert.pem" does not exist'

### ISSUE THREAD

**Issue by ElizabethAB** [ipython/ipython#8755]
I am having trouble following the description to launch an IPython server (https://ipython.org/ipython-doc/3/notebook/public_server.html). I get an error saying "~/.ipython/mycert.pem" does not exist.

I don't assume this is an error with IPython (the error messages suggest it might be an issue with Tornado), but I'm hoping someone might have guidance and that the doc can be updated.

The below bash script sets up the IPython profile:
```
ipython3 profile create nbserver
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout ~/.ipython/mycert.pem -out ~/.ipython/mycert.pem
echo "IPython password: "
read tmpswd
tmpswd=$(python3 -c 'from IPython.lib import passwd;print(passwd("$tmpswd"))')
echo "c.NotebookApp.certfile = u'~/.ipython/mycert.pem'
c.NotebookApp.keyfile = u'~/.ipython/mycert.pem'
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
c.NotebookApp.password = u'$tmpswd'" >> ~/.ipython/profile_nbserver/ipython_notebook_config.py
```

Then, I call `ipython3 notebook --profile nbserver` on the command line and it returns the error that mycert.pem cannot be found. 
```
2015-08-20 21:18:22.222 [NotebookApp] Config changed:
2015-08-20 21:18:22.222 [NotebookApp] {'BaseIPythonApplication': {'profile': 'nbserver'}, 'Application': {'log_level': 10}}
2015-08-20 21:18:22.223 [NotebookApp] Using existing profile dir: '/home/elizabeth/.ipython/profile_nbserver'
2015-08-20 21:18:22.223 [NotebookApp] Searching path ['/home/elizabeth/.ipython', '/home/elizabeth/.ipython/profile_nbserver'] for config files
2015-08-20 21:18:22.223 [NotebookApp] Attempting to load config file: ipython_config.py
2015-08-20 21:18:22.223 [NotebookApp] Loaded config file: /home/elizabeth/.ipython/profile_nbserver/ipython_config.py
2015-08-20 21:18:22.223 [NotebookApp] Attempting to load config file: ipython_notebook_config.py
2015-08-20 21:18:22.224 [NotebookApp] Loaded config file: /home/elizabeth/.ipython/profile_nbserver/ipython_notebook_config.py
2015-08-20 21:18:22.224 [NotebookApp] Config changed:
2015-08-20 21:18:22.224 [NotebookApp] {'ProfileDir': {}, 'BaseIPythonApplication': {'profile': 'nbserver'}, 'Application': {'log_level': 10}, 'NotebookApp': {'keyfile': '~/.ipython/mycert.pem', 'certfile': '~/.ipython/mycert.pem', 'password': 'sha1:***', 'open_browser': False, 'ip': '*'}}
2015-08-20 21:18:22.227 [NotebookApp] Adding cluster profile 'default'
2015-08-20 21:18:22.228 [NotebookApp] Adding cluster profile 'nbserver'
2015-08-20 21:18:22.229 [NotebookApp] Using system MathJax
Traceback (most recent call last):
  File "/usr/bin/ipython3", line 9, in <module>
    load_entry_point('ipython==1.2.1', 'console_scripts', 'ipython3')()
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 545, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 312, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 373, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 307, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 474, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 412, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/html/notebookapp.py", line 666, in initialize
    self.init_webapp()
  File "/usr/lib/python3/dist-packages/IPython/html/notebookapp.py", line 543, in init_webapp
    xheaders=self.trust_xheaders)
  File "/usr/lib/python3/dist-packages/tornado/httpserver.py", line 153, in __init__
    **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 103, in __init__
    self.ssl_options['certfile'])
ValueError: certfile "~/.ipython/mycert.pem" does not exist
```

**Comment by minrk** [comment]
I suspect you need to call `os.path.expanduser` to turn `~` into your home directory.

**Comment by ElizabethAB** [comment]
Welp, that worked, thank you!

(I could have sworn I tried this last night, but obviously not.)

**Comment by ljeffersonoh** [comment]
Hello, I have the same problem.  Could someone please provide the exact command for this solution in bash?  

Thanks
