### ISSUE TITLE
ipython notebook --profile=nbserver don't work

### ISSUE THREAD

**Issue by RenfengLiu** [ipython/ipython#8769]
```shell
ipython notebook --profile=nbserver
2015-08-24 21:50:31.723 [NotebookApp] Using existing profile dir: u'/home/datamining/.ipython/profile_nbserver'
2015-08-24 21:50:31.728 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/notebookapp.py", line 771, in initialize
    self.init_webapp()
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/notebookapp.py", line 658, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True


```

**Comment by minrk** [comment]
@RenfengLiu what version of IPython and what OS? Does it work if you do `ipython notebook --ip=127.0.0.1`?

**Comment by marbre** [comment]
With ipython 4.0.0, `ipython notebook --profile=nbserver` gives
~~~
[W 13:36:04.226 NotebookApp] Unrecognized alias: '--profile=nbserver', it will probably have no effect.
~~~
Anyway, `ipython notebook help` tells
~~~
Examples
--------

    ipython notebook                       # start the notebook
    ipython notebook --profile=sympy       # use the sympy profile
    ipython notebook --certfile=mycert.pem # use SSL/TLS certificate
~~~

**Comment by Carreau** [comment]
The help string has been fixed in #277

**Comment by marbre** [comment]
@Carreau Thanks for the quick reply, are you sure you mean #277?

**Comment by Carreau** [comment]
Yes, but I linked the wrong repo. Fixed my comment.

**Comment by marbre** [comment]
Thanks a lot.

**Comment by mpetruc** [comment]
since i updated to ipython 4 I too am having the same problem:
[W 22:35:23.157 NotebookApp] Unrecognized alias: '--profile=mp', it will probably have no effect.

i'm in windows7 with
 
ipykernel==4.0.3
ipython==4.0.0
ipython-genutils==0.1.0
ipywidgets==4.0.2
jsonschema==2.4.0
jupyter-client==4.0.0
jupyter-core==4.0.4
notebook==4.0.4
qtconsole==4.0.1

ipython --profile=mp works correctly. Only notebook and qtconsole have this issue.

**Comment by marbre** [comment]
@mpetruc There is no profile support anymore with jupyter. Try --config instead.

**Comment by jrenner** [comment]
Does the removal of profiles mean that custom color schemes are no longer supported in Jupyter? (editing of custom.css and custom.js in old ipython profiles)

**Comment by Carreau** [comment]
No, the things have just moved to `~/.jupyter/` instead of `~/.ipython/profile_default/`

**Comment by Carreau** [comment]
see https://github.com/jupyter/notebook/issues/419
