### ISSUE TITLE
traitlets issue: TypeError: 'LazyConfigValue' object is not iterable

### ISSUE THREAD

**Issue by foxmouldy** [ipython/ipython#8775]
I am trying to install IPython on my MacBook with OS X 10.8.5. 

I've tried using pip to install IPython with all its dependencies, and have encountered the following error when trying to start IPython. 

I've also tried a quarantined install in a virtualenv, and have found the same error so I know that its not a problem with conflicting versions. 

Any thoughts/suggestions on how to fix this problem?

Error:
--------------------------------
Traceback (most recent call last):
  File "/Users/frank/_notebook/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/frank/_notebook/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/frank/_notebook/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/frank/_notebook/lib/python2.7/site-packages/IPython/core/application.py", line 394, in initialize
    self.load_config_file()
  File "/Users/frank/_notebook/lib/python2.7/site-packages/IPython/core/application.py", line 258, in load_config_file
    path=self.config_file_paths
  File "<string>", line 2, in load_config_file
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/application.py", line 564, in load_config_file
    collisions = loaded[0].collisions(loaded[1])
  File "/Users/frank/_notebook/lib/python2.7/site-packages/traitlets/config/loader.py", line 212, in collisions
    for key in mine:
TypeError: 'LazyConfigValue' object is not iterable

**Comment by Carreau** [comment]
Do you have custom config ? If yes, can you share it ?

**Comment by foxmouldy** [comment]
Thanks for the response. I do have a config file, but there are only two active lines in it:

c = get_config()
c.inlineBackend.close_figures = False

I've also manage to get the notebook to work by simply commenting out the "for key in mine:" in loader.py, but I have no idea for what I may unwittingly broken by doing this.

**Comment by Carreau** [comment]
Hum... strange. Let me look a bit at the code in this area, and comme back to you. 
Does it work if you comment your config ?

**Comment by Carreau** [comment]
Can you around line 206, above `for key in mine:` print self and other ?

**Comment by foxmouldy** [comment]
Yeah, here you go:

{'inlineBackend': <traitlets.config.loader.LazyConfigValue object at 0x10f811c50>}
{'inlineBackend': <traitlets.config.loader.LazyConfigValue object at 0x10f811c50>}

**Comment by Carreau** [comment]
Ha ! 

Which config file ?

(can you try with upper case **`I`** for `InlineBackend`)

**Comment by foxmouldy** [comment]
Well, 
I've updated my ipython_config.py and ipython_notebook_config.py with an uppercase ``I``, while also uncommenting the ```for key in mine``` loop, and I still get the same error. 
The ipython notebook starts up, but the following happens:

```
{'inlineBackend': <traitlets.config.loader.LazyConfigValue object at 0x102436c90>}
{'inlineBackend': <traitlets.config.loader.LazyConfigValue object at 0x102436c90>}
[W 16:16:09.840 NotebookApp] Error loading config file: jupyter_notebook_config
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 202, in load_config_file
        path=path
      File "<string>", line 2, in load_config_file
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 564, in load_config_file
        collisions = loaded[0].collisions(loaded[1])
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/loader.py", line 215, in collisions
        for key in mine:
    TypeError: 'LazyConfigValue' object is not iterable
[I 16:16:09.896 NotebookApp] Serving notebooks from local directory: /Users/frank
[I 16:16:09.896 NotebookApp] 0 active kernels
[I 16:16:09.896 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 16:16:09.896 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/osascript) is code signed with entitlements
[I 16:18:56.578 NotebookApp] Creating new notebook in
[I 16:18:57.345 NotebookApp] Kernel started: 164a8b6b-7018-4eb9-849e-fa11af12864b
{'InlineBackend': {'close_figures': False}}
{'InlineBackend': {'close_figures': False}}
[I 16:19:24.345 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 164a8b6b-7018-4eb9-849e-fa11af12864b restarted
{'InlineBackend': {'close_figures': False}}
{'InlineBackend': {'close_figures': False}}
```

**Comment by Carreau** [comment]
now you need to remove the config option from `~/.jupyter/jupyter_notebook_config.py` where it will have no effect, and does not make sens as it is a IPython kernel specific thing.

**Comment by foxmouldy** [comment]
Alright! I think that its fixed now - no errors!

So in summary - the solution was to get rid of the config option in the jupyter and ipython config files, and to change ```inlineBackend``` to ```InlineBackend```?

Many thanks for your help!

**Comment by Carreau** [comment]
yep, there is an implicit `Uppercase = Class` and  `lowercase = instance value` mapping, anf the migration to 4.0 copied you config around. 
The config in Jupyter will just have no effect, so you could have just changed it to upper case. 

I'll leave this issue open to fix the crashing bug and try to print a warning.

**Comment by takluyver** [comment]
It looks like there's still a config bug to fix here. @Carreau are you going to have a go at that?

**Comment by Carreau** [comment]
> @Carreau are you going to have a go at that?

I'll try to tackle it with @parleur tomorrow.
