### ISSUE TITLE
ImportError: No module named pexpect

### ISSUE THREAD

**Issue by idgserpro** [ipython/ipython#8806]
When I use the ipython with Plone, when start instance, the error occurs:

    2015-09-10 10:46:22 INFO ZServer HTTP server started at Thu Sep 10 10:46:22 2015
        Hostname: 0.0.0.0
        Port: 8080
    2015-09-10 10:46:23 INFO rdflib RDFLib Version: 4.2.1
    Traceback (most recent call last):
      File "/tmp/brasil.gov.vcge/parts/instance/bin/interpreter", line 292, in <module>
        execfile(__file__)
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
        run()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
        starter.prepare()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
        self.startZope()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
        Zope2.startup()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
        _startup()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 118, in startup
        load_zcml()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
        load_site()
      File "/home/user/cache-python/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
        _context = xmlconfig.file(site_zcml)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
        include(context, name, package)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
        actions = self.handler(context, **args)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
        processxmlfile(f, context)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
        parser.parse(src)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
        self.feed(buffer)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
        self._parser.Parse(data, isFinal)
      File "/home/user/pythons/python279/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
        self._cont_handler.endElementNS(pair, None)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
        self.context.end()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
        self.stack.pop().finish()
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 705, in finish
        args = toargs(context, *self.argdata)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
        args[str(name)] = field.fromUnicode(s)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
        value = self.context.resolve(name)
      File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
        mod = __import__(mname, *_import_chickens)
      File "/home/user/cache-python/eggs/iw.debug-0.3-py2.7.egg/iw/debug/pdbview.py", line 26, in <module>
        from ipdb import set_trace
      File "/home/user/cache-python/eggs/ipdb-0.8.1-py2.7.egg/ipdb/__init__.py", line 16, in <module>
        from ipdb.__main__ import set_trace, post_mortem, pm, run, runcall, runeval, launch_ipdb_on_exception
      File "/home/user/cache-python/eggs/ipdb-0.8.1-py2.7.egg/ipdb/__main__.py", line 27, in <module>
        import IPython
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/__init__.py", line 47, in <module>
        from .core.application import Application
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/core/application.py", line 24, in <module>
        from IPython.core import release, crashhandler
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/core/crashhandler.py", line 28, in <module>
        from IPython.core import ultratb
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/core/ultratb.py", line 116, in <module>
        from IPython.utils import path as util_path
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/utils/path.py", line 19, in <module>
        from IPython.utils.process import system
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/utils/process.py", line 19, in <module>
        from ._process_posix import system, getoutput, arg_split, check_pid
      File "/home/user/cache-python/eggs/ipython-4.0.0-py2.7.egg/IPython/utils/_process_posix.py", line 24, in <module>
        import pexpect
    zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/tmp/brasil.gov.vcge/parts/instance/etc/site.zcml", line 15.2-15.55
        ZopeXMLConfigurationError: File "/tmp/brasil.gov.vcge/parts/instance/etc/package-includes/003-iw.debug-configure.zcml", line 1.0-1.52
        ZopeXMLConfigurationError: File "/home/user/cache-python/eggs/iw.debug-0.3-py2.7.egg/iw/debug/configure.zcml", line 7.2-13.4
        ImportError: No module named pexpect

The ipython not add pexpect package as a dependency.

I am using Linux/Ubuntu.

**Comment by minrk** [comment]
How did you install IPython? pexpect is a dependency in setup.py.

**Comment by idgserpro** [comment]
With the [buildout](https://github.com/plonegovbr/brasil.gov.vcge/blob/master/buildout.cfg). It seems that the pexpect is only installed on [Windows](https://github.com/ipython/ipython/blob/master/setup.py#L218-L221)

**Comment by idgserpro** [comment]
Sorry is the opposite.

**Comment by minrk** [comment]
I guess buildout doesn't support packages with dependencies?

**Comment by idgserpro** [comment]
Buildout support packages with dependencies. The problem is that when the ipython is installed with buildout, the [test](https://github.com/ipython/ipython/blob/master/setup.py#L211) returns false and pexpect package is not installed.

**Comment by minrk** [comment]
@idgserpro that bit is only relevent on very old, outdated pip. If your pip is relatively recent (≥ 6), that block does nothing, and the dependency is specified on all non-Windows in the line above.

**Comment by idgserpro** [comment]
The buildout don't use the pip but the setuptools. I am using setuptools 0.6c11. [This](https://github.com/ipython/ipython/blob/master/setup.py#L204) does not work in setuptools 0.6c11. You could not put the pexpect in install_requires instead of extras_require?

**Comment by minrk** [comment]
@idgserpro That's very unfortunate, since setuptools should never be used without pip. 0.6 is an *ancient* setuptools. Current version is 18.3.1. Can you update the package and see if it works?

**Comment by idgserpro** [comment]
@minrk in fact, it worked with the setuptools 0.7.2+. But with a small modification to your code would also work with the 0.6c11. 0.6c11 is the version used by the [Plone tests](https://github.com/plone/buildout.coredev/blob/4.3/versions.cfg#L34).

**Comment by minrk** [comment]
Thanks for checking, glad to see that it works even with very old setuptools, just not *extremely* old setuptools.

> But with a small modification to your code would also work with the 0.6c11

It may appear so, but a simple fix for the years-deprecated 0.6 can easily break existing builds, like wheels. The simplest fix, removing the condition protecting install_requires from platform dependencies, would do exactly that. Thankfully, plone [no longer](https://github.com/plone/buildout.coredev/blob/5.0/versions.cfg#L33) pins setuptools to 0.6.

**Comment by idgserpro** [comment]
@minrk I recommend then put a ```setuptools > 0.6.99``` on your ```install_requires```.
