### ISSUE TITLE
Older notebook not working after the big split

### ISSUE THREAD

**Issue by Japhiolite** [ipython/ipython#8817]
Hi there,

I'm testing older ipython notebooks, after our IT updated to Ipython 4.0.0 and Jupyter 4.0.4
When I'm executing a particular notebook, I get following error/message in the terminal:
``` 
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/usr/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
    message['content'] = self.unpack(msg_list[4])
  File "/usr/lib/python2.7/site-packages/jupyter_client/session.py", line 97, in <lambda>
    json_unpacker = lambda s: jsonapi.loads(s)
  File "/usr/lib64/python2.7/site-packages/zmq/utils/jsonapi.py", line 56, in loads
    return jsonmod.loads(s, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 453, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 429, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 449, in raw_decode
    obj, end = self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Invalid \escape: line 1 column 261 (char 261)
```
The error does not appear in the first cell, but a particular. And even commenting the whole cell does not change it. It works with Ipython 3.2.0 

Some search hinted, that the kernels may be fucked up, because there is no /kernels/bash in the paths given by
```
jupyter --paths
jupyter --data-dir
```
Can someone help me out with this?
Thanks in advance.

**Comment by minrk** [comment]
Can you share your `jupyter_notebook_config.py`? It seems like messages aren't JSON. Also, can you share `python -c "import zmq; print(zmq.zmq_version(), zmq.__version__)"`?

**Comment by Japhiolite** [comment]
I did not change something in the config. It's the default one, generated by ``` jupyter notebook --generate-config ```.
For the second question. ``` python -c "import zmq; print(zmq.zmq_version(), zmq.__version__)": ('4.1.2', '14.7.0') ```

**Comment by minrk** [comment]
You are using the bash kernel for this? Can you show the kernel.json for it (as found by `jupyter kernelspec list`)?

**Comment by Japhiolite** [comment]
I don't use the bash kernel (to my knowledge). I'm a bit puzzled that I don't find any ```kernels``` folder in ``` ~/.jupyter/ ``` or in ```/usr/local/share/ ``` (there is not even a jupyter folder).
```jupyter kernelspec list``` returns ```python2``` as available kernel. I must admit, I have not found the corresponding .json file.  
Could ```jupyter kernelspec install-self``` help there? I have to contact the IT, since I (frustratingly) have no sudo rights on this machine.

**Comment by minrk** [comment]
You can use `ipython kernelspec install-self --user` to install to a location that you control.

**Comment by Japhiolite** [comment]
Ah thanks, did that. Unfortunately, it dit not solve the error message. 
Here is the kernel.json:
```
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "/usr/bin/python", 
  "-m", 
  "ipykernel", 
  "-f", 
  "{connection_file}"
 ]
}
```
located in ```~/.local/share/jupyter/kernels/python2/```

**Comment by minrk** [comment]
Can you run the notebook server with `--debug`?

**Comment by Japhiolite** [comment]
Sure:
```
jni@esim39:~> jupyter notebook --debug
[D 14:37:26.885 NotebookApp] Config changed:
[D 14:37:26.885 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 14:37:26.885 NotebookApp] Searching [u'/home/jni', '/home/jni/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/etc/jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.py in path /home/jni/.jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.json in path /home/jni/.jupyter
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.py in path /home/jni
[D 14:37:26.886 NotebookApp] Attempting to load config file jupyter_config.json in path /home/jni
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/etc/jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/jni/.jupyter
[D 14:37:26.887 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/jni/.jupyter
[D 14:37:26.888 NotebookApp] Loaded config file: /home/jni/.jupyter/jupyter_notebook_config.py
[D 14:37:26.888 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /home/jni
[D 14:37:26.888 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /home/jni
[I 14:37:26.917 NotebookApp] The port 8888 is already in use, trying another random port.
[I 14:37:26.920 NotebookApp] Serving notebooks from local directory: /home/jni
[I 14:37:26.920 NotebookApp] 0 active kernels 
[I 14:37:26.920 NotebookApp] The IPython Notebook is running at: http://localhost:8889/
[I 14:37:26.920 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 14:37:27.152 NotebookApp] Using contents: services/contents
[D 14:37:27.178 NotebookApp] 200 GET /tree (::1) 27.09ms
[D 14:37:27.466 NotebookApp] 304 GET /custom/custom.css (::1) 8.70ms
[D 14:37:27.714 NotebookApp] 200 GET /static/services/contents.js?v=20150917143726 (::1) 0.94ms
[D 14:37:27.716 NotebookApp] 200 GET /custom/custom.js?v=20150917143726 (::1) 1.74ms
[D 14:37:27.795 NotebookApp] 200 GET /api/config/tree?_=1442493447628 (::1) 0.76ms
[D 14:37:27.796 NotebookApp] 200 GET /api/config/common?_=1442493447629 (::1) 0.48ms
[D 14:37:27.797 NotebookApp] 200 GET /api/terminals?_=1442493447630 (::1) 0.43ms
[D 14:37:27.798 NotebookApp] 200 GET /api/sessions?_=1442493447631 (::1) 1.14ms
[D 14:37:27.800 NotebookApp] 200 GET /api/terminals?_=1442493447632 (::1) 0.52ms
[D 14:37:27.812 NotebookApp] Found kernel python2 in /home/jni/.local/share/jupyter/kernels
[D 14:37:27.813 NotebookApp] Found kernel python2 in /home/jni/.local/share/jupyter/kernels
[D 14:37:27.814 NotebookApp] 304 GET /api/kernelspecs (::1) 2.31ms
[D 14:37:27.842 NotebookApp] 200 GET /api/contents?type=directory&_=1442493447633 (::1) 27.60ms
[D 14:37:32.608 NotebookApp] Using contents: services/contents
[D 14:37:32.639 NotebookApp] 200 GET /notebooks/Horner.ipynb (::1) 32.92ms
[D 14:37:32.734 NotebookApp] 304 GET /custom/custom.css (::1) 1.23ms
[D 14:37:32.755 NotebookApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 1.18ms
[D 14:37:32.844 NotebookApp] 304 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.5.3 (::1) 1.22ms
[D 14:37:33.110 NotebookApp] 304 GET /custom/custom.js?v=20150917143726 (::1) 1.91ms
[D 14:37:33.276 NotebookApp] 200 GET /api/config/notebook?_=1442493452933 (::1) 1.20ms
[D 14:37:33.278 NotebookApp] 200 GET /api/config/common?_=1442493452934 (::1) 1.10ms
[D 14:37:33.498 NotebookApp] 200 GET /api/contents/Horner.ipynb?type=notebook&_=1442493452935 (::1) 218.86ms
[D 14:37:33.499 NotebookApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.5.3 (::1) 0.54ms
[D 14:37:33.500 NotebookApp] Found kernel python2 in /home/jni/.local/share/jupyter/kernels
[D 14:37:33.500 NotebookApp] Found kernel python2 in /home/jni/.local/share/jupyter/kernels
[D 14:37:33.501 NotebookApp] 304 GET /api/kernelspecs (::1) 1.36ms
[D 14:37:33.503 NotebookApp] 200 GET /nbextensions/widgets/notebook/js/extension.js?v=20150917143726 (::1) 0.65ms
[D 14:37:34.236 NotebookApp] 200 GET /api/contents/Horner.ipynb/checkpoints?_=1442493452936 (::1) 1.27ms
[D 14:37:34.247 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/init.js?v=20150917143726 (::1) 1.69ms
[D 14:37:34.249 NotebookApp] 200 GET /nbextensions/widgets/notebook/js/widgetarea.js?v=20150917143726 (::1) 1.42ms
[D 14:37:34.299 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?rev=2.5.3 (::1) 1.22ms
[D 14:37:34.326 NotebookApp] Found kernel python2 in /home/jni/.local/share/jupyter/kernels
[D 14:37:34.330 NotebookApp] Connecting to: tcp://127.0.0.1:36812
[I 14:37:34.331 NotebookApp] Kernel started: 0009c94a-236b-472f-9dbc-2959fec9f6d8
[D 14:37:34.331 NotebookApp] Kernel args: {'kernel_name': u'python2', 'cwd': u'/home/jni'}
[D 14:37:34.332 NotebookApp] 201 POST /api/sessions (::1) 17.92ms
[D 14:37:34.343 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?rev=2.5.3 (::1) 0.55ms
[D 14:37:34.347 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/manager.js?v=20150917143726 (::1) 0.56ms
[D 14:37:34.349 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget.js?v=20150917143726 (::1) 0.53ms
[D 14:37:34.350 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_link.js?v=20150917143726 (::1) 0.47ms
[D 14:37:34.352 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_bool.js?v=20150917143726 (::1) 0.53ms
[D 14:37:34.353 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_button.js?v=20150917143726 (::1) 0.51ms
[D 14:37:34.353 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_box.js?v=20150917143726 (::1) 0.48ms
[D 14:37:34.354 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_image.js?v=20150917143726 (::1) 0.48ms
[D 14:37:34.355 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_float.js?v=20150917143726 (::1) 0.48ms
[D 14:37:34.366 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_int.js?v=20150917143726 (::1) 0.52ms
[D 14:37:34.367 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_output.js?v=20150917143726 (::1) 0.50ms
[D 14:37:34.368 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_selection.js?v=20150917143726 (::1) 0.51ms
[D 14:37:34.369 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_string.js?v=20150917143726 (::1) 0.47ms
[D 14:37:34.369 NotebookApp] 200 GET /nbextensions/widgets/widgets/js/widget_selectioncontainer.js?v=20150917143726 (::1) 0.51ms
[D 14:37:34.701 NotebookApp] 200 GET /static/components/backbone/backbone-min.js?v=20150917143726 (::1) 1.19ms
[D 14:37:34.702 NotebookApp] Initializing websocket connection /api/kernels/0009c94a-236b-472f-9dbc-2959fec9f6d8/channels
[D 14:37:34.703 NotebookApp] Requesting kernel info from 0009c94a-236b-472f-9dbc-2959fec9f6d8
[D 14:37:34.703 NotebookApp] Connecting to: tcp://127.0.0.1:33375
[D 14:37:34.819 NotebookApp] Received kernel info: {'language_info': {'mimetype': 'text/x-python', 'nbconvert_exporter': 'python', 'name': 'python', 'pygments_lexer': 'ipython2', 'version': '2.7.3', 'file_extension': '.py', 'codemirror_mode': {'version': 2, 'name': 'ipython'}}, 'implementation': 'ipython', 'implementation_version': '4.0.0', 'protocol_version': '5.0', 'banner': 'Python 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]\nType "copyright", "credits" or "license" for more information.\n\nIPython 4.0.0 -- An enhanced Interactive Python.\n?         -> Introduction and overview of IPython\'s features.\n%quickref -> Quick reference.\nhelp      -> Python\'s own help system.\nobject?   -> Details about \'object\', use \'object??\' for extra details.\n%guiref   -> A brief reference about the graphical user interface.\n', 'help_links': [{'url': 'http://docs.python.org/2.7', 'text': 'Python'}, {'url': 'http://ipython.org/documentation.html', 'text': 'IPython'}, {'url': 'http://docs.scipy.org/doc/numpy/reference/', 'text': 'NumPy'}, {'url': 'http://docs.scipy.org/doc/scipy/reference/', 'text': 'SciPy'}, {'url': 'http://matplotlib.org/contents.html', 'text': 'Matplotlib'}, {'url': 'http://docs.sympy.org/latest/index.html', 'text': 'SymPy'}, {'url': 'http://pandas.pydata.org/pandas-docs/stable/', 'text': 'pandas'}]}
[D 14:37:34.820 NotebookApp] Opening websocket /api/kernels/0009c94a-236b-472f-9dbc-2959fec9f6d8/channels
[D 14:37:34.820 NotebookApp] Connecting to: tcp://127.0.0.1:33375
[D 14:37:34.821 NotebookApp] Connecting to: tcp://127.0.0.1:51423
[D 14:37:34.821 NotebookApp] Connecting to: tcp://127.0.0.1:42805
[D 14:37:35.367 NotebookApp] 304 GET /nbextensions/widgets/widgets/css/widgets.min.css (::1) 1.13ms
[D 14:37:35.397 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/Main/Italic/Main.js?rev=2.5.3 (::1) 0.70ms
[D 14:37:35.697 NotebookApp] 304 GET /static/components/MathJax/fonts/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Italic.woff?rev=2.5.3 (::1) 1.21ms
[D 14:37:35.960 NotebookApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/Main/Regular/Main.js?rev=2.5.3 (::1) 1.21ms
[D 14:37:36.217 NotebookApp] 304 GET /static/components/MathJax/fonts/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Regular.woff?rev=2.5.3 (::1) 1.21ms
```

**Comment by minrk** [comment]
And after that output it starts showing the json decoder errors?

**Comment by Japhiolite** [comment]
ah yes.
Following the last output of the post above:
```
[D 14:37:36.217 NotebookApp] 304 GET /static/components/MathJax/fonts/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Regular.woff?rev=2.5.3 (::1) 1.21ms
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/usr/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
    message['content'] = self.unpack(msg_list[4])
  File "/usr/lib/python2.7/site-packages/jupyter_client/session.py", line 97, in <lambda>
    json_unpacker = lambda s: jsonapi.loads(s)
  File "/usr/lib64/python2.7/site-packages/zmq/utils/jsonapi.py", line 56, in loads
    return jsonmod.loads(s, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 453, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 429, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 449, in raw_decode
    obj, end = self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Invalid \escape: line 1 column 261 (char 261)
```

**Comment by Japhiolite** [comment]
I figured it out. Missing jsonutils caused the error messages.  
Simply installing them fixed the issue for me. 
Anyway, thanks minrk for your help in trying to track it down :) .

**Comment by Carreau** [comment]
How could you miss a dependency ? Are you speeking of jsonutils that hasn't been updated since 2006 ?
