### ISSUE TITLE
Cannot import pexpect

### ISSUE THREAD

**Issue by aaren** [ipython/ipython#8833]
Not sure where this is coming from. I'm creating a new conda env and doing `conda install jupyter`. Following this I can't use anything because ipython won't work. `pexpect` is definitely installed but ipython can't find it:

```python
(jupyter)see4-206:~/code/notedown (master *=)$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import IPython
/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/core/application.py", line 24, in <module>
    from IPython.core import release, crashhandler
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/core/ultratb.py", line 116, in <module>
    from IPython.utils import path as util_path
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/utils/path.py", line 21, in <module>
    from IPython.utils.process import system
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/utils/process.py", line 28, in <module>
    from ._process_posix import _find_cmd, system, getoutput, arg_split, check_pid
  File "/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/utils/_process_posix.py", line 24, in <module>
    from IPython.external import pexpect
ImportError: cannot import name pexpect
>>> import pexpect
>>> pexpect.__file__
'/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/pexpect/__init__.pyc'
>>>
```

This isn't a problem if I `pip install jupyter` - in that case I have a jsonschema problem that can be upgraded out of.

**Comment by minrk** [comment]
What do you get from `conda list` and `pip list`? That looks a bit like you have a mixture of old and new IPythons at the same time.

**Comment by aaren** [comment]
conda list:

```bash
(jupyter)see4-206:~/code/notedown (master *=)$ conda list
# packages in environment at /nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter:
#
backports.ssl-match-hostname 3.4.0.2                   <pip>
certifi                   14.05.14                 py27_0
decorator                 4.0.2                    py27_0
fontconfig                2.11.1                        4
freetype                  2.5.2                         2
functools32               3.2.3.post2               <pip>
ipykernel                 4.0.3                    py27_0
ipython                   4.0.0                    py27_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.0.3                    py27_0
jinja2                    2.8                      py27_0
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_0
jupyter-client            4.0.0                     <pip>
jupyter-console           4.0.2                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.0.0                    py27_0
jupyter_console           4.0.2                    py27_0
jupyter_core              4.0.6                    py27_0
libpng                    1.6.17                        0
libsodium                 0.4.5                         0
libxml2                   2.9.2                         0
markupsafe                0.23                     py27_0
mistune                   0.7.1                    py27_0
nbconvert                 4.0.0                    py27_0
nbformat                  4.0.0                    py27_0
notebook                  4.0.5                    py27_0
openssl                   1.0.1k                        1
path.py                   8.1.1                    py27_0
pexpect                   3.3                      py27_0
pickleshare               0.5                      py27_0
pip                       7.1.2                    py27_0
ptyprocess                0.4                      py27_0
pygments                  2.0.2                    py27_0
pyqt                      4.11.3                   py27_1
python                    2.7.10                        1
pyzmq                     14.7.0                   py27_0
qt                        4.8.6                         3
qtconsole                 4.0.1                    py27_0
readline                  6.2                           2
setuptools                18.3.2                   py27_0
simplegeneric             0.8.1                    py27_0
sip                       4.16.5                   py27_0
sqlite                    3.8.4.1                       1
ssl_match_hostname        3.4.0.2                  py27_0
terminado                 0.5                      py27_0
tk                        8.5.18                        0
tornado                   4.2.1                    py27_0
traitlets                 4.0.0                    py27_0
wheel                     0.26.0                   py27_1
zeromq                    4.0.5                         0
zlib                      1.2.8                         0
```

**Comment by aaren** [comment]
pip list:

```
(jupyter)see4-206:~/code/notedown (master *=)$ pip list
backports.ssl-match-hostname (3.4.0.2)
certifi (14.5.14)
decorator (4.0.2)
functools32 (3.2.3.post2)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.2)
jupyter-core (4.0.6)
MarkupSafe (0.23)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.0)
notebook (4.0.5)
path.py (0.0.0)
pexpect (3.3)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.4)
Pygments (2.0.2)
pyzmq (14.7.0)
qtconsole (4.0.1)
setuptools (18.3.2)
simplegeneric (0.8.1)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
wheel (0.26.0)
```

**Comment by aaren** [comment]
This is in a new conda env with no pre-existing ipython.

**Comment by minrk** [comment]
Something is definitely wrong, because `from IPython.external import pexpect` does not exist in IPython 4.0. That means you have some parts of IPython that are not from 4.0. Perhaps this is a problem with the conda package. Try reinstalling IPython:

    conda uninstall ipython
    conda install ipython

and see if it is resolved.

You may also want to check `ipython -V` to see what version IPython thinks it is.

**Comment by aaren** [comment]
`ipython -V` doesn't work because of the pexpect error. Here is uninstall / reinstall:

```bash
(jupyter)see4-206:~/code/notedown (master *=)$ ipython -V
/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has
been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
...
    from IPython.external import pexpect
ImportError: cannot import name pexpect

(jupyter)see4-206:~/code/notedown (master *=)$ conda uninstall ipython
Fetching package metadata: ....

Package plan for package removal in environment /nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter:

The following packages will be REMOVED:

    ipython: 4.0.0-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|########################################################################################################################| 100%
(jupyter)see4-206:~/code/notedown (master *=)$ conda install ipython
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter:

The following NEW packages will be INSTALLED:

    ipython: 4.0.0-py27_0 (soft-link)

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|########################################################################################################################| 100%

(jupyter)see4-206:~/code/notedown (master *=)$ ipython -V
/nfs/see-fs-02_users/eeaol/src/anaconda/envs/jupyter/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has
been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
...
    from IPython.external import pexpect
ImportError: cannot import name pexpect
```

**Comment by aaren** [comment]
I did some more testing. The following work fine:

- new environment with jupyter created from a new miniconda install.
- jupyter install in root of new miniconda install
- new environment with jupyter in a new anaconda install
- jupyter install in root of new anaconda install

Which implies that this is a problem with my local environment.

**Comment by aaren** [comment]
Problem fixed (for me at least).

I noticed that my ipython installs were coming from a cache rather than a new download. I 'fixed' the error by physically deleting all ipython packages from `anaconda/pkgs` and then reinstalling. There is probably a better way of fixing it (possibly with `conda clean`) but I can't test now because the bad environment is gone.

I've no idea how it went bad in the first place, but this is a fairly old anaconda install.

**Comment by minrk** [comment]
I suspect it's a conda packaging issue. I don't know the root cause - if an early build of a conda package was messed up, or if something got confused in the install process, but there shouldn't be anything for us to do here, and it seems to be fixed.

@asmeurer do you have any insight on what might cause a package to have contents from an earlier version?

**Comment by asmeurer** [comment]
A possibility is that if you `pip install IPython` and then `conda install ipython` a newer version over it it won't remove any files that should have been deleted.

**Comment by minrk** [comment]
@asmeurer good to know. I don't think that's exactly what happened here, because the error is happening in a file that is still around, but the content of the file has been modified.

**Comment by GCardellini** [comment]
Had exactly the same issue in deleting an environment and recreating another one with same name. I  solved the prob cleaning (conda clean -p -t -i -y) before creating the new enviro
