### ISSUE TITLE
IPython Failed to start the R kernel (Mac OS X El Capitan)

### ISSUE THREAD

**Issue by carloshdezv** [ipython/ipython#8860]
Hi, 

After updating my OS to El Capitan Jupyter R Kernel does not start any more, I get this error:

```
Failed to start the kernel

Unknown server error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 441, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/manager.py", line 240, in start_kernel
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

![screen shot 2015-10-02 at 23 07 45](https://cloud.githubusercontent.com/assets/13800686/10261383/86488b3c-695a-11e5-8f76-808c4bf4ca70.png)

Any help is appreciated.

Thanks!

**Comment by minrk** [comment]
I suspect that means that R has moved, or isn't there anymore. What do you get from `which -a r`?

**Comment by MrMino** [comment]
No further info provided.
