### ISSUE TITLE
Jupyter (4.0) does not find latex_nocode.tplx in working directory?

### ISSUE THREAD

**Issue by dartdog** [ipython/ipython#8868]
Using NB convert..( Used to work with prior IPython nb)

```
!ipython nbconvert --to=latex --template=latex_nocode.tplx Surveyanalysis_Sep2015.ipynb
Gives me this traceback:
/usr/local/lib/python2.7/dist-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
[NbConvertApp] Converting notebook Surveyanalysis_Sep2015.ipynb to latex
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 349, in start
    return self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 286, in start
    self.convert_notebooks()
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 409, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 380, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 332, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 166, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/latex.py", line 88, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/templateexporter.py", line 206, in from_notebook_node
    raise IOError('template file "%s" could not be found' % self.template_file)
IOError: template file "latex_nocode.tplx" could not be found
```

And here is the ls of the working directory

```
!ls
ACRE_Survey_registationLables103.csv   LablessurveydataNewreg782015.ipynb
ACRE_Survey_registationValues103.csv   latex_nocode.tplx
annonallanswerswithmaster10152015.csv  Surveyanalysis_Sep2015.ipynb
Cleansurveydata10152015.ipynb	       surveydata_fixValues.ipynb
fxdvalues.csv
```

**Comment by dartdog** [comment]
FWIW the nbconvert woks fine just can't find the alternative template.

**Comment by matiasdahl** [comment]
The command line option `--TemplateExporter.template_path` can be used to add paths for finding templates on the command line. For example: 

```
jupyter nbconvert --execute \
            --to markdown README.ipynb \
            --template=hidecode.tpl \
            '--TemplateExporter.template_path=["."]'
```

(A list of all options can be obtained by `jupyter nbconvert --help-all`.) 

To add "." permanently, I edited `jupyter_nbconvert_config.json` and added "." to the `template_path` list, e.g. like

```
"template_path": [ ".", "/Users/<username>/Library/Jupyter/templates"]
```

(Jupyter v. 4.0.6, OSX)

**Comment by Carreau** [comment]
Migrated to jupyter/nbconvert#206
