### ISSUE TITLE
errors running kernelspec list

### ISSUE THREAD

**Issue by ittayd** [ipython/ipython#8902]
I installed ipython (used 'pip install --upgrade ipython' as ipython[all] didn't work since it tried to install gnu readline module on my Windows machine and failed)

Running `ipython kernelspec list`:

```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\IPython\__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python27\lib\site-packages\IPython\terminal\ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python27\lib\site-packages\IPython\core\application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "C:\Python27\lib\site-packages\IPython\terminal\ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python27\lib\site-packages\traitlets\config\application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "C:\Python27\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_client.kernelspecapp
```

**Comment by minrk** [comment]
What do you get from `pip --version`?

**Comment by ittayd** [comment]
pip 1.5.6 from C:\Python27\lib\site-packages (python 2.7)

**Comment by minrk** [comment]
That might be the issue, since current pip is 7.1.

Try:

    pip install --upgrade setuptools pip

`ipython[all]` should work, but the new name for the all-the-things is `jupyter`:

    pip install jupyter

If `ipython[all]` still doesn't work after upgrading pip, there might be something wrong in how we specify the conditions for depending on gnureadline, which should be only on OS X.

**Comment by ittayd** [comment]
> pip install --upgrade setuptools pip
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.5/s/setuptools/setuptools-18.4-py2.py3-none-any.whl#md5=7fcc3027ef72df6be665c271d3c457b2
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 7.0
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    "filters": {
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run
    )
  File "C:\Python27\lib\site-packages\pip\req.py", line 1443, in install
  File "C:\Python27\lib\site-packages\pip\req.py", line 610, in commit_uninstall
  File "C:\Python27\lib\site-packages\pip\req.py", line 1860, in commit
  File "C:\Python27\lib\site-packages\pip\util.py", line 43, in rmtree
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\site-packages\pip\util.py", line 62, in rmtree_errorhandler
WindowsError: [Error 5] Access is denied: 'c:\\users\\idror\\appdata\\local\\temp\\pip-g31c80-uninstall\\python27\\scripts\\pip.exe'

Storing debug log for failure in C:\Users\idror\pip\pip.log

**Comment by minrk** [comment]
Arg, pip. Try this:

    pip install --upgrade setuptools
    easy_install --upgrade pip

**Comment by takluyver** [comment]
Closing as it doesn't appear to be an IPython bug.
