### ISSUE TITLE
`run_line_magic()` and Python 3.5

### ISSUE THREAD

**Issue by lgautier** [ipython/ipython#8941]
When testing rpy2 with Python 3.5, a test for the R magic starts failing (it is not failing with Python < 3.5) with the call:
```python
self.ip.run_line_magic('Rpush', 'df')
```

On the receiving end, `Rpush` receives `"d"` instead of `"df"`.

---
```
{'commit_hash': 'f534027',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/laurent/Desktop/software/python/py35_env/lib/python3.5/site-packages/IPython',
 'ipython_version': '4.0.0',
 'os_name': 'posix',
 'platform': 'Linux-4.2.0-16-generic-x86_64-with-Ubuntu-15.10-wily',
 'sys_executable': '/home/laurent/Desktop/software/python/py35_env/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.0+ (default, Oct 11 2015, 09:05:38) \n'
                '[GCC 5.2.1 20151010]'}
```

**Comment by Carreau** [comment]
can you tell us which test ?
And it seem to me that R magic in in rpy2 package not IPython itself.

**Comment by lgautier** [comment]
Yes. More details.

The R magic is in now in `rpy2`, but tracing the error leads me to ipython.
The test in `rpy2` is `rpy2.ipython.tests.test_rmagic.TestRmagic.test_push_dataframe`,  and the traceback is:
```
Traceback (most recent call last):
  File "/home/laurent/Desktop/software/python/py35_env/lib/python3.5/site-packages/rpy2-2.7.4-py3.5-linux-x86_64.egg/rpy2/ipython/tests/test_rmagic.py", line 81, in test_push_dataframe
    self.ip.run_line_magic('Rpush', 'df')
self.ip.run_line_magic('Rpush', 'df')
  File "/home/laurent/Desktop/software/python/py35_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2257, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-119>", line 2, in Rpush
  File "/home/laurent/Desktop/software/python/py35_env/lib/python3.5/site-packages/IPython/core/magic.py", line 193, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/home/laurent/Desktop/software/python/py35_env/lib/python3.5/site-packages/rpy2-2.7.4-py3.5-linux-x86_64.egg/rpy2/ipython/rmagic.py", line 302, in Rpush
    raise NameError("name '%s' is not defined" % input)
NameError: name 'd' is not defined
```

The call `self.ip.run_line_magic('Rpush', 'df')` leads to a variable `d` being searched on the ipython end whereas the test appears to be working with Python < 3.5.

**Comment by Carreau** [comment]
hum... strange, thanks for the traceback. I see if I can get rpy2 installed. Usaully it's a pain, but maybe with conda will be easier.

**Comment by lgautier** [comment]
Installing rpy2 usually requires to write `pip install rpy2`. You may want check your system.

**Comment by Carreau** [comment]
The install part problem was not rpy2 it was R, but it was another computer some month ago.

**Comment by lgautier** [comment]
I double-checked and the test is passing with Python 3.4 but not Python 3.5.

Tracing code a little I am landing on ipython code for which the docstring-based tests are skipped for Python 3 (how convenient ;-)).
 https://github.com/ipython/ipython/blob/40c34d3369c3d271149e13ac07f1bd2f5a716635/IPython/utils/text.py#L577

I think that I identified the root of the problem, and it does seem to be with either ipython or Python. The behavior of `IPython.utilts.text.DollarFormatter` is different between Python 3.4 and Python 3.5.

See below for a minimal example:

```python
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from IPython.utils.text import DollarFormatter

In [2]: df = DollarFormatter()

In [3]: df.vformat('foo', args=[], kwargs={})
Out[3]: 'foo'
```


```python
Python 3.5.0+ (default, Oct 11 2015, 09:05:38) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from IPython.utils.text import DollarFormatter

In [2]: df = DollarFormatter()

In [3]: df.vformat('foo', args=[], kwargs={})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ba4c00aec410> in <module>()
----> 1 df.vformat('foo', args=[], kwargs={})

/usr/lib/python3.5/string.py in vformat(self, format_string, args, kwargs)
    189     def vformat(self, format_string, args, kwargs):
    190         used_args = set()
--> 191         result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
    192         self.check_unused_args(used_args, args, kwargs)
    193         return result

ValueError: too many values to unpack (expected 2)
```

**Comment by takluyver** [comment]
I think this was fixed by #8985

**Comment by wuqiaomin** [comment]
but a problem such as "get_IPython has attribute called run_line_magic", how can I resolve it?

**Comment by wuqiaomin** [comment]
but a problem such as "get_IPython has not attribute called run_line_magic", how can I resolve it?
