### ISSUE TITLE
Source highlighting lost of oinspect.Inspector() object created.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8965]
An image is worth 1000 words:

<img width="410" alt="screen shot 2015-11-08 at 19 13 07" src="https://cloud.githubusercontent.com/assets/335567/11025189/f42ee448-864c-11e5-8d9a-dda0b36cfe0a.png">

Discover because actually my pygments branch fixes that, and our tests are implicitely relying on it:

```
======================================================================
FAIL: IPython.core.tests.test_oinspect.test_definition_kwonlyargs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/Carreau/ipython/IPython/testing/decorators.py", line 208, in skipper_func
    return f(*args, **kwargs)
  File "/home/travis/build/Carreau/ipython/IPython/core/tests/test_oinspect.py", line 297, in test_definition_kwonlyargs
    nt.assert_equal(i['definition'], "f_kwarg(pos, *, kwonly)\n")
AssertionError: '\x1b[38;5;252mf_kwarg\x1b[39m\x1b[38;5;25[199 chars]9m\n' != 'f_kwarg(pos, *, kwonly)\n'
- f_kwarg(pos, *, kwonly)
+ f_kwarg(pos, *, kwonly)
    """Fail immediately, with the given message."""
>>  raise self.failureException("'\\x1b[38;5;252mf_kwarg\\x1b[39m\\x1b[38;5;25[199 chars]9m\\n' != 'f_kwarg(pos, *, kwonly)\\n'\n- \x1b[38;5;252mf_kwarg\x1b[39m\x1b[38;5;252m(\x1b[39m\x1b[38;5;252mpos\x1b[39m\x1b[38;5;252m,\x1b[39m\x1b[38;5;252m \x1b[39m\x1b[38;5;68m*\x1b[39m\x1b[38;5;252m,\x1b[39m\x1b[38;5;252m \x1b[39m\x1b[38;5;252mkwonly\x1b[39m\x1b[38;5;252m)\x1b[39m\n+ f_kwarg(pos, *, kwonly)\n")
    
----------------------------------------------------------------------
```

**Comment by minrk** [comment]
Well, that's weird. There's supposed to be no highlighting in the tests because we aim to use NoColor everywhere.

**Comment by Carreau** [comment]
The fail might be due to some refactoring I am doing, but the reset of color in the live session is not expected.

**Comment by Carreau** [comment]
Not sure it's important for 4.1 though. It's probably a decade old bug.

**Comment by Carreau** [comment]
I'll bump to 5.0
