### ISSUE TITLE
IPython fails in a really obscure way when PYTHONOPTIMIZE is set

### ISSUE THREAD

**Issue by croepha** [ipython/ipython#8971]
To reproduce:

```
PYTHONOPTIMIZE=2 ipython

Traceback (most recent call last):
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/__init__.py", line 47, in <module>
    from .core.application import Application
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/core/application.py", line 24, in <module>
    from IPython.core import release, crashhandler
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/core/crashhandler.py", line 30, in <module>
    from IPython.utils.sysinfo import sys_info
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/utils/sysinfo.py", line 101, in <module>
    @py3compat.doctest_refactor_print
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/utils/py3compat.py", line 50, in wrapper
    doc = str_change_func(doc)
  File "/Users/davidbutler/PycharmProjects/tanager_local/streaming_engine_project/run/venv/lib/python3.4/site-packages/IPython/utils/py3compat.py", line 197, in doctest_refactor_print
    return _print_statement_re.sub(_print_statement_sub, doc)
TypeError: expected string or buffer
```

Please fix, or disable PYTHONOPTIMIZE or at the very least, add a early check to fail with a message

**Comment by takluyver** [comment]
`PYTHONOPTIMIZE=2` strips docstrings out of code, which doesn't make much sense when using IPython, and it's hard to imagine that there's any significant speedup in doing so. However, IPython should still be able to start, and #9171 fixes this.
