### ISSUE TITLE
ubuntu 15.10 IPython return "kernel dead"

### ISSUE THREAD

**Issue by trew100** [ipython/ipython#8972]
i try to run ipython and it's work well and open the home page of Jupyter/
when i open my notebook the "kernel dead" with this error

```
$ ipython notebook                  
[I 00:56:23.670 NotebookApp] Serving notebooks from local directory: /home/myuser
[I 00:56:23.670 NotebookApp] 0 active kernels 
[I 00:56:23.670 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 00:56:23.670 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 00:56:30.527 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "/usr/local/lib/python2.7/dist-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 244, in start_kernel
        **kw)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[E 00:56:30.534 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '77', 'Accept-Language': 'he,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python2', 'Content-Type': 'application/json; charset=UTF-8'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 454, in wrapper
        self.finish(json.dumps(reply))
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/usr/local/lib/python2.7/dist-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
        chunks = list(chunks)
      File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7f0f12a7a550> is not JSON serializable
[E 00:56:30.535 NotebookApp] Cannot send error response after headers written
[E 00:56:30.536 NotebookApp] Failed to flush partial response
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 960, in send_error
        self.finish()
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/usr/local/lib/python2.7/dist-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
        chunks = list(chunks)
      File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7f0f12a7a550> is not JSON serializable

```

how can i fix this?

**Comment by minrk** [comment]
What do you get from

    jupyter kernelspec list

**Comment by trew100** [comment]
$ jupyter kernelspec list
Available kernels:
  python2    /home/trew/.local/share/jupyter/kernels/python2

**Comment by trew100** [comment]
ok  it's work well
i jest removed kernel of python2 and all the file of ipython / jupyter
