### ISSUE TITLE
ValueError: invalid capstyle value

### ISSUE THREAD

**Issue by xiang-yu** [ipython/ipython#8998]
```
import matplotlib
import matplotlib.pyplot as plt
x=[1,2,3,4]
y=x
plt.plot(x,y)
```
version: '1.5.0'

operating system: Ubuntu 14.04 LST
```
Traceback (most recent call last):
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 176, in __draw_idle_agg
FigureCanvasAgg.draw(self)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 474, in draw
self.figure.draw(self.renderer)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
draw(artist, renderer, args, *kwargs)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/figure.py", line 1071, in draw
self.patch.draw(renderer)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
draw(artist, renderer, args, *kwargs)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/patches.py", line 522, in draw
renderer.draw_path(gc, tpath, affine, rgbFace)
File "/home/xiangyu/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 166, in draw_path
self._renderer.draw_path(gc, path, transform, rgbFace)
ValueError: invalid capstyle value

If you suspect this is an IPython bug, please report it at:
https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
%config Application.verbose_crash=True
```

**Comment by tacaswell** [comment]
This should probably be sent to the matplotlib-users@python.org mailing list (you will have to register to post unmoderated).  I suspect that you some how got invalid values into your `matplotlib.rcparams`

You can test this on tmpnb.org (which only has 1.4.3)

```python
%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt
x=[1,2,3,4]
y=x
plt.plot(x,y)
```

plots as expected.

Try running 

```python
matplotlib.rcdefaults()
```

before plotting.

**Comment by Carreau** [comment]
Thanks @tacaswell for tracking matplotlib issues on repos that are not your. Closing here. Feel free to reopen if we there is something we can do on our end.
