### ISSUE TITLE
Ipython notebook doesn't start on ubuntu 15.10

### ISSUE THREAD

**Issue by london111** [ipython/ipython#9115]
If I try to start ipython3 notebook I get the following error message on ubuntu 15.10. Any idea how to fix it?
```
2016-01-06 21:10:44.930 [NotebookApp] Using system MathJax
Traceback (most recent call last):
  File "/usr/bin/ipython3", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 564, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/html/notebookapp.py", line 773, in initialize
    self.init_webapp()
  File "/usr/lib/python3/dist-packages/IPython/html/notebookapp.py", line 667, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 182, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```
If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by minrk** [comment]
Does it work if you do:

    ipython notebook --ip=127.0.0.1

**Comment by london111** [comment]
Thanks, that works.

**Comment by minrk** [comment]
What version of IPython/Jupyter do you have? I believe the current version (4.0) handles this properly.

**Comment by Carreau** [comment]
This has been inactive for 10 days. I marked a "no actions" and close in a few days if no other comments. 
Thanks.

**Comment by takluyver** [comment]
Closing as we think it was already fixed. If someone reproduces this with the latest version of the notebook, please open a new issue on the jupyter/notebook repo.
