### ISSUE TITLE
tools/github_stats fails on 2fa. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9179]
```
$ python tools/github_stats.py --milestone 4.1 --since-tag 4.0.0
no cache
fetching GitHub stats since 2015-08-12 00:00:00 (tag: 4.0.0, milestone: 4.1)
Please enter your github username and password. These are not stored, only used to get an oAuth token. You can revoke this at any time on Github.
Username: *****
Password:*****
Traceback (most recent call last):
  File "github_stats.py", line 165, in <module>
    auth=True)
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 175, in get_milestone_id
    milestones = get_milestones(project, auth=auth, **params)
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 168, in get_milestones
    headers = make_auth_header()
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 73, in make_auth_header
    return {'Authorization': 'token ' + get_auth_token()}
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 67, in get_auth_token
    response.raise_for_status()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/authorizations
```

**Comment by Carreau** [comment]
I will tackle this one in a couple of hours with @parleur.

**Comment by Carreau** [comment]
Not always worth fixing, but once we handle 2fa the following can happen:

```
Traceback (most recent call last):
  File "tools/github_stats.py", line 173, in <module>
    issues = issues_closed_since(since, project=project, pulls=False)
  File "tools/github_stats.py", line 79, in issues_closed_since
    allclosed = get_paged_request(url, headers=make_auth_header())
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 80, in make_auth_header
    return {'Authorization': 'token ' + get_auth_token()}
  File "/Users/bussonniermatthias/dev/ipython/tools/gh_api.py", line 74, in get_auth_token
    response.raise_for_status()
  File "/Users/bussonniermatthias/anaconda3/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/authorizations
```

Which happen if the personal access token `IPython tools` already exists. Which for example can be the case if you change machines,or delete the token from your keychain.

**Comment by takluyver** [comment]
Yeah, it's annoying that the name has to be unique. Maybe we should try to use the hostname of the computer or something to make them more unique?

**Comment by Carreau** [comment]
> Yeah, it's annoying that the name has to be unique. Maybe we should try to use the hostname of the computer or something to make them more unique?

We can improve that later. It's really an edge case, and the unique name allow you to share your token in between computer if you really wants by syncing your key.db or whatever format it is.
