### ISSUE TITLE
ipython 4.1.0 installation

### ISSUE THREAD

**Issue by papachoco** [ipython/ipython#9208]
Hello, I am getting the error below while installing ipython 4.1.0 using zc.buildout (easy-install) . I think it needs to declare a dependency from traitlets

Carlos

"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-tUac6O/ipython-4.1.0/setupbase.py", line 154, in run
  File "/var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-tUac6O/ipython-4.1.0/setupbase.py", line 428, in run
  File "/var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-tUac6O/ipython-4.1.0/IPython/__init__.py", line 48, in <module>
  File "/var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-tUac6O/ipython-4.1.0/IPython/core/application.py", line 22, in <module>
ImportError: No module named traitlets.config.application

**Comment by takluyver** [comment]
We do specify a dependency, but possibly not in a way that easy_install picks up. Frankly, I don't think we should be accommodating easy_install - pip has been the recommended tool to use for years now.

**Comment by jakirkham** [comment]
FWIW, I also see this sort of issue with `pip`. It is also affecting me on Travis CI. Here is the log from a local install below.

```
$  pip install ipython
Downloading/unpacking ipython
  Downloading ipython-4.1.0.tar.gz (4.9Mb): 4.9Mb downloaded
  Running setup.py egg_info for package ipython
    
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.7/dist-packages (from ipython)
Downloading/unpacking decorator (from ipython)
  Downloading decorator-4.0.6.tar.gz (68Kb): 68Kb downloaded
  Running setup.py egg_info for package decorator
    
Downloading/unpacking pickleshare (from ipython)
  Downloading pickleshare-0.6.tar.gz
  Running setup.py egg_info for package pickleshare
    
Downloading/unpacking simplegeneric>0.8 (from ipython)
  Downloading simplegeneric-0.8.1.zip
  Running setup.py egg_info for package simplegeneric
    
Downloading/unpacking traitlets (from ipython)
  Downloading traitlets-4.1.0.tar.gz (76Kb): 76Kb downloaded
  Running setup.py egg_info for package traitlets
    
Downloading/unpacking pexpect (from ipython)
  Downloading pexpect-4.0.1.tar.gz (143Kb): 143Kb downloaded
  Running setup.py egg_info for package pexpect
    
Downloading/unpacking path.py>=6.2 (from pickleshare->ipython)
  Downloading path.py-8.1.2.tar.gz
  Running setup.py egg_info for package path.py
    
    Installed /build/path.py/setuptools_scm-1.10.1-py2.7.egg
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    
Downloading/unpacking ipython-genutils (from traitlets->ipython)
  Downloading ipython_genutils-0.1.0.tar.gz
  Running setup.py egg_info for package ipython-genutils
    
    warning: no directories found matching 'docs'
    warning: no previously-included files found matching 'docs/#*'
    warning: no directories found matching 'examples'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    no previously-included directories found matching 'docs/dist'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
Downloading/unpacking ptyprocess>=0.5 (from pexpect->ipython)
  Downloading ptyprocess-0.5.tar.gz
  Running setup.py egg_info for package ptyprocess
    
Installing collected packages: ipython, decorator, pickleshare, simplegeneric, traitlets, pexpect, path.py, ipython-genutils, ptyprocess
  Running setup.py install for ipython
    checking package data
    check version number
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/ipython/setup.py", line 296, in <module>
        main()
      File "/build/ipython/setup.py", line 293, in main
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setupbase.py", line 154, in run
        command.run(self)
      File "setupbase.py", line 428, in run
        import IPython.core.release as r
      File "IPython/__init__.py", line 48, in <module>
        from .core.application import Application
      File "IPython/core/application.py", line 22, in <module>
        from traitlets.config.application import Application, catch_config_error
    ImportError: No module named traitlets.config.application
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/ipython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-2Q7KCX-record/install-record.txt:
    running install

running build

running build_py

checking package data

check version number

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/build/ipython/setup.py", line 296, in <module>

    main()

  File "/build/ipython/setup.py", line 293, in main

    setup(**setup_args)

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "setupbase.py", line 154, in run

    command.run(self)

  File "setupbase.py", line 428, in run

    import IPython.core.release as r

  File "IPython/__init__.py", line 48, in <module>

    from .core.application import Application

  File "IPython/core/application.py", line 22, in <module>

    from traitlets.config.application import Application, catch_config_error

ImportError: No module named traitlets.config.application

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/ipython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-2Q7KCX-record/install-record.txt failed with error code 1
Storing complete log in /root/.pip/pip.log
```

**Comment by takluyver** [comment]
Sigh, executable install scripts are a pain. It's installing the necessary dependencies, but it's trying to install IPython before installing its dependencies.

Your version of pip is more than two years out of date - newer versions of pip prefer wheels, which don't suffer from this problem. So, start by doing:

```
pip install --upgrade pip
```

**Comment by jakirkham** [comment]
You're right. I am trying to figure out a way to reproduce this locally in a simpler manner, but I'm clearly not hitting the mark. Maybe it is just easier to show you what I am seeing. When trying to install `ipython`, it somehow doesn't get `traitlets` installed. I am using the 8.0.2 version of `pip` from `conda` here. This happens on multiple Python environments.

Here is the build log ( https://travis-ci.org/paulgb/runipy/jobs/106632660#L582-L727 )

**Comment by papachoco** [comment]
FWIW 4.0.3  did not present this issue

**Comment by takluyver** [comment]
@jakirkham the build is doing `setup.py install` - the official advice is to always do `pip install .` instead now. I know, it's stupid, but that's the way Python packaging goes.

@Carreau I think it's your changes to check the version number at build time that's causing this. We may need to back them out.

**Comment by takluyver** [comment]
#9209 should fix it.

**Comment by jakirkham** [comment]
Ah, I see. What a mess indeed. So, I tried doing `pip install .`, but I had a different problem where it somehow doesn't install `runipy` as an egg while expecting to find one, but I think this has nothing to with `ipython`. Though maybe you know what is going on here.

```
Traceback (most recent call last):
  File "/opt/conda/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/opt/conda/lib/python2.7/site-packages/pip/__init__.py", line 230, in main
    return command.main(cmd_args)
  File "/opt/conda/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
    pip_version_check(session)
  File "/opt/conda/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/opt/conda/lib/python2.7/site-packages/pip/utils/__init__.py", line 817, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__
    self.add_entry(entry)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2080, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1610, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1968, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1848, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/conda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1788, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/opt/conda/lib/python2.7/site-packages/runipy-0.1.5+5.g1f1380e-py2.7.egg'
```

Running `pip install .` again not only works fine, but complains that `runipy` is installed correctly. Log snippet from the problem portion below.

**Comment by takluyver** [comment]
That looks like some generic Python packaging fail. No idea what state it's managed to get itself into.

**Comment by jakirkham** [comment]
Figured it out. I had `python setup.py install` so it got confused when running `pip install .` as there was some build cruft generated from the former that the latter didn't know what to do with. If I clean up this build cruft or start fresh, the problem resolves itself.
