### ISSUE TITLE
SSL Error when connecting to notebook server 

### ISSUE THREAD

**Issue by j-greer** [ipython/ipython#9212]
When trying to access the notebook server I receive one of two errors. 

Either:

`2016-02-04 09:29:38.017 [NotebookApp] Using existing profile dir: u'/home/ubuntu/.ipython/profile_nospark'
2016-02-04 09:29:38.022 [NotebookApp] Using system MathJax
2016-02-04 09:29:38.026 [NotebookApp] The port 8888 is already in use, trying another random port.
2016-02-04 09:29:38.027 [NotebookApp] Serving notebooks from local directory: /home/ubuntu
2016-02-04 09:29:38.027 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8889/
2016-02-04 09:29:38.027 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2016-02-04 09:29:56.436 [tornado.general] WARNING | SSL Error on 3 ('88.151.155.34', 64996): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
WARNING:tornado.general:SSL Error on 3 ('88.151.155.34', 64996): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
2016-02-04 09:30:45.822 [tornado.general] WARNING | SSL Error on 3 ('88.151.155.34', 64997): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
WARNING:tornado.general:SSL Error on 3 ('88.151.155.34', 64997): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
2016-02-04 09:30:47.346 [tornado.general] WARNING | SSL Error on 3 ('88.151.155.34', 64998): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
WARNING:tornado.general:SSL Error on 3 ('88.151.155.34', 64998): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
2016-02-04 09:30:48.158 [tornado.general] WARNING | SSL Error on 3 ('88.151.155.34', 64999): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
WARNING:tornado.general:SSL Error on 3 ('88.151.155.34', 64999): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request

2016-02-04 09:41:19.562 [tornado.general] WARNING | SSL Error on 3 ('88.151.155.34', 65166): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
WARNING:tornado.general:SSL Error on 3 ('88.151.155.34', 65166): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request`

In which case I am not able to connect to the notebook at all from my browser (I've tried both Firefox and Chrome)

I am sometimes able to connect to a notebook, albeit an ipython notebook (rather than jupyter which I was getting before these issues started).

When this happens I'm able to create new notebooks but not able to view some of my older ones

In such case I still receive an errror

`
2016-02-04 09:23:39.055 [NotebookApp] CRITICAL | Shutdown confirmed
2016-02-04 09:23:39.056 [NotebookApp] Shutting down kernels
ubuntu@ip-172-31-47-46:~/.ipython/profile_nospark$ vim ipython_notebook_config.py
ubuntu@ip-172-31-47-46:~/.ipython/profile_nospark$ ipython notebook --profile=nospark
2016-02-04 09:24:08.506 [NotebookApp] Using existing profile dir: u'/home/ubuntu/.ipython/profile_nospark'
2016-02-04 09:24:08.510 [NotebookApp] Using system MathJax
2016-02-04 09:24:08.515 [NotebookApp] The port 8888 is already in use, trying another random port.
2016-02-04 09:24:08.515 [NotebookApp] Serving notebooks from local directory: /home/ubuntu/.ipython/profile_nospark
2016-02-04 09:24:08.515 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8889/
2016-02-04 09:24:08.515 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2016-02-04 09:24:26.548 [tornado.general] WARNING | error on read
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 391, in _handle_read
    if self._read_to_buffer() == 0:
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 447, in _read_to_buffer
    chunk = self.read_from_fd()
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 911, in read_from_fd
    chunk = self.socket.read(self.read_chunk_size)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
WARNING:tornado.general:error on read
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 391, in _handle_read
    if self._read_to_buffer() == 0:

  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 447, in _read_to_buffer
    chunk = self.read_from_fd()

  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 911, in read_from_fd
    chunk = self.socket.read(self.read_chunk_size)

  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)

SSLError: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
`

**Comment by minrk** [comment]
What browser/OS are you using? What do you get from `pip list`? Are you certainly connecting to the notebook with HTTPS and not HTTP? HTTP requests to HTTPS servers are known to cause log messages similar to this.

**Comment by j-greer** [comment]
I'm trying to remotely access an ubuntu 14.0 instance and I've tried both firefox and chrome.

ubuntu@ip-172-31-47-46:~$ /usr/local/bin/pip list
apt-xapian-index (0.45)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
beautifulsoup4 (4.2.1)
bokeh (0.9.0)
certifi (2015.11.20.1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.3.3)
configobj (4.7.2)
cvxopt (1.1.4)
data-samples (0.1)
decorator (3.4.0)
Flask (0.10.1)
functools32 (3.2.3.post1)
gevent (1.0.2)
gevent-websocket (0.9.5)
greenlet (0.4.7)
html5lib (0.999)
ipykernel (4.2.2)
ipython (4.1.0)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
itsdangerous (0.24)
Jinja2 (2.7.2)
joblib (0.7.1)
jsonpatch (1.3)
jsonpointer (1.0)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.1.0)
jupyter-core (4.0.6)
Landscape-Client (14.12)
Markdown (2.6.2)
MarkupSafe (0.18)
matplotlib (1.3.1)
mistune (0.7.1)
MySQL-python (1.2.3)
nbconvert (4.1.0)
nbformat (4.0.1)
nltk (3.0.2)
nose (1.3.1)
notebook (4.1.0)
numexpr (2.2.2)
numpy (1.9.2)
oauth (1.0.1)
openpyxl (1.7.0)
PAM (0.4.2)
pandas (0.17.1)
path.py (8.1.2)
patsy (0.2.1)
pexpect (3.1)
pickleshare (0.6)
Pillow (2.3.0)
pip (8.0.2)
prettytable (0.7.2)
ptyprocess (0.5.1)
pycurl (7.19.3)
Pygments (2.0.2)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyserial (2.6)
pystache (0.5.4)
python-apt (0.9.3.5ubuntu1)
python-dateutil (2.4.2)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012rc0)
PyYAML (3.10)
pyzmq (14.6.0)
qtconsole (4.1.1)
requests (2.2.1)
scikit-learn (0.16.1)
scipy (0.15.1)
seaborn (0.5.1)
setuptools (19.7)
simplegeneric (0.8.1)
simplejson (3.3.1)
singledispatch (3.4.0.3)
six (1.10.0)
ssh-import-id (3.21)
statsmodels (0.5.0)
sympy (0.7.4.1)
tables (3.1.1)
terminado (0.6)
tornado (4.3)
traitlets (4.1.0)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
ua-parser (0.3.6)
urllib3 (1.7.1)
user-agents (0.3.2)
websocket (0.2.1)
Werkzeug (0.10.4)
xlrd (0.9.2)
xlwt (0.7.5)
zope.interface (4.0.5)

**Comment by minrk** [comment]
what do you get from `curl -v https://127.0.0.1:8888` when this is running?

**Comment by ivanov** [comment]
I'm closing this issue due to inactivity. Feel free to open a new issue with [jupyter/notebook](https://github.com/jupyter/notebook) if the problem persists.
