### ISSUE TITLE
ImportError: No module named notebook.utils

### ISSUE THREAD

**Issue by dsharpen** [ipython/ipython#9218]
➜  Application Support  sudo ipcluster nbextension enable
Traceback (most recent call last):
  File "/usr/local/bin/ipcluster", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 622, in start
    return self.subapp.start()
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 582, in start
    from ipyparallel.nbextension.install import install_server_extension
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/nbextension/**init**.py", line 1, in <module>
    from .handlers import load_jupyter_server_extension
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/nbextension/handlers.py", line 12, in <module>
    from notebook.utils import url_path_join as ujoin
ImportError: No module named notebook.utils

**Comment by minrk** [comment]
@dsharpen what do you get from `pip list`? Perhaps you need to add `pip install notebook` first.

**Comment by kondor6c** [comment]
Replicated the original error and confirmed that installing notebook first resolves this issue,
```
[kondor6c@horse ~]$ sudo ipcluster nbextension start
Traceback (most recent call last):
  File "/bin/ipcluster", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 641, in start
    return self.subapp.start()
  File "/usr/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 598, in start
    from ipyparallel.nbextension.install import install_extensions
  File "/usr/lib/python2.7/site-packages/ipyparallel/nbextension/__init__.py", line 1, in <module>
    from .handlers import load_jupyter_server_extension
  File "/usr/lib/python2.7/site-packages/ipyparallel/nbextension/handlers.py", line 12, in <module>
    from notebook.utils import url_path_join as ujoin
ImportError: No module named notebook.utils

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
#After pip install notebook
[kondor6c@horse ~]$ sudo ipcluster nbextension enable
Enabling IPython clusters tab
[kondor6c@horse ~]$ 
```

**Comment by minrk** [comment]
@kondor6c thanks!

**Comment by teravaidya** [comment]
I still face issue after "sudo ipcluster nbextension start" command
