### ISSUE TITLE
`pip install ipython[notebook]` breaks ssl for python

### ISSUE THREAD

**Issue by shackenberg** [ipython/ipython#9220]
#Hi,

my issue is, that it seems that something in iPython or its requirements breaks ssl for python on my machine:

Used version:
- Ubuntu 14.04
- Python 2.7.6
- iPython 4.1.1

These are the steps to recreate the error message:
```
virtualenv debug
source debug/bin/activate
pip install requests
python -c "import requests; requests.get('https://www.google.com')"
```
the last command results in `insecureplatformwarning` + `snimissingwarning` which I fix according to the [documentation](http://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) with 

```
pip install ndg-httpsclient --upgrade
```
I then run
```
python -c "import requests; requests.get('https://www.google.com')"
``` 
which returns without output which tells me that it worked.
I then I try the globally installed ipython notebook and get following warning:
```
ipython -c "import requests; requests.get('https://www.google.com')"
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Out[1]: <Response [200]>
```
To fixt that warning I install ipython in the virtualenv with 
```
pip install ipython[notebook]
```
But then when I try the request again I get following error:
```
python -c "import requests; requests.get('https://www.google.com')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ludwig/envs/debug/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ludwig/envs/debug/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ludwig/envs/debug/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ludwig/envs/debug/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/ludwig/envs/debug/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
```

**Comment by minrk** [comment]
Can you share `pip list` before/after? It's presumably a dependency that's getting pulled in that's causing it.

**Comment by minrk** [comment]
I have been able to reproduce this. The culprit is the `certifi` package, which is a dependency of tornado, the webserver the IPython notebook uses. When I run the example, I get the following probably-relevant warnings from requests:

```
(debug) user@229b335c7df5:/# python -c "import requests; requests.get('https://www.google.com')"
/debug/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/debug/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

I'm guessing the "may cause certain SSL connections to fail" is relevant here. SSLContext was backported to Python 2.7.9 as a security fix, and may be what's needed here. There might be a question for either the certifi or requests folks for why there is an error.

**Comment by shackenberg** [comment]
Okay, so I will close this issue here as I understand nothing can be done from the ipython side.
