### ISSUE TITLE
El Capitan, SIP, and pip install sadness

### ISSUE THREAD

**Issue by scub** [ipython/ipython#9222]
The following can be observed when using pip to install ipython as described by the documentation. This was a fresh install of El Capitan using pip 8.0.2 and is seemingly due to the recently implemented [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection). 

By specifying '--user python' we ensure that pip is using the correct user for these operations. You may wish to note this caveat in the OSX section, in addition that specifying '--user python' when using pip - otherwise the reinstall of setuptools fails mid-run.

```
$ pip install ipython[all]
 ...
>ipython[all])
Installing collected packages: setuptools, appnope, ptyprocess, pexpect, nose, backports.ssl-match-hostname, singledispatch, certifi, backports-abc, tornado, jupyter-core, pyzmq, jupyter-client, futures, ipykernel, ipyparallel, pygments, functools32, jsonschema, nbformat, mistune, MarkupSafe, jinja2, nbconvert, terminado, notebook, ipywidgets, requests, babel, snowballstemmer, sphinx-rtd-theme, docutils, alabaster, Sphinx, testpath, qtconsole, ipython
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.0.2-py2.7.egg/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/var/folders/yn/9fd58xw17zl7g8_zq2zh892w0000gn/T/pip-2AeIsl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

```
$ pip install ipython[all] --user python
...
>ipython[all])
Installing collected packages: setuptools, appnope, ptyprocess, pexpect, nose, backports.ssl-match-hostname, singledispatch, certifi, backports-abc, tornado, jupyter-core, pyzmq, jupyter-client, futures, ipykernel, ipyparallel, pygments, functools32, jsonschema, nbformat, mistune, MarkupSafe, jinja2, nbconvert, terminado, notebook, ipywidgets, requests, babel, snowballstemmer, sphinx-rtd-theme, docutils, alabaster, Sphinx, testpath, qtconsole, ipython
  Running setup.py install for pexpect ... done
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for tornado ... done
  Running setup.py install for functools32 ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for terminado ... done
  Running setup.py install for docutils ... done
Successfully installed MarkupSafe Sphinx alabaster appnope babel backports-abc backports.ssl-match-hostname certifi docutils functools32 futures ipykernel ipyparallel ipython ipywidgets jinja2 jsonschema jupyter-client jupyter-core mistune nbconvert nbformat nose notebook pexpect ptyprocess pygments pyzmq qtconsole requests setuptools-1.1.6 singledispatch snowballstemmer sphinx-rtd-theme terminado testpath tornado

**Comment by mumrah** [comment]
Once installing using this procedure, how do you launch ipython?

**Comment by minrk** [comment]
It's *really* strongly advised against installing things with the System Python on OS X. You can get a working Python installation from Python.org or conda or brew (...or canopy or brew cask, or macports, or ...).

But if you really want to use it, you will need to add `/Library/Python/2.7/bin` to your PATH, since that's where it puts executables.

**Comment by vqgxie** [comment]
I have the same problem after installing, how to launch ipython?

**Comment by minrk** [comment]
@vqgxie makes sure that where your Python installs scripts is on your PATH, then type `ipython`. Alternately, you can type `python -m IPython`.

**Comment by vanallen** [comment]
This arises because of System Integrity Protection. I found this solution very helpful.
http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade
