### ISSUE TITLE
Complex gnureadline requirement breaks application startup 

### ISSUE THREAD

**Issue by miohtama** [ipython/ipython#9311]
For some reason `gnureadline` requirement breaks a Python application startup. Something inside Python itself breaks during `pkg_resources.load_entry_point` call. This is regardless which Python package you load through `load_entry_point`.

The violation spec is `Requires-Dist: gnureadline; sys.platform == 'darwin' and platform.python_implementation == 'CPython'` (see below).

IPython 3.2.3.

Ubuntu 14.04.

Python 3.5.

This is definitely something related to Python environment, but I have no idea how to repeat yet.

Python traceback when starting application (non pip install)::

    Traceback (most recent call last):
      File "/srv/pyramid/xxx/venv/bin/ws-alembic", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2912, in <module>
        @_call_aside
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
        f(*args, **kwargs)
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 642, in _build_master
        ws.require(__requires__)
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 838, in resolve
        new_requirements = dist.requires(req.extras)[::-1]
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2462, in requires
        dm = self._dep_map
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2686, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2696, in _compute_dependencies
        current_req = packaging.requirements.Requirement(req)
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
        raise InvalidRequirement(
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; sys.pl'"

Traced back it to this line::

    venv/lib64/python3.5/site-packages/ipython-3.2.3.dist-info/METADATA:Requires-Dist: gnureadline; sys.platform == 'darwin' and platform.python_implementation == 'CPython'

Removing the line and similar lines which have complex requirement definitions  cures the situation.

**Comment by minrk** [comment]
Looks like setuptools is outdated. Try:

    pip install --upgrade setuptools pip

**Comment by miohtama** [comment]
@minrk: Perfect will try upgrade later today. Do you remember out of the bat which setuptools version fixes this, so I can pin down relative dependency in the application?

**Comment by minrk** [comment]
18.5, I think.

**Comment by miohtama** [comment]
Looks like something is broken. I get the same error with Python 3.5 and setuptools 20.2.2 (installed with easy_install for just in case pip install doesn't get the latest version):

      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 2898, in _call_aside
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 642, in _build_master
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 943, in require
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 838, in resolve
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 2462, in requires
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 2686, in _dep_map
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/__init__.py", line 2696, in _compute_dependencies
      File "/srv/pyramid/xxx/venv/lib/python3.5/site-packages/setuptools-20.2.2-py3.5.egg/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; sys.pl'"

**Comment by miohtama** [comment]
Ah looks like it has gone stackoverflow:

http://stackoverflow.com/q/35625488/315168

Setuptools 20.2.1 is broken. Downgrade.

**Comment by miohtama** [comment]
Moving to setuptools discussions:

https://bitbucket.org/pypa/setuptools/issues/502/packaging-164-does-not-allow-whitepace
