### ISSUE TITLE
Issue when starting ipython3

### ISSUE THREAD

**Issue by ohreooo** [ipython/ipython#9319]
Whenever I try to start ipython3, this message would show up:

duque@ua11:~>ipython3
Traceback (most recent call last):
  File "/usr/bin/ipython3", line 9, in <module>
    load_entry_point('ipython==1.2.1', 'console_scripts', 'ipython3')()
  File "/usr/lib/python3/dist-packages/IPython/**init**.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, *_kwargs)
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 545, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, *_kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 323, in initialize
    self.init_shell()
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 339, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/usr/lib/python3/dist-packages/IPython/config/configurable.py", line 349, in instance
    inst = cls(_args, *_kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 320, in **init**
    *_kwargs
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 457, in **init**
    self.init_history()
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 1481, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 481, in **init**
    self.new_session()
  File "<string>", line 2, in new_session
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 65, in needs_sqlite
    return f(self, *a, *_kw)
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 500, in new_session
    self.session_number = cur.lastrowid
sqlite3.OperationalError: database is locked

**Comment by takluyver** [comment]
It looks like you're using an old version of IPython - I'd recommend upgrading to the latest, which should catch this error and start without saving history.

You may be able to work around it by moving or removing the history database file, which by default you can find in `~/.ipython/profile_default/history.sqlite`. It will automatically create a new database if that file is not there.

**Comment by Carreau** [comment]
This issue has been inactive for about a year. Closing. Feel free to reopen if you still have this issue.
