### ISSUE TITLE
NameError while using IPDB

### ISSUE THREAD

**Issue by ktho22** [ipython/ipython#9332]
Hi all,

Though I;m not quite sure that this bug is caused by Ipython,
I got below error for using 'python -m ipdb script.py'

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/lib/python2.7/dist-packages/ipdb/__main__.py", line 217, in <module>
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/ipdb/__main__.py", line 200, in main
>     except Restart:
> NameError: global name 'Restart' is not defined

I installed ipython 4.1.2 and ipdb 0.9.0 on ubuntu 14.04.
Thank you in advance.

**Comment by takluyver** [comment]
Sounds like an issue in [ipdb](https://github.com/gotcha/ipdb).
