### ISSUE TITLE
unexisting variable self.log

### ISSUE THREAD

**Issue by aongenae** [ipython/ipython#9351]
because of a corrupt sqlite db, I hit the following piece of code in 
`IPython/core/history.py`
https://github.com/ipython/ipython/blob/master/IPython/core/history.py#L520

`self.log` does not seems to exists.

Here is the trace:
```
└─⊳ ipython
Traceback (most recent call last):
  File "/home/aongenae/newenv/bin/ipython", line 9, in <module>
    load_entry_point('ipython', 'console_scripts', 'ipython')()
  File "/home/aongenae/ipython/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/aongenae/newenv/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "/home/aongenae/newenv/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/aongenae/ipython/IPython/terminal/ipapp.py", line 305, in initialize
    self.init_shell()
  File "/home/aongenae/ipython/IPython/terminal/ipapp.py", line 321, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/aongenae/newenv/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/aongenae/ipython/IPython/terminal/ptshell.py", line 238, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/aongenae/ipython/IPython/core/interactiveshell.py", line 466, in __init__
    self.init_history()
  File "/home/aongenae/ipython/IPython/core/interactiveshell.py", line 1581, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/home/aongenae/ipython/IPython/core/history.py", line 520, in __init__
    self.log.error("Failed to create history session in %s. History will not be saved.",
AttributeError: 'HistoryManager' object has no attribute 'log'
```

**Comment by takluyver** [comment]
Thanks, #9352 should fix that.

**Comment by makmanalp** [comment]
Just pinging to say that I hit something like this today with 4.1.1:

```
Traceback (most recent call last):
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 518, in __init__
    self.new_session()
  File "<decorator-gen-21>", line 2, in new_session
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 68, in needs_sqlite
    return f(self, *a, **kw)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 545, in new_session
    self.session_number = cur.lastrowid
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 306, in initialize
    self.init_shell()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 322, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 465, in __init__
    self.init_history()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1586, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 520, in __init__
    self.log.error("Failed to create history session in %s. History will not be saved.",
AttributeError: 'HistoryManager' object has no attribute 'log'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

Bumping to 4.2.0 got me a more different message:

```
[TerminalIPythonApp] ERROR | Failed to create history session in /nfs/home/M/makmanalp/.ipython/profile_default/history.sqlite. History will not be saved.
Traceback (most recent call last):
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 518, in __init__
    self.new_session()
  File "<decorator-gen-21>", line 2, in new_session
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 68, in needs_sqlite
    return f(self, *a, **kw)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 545, in new_session
    self.session_number = cur.lastrowid
sqlite3.OperationalError: database is locked
Traceback (most recent call last):
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    self.init_shell()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 321, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 483, in __init__
    self.init_readline()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 435, in init_readline
    self.refill_readline_hist()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 470, in refill_readline_hist
    include_latest=True):
  File "<decorator-gen-18>", line 2, in get_tail
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 90, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 335, in get_tail
    self.writeout_cache()
  File "<decorator-gen-22>", line 2, in writeout_cache
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 68, in needs_sqlite
    return f(self, *a, **kw)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 755, in writeout_cache
    self._writeout_input_cache(conn)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/peru/env/lib/python3.4/site-packages/IPython/core/history.py", line 739, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.OperationalError: database is locked

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```

**Comment by makmanalp** [comment]
The solution, for posterity, was doing something like this: 

`echo ".dump" | sqlite3 history.sqlite | sqlite3 new.db` and then swapping the new file in place of the old one.

http://stackoverflow.com/a/7740613

No process seemed to be reading the file, and I couldn't find a way to reset the lock otherwise - might be a weird NFS thing.

**Comment by makmanalp** [comment]
Looks like #9418 might be a decent enough workaround for this, even though I think it'd mean losing the history.

**Comment by takluyver** [comment]
Yeah, if something goes wrong with the database file, the automated options we have all lose it. SQLite has known issues with NFS, though I think it depends on the configuration and possibly the implementation.

**Comment by debboutr** [comment]
I get the same thing after stopping a console while in process:

    C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda>ipython --deep-reload
Traceback (most recent call last):
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(IPython.start_ipython())
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\traitlets\config\application.py", line 595, in launch_i
nstance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\traitlets\config\application.py", line 74, in catch_con
fig_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\terminal\ipapp.py", line 306, in initialize
    self.init_shell()
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\terminal\ipapp.py", line 322, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\traitlets\config\configurable.py", line 405, in instanc
e
    inst = cls(*args, **kwargs)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 465, in __init_
_
    self.init_history()
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 1586, in init_h
istory
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "C:\Users\Rdebbout\AppData\Local\Continuum\Anaconda\lib\site-packages\IPython\core\history.py", line 520, in __init__
    self.log.error("Failed to create history session in %s. History will not be saved.",
AttributeError: 'HistoryManager' object has no attribute 'log'

**Comment by minrk** [comment]
What is `ipython --version`? History does have `self.log` in current IPython (4.2).
