### ISSUE TITLE
issues with automount sec=krb for user home

### ISSUE THREAD

**Issue by steverweber** [ipython/ipython#9380]
fresh install ubuntu16.04 beta
```
apt-get install -y python3-pip
apt-get install -y nodejs-legacy
apt-get install -y npm
npm install -g configurable-http-proxy
pip3 install setuptools
pip3 install jupyterhub
pip3 install --upgrade notebook

jupyterhub --generate-config
jupyterhub --config=./jupyterhub_config.py --no-ssl
```
works:
 - point browser at localhost:8000 and login.
 - browse around home dir 
 - create text files edat and save
 - test terminal

fails:
 - attempted to create python3 notebook
```
[I 2016-04-06 20:48:40.770 s8weber log:47] 302 GET /user/s8weber (127.0.0.1) 0.54ms
[I 2016-04-06 20:48:40.771 JupyterHub base:301] User s8weber server took 0.613 seconds to start
[I 2016-04-06 20:48:40.771 JupyterHub orm:159] Adding user s8weber to proxy /user/s8weber => http://127.0.0.1:35474
[I 2016-04-06 20:48:40.780 JupyterHub log:100] 302 POST /hub/login?next=%2Fhub%2Fuser%2Fs8weber%2Ftree (@::ffff:172.16.37.150) 782.62ms
[I 2016-04-06 20:48:40.780 JupyterHub login:79] User logged in: s8weber
[I 2016-04-06 20:48:40.822 JupyterHub log:100] 302 GET /hub/user/s8weber/tree (s8weber@::ffff:172.16.37.150) 4.29ms
[I 2016-04-06 20:48:40.868 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-s8weber/[secret] (s8weber@127.0.0.1) 7.86ms
[I 2016-04-06 20:48:47.561 s8weber handlers:170] Creating new notebook in 
[E 2016-04-06 20:48:52.593 s8weber filemanager:406] Error while saving file: Untitled.ipynb database is locked
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'db'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 391, in save
        self.check_and_sign(nb, path)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/usr/local/lib/python3.5/dist-packages/nbformat/sign.py", line 246, in sign
        self.store_signature(signature, nb)
      File "/usr/local/lib/python3.5/dist-packages/nbformat/sign.py", line 249, in store_signature
        if self.db is None:
      File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/usr/local/lib/python3.5/dist-packages/nbformat/sign.py", line 127, in _db_default
        self.init_db(db)
      File "/usr/local/lib/python3.5/dist-packages/nbformat/sign.py", line 139, in init_db
        )""")
    sqlite3.OperationalError: database is locked
[W 2016-04-06 20:48:52.594 s8weber handlers:463] Unexpected error while saving file: Untitled.ipynb database is locked
[E 2016-04-06 20:48:52.595 s8weber log:46] {
      "Origin": "http://jupyterhub-d01.math.cccc.ca:8000",
      "X-Forwarded-For": "::ffff:172.16.37.150",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Cookie": "jupyter-hub-token-s8weber=\"2|1:0|10:1459990120|25:jupyter-hub-token-s8weber|44:cccc=|cccccccc\"; _ga=GA1.2.1253018859.1458606729",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-Proto": "http",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Type": "application/json",
      "Referer": "http://jupyterhub-d01.math.cccc.ca:8000/user/s8weber/tree",
      "Accept-Language": "en-US,en;q=0.8",
      "Connection": "close",
      "Host": "jupyterhub-d01.math.cccc.ca:8000",
      "Content-Length": "19"
    }
```

The users home directory is auto-mounted and uses sec=krb... but that don't seem to cause issues when creating normal text files...

If I login using a local system account I don't get this error.

**Comment by steverweber** [comment]
disregard... added mount option nolock for cifs.

**Comment by minrk** [comment]
Glad you figured it out! Hopefully this will serve to help the next person who runs into this.
