### ISSUE TITLE
ipdb set_trace

### ISSUE THREAD

**Issue by batmanatucsd** [ipython/ipython#9393]
Traceback (most recent call last):
  File "prime.py", line 54, in <module>
    main()
  File "prime.py", line 46, in main
    print isprime(eval(raw_input("input: ")))
  File "prime.py", line 33, in isprime
    import ipdb; ipdb.set_trace()  # XXX BREAKPOINT
  File "/usr/lib/python2.7/site-packages/ipdb/__main__.py", line 133, in set_trace
    p.shell.restore_sys_module_state()
AttributeError: 'NoneType' object has no attribute 'shell'

I don't really know what p.shell.restore_sys_module_state() do, but after commenting that line out from the __main__.py file, everything started to work fine.
For reference, p was an instance of IPython.core.debugger.

**Comment by takluyver** [comment]
ipdb is a separate project. It looks like the same issue has been reported there: gotcha/ipdb#93
