### ISSUE TITLE
IPython interactive crash when redirecting output.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9402]
Yes, I know it is stupid, but still:

```python
$ ipython > foo
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 368, in run
    self._redraw()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 327, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/renderer.py", line 389, in render
    size = output.get_size()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/terminal/vt100_output.py", line 352, in get_size
    rows, columns = _get_size(stdout.fileno())
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/terminal/vt100_output.py", line 317, in _get_size
    fcntl.ioctl(fileno, termios.TIOCGWINSZ, buf, True)
OSError: [Errno 25] Inappropriate ioctl for device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/bin/ipython", line 9, in <module>
    load_entry_point('ipython', 'console_scripts', 'ipython')()
  File "/Users/bussonniermatthias/dev/ipython/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/bussonniermatthias/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ipapp.py", line 344, in start
    self.shell.mainloop()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ptshell.py", line 335, in mainloop
    self.interact()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ptshell.py", line 318, in interact
    code = self.prompt_for_code()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ptshell.py", line 263, in prompt_for_code
    document = self.pt_cli.run(pre_run=self.pre_prompt)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 380, in run
    self._redraw()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/interface.py", line 327, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/renderer.py", line 389, in render
    size = output.get_size()
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/terminal/vt100_output.py", line 352, in get_size
    rows, columns = _get_size(stdout.fileno())
  File "/Users/bussonniermatthias/dev/python-prompt-toolkit/prompt_toolkit/terminal/vt100_output.py", line 317, in _get_size
    fcntl.ioctl(fileno, termios.TIOCGWINSZ, buf, True)
OSError: [Errno 25] Inappropriate ioctl for device

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by minrk** [comment]
Most applications disable interactive mode when they detect that they are being piped. We could restrict this to `ipython script.py > foo`, and show only `No script specified` if you do what you typed.

Interestingly enough, `python > foo` seems to start the interpreter as normal, ignoring the pipe. Not sure how that works.

**Comment by takluyver** [comment]
Yeah, I think it's fine to just have a shorter, clearer error message in that case - `ipython > foo` without a script name doesn't really make any sense.

> python > foo seems to start the interpreter as normal, ignoring the pipe. Not sure how that works.

I'd guess it opens the controlling tty directly, bypassing stdout.

**Comment by Carreau** [comment]
even non interactive crash:
```
ipython foo.py > xxx
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda/bin/ipython", line 9, in <module>
    load_entry_point('ipython', 'console_scripts', 'ipython')()
  File "/Users/bussonniermatthias/dev/ipython/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ipapp.py", line 305, in initialize
    self.init_shell()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ipapp.py", line 321, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ptshell.py", line 346, in __init__
    self.init_term_title()
  File "/Users/bussonniermatthias/dev/ipython/IPython/terminal/ptshell.py", line 149, in init_term_title
    set_term_title('IPython: ' + abbrev_cwd())
  File "/Users/bussonniermatthias/dev/ipython/IPython/utils/terminal.py", line 111, in set_term_title
    _set_term_title(title)
  File "/Users/bussonniermatthias/dev/ipython/IPython/utils/terminal.py", line 74, in _set_term_title_xterm
    sys.stdout.write('\033]0;%s\007' % title)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/colorama/ansitowin32.py", line 163, in write_and_convert
    text = self.convert_osc(text)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/colorama/ansitowin32.py", line 235, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by takluyver** [comment]
Why TF is it going through colorama? That's only supposed to happen in a Windows command prompt!

**Comment by Carreau** [comment]
Ho, I did not even spotted that. Trying to debug your other PR were `_eventloop` does not exists.

**Comment by Carreau** [comment]
> Why TF is it going through colorama? That's only supposed to happen in a Windows command prompt!

I've narrowed it down :

```
if isinstance(sys.stdout, colorama.ansitowin32.StreamWrapper): raise ValueError('OhNow')
```

To `import jedi`.

**Comment by Carreau** [comment]
Found offender openned upstream, https://github.com/davidhalter/jedi/issues/724

**Comment by Carreau** [comment]
This seem fixed on master... for whatever reason... closing.

**Comment by Suor** [comment]
Still having this.

**Comment by Kache** [comment]
I'm also encountering this, don't have a minimal repro yet, but running a module like:

```python
python -m foo.prints_to_stdout | head
```

and hitting a breakpoint via IPython debugger inside will crash in the same way

**Comment by MrMino** [comment]
@Kache @Suor which IPython / Python versions are you using?

**Comment by Suor** [comment]
Tried now, it works as expected no crash.

**Comment by Kache** [comment]
Hm, actually getting different error this time

I have: ipython 7.22.0, python 3.7.10

Example file:

```python
from IPython.terminal.debugger import set_trace
# import pretty_errors  # just for nicer error output

print("asdf")

# breakpoint()  # if using export PYTHONBREAKPOINT=IPython.terminal.debugger.set_trace
set_trace()

# import pdb; pdb.set_trace()  # no problems

print("asdf")
```

calling with: `python -m foo.bar | head`:

```sh
asdf

-------------------------------------------------------------------------------
runpy.py 193 _run_module_as_main
"__main__", mod_spec)

runpy.py 85 _run_code
exec(code, run_globals)

foo.py 7 <module>
set_trace()

debugger.py 149 set_trace
TerminalPdb().set_trace(frame or sys._getframe().f_back)

debugger.py 30 __init__
Pdb.__init__(self, *args, **kwargs)

debugger.py 237 __init__
self.shell = TerminalInteractiveShell.instance()

configurable.py 537 instance
inst = cls(*args, **kwargs)

interactiveshell.py 527 __init__
self.init_term_title()

interactiveshell.py 269 init_term_title
set_term_title(self.term_title_format.format(cwd=abbrev_cwd()))

terminal.py 112 set_term_title
_set_term_title(title)

terminal.py 69 _set_term_title_xterm
sys.stdout.write('\033]0;%s\007' % title)

ansitowin32.py 41 write
self.__convertor.write(text)

ansitowin32.py 162 write
self.write_and_convert(text)

ansitowin32.py 184 write_and_convert
text = self.convert_osc(text)

ansitowin32.py 257 convert_osc
winterm.set_title(params[1])

AttributeError:
'NoneType' object has no attribute 'set_title'
```

**Comment by Carreau** [comment]
Please give more than just the filename, I'm not sure which package it belongs to. We have no file `ansitowin32.py` in IPython itself.
