### ISSUE TITLE
Exception thrown without source code available

### ISSUE THREAD

**Issue by MiguelLatorre** [ipython/ipython#9486]
I got a reproducible crash, apparently when ipython tries to locate the source code (which does not exist).
The referenced file `/tmp/zipper/dbtaric.dat` is a zip file used through **zipimport.zipimporter**

```
ipython --version: 4.2.0
uname -a: Linux l034int 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux

Traceback` (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-bee41c3a1cc0>", line 1, in <module>
    db.countries['KK']
  File "countries.py", line 49, in __getitem__
KeyError: 'KK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1827, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2831, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2902, in run_code
    self.showtraceback()
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1830, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1394, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1302, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1152, in structured_traceback
    tb_offset)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1103, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 835, in format_records
    frames.append(self.format_record(*r))
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 925, in format_record
    file = openpy.source_from_cache(file)
  File "<frozen importlib._bootstrap_external>", line 302, in source_from_cache
ValueError: __pycache__ not bottom-level directory in '/tmp/zipper/dbtaric.dat/py3_logic_dbtaric/countries.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1827, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 344, in start
    self.shell.mainloop()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 550, in mainloop
    self.interact(display_banner=display_banner)
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 674, in interact
    self.run_cell(source_raw, store_history=True)
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    self.showtraceback()
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1830, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1394, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1302, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1171, in structured_traceback
    chained_exceptions_tb_offset)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 1103, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 835, in format_records
    frames.append(self.format_record(*r))
  File "/usr/lib/python3.5/site-packages/IPython/core/ultratb.py", line 925, in format_record
    file = openpy.source_from_cache(file)
  File "<frozen importlib._bootstrap_external>", line 302, in source_from_cache
ValueError: __pycache__ not bottom-level directory in '/tmp/zipper/dbtaric.dat/py3_logic_dbtaric/countries.pyc'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by takluyver** [comment]
Can you have a go with #9488 ?

**Comment by MiguelLatorre** [comment]
Yeap!
Solves the crash :)
Thanks so much.
