### ISSUE TITLE
tab completion crash on master, Windows only(?)

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9492]
As of 14141b539d65ad6667677379327b26d64e2738bc:
```
In [1]: cd C:/
C:\

In [2]: cd "Program Files"<TAB>Exception in thread Thread-132:
Traceback (most recent call last):
  File "C:\Users\palm\Miniconda3\envs\ipytest\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\palm\Miniconda3\envs\ipytest\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\palm\Miniconda3\envs\ipytest\lib\site-packages\prompt_toolkit\interface.py", line 759, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Users\palm\Documents\antony\src\ipython\IPython\terminal\ptshell.py", line 59, in get_completions
    if wcwidth(m[0]) == 0:
IndexError: string index out of range
```

**Comment by Carreau** [comment]
Thanks for the report. Not sure how a completion can give an empty string though.

**Comment by takluyver** [comment]
Fixing this will conflict with #9487, so I'll do it once that's merged :-)

**Comment by Carreau** [comment]
@takluyver, this is up fro grab now, that #9487 is merged.

**Comment by takluyver** [comment]
Thanks for the reminder, had indeed forgotten
