### ISSUE TITLE
Install fails with "Operation Not Permitted" with pip-8.1.2 (OS X)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ipython/ipython#9523]
I am trying to install ipython via `pip-8.1.2 in` OS X 10.11.5 and getting `Operation Not Permitted` error:

```
$ sudo pip install ipython
The directory '/Users/alp/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/alp/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ipython
  Downloading ipython-4.2.0-py2-none-any.whl (736kB)
    100% |████████████████████████████████| 737kB 1.5MB/s
Requirement already satisfied (use --upgrade to upgrade): traitlets in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): gnureadline; sys_platform == "darwin" and platform_python_implementation == "CPython" in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): pexpect; sys_platform != "win32" in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): backports.shutil-get-terminal-size in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): decorator in /Library/Python/2.7/site-packages (from ipython)
Collecting setuptools>=18.5 (from ipython)
  Downloading setuptools-22.0.0-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 2.0MB/s
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): appnope; sys_platform == "darwin" in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /Library/Python/2.7/site-packages (from traitlets->ipython)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /Library/Python/2.7/site-packages (from pexpect; sys_platform != "win32"->ipython)
Requirement already satisfied (use --upgrade to upgrade): path.py>=6.2 in /Library/Python/2.7/site-packages (from pickleshare->ipython)
Installing collected packages: setuptools, ipython
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-OcVZvi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
````

**Comment by Carreau** [comment]
Hi, thanks for your report, 

The new versions of Mac Os come with high restrictions on what you can do and is called: [System Integrity Protection](https://support.apple.com/en-us/HT204899). 

There is unfortunately not much we can do about that, and anyway the reason for System Integrity Protections seem to be reasonable. 

Plus usually you do not want to install things systemwide, there is no reason to use `sudo` in front of `pip`. If you don't have the permissions, there is likely a good reason. 

You should be able to install any packages as user by using the `--user`: 

```
pip install ipython --user
```

Which will have the advantage of installing in your home, where you have ~0 chance of breaking your system. Moreover it will not require you to use `sudo` that you shouldn't have to use anyway. 

I would also encourage you to not use system-python on a mac:
  1) It's never up to date, and is linked weirdly with some binary libraries
  2) It's Python2.7, which [will not be supported anymore soon](http://python3statement.github.io/)  

Prefer [`brew install python`/`brew install python3`](http://brew.sh/) that have complete separate Python installation that do not require sudo either. Or, [anaconda](https://www.continuum.io/downloads) that does the same, support multiple environment, and have binary of many python packages that Homebrew lacks.

**Comment by takluyver** [comment]
Closing as not an issue we can fix.

**Comment by ahmetalpbalkan** [comment]
Thanks folks, sorry for not doing my research. 

I installed ipython with `pip install --user` and now I can't seem to find it anywhere in my $PATH. Does it supposed to add a symlink for itself to a well known location? My PATH is as follows:

    /usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by Carreau** [comment]
> Thanks folks, sorry for not doing my research.

Not obvious to find, no worries. 

> /usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Ouch you have a really short PATH. Yes IIRC it should add itself to `.local/bin/`

**Comment by takluyver** [comment]
Unfortunately I don't think `~/.local/bin/` in on PATH by default on most systems. It's easy for us to forget because we've likely added it a long time ago and forgotten. But the only way for a user install to reliably put something on PATH is to modify your `.bashrc` (or `.bash_profile` or `.profile` or one of that mess of files) to change PATH itself. And we can't sanely do that when installing a Python package.

**Comment by Carreau** [comment]
> Unfortunately I don't think ~/.local/bin/ in on PATH by default on most systems. It's easy for us to forget because we've likely added it a long time ago and forgotten. But the only way for a user install to reliably put something on PATH is to modify your .bashrc (or .bash_profile or .profile or one of that mess of files) to change PATH itself. And we can't sanely do that when installing a Python package.

You made me sad for today.

**Comment by DMIND408p** [comment]
try used pip2 instead of pip i worked for me
