### ISSUE TITLE
MultipleInstanceError: Multiple incompatible subclass instances of InteractiveShellEmbed are being created.

### ISSUE THREAD

**Issue by akankshavalecha** [ipython/ipython#9563]
Getting following error. and found no relevant solution. 
I am unable to open ipython shell and cant even update or uninstall ipython version, it says:

> Not uninstalling ipython at /usr/lib/python2.7/dist-packages, owned by OS

```
Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/shell.py", line 54, in handle_noargs
    self.run_shell()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/shell.py", line 37, in run_shell
    return getattr(self, shell)()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/shell.py", line 17, in ipython
    embed()
  File "/usr/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 301, in embed
    shell = InteractiveShellEmbed.instance(**kwargs)
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 360, in instance
    '%s are being created.' % cls.__name__
MultipleInstanceError: Multiple incompatible subclass instances of InteractiveShellEmbed are being created.
```
python -c "import IPython; print(IPython.sys_info())" -->
```
{'codename': 'An Afternoon Hack',
 'commit_hash': '9c4f59d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python2.7/dist-packages/IPython',
 'ipython_version': '1.2.1',
 'os_name': 'posix',
 'platform': 'Linux-4.2.0-36-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'}
```

**Comment by minrk** [comment]
The failure to update is likely due to a setuptools bug. What do you see for:

    python -m site

? If you see '/usr/lib/python2.7/dist-packages' higher than things in `/usr/local/lib`, then you have been bitten by a common setuptools bug. The fix is to make sure that no `easy-install.pth` file has a line containing `dist-packages` or `site-packages`. You can find these files with:

    find / -name '*.pth'

And edit them, to remove any lines with `dist-packages` or `site-packages`. Once you have done this, you can install upgraded setuptools/pip:

    pip install --upgrade setuptools pip

and then upgrade IPython:

    pip install --upgrade ipython

**Comment by akankshavalecha** [comment]
It solved:
` sudo apt-get remove ipython `
` sudo pip install ipython==4.0.0 `

Now its working. Thanks

**Comment by QinHuannet** [comment]
maybe cause import the other ipython-isinstance, eg:import ipdb,remove it, it works
