### ISSUE TITLE
5b2: cd with tab completion crashes at execution

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#9585]
All I do is `cd Dro` then press <TAB> to have the path completed. At that moment the path to just the Dropboxfolder is shown and I just press <return> to confirm.
This is when it crashes like so:
```bash
(stable)└─❱❱❱ ipython                                                          1 ⏎  +4066 16:42 ❰─┘
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0b2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Automatic calling is: Smart

In [1]: cd Dropbox/
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/stable/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 398, in mainloop
    self.interact()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 381, in interact
    code = self.prompt_for_code()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 324, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 387, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 376, in feed
    self._input_parser.send(c)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 295, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 328, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 916, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 174, in feed_key
    self._process_coroutine.send(key_press)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 146, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 190, in _call_handler
    handler.call(event)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 32, in call
    return self.handler(event)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 187, in _
    b.apply_completion(cs.current_completion)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/prompt_toolkit/buffer.py", line 762, in apply_completion
    assert isinstance(completion, Completion)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

My system: OSX 10.10.5, conda (all updates), iTerm 3.0

**Comment by michaelaye** [comment]
already fixed on master i hear. closing.
