### ISSUE TITLE
AttributeError when launching ipython

### ISSUE THREAD

**Issue by Achifaifa** [ipython/ipython#9591]
I just tried the last ipython build from master, and it crashes when launching it.

Not sure where that comes from, since I looked it up and I haven't found anything about it. Any clues about this?

```
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 24, in <module>
    from IPython.core import release, crashhandler
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/ultratb.py", line 117, in <module>
    from IPython.core import debugger
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/debugger.py", line 35, in <module>
    from IPython.utils import PyColorize, ulinecache
  File "/usr/local/lib/python2.7/dist-packages/IPython/utils/PyColorize.py", line 57, in <module>
    from .colorable import Colorable
  File "/usr/local/lib/python2.7/dist-packages/IPython/utils/colorable.py", line 21, in <module>
    class Colorable(Configurable):
  File "/usr/local/lib/python2.7/dist-packages/IPython/utils/colorable.py", line 25, in Colorable
    default_style=Unicode('lightbg').tag(config=True)
AttributeError: 'Unicode' object has no attribute 'tag'
```

**Comment by Carreau** [comment]
IPython now [requires traitlets > 4.2](https://github.com/ipython/ipython/blob/master/setup.py#L198) how did you install ? `pip install (-e) .` should take care of dependencies.

**Comment by Achifaifa** [comment]
Oh, right. I just did a git pull to the master branch, but that fails when there are new dependencies. Is there a better way?

**Comment by Carreau** [comment]
> Oh, right. I just did a git pull to the master branch, but that fails when there are new dependencies. Is there a better way?

No, if you have a developer install  it's expected for people to know what they are doing. 
you might want to explicitely try without some dependencies when developpeing.
