### ISSUE TITLE
Post-completion crash

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9599]
IPython 5.0b2 from pypi, Arch Linux.
After `from scipy.io import save<TAB>` completes to `savemat` and the completion is chosen, pressing Enter crashes IPython:
```
In [1]: from scipy.io import savemat                                                                                                                                                                
Traceback (most recent call last):
  File "/home/antony/.local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 398, in mainloop
    self.interact()
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 381, in interact
    code = self.prompt_for_code()
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 324, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 387, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 376, in feed
    self._input_parser.send(c)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 295, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 328, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 916, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 174, in feed_key
    self._process_coroutine.send(key_press)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 146, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 190, in _call_handler
    handler.call(event)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 32, in call
    return self.handler(event)
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ptshell.py", line 187, in _
    b.apply_completion(cs.current_completion)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/buffer.py", line 762, in apply_completion
    assert isinstance(completion, Completion)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
IPython quits immediately after that.

**Comment by takluyver** [comment]
Yep, Matthias just released beta 3 which should fix this. Thanks for testing, though.
