### ISSUE TITLE
ipython crashes

### ISSUE THREAD

**Issue by hhsieh** [ipython/ipython#9620]
Hi I am sorry for posting this naive question. 
I got this error when i do $ipython or $ipython notebook

Traceback (most recent call last):
  File "/opt/conda/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/opt/conda/lib/python2.7/site-packages/IPython/__init__.py", line 47, in <module>
    from .core.application import Application
  File "/opt/conda/lib/python2.7/site-packages/IPython/core/application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 16, in <module>
    from decorator import decorator
ImportError: No module named decorator

Is this just because I accidentally deleted some important things? Thank you.

This only happens in my vagrant environment, but not in my local machine. Thank you.

**Comment by takluyver** [comment]
It relies on the [decorator](https://pypi.python.org/pypi/decorator) package. You can probably install that with `conda install decorator`. Though I'm not sure how you got IPython installed without it.

**Comment by hhsieh** [comment]
Thank you for your suggestion. I tried conda install decorator, but it showed
$ conda install decorator
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 61, in main
    from conda.cli import conda_argparse
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "/opt/conda/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "/opt/conda/lib/python2.7/site-packages/conda/logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat


Should I installed pycosat? I am not sure if I can do this in a vagrant environment.

**Comment by takluyver** [comment]
It looks like you've completely broken your conda installation. Try ditching it entirely and installing it from scratch.

**Comment by hhsieh** [comment]
Thank you. The administrator fixed it remotely. Now it is running.
