### ISSUE TITLE
pySpark kernal dead

### ISSUE THREAD

**Issue by krishnachaitanyareddy** [ipython/ipython#9654]
I have sucessfully integrated iPython(Jupyter) with Spark...
when i start server i'm not getting any error, but when i click pySpark on Jupyter webUI, its giving below error

`[admin@hostname ~]$ pyspark
WARNING: User-defined SPARK_HOME (/opt/cloudera/parcels/CDH-5.7.0-1.cdh5.7.0.p0.45/lib/spark) overrides detected (/opt/cloudera/parcels/CDH/lib/spark/).
WARNING: Running pyspark from user-defined location.
[W 17:13:58.633 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 17:13:58.633 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 17:13:58.637 NotebookApp] Serving notebooks from local directory: /home/ksm8kor
[I 17:13:58.637 NotebookApp] 0 active kernels
[I 17:13:58.637 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8880/
[I 17:13:58.637 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 17:14:02.903 NotebookApp] Failed to run command:
    [u'/opt/anaconda2/bin', u'-m', u'IPython.kernel', u'-f', u'/run/user/80622/jupyter/kernel-f8d3c409-28e5-4cf7-a19a-7435c35278e2.json']
    with kwargs:
`

`[E 17:14:02.905 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 458, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 58, in post
        sm.create_session(path=path, kernel_name=kernel_name))
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/opt/anaconda2/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/opt/anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 13] Permission denied
[E 17:14:02.907 NotebookApp] {
      "Origin": "http://hostname:8880",
      "Content-Length": "77",
      "Accept-Language": "en-GB,en-US;q=0.8,en;q=0.6",
      "Accept-Encoding": "gzip, deflate",
      "Host": "hostname:8880",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Cache-Control": "max-age=0",
      "Referer": "http://hostname:8880/notebooks/Untitled1.ipynb?kernel_name=pyspark",
      "Content-Type": "application/json"
    }
[E 17:14:02.907 NotebookApp] 500 POST /api/sessions (10.170.46.44) 24.11ms referer=http://hostname:8880/notebooks/Untitled1.ipynb?kernel_name=pyspark`

In web UI showing kernal dead and below code
`Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/opt/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/opt/anaconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied`

**Comment by krishnachaitanyareddy** [comment]
Sorry its my kernal file mistake i forgot to add exact path. now its resolved
`{
 "display_name": "pySpark (Spark 1.6.0)",
 "language": "python",
 "argv": [
  "/opt/anaconda2/bin/**python2.7**",
  "-m",
  "IPython.kernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark/",
  "PYTHONPATH": "/opt/cloudera/parcels/CDH/lib/spark/python/:/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS":"--master yarn --deploy-mode client --num-executors 24 --executor-memory 10g --executor-cores 5"
 }
}
`
