### ISSUE TITLE
Completion crash (IPython 5.0b4, ptk 1.0.3)

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9678]
After installing `asteval` (https://pypi.python.org/pypi/asteval) (which I know is really not up to its claims of being a safe evaluator, but that's not the issue here)
```
In [1]: from asteval import <TAB>Exception in thread Thread-43:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()                   
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/terminal/ptutils.py", line 24, in
    cursor_pos=document.cursor_position_col
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 1185, in
    custom_res = self.dispatch_custom_completer(text)
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 1113, in
    withcase = [cast_unicode_py2(r) for r in res if r.startswith(text)]
  File "/home/antony/.local/lib/python3.5/site-packages/IPython/core/completer.py", line 1113, in
    withcase = [cast_unicode_py2(r) for r in res if r.startswith(text)]
AttributeError: type object 'NameFinder' has no attribute 'startswith'
```

**Comment by Carreau** [comment]
Thanks for doing crazy things :-)

**Comment by anntzer** [comment]
C'mon, that hardly qualifies...

**Comment by takluyver** [comment]
It's annoying that the traceback is cut off on the right. Hopefully that only affects tracebacks from completions, but we may want to fix it.

I'll try to work out how that object is ending up where only strings should be.

**Comment by takluyver** [comment]
I've made a PR to fix it in asteval (newville/asteval#19). Now I'll work on catching it on our side.

**Comment by takluyver** [comment]
#9679 filters out non-string completions from importing a module.

**Comment by newville** [comment]
@anntzer  Sorry for the trouble with `__all__` in `asteval`.  This is now fixed in git master, thanks  to @takluyver 

But I also feel that I should emphasize that `asteval` does not actually claim to be a safe evaluator, just safer at handling user input than the builtin `eval`. The docs are pretty clear about what it does and does not do.   Suggestions for improvements welcome.
