### ISSUE TITLE
IPython 5 breaks Emacs behaviour on Windows

### ISSUE THREAD

**Issue by ThatGeoGuy** [ipython/ipython#9725]
Hi all, I have successfully used IPython from within an Emacs buffer in the past, usually by using the `jupyter console` command. My basic config uses the following:

```
(setq-default python-shell-interpreter "C:/Python34/Scripts/jupyter.exe"
              python-shell-interpreter-args "console")
```

The problem seems to be that the latest version of IPython breaks this integration, as the following error message / traceback appears:

```
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python34\Scripts\ipython.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python34\lib\site-packages\IPython\terminal\ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python34\lib\site-packages\IPython\core\application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "c:\python34\lib\site-packages\IPython\terminal\ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "c:\python34\lib\site-packages\IPython\core\application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python34\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "c:\python34\lib\site-packages\jupyter_console\app.py", line 110, in init_shell
    client=self.kernel_client,
  File "c:\python34\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\python34\lib\site-packages\jupyter_console\ptshell.py", line 252, in __init__
    self.init_prompt_toolkit_cli()
  File "c:\python34\lib\site-packages\jupyter_console\ptshell.py", line 404, in init_prompt_toolkit_cli
    self.pt_cli = CommandLineInterface(app, eventloop=self._eventloop)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 80, in __init__
    self.output = output or create_output()
  File "c:\python34\lib\site-packages\prompt_toolkit\shortcuts.py", line 114, in create_output
    return Win32Output(stdout)
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

It seems even though it should load, `prompt_toolkit` does not like that Emacs is 1) on Windows and 2) is not in a known shell. I imagine this isn't anything to do with Emacs, as this shouldn't be any different than starting any other type of console from within the editor. Is this fixable? It seems to just be that `prompt_toolkit` doesn't know what it is executing inside. 

Anyways, thanks for the IPython 5 release, I really like the new REPL and completion, but being able to use it with Emacs as I have been is important to me as well. Hopefully the fix is as simple as adding some sort of Emacs clause to `get_win32_screen_buffer_info`.

**Comment by Carreau** [comment]
Can you use plain IPython instead of jupyter console ? Or do you **have to** use Jupyter console ?

If so you can pass the extra `--simple-prompt`.

THere is the same issue with the emacs inferior-shell which is not vt100 compliant, but you can use emacs-terminal that works.

**Comment by ThatGeoGuy** [comment]
I am opting to use jupyter console because otherwise, the threading for `%matplotlib` doesn't work, and you can't plot things from Emacs (window freezes and then just kills the process). Otherwise IPython just works, no `--simple-prompt` needed.

**Comment by Carreau** [comment]
do you use just `%matplotlib` or something like `%matplotlib qt` it might be a bug.

**Comment by ThatGeoGuy** [comment]
I use `%matplotlib`, but `%matplotlib qt` would also exhibit the same behaviour. They both work fine if I use them in the REPL directly, but they break as soon as you try to plot something while in an Emacs buffer.

I've found a similar issue on StackOverflow, however it seems the issue has persisted from an older version of IPython. Back then the solution was to use the `jupyter console`, however this no longer works with IPython 5.

**Comment by Carreau** [comment]
Hum that's extremely weird. Do you have any link to these SO questions or more info ?
I'm not an emacs user, so it's hard for me to investigate, unless you walk me through what you are doing. 

@fperez and @tacaswell you are emacs users right ? Maybe you can sort out how to do what @ThatGeoGuy wants with plain IPython ?

**Comment by ThatGeoGuy** [comment]
Ah sorry, I was going to link the SO question above. See [this question](https://stackoverflow.com/questions/17117074/python-shell-in-emacs-freezes-when-using-matplotlib#18745188), which outlines the issue.

**Comment by fperez** [comment]
I use emacs, but unfortunately I don't really use our ipython/emacs integration at all (I used to a very long time ago, but eventually switched to using it in a plain terminal, which I prefer).  So I'm afraid I won't be of much help here.

Our emacs integration has always been brittle and little maintained, sadly. It's very much in need of a good "champion" from the community who uses it regularly and can help us stay on top of things.  It's quite hard to test it automatically in CI (I wouldn't know how to), so it tends to break badly and nobody notices for a while until a release happens.

Sorry not to offer a better answer. We might just spin that off into a standalone separate little extension that can be maintained by someone else, since evidently we don't have the cycles or expertise to do a good job on this one.

**Comment by shelper** [comment]
same here, 
emacs with ipython 4.0 works fine, 
with 4.2, it has problem when you type “function?" for help information, 
and with 5.0, console didnt work, and if without console option, any plotting will freeze

**Comment by tacaswell** [comment]
For ipython run in comint mode the best solution is a) use strait ipython b) use it in 'simple' mode which disables all of the prompt toolkit stuff which lets emacs do it's job and handle the typing stuff.

See the discussion in https://github.com/ipython/ipython/pull/9399#issuecomment-222003924

I do use IPython + emacs + orgmode every day, but I mostly rely on elpy to make that work (and the issue in #9399 is the first real issue I have had in years).  I will try to keep at least one of my machines on bleeding edge if that will help.

For the plotting freezing you _must_ (until mpl 2.0) use `%matplotlib` with IPython 5 for the event loop integrations to work.

**Comment by fperez** [comment]
Thanks much @tacaswell! Any input/help you can give us here is much appreciated.

**Comment by shelper** [comment]
for me, %matplotlib does not solve the plotting freezing on windows + emacs. 
to get everything work, i have to use emacs + ipython<=4.1.0 + jupyter-console<=4.1.0

**Comment by Carreau** [comment]
I'm marking this issue as "need info", I would like to mark this with an explicit milestone, but unfortunately we seem to miss a developper with the right knowledge and set of tools to figure that out. 

I'm wondering if we should  have a tag: `help-needed` for bugs that do hit this kind of spot [mostly os version we don't have access to].

**Comment by fperez** [comment]
not a bad idea (`help-needed`)... Otherwise, milestone-wise this will remain wishlist material until the person with the right skills/bandwidth shows up. For now, from us I think it's not something we'll get to...

**Comment by luckjiff** [comment]
I have been tinkering with ipython+emacs+mpl for many moons.  
The best setup I have found that works practically is
(setq
 python-shell-interpreter "C:\\Anaconda2\\python.exe"
 python-shell-interpreter-args "-i C:\\Anaconda2\\Scripts\\jupyter-console-script.py")

with these versions at best!
ipython 4.1.2 py27_1
jupyter 1.0.0 py27_3
jupyter_client 4.3.0 py27_0
jupyter_console 4.1.1 py27_0
jupyter_core 4.1.1 py27_0

Use %pylab to get plotting to work

If anyone can get beyond these versions please let us know.
Thanks!

**Comment by avigan** [comment]
I I have a very similar issue in emacs on Mac OS X: since the update to IPython 5 I cannot really use matplotlib any more because of this window freezing problem. My solution was also to use ```jupyter console``` but it seems this is also now broken:

```python
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x11411f598>)
Traceback (most recent call last):
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in enter_eventloop
    self.eventloop(self)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 277, in loop_cocoa
    show.mainloop()
AttributeError: 'function' object has no attribute 'mainloop'
Jupyter console 5.2.0
```

Sorry I've opened another ticket (#10921) because I have the feeling that there could be a workaround. If I understand correctly, the ```--simple-prompt``` option does not only disable the coloring and complete system but also some things related to events handling. Maybe there could be possibility to disable some of these things separately?

Obviously I don't know much of the inner workings of IPython 5 so it's probably not that simple. Sorry if my proposition seems very naive ;)
