### ISSUE TITLE
Cannot start notebook: No usable temporary directory

### ISSUE THREAD

**Issue by lakshay42** [ipython/ipython#9727]
Ipython notebook was working fine up till yesterday and if i try to open a notebook from the home directory, it gives the following error. Please help ASAP. I'm using Ubuntu 16.04. 

P.S : At first, the error message also showed something like "unable to write to /tmp" "SQLite error", but now those messages seem to have disappeared. 

**Error Message**

```
[E 10:36:34.487 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/lakshay/.local/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/lakshay/.local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/lakshay/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/home/lakshay/.local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/lakshay/.local/lib/python2.7/site-packages/notebook/services/contents/handlers.py", line 124, in get
        path=path, type=type, format=format, content=content,
      File "/home/lakshay/.local/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 358, in get
        model = self._notebook_model(path, content=content)
      File "/home/lakshay/.local/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 318, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/home/lakshay/.local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 447, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/home/lakshay/.local/lib/python2.7/site-packages/nbformat/sign.py", line 233, in check_signature
        (datetime.utcnow(), self.algorithm, signature),
    OperationalError: unable to open database file
[E 10:36:34.488 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.8", 
      "Accept-Encoding": "gzip, deflate, sdch", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/Untitled1.ipynb", 
      "X-Requested-With": "XMLHttpRequest"
    }
[E 10:36:34.489 NotebookApp] 500 GET /api/contents/Untitled1.ipynb?type=notebook&_=1468040793654 (127.0.0.1) 197.80ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
[W 10:36:34.511 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160709103627 (127.0.0.1) 16.85ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
```

EDIT : I tried to uninstall ipython and got the following error :
 IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/lakshay']

I guess this is the same issue that was creeping up when i was trying to create a notebook and it said that /tmp is in not writable. How can i fix this?

**Comment by minrk** [comment]
Can you check free disk space (`df -h`)? This is happening because Jupyter cannot figure out how to create any temporary files. This could be due to a full disk, or a read-only mounted filesystem. Can you make files by hand:

    echo 'some stuff' > /tmp/new-file-test

**Comment by lakshay42** [comment]
Yes, as i soon as i cleared up disk space, it got back to normal. Thank you so much for your help @minrk !!
