### ISSUE TITLE
ipython 5.0 cause error when run 'ipython console'

### ISSUE THREAD

**Issue by shelper** [ipython/ipython#9758]
full error message is as below:

```
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\ipython.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 300, in
initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\IPython\core\application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "c:\anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 295, in
parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "c:\anaconda3\lib\site-packages\IPython\core\application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "c:\anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\jupyter_console\app.py", line 138, in initialize
    self.init_shell()
  File "c:\anaconda3\lib\site-packages\jupyter_console\app.py", line 111, in init_shell
    client=self.kernel_client,
  File "c:\anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 135, in __init__
    super(ZMQTerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 359, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 487, in __init__
    self.init_completer()
  File "c:\anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 160, in init_completer
    if self.has_readline:
AttributeError: 'ZMQTerminalInteractiveShell' object has no attribute 'has_readline'
```

**Comment by takluyver** [comment]
You probably need to upgrade `jupyter_console` as well.

**Comment by shelper** [comment]
you are right, but then i have issue
https://github.com/ipython/ipython/issues/9725

**Comment by takluyver** [comment]
With IPython 5 in emacs inferior shell, you need to use the `--simple-prompt` flag.

**Comment by dsblank** [comment]
I realize that this is the ipython issue tracker, but is there a work-around for not having a --simple-prompt flag for jupyter console? What should other languages do inside emacs?

**Comment by shelper** [comment]
with the --simple-prompt flag the matplotlib still freezes emacs and ​hangs
there...

**Comment by takluyver** [comment]
- We should probably add a similar option to jupyter_console; we haven't got round to it yet.
- Our event loop integration won't work in --simple-prompt, but with at least some backends it [appears emacs+matplotlib works OK anyway](https://github.com/ipython/ipython/pull/9399#issuecomment-222003924).
