### ISSUE TITLE
Handle prompt-toolkit exceptions safely

### ISSUE THREAD

**Issue by haridsv** [ipython/ipython#9769]
I recently hit a [bug in prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit/issues/345) and noticed that iPython immediately exited causing me to loose my session. I think iPython should be more resilient than this and there is no need to panic and exit. Please add a fallback mechanism, which would be to restore the buffer to a safe state, while still giving all the information that the end user can use to file a bug with prompt-toolkit. Perhaps python-toolkit already leaves the buffer in a usable state, so may be iPython doesn't need to do anything. Best course of action needs to be further studied.

**Comment by Carreau** [comment]
Thanks for the bug report, and the proposal. I think it totally make sens, we'll see if we can figure out what how to do it !

**Comment by dsclose** [comment]
Saw another example relevant to error handling today. Because prompt_toolkit uses the select.select function, any Python 5.0 prompt on a machine with more than 1024 open file-descriptors will raise a "ValueError: file descriptor out of range in select()". The result is that IPython crashes and the prompt blocks - I needed to kill the process.

I'll recommend the select.poll function to the prompt_toolkit team - this would get around that limitation on POSIX environments.

**Comment by dsclose** [comment]
Raised file-descriptor issue with prompt_toolkit: https://github.com/jonathanslenders/python-prompt-toolkit/issues/354

**Comment by dsclose** [comment]
The file-descriptor issue has been solved by @jonathanslenders for python-prompt-toolkit (although not pushed to PyPi yet.) As this is no-longer relevant to this issue I won't provide further updates here.

**Comment by minrk** [comment]
@dsclose thanks!

**Comment by haridsv** [comment]
@minrk I think @dsclose was talking about a different issue, this issue should still be kept opened.

**Comment by Carreau** [comment]
> @minrk I think @dsclose was talking about a different issue, this issue should still be kept opened.

reopening just in case then.

**Comment by dsclose** [comment]
@minrk @haridsv @Carreau 

This issue should remain open. I was highlighting an example of an unhanded exception - one which the next version of prompt-toolkit will probably now handle.

Sorry for any confusion!

**Comment by minrk** [comment]
@dsclose sorry, I misread the last bit as resolving the original issue. Leaving it open.

**Comment by stefanv** [comment]
Another mechanism to trigger a crash: view a function docstring (which opens less), then press q to quit but before the prompt displays type ctrl-C.  IPython exits back to the terminal with:

```
In [5]: np.testing.assert_array_almost_equal?
In [6]:                                                                                                                                                       

KeyboardInterrupt escaped interact()


In [6]:                                                                                                                                                       
Traceback (most recent call last):
  File "/home/stefan/envs/py3/bin/ipython", line 9, in <module>
    load_entry_point('ipython==5.1.0.dev0', 'console_scripts', 'ipython')()
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 402, in mainloop
    self.interact()
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 385, in interact
    code = self.prompt_for_code()
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/home/stefan/envs/py3/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 55, in run
    assert not self._running
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by eudoxos** [comment]
Also, exception in callback registered via `InteractiveShellEmbed().pt_cli.application.key_bindings_registry.add_binding` makes ipython exit as well. Perhaps out of scope of this issue.
