### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

### ISSUE THREAD

**Issue by jm-huang** [ipython/ipython#9777]
Recently when I install Anaconda2-x64-4.1.1,  I got this errors:(platform: windows10, x64):
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(IPython.start_ipython())
  File "C:\Anaconda2\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py", line 305, in initialize
    self.init_shell()
  File "C:\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py", line 321, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 463, in __init__
    self.db = PickleShareDB(os.path.join(self.profile_dir.location, 'db'))
  File "C:\Anaconda2\lib\site-packages\pickleshare.py", line 65, in __init__
    root = os.path.abspath(os.path.expanduser(str(root)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

**Comment by takluyver** [comment]
Would I be right in guessing that you have a non-ascii character in your username?

There might be a way to fix it, but in general, if you want to deal with non-ascii paths on Windows, you'll be better off with Python 3.

**Comment by Carreau** [comment]
Hum, do we need to take care of that in pickleshare ?

**Comment by minrk** [comment]
Yeah, the `str(root)` is probably a bug in pickleshare, since it should allow unicode.

**Comment by takluyver** [comment]
pickleshare/pickleshare#24

**Comment by takluyver** [comment]
Fixed in pickleshare, though we still need to make a release of it.
