### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by applar** [ipython/ipython#9788]
$sudo python setup.py install
$ipython
There is a error as flows.

jiangyuping@Lenovo:~/ipython$ ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/home/jiangyuping/ipython/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/jiangyuping/ipython/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named traitlets.config.application

Then, $pip install ipython          
to solve this problem
And, it appears the other error as flows.

jiangyuping@Lenovo:~/ipython$ pip install -e
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by takluyver** [comment]
That's not an IPython issue, but you've got your Python into a mess somehow. I'd start by deleting the copy of pip you've got installed as an egg:

```
rm -r /usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg
rm -r /usr/local/bin/pip
```

Then, guessing that you're on Debian/Ubuntu or something similar, start with pip provided by the distribution, and use that to install a newer version:

```
sudo apt-get install python-pip
pip install --upgrade --user setuptools pip
```

And then try installing IPython again:

```
pip install ipython
```

**Comment by applar** [comment]
I do it with your suggestion, but, it doesn't work.

**Comment by takluyver** [comment]
> it doesn't work. 

Which bit didn't work? I'm not psychic ;-)

**Comment by applar** [comment]
@takluyver The last one code doesn't work. When running it, it appears that error. However, thank you very much.

**Comment by takluyver** [comment]
Can you paste the error you get? If the earlier commands worked, it can't be exactly the same, because you deleted the file that the error was coming from before.

**Comment by applar** [comment]
@takluyver 

jiangyuping@Lenovo:/$ pip install --upgrade --user setuptools pip

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by takluyver** [comment]
It appears that this command had no effect:

```
rm -r /usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg
```

**Comment by hzcyf** [comment]
thanks you !
