### ISSUE TITLE
Add multiline coding in ipython 5 with --simple-prompt

### ISSUE THREAD

**Issue by Crandel** [ipython/ipython#9816]
As emacs user I often use emacs repl with **ipython**, but after update to **ipython 5** I need to use `--simple-prompt` flag for my work. But when I try to create new def or class I get this error message

``` python
In [1]: def new():
  File "<ipython-input-1-ce93a60072ff>", line 1
    def new():
              ^
SyntaxError: unexpected EOF while parsing
```

**Comment by takluyver** [comment]
The simple-prompt option doesn't support multi-line input, but I thought Emacs 'inferior-shell' magic was working round that. @tacaswell ?

**Comment by Crandel** [comment]
In ansi-term ipython work well, but I need REPL. Standart python interactive shell works fine, but I really miss %magic%

**Comment by jonathanslenders** [comment]
FYI: prompt_toolkit 1.0.4 has been released today, it has one improvement that should make prompt_toolkit render at least slightly better in emacs-term. Can you have a try?

**Comment by takluyver** [comment]
In the context of IPython,  that means try without `--simple-prompt`, so that it uses prompt_toolkit.

@tacaswell might also be interested in testing.

**Comment by ajsteven130** [comment]
Hello, I have updated to prompt_toolkit 1.0.4 with emacs 25.0.95.1 and ipython 5.0.0. For some reason, running just ipython defaults to the simple-prompt and I am having trouble testing with prompt_toolkit - which is weird and I cannot figure out why.

However, running `jupyter console` still returns the same error it was returning before updating prompt_toolkit. Not sure if this helps or just confuses things further.

Here is the traceback

```
Traceback (most recent call last):
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\Scripts\jupyter-console-script.py", line 5, in <module>
    sys.exit(jupyter_console.app.main())
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\jupyter_console\app.py", line 110, in init_shell
    client=self.kernel_client,
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 252, in __init__
    self.init_prompt_toolkit_cli()
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 404, in init_prompt_toolkit_cli
    self.pt_cli = CommandLineInterface(app, eventloop=self._eventloop)
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\prompt_toolkit\interface.py", line 80, in __init__
    self.output = output or create_output()
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\prompt_toolkit\shortcuts.py", line 114, in create_output
    return Win32Output(stdout)
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Users\A6419643\AppData\Local\Continuum\Miniconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

Process Python exited abnormally with code 1

```

**Comment by takluyver** [comment]
I'd guess that maybe our checks for a terminal fail, so it falls back to simple-prompt automatically.

@jonathanslenders - I take it that traceback is not what you were expecting! Is there anything else the Windows+Emacs users should try?

**Comment by osdf** [comment]
Any progress on this issue?

**Comment by tacaswell** [comment]
Sorry, I missed the ping on this in July.

In comint mode you only get one line, but you can use one of the `send-buffer-to-shell` commands in python-mode / elpy to send a buffer to the interpreter.  That plus an org-mode source region or just a `/tmp/scratch.py` file is how I do multi-line editing these days.

**Comment by AndreaOrru** [comment]
This is pretty huge for our Emacs users. :(

Why does it work on iPython 4.x? What changed exactly?

**Comment by tacaswell** [comment]
@AndreaOrru Pretty sure the change is moving from readline to prompt toolkit which lots some of the special-cased work arounds on both sides.

I strongly suggest opening `/tmp/scratch.py`, writing your multi-line stuff there (or using org-mode + source blocks), and shipping it to the shell via `send-buffer-to-shell` (bound to `C-c C-c` by elpy).

**Comment by mashu** [comment]
Hi guys,

I have the following problem. I am using ipython 5, as it uses some strange colours I am using this walk-around
```
(setq python-shell-interpreter "ipython" python-shell-interpreter-args "--simple-prompt -i")
```
but then I get this error as in reported bug
```
SyntaxError: unexpected EOF while parsing
```
whenever I try to send multiline code ending with ':' character. Sending whole buffer works just fine but individual lines are problematic, which makes testing code very difficult.

Please help.

**Comment by ajsteven130** [comment]
hi @mashu,

the work around you use above makes the ipython prompt work in emacs, but it does not allow multiline editing. There is currently no solution that allows multiline editing in an ipython shell in emacs.

If you want multiline editing, I would follow @tacaswell's advice above using python buffers, etc.

**Comment by Crandel** [comment]
So why you couldn`t have both readline and promt_toolkit and switching them using some flags? Even if you won`t support readline you can at least leave it as it is. This is huge regression for many users and I don`t think promt_toolkit is much better then readline. It dont work with ipdb also.

**Comment by mashu** [comment]
@ajsteven130 Thanks for great advice
@all Using python instead of ipython5 with emacs seems like a better solution for now.

What works for me is that I can copy now multiple lines into the python buffer and they get executed.
That wasn't the case when using ipython. However, line-by-line sending does not work in Emacs(elpy) at the moment of writing I encounter this bug [#907](https://github.com/jorgenschaefer/elpy/issues/907) and suggested alternative C-M-x does not work as expected as well. Kind of stucked now with copying blocks of code, but better than nothing.

**Comment by Crandel** [comment]
@mashu I installed ipython 4.2.1 and won`t update it until multiline in emacs will not fixed.

**Comment by mashu** [comment]
@Crandel indeed downgrading to ipython 4.2.1 is a way better solution! 
All works as expected.

Quick command for people in a hurry
```
pip install --force-reinstall ipython==4.2.1
```

And as @Crandel suggested option for readline support on ipython side would be nice for other projects, not only Emacs community. Hope you guys consider this!

**Comment by takluyver** [comment]
> option for readline support on ipython side would be nice for other projects, not only Emacs community.

Sorry we hit your workflow, but one of the motivations behind switching to prompt_toolkit was that we could get rid of a whole lot of code that was supporting the readline interface. I don't see us adding that back.

What other projects are affected? So far, Emacs inferior shell is the only thing where I've heard of problems with the new interface.

**Comment by bennigoetz** [comment]
I have a similar problem with a relatively unique vi+tmux+slimux+ipython workflow. I use tmux to open up a vi pane, and an ipython pane, and slimux lets me use a key combo in vi to send a line--or block of text--to the ipython interpreter to be executed. Very nice: the lines sent from vi go into an [In] prompt, and the output is in an [Out] prompt.

With the "upgrade" to iPython 5, I can no longer send a block of code via slimux. If I want to send a loop or function definition, I have to send them line-by-line. Granted, it works that way, but sending over a block of text is *way* easier. I haven't been able to find a work-around, and am about to go back to iPython 4.x.

**Comment by takluyver** [comment]
Do you know how those lines are being sent to IPython? Just sending them with newlines between them should work, and if you can get that machinery to use the [bracketed paste](https://cirw.in/blog/bracketed-paste) mechanism, it should be even better.

**Comment by bennigoetz** [comment]
I don't know any `vimscript`, and have no desire to learn, but digging into `slimux.vim`, this is what I can make out as relevant:

```vimscript
command! SlimuxREPLSendLine call SlimuxSendCode(getline(".") . "\n")
command! -range=% -bar -nargs=* SlimuxREPLSendSelection call SlimuxSendCode(s:GetVisual())
```
It looks like SendLine sends a newline after the line of code, but GetVisual() doesn't necessarily insert extra newlines? I suppose I can try modifying the function GetVisual to insert newlines or something (there are already newlines in the selection, though...).

But one of the nice things about Slimux is that it's agnostic as far as the REPL goes. All it does is send selected text from one tmux pane to another. So the exact same setup works for bash, etc.

**Comment by takluyver** [comment]
And what do you see when you do try to send a block of code to IPython? I don't know vimscript either, but there's nothing obviously wrong with that.

If you're willing to try debugging, could you run [this script](https://github.com/pexpect/pexpect/blob/master/tests/getch.py) in the terminal part and send a multiline block to it? It should show the bytes that are sent to the terminal. Then you can use Ctrl-Space to quit it.

**Comment by bennigoetz** [comment]
Thanks for taking a look at this. I know I'm just presenting a wish list, hoping that other people will make what I want.

Anyway, here are a couple examples.

In my code file (vim):
```python
walrus_parts = ['blubber', 'flipper']                                                                                                                                                                                                                                           
walrus_locations = {'ET': 'Point Defiance', 'Antje': 'Tierpark Hagenbeck'}
```
when I send this to iPython 5, I get:
```python
In [9]: walrus_parts = ['blubber', 'flipper']                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
In [10]: walrus_locations                                                                                                                                                                                                                                                       
---------------------------------------------------------------------------                                                                                                                                                                                                     
NameError                                 Traceback (most recent call last)                                                                                                                                                                                                     
<ipython-input-10-ea59699135df> in <module>()                                                                                                                                                                                                                                   
----> 1 walrus_locations                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                
NameError: name 'walrus_locations' is not defined
```

If I send:
```python
walruses = ['Jocko', 'Antje', 'ET']                                                                                                                                                                                                                                             
for walrus in walruses:                                                                                                                                                                                                                                                         
    print walrus 
```
I get:
```python
In [12]: walruses = ['Jocko', 'Antje', 'ET']
```

If I just send the `for` loop (and now `walruses` has been defined):
```python
In [13]: for walrus in walruses:                                                                                                                                                                                                                                                
    ...:         print walrus                                                                                                                                                                                                                                                   
  File "<ipython-input-13-a3d3c22573d1>", line 2                                                                                                                                                                                                                                
    print walrus                                                                                                                                                                                                                                                                
               ^                                                                                                                                                                                                                                                                
SyntaxError: invalid syntax
```

In contrast, in iPython 4.x I get:
```python
In [1]: walruses = ['Jocko', 'Antje', 'ET']                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                
In [2]: for walrus in walruses:                                                                                                                                                                                                                                                 
   ...:         print walrus                                                                                                                                                                                                                                                    
   ...:                                                                                                                                                                                                                                                                         
Jocko                                                                                                                                                                                                                                                                           
Antje                                                                                                                                                                                                                                                                           
ET
```

It looks to me like iPython 5 treats the first line differently from subsequent lines. In the non-loop block, it *only* executed the first line.

Running the function you gave me (I skipped the shebang and comments). (And when I say "running", I mean my REPL setup, sending from vi to iPython 5 using slimux.)

```python
In [5]: from __future__ import print_function                                                                                                                                                                                                                                   

In [6]:   break                                                                                                                                                                                                                                                                 
  File "<ipython-input-6-b20fcc2397e7>", line 1                                                                                                                                                                                                                                 
    break                                                                                                                                                                                                                                                                       
SyntaxError: 'break' outside loop
```

Hope that helps. Happy to try and clarify anything.

**Comment by takluyver** [comment]
That's confusing...

For the script I linked to above, I mean: get that script running in the terminal by a means that works (like `python getch.py`), and then send text to that terminal as you would with IPython. The script is designed to show the raw bytes that it's receiving, which should help us work out what's going on.

**Comment by bennigoetz** [comment]
Oh, I see. I ran `getch.py` in one tmux pane, and sent over the following code via slimux. (This is one of the same walrus examples as before.)

If you'd like other pieces of code, happy to do it. I figured this was long enough for one post.

```python
walrus_parts = ['blubber', 'flipper']                                                                                                                                                                                                                                           
walrus_locations = {'ET': 'Point Defiance', 'Antje': 'Tierpark Hagenbeck'}
```

```
$ getch.py                                                                                                                                                                                                                                                                      
READY                                                                                                                                                                                                                                                                           
119<STOP>                                                                                                                                                                                                                                                                       
97<STOP>                                                                                                                                                                                                                                                                        
108<STOP>                                                                                                                                                                                                                                                                       
114<STOP>                                                                                                                                                                                                                                                                       
117<STOP>                                                                                                                                                                                                                                                                       
115<STOP>                                                                                                                                                                                                                                                                       
95<STOP>                                                                                                                                                                                                                                                                        
112<STOP>                                                                                                                                                                                                                                                                       
97<STOP>                                                                                                                                                                                                                                                                        
114<STOP>                                                                                                                                                                                                                                                                       
116<STOP>                                                                                                                                                                                                                                                                       
115<STOP>                                                                                                                                                                                                                                                                       
32<STOP>                                                                                                                                                                                                                                                                        
61<STOP>                                                                                                                                                                                                                                                                        
32<STOP>                                                                                                                                                                                                                                                                        
91<STOP>                                                                                                                                                                                                                                                                        
39<STOP>                                                                                                                                                                                                                                                                        
98<STOP>                                                                                                                                                                                                                                                                        
108<STOP>                                                                                                                                                                                                                                                                       
117<STOP>                                                                                                                                                                                                                                                                       
98<STOP>                                                                                                                                                                                                                                                                        
98<STOP>                                                                                                                                                                                                                                                                        
101<STOP>                                                                                                                                                                                                                                                                       
114<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
44<STOP>                                                                                                                                                                                                                                                                        
32<STOP>                                                                                                                                                                                                                                                                        
39<STOP>                                                                                                                                                                                                                                                                        
102<STOP>                                                                                                                                                                                                                                                                       
108<STOP>                                                                                                                                                                                                                                                                       
105<STOP>                                                                                                                                                                                                                                                                       
112<STOP>                                                                                                                                                                                                                                                                       
112<STOP>                                                                                                                                                                                                                                                                       
101<STOP>                                                                                                                                                                                                                                                                       
114<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
93<STOP>                                                                                                                                                                                                                                                                        
13<STOP>                                                                                                                                                                                                                                                                        
119<STOP>                                                                                                                                                                                                                                                                       
97<STOP>                                                                                                                                                                                                                                                                        
108<STOP>                                                                                                                                                                                                                                                                       
114<STOP>                                                                                                                                                                                                                                                                       
117<STOP>                                                                                                                                                                                                                                                                       
115<STOP>                                                                                                                                                                                                                                                                       
95<STOP>                                                                                                                                                                                                                                                                        
108<STOP>                                                                                                                                                                                                                                                                       
111<STOP>                                                                                                                                                                                                                                                                       
99<STOP>                                                                                                                                                                                                                                                                        
97<STOP>                                                                                                                                                                                                                                                                        
116<STOP>                                                                                                                                                                                                                                                                       
105<STOP>                                                                                                                                                                                                                                                                       
111<STOP>                                                                                                                                                                                                                                                                       
110<STOP>                                                                                                                                                                                                                                                                       
115<STOP>                                                                                                                                                                                                                                                                       
32<STOP>                                                                                                                                                                                                                                                                        
61<STOP>                                                                                                                                                                                                                                                                        
32<STOP>                                                                                                                                                                                                                                                                        
123<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
69<STOP>                                                                                                                                                                                                                                                                        
84<STOP>                                                                                                                                                                                                                                                                        
39<STOP>                                                                                                                                                                                                                                                                        
58<STOP>                                                                                                                                                                                                                                                                        
32<STOP>
39<STOP>                                                                                                                                                                                                                                                                        
80<STOP>                                                                                                                                                                                                                                                                        
111<STOP>                                                                                                                                                                                                                                                                       
105<STOP>                                                                                                                                                                                                                                                                       
110<STOP>                                                                                                                                                                                                                                                                       
116<STOP>                                                                                                                                                                                                                                                                       
32<STOP>                                                                                                                                                                                                                                                                        
68<STOP>                                                                                                                                                                                                                                                                        
101<STOP>                                                                                                                                                                                                                                                                       
102<STOP>                                                                                                                                                                                                                                                                       
105<STOP>                                                                                                                                                                                                                                                                       
97<STOP>                                                                                                                                                                                                                                                                        
110<STOP>                                                                                                                                                                                                                                                                       
99<STOP>                                                                                                                                                                                                                                                                        
101<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
44<STOP>                                                                                                                                                                                                                                                                        
32<STOP>                                                                                                                                                                                                                                                                        
39<STOP>                                                                                                                                                                                                                                                                        
65<STOP>                                                                                                                                                                                                                                                                        
110<STOP>                                                                                                                                                                                                                                                                       
116<STOP>                                                                                                                                                                                                                                                                       
106<STOP>                                                                                                                                                                                                                                                                       
101<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
58<STOP>                                                                                                                                                                                                                                                                        
32<STOP>                                                                                                                                                                                                                                                                        
39<STOP>                                                                                                                                                                                                                                                                        
84<STOP>                                                                                                                                                                                                                                                                        
105<STOP>                                                                                                                                                                                                                                                                       
101<STOP>                                                                                                                                                                                                                                                                       
114<STOP>                                                                                                                                                                                                                                                                       
112<STOP>                                                                                                                                                                                                                                                                       
97<STOP>                                                                                                                                                                                                                                                                        
114<STOP>                                                                                                                                                                                                                                                                       
107<STOP>                                                                                                                                                                                                                                                                       
32<STOP>                                                                                                                                                                                                                                                                        
72<STOP>                                                                                                                                                                                                                                                                        
97<STOP>                                                                                                                                                                                                                                                                        
103<STOP>                                                                                                                                                                                                                                                                       
101<STOP>                                                                                                                                                                                                                                                                       
110<STOP>                                                                                                                                                                                                                                                                       
98<STOP>                                                                                                                                                                                                                                                                        
101<STOP>                                                                                                                                                                                                                                                                       
99<STOP>                                                                                                                                                                                                                                                                        
107<STOP>                                                                                                                                                                                                                                                                       
39<STOP>                                                                                                                                                                                                                                                                        
125<STOP>                                                                                                                                                                                                                                                                       
13<STOP>
```

**Comment by takluyver** [comment]
OK, so the line breaks are going through as 13, which is carriage return. But that's the same as what happens when I press enter in a terminal, and prompt_toolkit specifically [handles that](https://github.com/jonathanslenders/python-prompt-toolkit/blob/9b6cd5adfc6892e0bf9251366e03041a45885430/prompt_toolkit/terminal/vt100_input.py#L393).

Is your prompt_toolkit up to date?

@jonathanslenders, might you have a moment to investigate this? Thanks!

**Comment by bennigoetz** [comment]
```python
In [2]: prompt_toolkit.__version__
Out[2]: '1.0.7'
```

So I guess it's 0.0.1 out-of-date. I don't have a lot of control of the Python libraries on the system, as I'm on a large cluster (TACC). If you think it would make a difference, I could try installing 1.0.8 locally, and rearranging my PYTHONPATH so my local library takes precedence?

**Comment by takluyver** [comment]
I don't think that would be it - I think the CR->LF conversion has been there a while. If you've got time to fiddle with it then go for it, otherwise let's see what Jonathan (the author of prompt_toolkit) thinks.

**Comment by usnigg** [comment]
Like Crandel I downgraded to ipython4 because of the lack of multi-line support when running ipython in emacs repl. I tried to use the EIN emacs mode and that works fine with ipython5 although tabs don't work well. Also the notebook flow slows me down so It would be great if someone could add multi-line support with emacs in ipython5 : ). I don't see myself abandoning emacs just yet ;-)

**Comment by bennigoetz** [comment]
Hi @usnigg, not to get sidetracked here, but does your Emacs Python REPL show the input commands in the interpreter? I like my vi setup, but I've been playing with Emacs, and one thing that annoys me about the Python major mode and associated inferior process is that it only displays things that I explicitly ask it to print, not the input. For my work I execute a lot of lines or code blocks individually, and seeing the command displayed in the interpreter helps keep track of what's going on.

**Comment by usnigg** [comment]
@bennigoetz. No it doesn't at least with C-c | (execute region). I rarely use that though. If I needed to see the input I'd just select and copy the lines of code into the ipython buffer and execute, which works with multi-line support.

**Comment by altaurog** [comment]
I am also having trouble pasting multiline blocks.  I use [jessies.org terminator](https://github.com/software-jessies-org/jessies/wiki/Terminator) which seems to be sending LF between lines, but ipython only gets the first line.

```
$ python getch.py 
READY
107<STOP>
32<STOP>
61<STOP>
32<STOP>
49<STOP>
48<STOP>
50<STOP>
52<STOP>
10<STOP>
109<STOP>
32<STOP>
61<STOP>
32<STOP>
107<STOP>
32<STOP>
42<STOP>
32<STOP>
107<STOP>
10<STOP>
0<STOP>
$ ipython
In [1]: k = 1024
In [2]: 
$ pip freeze | grep -e ipython -e prompt
ipython==5.1.0
ipython-genutils==0.1.0
prompt-toolkit==1.0.9
```

**Comment by patfla** [comment]
iPython 5.1 in Windows (7) Emacs 25.1.2 run-python.

The trick to use an elpy buffer to send to *Python* works well - thanks.

None of the %magic% functions work and, in particular, I'd like %recall.  Backed up briefly to iPython 4.2.1 however this put me back to no Output at all so that's not an option.

What programming changes would be involved to make %recall work?

**Comment by fperez** [comment]
I'm curious if @ivanov might have some ideas on the vim front (I know the Emacs issues are separate)?

**Comment by ivanov** [comment]
nope, no clue, unfortunately. I still have an old IPython installed when I need to get a lot of interactive work done because it respects `.inputrc` and I haven't made the time to make prompt_toolkit act the ways readline does. The functionality provided by `--TerminalInteractiveShell.editing_mode=vi` is inconsistent enough wih muscle memory that it makes it more frustrating than just using the default mode, so I stick with that when I'm in IPython 5 these days.

**Comment by samrayleung** [comment]
Ipython6 is released, is this issue fixed?

**Comment by tttuuu888** [comment]
I upgraded to Ipython5 and downgraded to Ipython4 with same Emacs issue. If everything works same, I could just stick with Ipython4 but something is changed and work weird now.
When I define simple function and execute it twice in ipython, it shows like below:
```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: def temp():
   ....: return 0
   ....: 

In [12]: temp()
%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
raise;range;raw_input;%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%rmdir;round;%%ruby;%run
return
return
return
raise;range;raw_input;%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%rmdir;round;%%ruby;%run
return
return
return
raise;range;raw_input;%recall;reduce;%rehashx;reload;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%rmdir;round;%%ruby;%run
Out[16]: 0

In [17]: temp()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-21-9a3c6ba04cf8> in <module>()
----> 1 temp()

<ipython-input-11-059b6888777a> in temp()
      1 def temp():
----> 2     import codecs, os;__pyfile = codecs.open('''/tmp/py42419kY''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py42419kY''');exec(compile(__code, '''/tmp/py42419kY''', 'exec'));
      3     import codecs, os;__pyfile = codecs.open('''/tmp/py4241Kve''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py4241Kve''');exec(compile(__code, '''/tmp/py4241Kve''', 'exec'));
      4     import codecs, os;__pyfile = codecs.open('''/tmp/py4241X5k''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py4241X5k''');exec(compile(__code, '''/tmp/py4241X5k''', 'exec'));
      5     import codecs, os;__pyfile = codecs.open('''/tmp/py4241kDr''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py4241kDr''');exec(compile(__code, '''/tmp/py4241kDr''', 'exec'));

/usr/lib/python2.7/codecs.pyc in open(filename, mode, encoding, errors, buffering)
    894             # Force opening of the file in binary mode
    895             mode = mode + 'b'
--> 896     file = __builtin__.open(filename, mode, buffering)
    897     if encoding is None:
    898         return file

IOError: [Errno 2] No such file or directory: '/tmp/py49784HG'
```

It works fine if I execute ipython in terminal.

**Comment by ivanov** [comment]
I just want to mention that if you would like the old (IPython <= 4.x) readline interface, it is now available separately as [rlipython](https://github.com/ipython/rlipython). 

```
pip install rlipython
python -c "import rlipython as r; r.install()"
```

Right now, it only works in IPython 6.0 (Python 3), but it will also work in Python 2 with the next IPython 5 release (5.4).

I suspect, but have not verified, that the style of interaction with emacs that used to work in IPython <= 4 should work again with rlipython. If not, file an issue there and I can take a look.

**Comment by tttuuu888** [comment]
Thanks for your suggestion @ivanov but unfortunately I have a same issue even after rlipython installed. 
Error messages are shown as below:
```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def temp():
   ...: return 0
   ...: 

In [9]: temp()
%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed
raise;range;%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%r\
mdir;round;%%ruby;%run
return
return
return
raise;range;%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%r\
mdir;round;%%ruby;%run
return
return
return
raise;range;%recall;%rehashx;%reload_ext;%rep;repr;%rerun;%reset;%reset_selective;return;reversed;%rm;%r\
mdir;round;%%ruby;%run
Out[12]: 0

In [13]: temp()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-17-9a3c6ba04cf8> in <module>()
----> 1 temp()

<ipython-input-8-3cf4da01de46> in temp()
      1 def temp():
----> 2     import codecs, os;__pyfile = codecs.open('''/tmp/py30478b2j''', encoding='''utf-8''');__code\
 = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py30478b2j''');exec(compile(__\
code, '''/tmp/py30478b2j''', 'exec'));
      3     import codecs, os;__pyfile = codecs.open('''/tmp/py30478oAq''', encoding='''utf-8''');__code\
 = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py30478oAq''');exec(compile(__\
code, '''/tmp/py30478oAq''', 'exec'));
      4     import codecs, os;__pyfile = codecs.open('''/tmp/py304781Kw''', encoding='''utf-8''');__code\
 = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py304781Kw''');exec(compile(__\
code, '''/tmp/py304781Kw''', 'exec'));
      5     import codecs, os;__pyfile = codecs.open('''/tmp/py30478CV2''', encoding='''utf-8''');__code\
 = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py30478CV2''');exec(compile(__\
code, '''/tmp/py30478CV2''', 'exec'));

/usr/lib/python3.5/codecs.py in open(filename, mode, encoding, errors, buffering)
    893         # Force opening of the file in binary mode
    894         mode = mode + 'b'
--> 895     file = builtins.open(filename, mode, buffering)
    896     if encoding is None:
    897         return file

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/py30478b2j'

In [18]: 

```

Looks like something is broken on the process to upgrade and downgrade ipython.
I found simple-prompt option does not support mulitline coding too late, so I had to downgrade ipython on my home PC, company PC and server PC. Now all ipython from those computers shows same error.
I hope anyhow this issue will be solved soon. Thanks a lot.

**Comment by tttuuu888** [comment]
In case of my emacs + ipython error, It is solved when I try python-mode package instead of built-in emacs python package. It works as usual when I start ipython using python-mode package.(w/ Ipython 4.2.1 version)  I hope this would be helpful for anybody having same problem with me. 

Thanks again for all contributing to ipython.

**Comment by infinity0** [comment]
This is [preventing the cantor sage backend from working](https://groups.google.com/d/msg/sage-packaging/MnHC3OzgAjQ/XwcMCo1jBQAJ).

**Comment by Carreau** [comment]
You most likely want to have a look at [rlipython](https://github.com/ipython/rlipython), it allows to re-use readline as a backend and should work way better with emacs.

**Comment by memeplex** [comment]
@ivanov @Carreau I've been using `--simple-prompt` which currently allows some kind of primitive multiline editing in emacs although I've always missed the superior pt capabilities since I started running my repls inside emacs. So I googled for alternatives and ended up here. After testing rlipython I'm unable to find any relevant differences vs plain `--simple-prompt`, at least for multiline editing. What would be rlipython selling points for emacs users? Do you know?

**Comment by ivanov** [comment]
@memeplex - does the emacs repl allow you to use up arrows to cycle in history? `--simple-prompt` does not support that, but that's the only thing that comes immediately to mind. I guess the lack of that feature also implies that you do not get history across sessions.

**Comment by memeplex** [comment]
Up/down arrows work for moving between lines in a multiline input but not for history cycling.
