### ISSUE TITLE
Error, don't know the reasons, can anyone help me?

### ISSUE THREAD

**Issue by AleXY42** [ipython/ipython#9836]
Please help me out. I just installed ipython. but when I try to run it,  it shows some following info:

```
C:\Windows\system32>ipython
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_i
python
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 596
, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in s
tart
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 402, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 385, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 389, in
 run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 6
6, in run
    self._inputhook_context.call_inputhook(ready)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\inputhook.py", li
ne 82, in call_inputhook
    select_fds([self._r], timeout=None)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line
49, in select_fds
    result = _select(read_fds, timeout)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line
99, in _select
    return select.select(read_fds, [], [], timeout)[0]
error: (10038, '')

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True


C:\Windows\system32>
```

**Comment by takluyver** [comment]
@jonathanslenders have you seen this before? Error 10038 is 'Socket operation on nonsocket.' - i.e. it's trying to select() on something that isn't selectable on Windows.

**Comment by taogao** [comment]
I may got a similar error:

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in start
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 402, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 385, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 66, in run
    self._inputhook_context.call_inputhook(ready)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\inputhook.py", line 82, in call_inputhook
    select_fds([self._r], timeout=None)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line 49, in select_fds
    result = _select(read_fds, timeout)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line 99, in _select
    return select.select(read_fds, [], [], timeout)[0]
error: (10038, 'An operation was attempted on something that is not a socket')

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by ttolttol2** [comment]
I got same issue too

`C:\Documents and Settings\Administrator>ipython
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_i
python
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 596
, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in s
tart
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 402, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 385, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 389, in
 run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 6
6, in run
    self._inputhook_context.call_inputhook(ready)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\inputhook.py", li
ne 82, in call_inputhook
    select_fds([self._r], timeout=None)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line
49, in select_fds
    result = _select(read_fds, timeout)
  File "c:\python27\lib\site-packages\prompt_toolkit\eventloop\select.py", line
99, in _select
    return select.select(read_fds, [], [], timeout)[0]
error: (10038, '')

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True`

**Comment by takluyver** [comment]
From the sudden influx of errors, I suspect that this bug was introduced by [this prompt_toolkit commit](https://github.com/jonathanslenders/python-prompt-toolkit/commit/ac26b0257427285ae20aa893da08e0f64b824d4d) working around a gevent bug.

I'm also guessing that it only shows up on Python 2: because of the exception reorganisation that took place in Python 3.3, the error in Python 3 is probably a subclass of `OSError`, and so it gets caught.

**Comment by takluyver** [comment]
Can you try installing prompt_toolkit from my pull request at jonathanslenders/python-prompt-toolkit#368? I think that should make it work.

**Comment by jonathanslenders** [comment]
Prompt_toolkit 1.0.5 has been released. Can you do ``pip install -U prompt_toolkit`` and try again?
Excuse me for the inconvenience!

**Comment by takluyver** [comment]
Closing as this should be fixed - thanks Jonathan.

**Comment by AleXY42** [comment]
thank you Jonathan and Takluyver, problem solved

**Comment by letoncse** [comment]
I'm getting this issue , using python 2.7.11 and windows 7
`Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\src\ckan\ckan\Scripts\paster.exe\__main__.py", line 9, in <module>
  File "c:\src\ckan\ckan\lib\site-packages\paste\script\command.py", line 101, i
n run
    command = commands[command_name].load()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2443
, in load
    return self.resolve()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2449
, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\src\ckan\ckan\lib\cli.py", line 4, in <module>
    import os
  File "C:\src\ckan\ckan\lib\os.py", line 120, in <module>
    from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: No module named path
`
Anyone help please
