### ISSUE TITLE
sqlite3 OperationalError

### ISSUE THREAD

**Issue by marius311** [ipython/ipython#9909]
I'm seeing the following history-related error when I start up IPython. If I set `
c.HistoryAccessor.enabled = False` it goes away. This is after upgrading to the latest IPython using pip from some ancient version that was available on this cluster. I've tried

* deleting the entire `~/.ipython` folder
* putting the history file on a different filesystem with `HistoryManager.hist_file` as well as setting it to `:memory:`

Any ideas? Output attached below. Thanks for any help!

```
$ ipython3
[TerminalIPythonApp] ERROR | Failed to open SQLite history /home/mmillea/.ipython/profile_default/history.sqlite (near "NOT": syntax error).
[TerminalIPythonApp] ERROR | History file was moved to /home/mmillea/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /home/mmillea/.ipython/profile_default/history.sqlite (near "NOT": syntax error).
[TerminalIPythonApp] ERROR | History file was moved to /home/mmillea/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /home/mmillea/.ipython/profile_default/history.sqlite (near "NOT": syntax error).
[TerminalIPythonApp] ERROR | Failed to load history too many times, history will not be saved.
[TerminalIPythonApp] ERROR | Failed to open SQLite history :memory: (near "NOT": syntax error).
Traceback (most recent call last):
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 89, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 259, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.OperationalError: near "NOT": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 89, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 259, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.OperationalError: near "NOT": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 89, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 259, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.OperationalError: near "NOT": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmillea/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/mmillea/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/mmillea/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/mmillea/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 309, in initialize
    self.init_shell()
  File "/home/mmillea/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 325, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/mmillea/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 396, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 477, in __init__
    self.init_history()
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1577, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 542, in __init__
    **traits)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 231, in __init__
    self.init_db()
  File "<decorator-gen-14>", line 2, in init_db
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 117, in catch_corrupt_db
    self.init_db()
  File "<decorator-gen-14>", line 2, in init_db
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 117, in catch_corrupt_db
    self.init_db()
  File "<decorator-gen-14>", line 2, in init_db
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 117, in catch_corrupt_db
    self.init_db()
  File "<decorator-gen-14>", line 2, in init_db
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 89, in catch_corrupt_db
    return f(self, *a, **kw)
  File "/home/mmillea/lib/python3.5/site-packages/IPython/core/history.py", line 259, in init_db
    end timestamp, num_cmds integer, remark text)""")
sqlite3.OperationalError: near "NOT": syntax error

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

Here's my info:

```
$ python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/mmillea/lib/python3.5/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.16.60-0.103.1-smp-x86_64-with-SuSE-10-x86_64',
 'sys_executable': '/home/mmillea/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Aug 24 2016, 19:25:45) \n[GCC 4.8.2]'}
```

**Comment by Carreau** [comment]
what version of sqlite3 do you have ?

**Comment by marius311** [comment]
Here's what I see:

```
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.2.8'
>>> sqlite3.version
'2.6.0'
```

**Comment by Carreau** [comment]
form https://sqlite.org/changes.html:

> 2006-01-11 (3.3.0 alpha)

> ...  IF EXISTS and IF NOT EXISTS clauses on CREATE/DROP TABLE/INDEX.

And you have 3.2, so you likely need to upgrade that. Not sure why sqlite is using this old version....

**Comment by marius311** [comment]
Indeed, updated sqlite and it fixed it. Certainly this old version is what was present on this system. Does Python come with its own version? No idea why it wasn't using that if that's the case. At any rate, upgrading it by hand seems to have fixed it.Thanks!

**Comment by takluyver** [comment]
> Does Python come with its own version? 

I think it depends how you get it. If you compile Python from source, it will pick up the version installed on your system.
