### ISSUE TITLE
I install and run the ipython first time, but it happens an error whatever code I run.

### ISSUE THREAD

**Issue by zhuyuxing** [ipython/ipython#9921]
The error is TypeError: argument of type 'NoneType' is not iterable.
the error msg is before, and I don't the reason.
the env is "Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AM
D64)]"

_In [1]: Traceback (most recent call last):
  File "C:\Python34\Scripts\ipython-script.py", line 9, in <module>
    load_entry_point('ipython==5.1.0', 'console_scripts', 'ipython')()
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\__init__.p
y", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 596
, in launch_instance
    app.start()
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\terminal\i
papp.py", line 348, in start
    self.shell.mainloop()
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\terminal\i
nteractiveshell.py", line 440, in mainloop
    self.interact()
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\terminal\i
nteractiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\terminal\i
nteractiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 389, in
 run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\python34\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 8
1, in run
    callbacks.feed_key(k)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 1019, i
n feed_key
    cli.input_processor.process_keys()
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor
.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor
.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\input_processor
.py", line 228, in _call_handler
    handler.call(event)
  File "c:\python34\lib\site-packages\prompt_toolkit\key_binding\registry.py", l
ine 31, in call
    return self.handler(event)
  File "c:\python34\lib\site-packages\ipython-5.1.0-py3.4.egg\IPython\terminal\s
hortcuts.py", line 103, in newline_or_execute
    b.accept_action.validate_and_handle(event.cli, b)
  File "c:\python34\lib\site-packages\prompt_toolkit\buffer.py", line 83, in val
idate_and_handle
    self.handler(cli, buffer)
  File "c:\python34\lib\site-packages\prompt_toolkit\buffer.py", line 89, in _re
turn_document_handler
    cli.set_return_value(buffer.document)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 580, in
 set_return_value
    self._redraw()  # Redraw in "done" state, after the return value has been se
t.
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 346, in
 _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 449, in
render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 125, in
_output_screen_diff
    current_pos = move_cursor(Point(0, 0))
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 91, in m
ove_cursor
    _output_cursor_backward(current_x - new.x)
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 256, in cursor_backward
    self.cursor_forward(-amount)
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 249, in cursor_forward
    sr = self.get_win32_screen_buffer_info().dwCursorPosition
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 50, in __init__
    xterm = 'xterm' in os.environ.get('TERM')
TypeError: argument of type 'NoneType' is not iterable

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True_

**Comment by minrk** [comment]
There's a bug in how prompt-toolkit handles TERM being undefined, but I suspect there might be another issue. cc @jonathanslenders for ideas.

**Comment by jonathanslenders** [comment]
Hi @zhuyuxing, the error message has been fixed in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d

However, this happens during the error handling of another issue.
I guess that you are not starting IPython from cmd.exe, is that possible?

**Comment by zhuyuxing** [comment]
Hi @jonathanslenders ,Thank you for your solution, but  I'm sure I start IPython from cmd.exe.

I edited the code in prompt_toolkit/terminal/win32_output.py according your solution, the error is that your said "prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows cons
ole found. Are you running cmd.exe?".

Also, I tried to test them in virtualenv.
when I ran IPython from python27 in virtualenv, then pip install ipython, and it hadn't any error and ran it successfully.
when I ran IPython from python34 in virtualenv with no packages, then pip install ipython, but it happened the same error again.

I have no idea for it, I guess I will test it in my home using another computer, just want to know if this current computer  has any problem.

**Comment by zhuyuxing** [comment]
I think I have solved it though I don't know the reason. I pip install python4, then the error doesn't happen again.

My ipython version is python5. When I ran pycharm to use python3.4 console, it got an error: 'PyDevTerminalInteractiveShell' object has no attribute 'has_readline'
then I internet the error to solve it, and someone solved it :  http://stackoverflow.com/questions/38341240/pydevterminalinteractiveshell-object-has-no-attribute-has-readline.

When I changed my ipython5 to ipython4, the error doesn't happen again.

**Comment by ouverz** [comment]
I too have this same issue. Running pip install for IPython didn't work for version 4 as well. I had to manually install IPython and the various dependencies. I have Windows 10 and ran pip install for version 5.0 from the command line

**Comment by takluyver** [comment]
That's a different error, and looking at the Jetbrains issue tracker, it should be fixed if you upgrade Pycharm to 2016.2.

**Comment by aaronmyatt** [comment]
@takluyver @jonathanslenders @minrk @ouverz @zhuyuxing 

Hi all, brought here by [Code Triage](https://www.codetriage.com/). I am making a public commitment to seeing this random issue through to a satisfactory resolution! I hope I can count on your support in this endeavour.

Does this issue still merit investigation? If so, could you please confirm if I can (most likely) reproduce this issue by fulfilling the following dependencies/environment:

- Windows ( @ouverz mentions Windows 10? )
- Virtualenv
- Python 3.4
- iPython (version 5?)

**Comment by takluyver** [comment]
The original error reported has been fixed in prompt_toolkit. There was another issue with PyCharm described above which has been fixed in PyCharm. And there was a third issue (`NoConsoleScreenBufferError`) related to prompt_toolkit in Windows, but I don't think we've ever had a reliable way to replicate that - prompt_toolkit usually works in Windows, and we haven't identified any pattern in people reporting issues with it. There may also have been upgrades to prompt_toolkit which fixed it in the meantime.

If you have a Windows computer, then feel free to install and launch it in different ways and see if you can replicate the issue.

**Comment by aaronmyatt** [comment]
@takluyver appreciate your quick and informative response.

Time to give the old windows box some life!

**Comment by jonathanslenders** [comment]
The ``NoConsoleScreenError`` is probably fixed as well. (See: https://github.com/jonathanslenders/python-prompt-toolkit/commit/d5d9e29 ). I'm not 100% sure, because this only happened on certain installations of Windows in a particular situation, and it was hard to reproduce. But I haven't heard of anyone having that issues for some time.

**Comment by aaronmyatt** [comment]
@takluyver @jonathanslenders 

Please excuse my naivety, considering the general sentiment you are both expressing "it's an old issue, there have been updates/fixes, no one has reported it in some time", is there a protocol for retiring such issues? Or is the policy to maintain unresolved issues indefinitely?

Meanwhile I've got a vagrant image downloading and I'll at least try to replicate the environment conditions!

**Comment by takluyver** [comment]
In a situation like this, we'd probably close the issue normally and suggest people file a new one if they can still reproduce a similar error. There's no special protocol for that, though.

As you were preparing to try to replicate it, let's leave it open until you've had a go. If you can replicate it, we can attempt to work out what's going on; if not, we'll close the issue.

**Comment by aaronmyatt** [comment]
@takluyver I took my sweet ass time but I finally have an environment set up to try reproducing this issue.

I'm running Windows 10, and I have replicated the original issuers Python settings:
```Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.```

I now face a different Prompt Toolkit error:

```Traceback (most recent call last):
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 413, in run
    self._redraw()
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 450, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 128, in _output_screen_diff
    output.erase_down()
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 193, in erase_down
    sbinfo = self.get_win32_screen_buffer_info()
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python34\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python34\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python34\lib\site-packages\IPython\terminal\ipapp.py", line 348, in start
    self.shell.mainloop()
  File "c:\python34\lib\site-packages\IPython\terminal\interactiveshell.py", line 440, in mainloop
    self.interact()
  File "c:\python34\lib\site-packages\IPython\terminal\interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "c:\python34\lib\site-packages\IPython\terminal\interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 425, in run
    self._redraw()
  File "c:\python34\lib\site-packages\prompt_toolkit\interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 450, in render
    previous_width=(self._last_size.columns if self._last_size else 0))
  File "c:\python34\lib\site-packages\prompt_toolkit\renderer.py", line 128, in _output_screen_diff
    output.erase_down()
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 193, in erase_down
    sbinfo = self.get_win32_screen_buffer_info()
  File "c:\python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True```

Here are some issues with similar errors:

https://github.com/ipython/ipython/issues/10070
https://github.com/jonathanslenders/python-prompt-toolkit/issues/406

What could I have missed in my setup? Perhaps something to do with my unfamiliarity with windows.

**Comment by jonathanslenders** [comment]
Hi @aaronmyatt,

Is it possible that you are running IPython from within git-bash or something similar instead of cmd.exe?
If so, it will probably work using winpty, but better is to use a real console.
