### ISSUE TITLE
ImportError: cannot import name Widget

### ISSUE THREAD

**Issue by monajalal** [ipython/ipython#9928]
How can I solve this issue for `Python 2.7.10` in `Ubuntu 15.10`?

```
jalal@klein:/usr/local/MATLAB/R2016a/sys/os/glnxa64$ python -m matlab_kernel install
/usr/local/lib/python2.7/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 9, in <module>
    from metakernel import MetaKernel
  File "/usr/local/lib/python2.7/dist-packages/metakernel/__init__.py", line 1, in <module>
    from ._metakernel import (
  File "/usr/local/lib/python2.7/dist-packages/metakernel/_metakernel.py", line 32, in <module>
    from IPython.html.widgets import Widget
ImportError: cannot import name Widget

```

**Comment by takluyver** [comment]
`IPython.html.widgets` was moved to a separate package called `ipywidgets`. You may need  to install it.

**Comment by Carreau** [comment]
Closing as this has likely be fixed. 

If this is not the case let us know @monajalal
