### ISSUE TITLE
Invalid rgba arg kills ipython session in pylab mode

### ISSUE THREAD

**Issue by notmatthancock** [ipython/ipython#9937]
When `pylab` is invoked, if an invalid rgb value is specified, the ipython session is effectively killed.

```
In [1]: pylab
Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib

In [2]: plot([1,2,3], c=(1.0,1.0,1.5))
Out[2]: [<matplotlib.lines.Line2D at 0x7f9b2c063990>]

In [3]: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.pg
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py",w
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in dr
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1159, inw
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in dr
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2319w
    a.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in dr
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/lines.py", line 752, in dw
    ln_color_rgba = self._get_rgba_ln_color()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/lines.py", line 1290, in r
    return colorConverter.to_rgba(self._color, self._alpha)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/colors.py", line 376, in a
    'to_rgba: Invalid rgba arg "%s"\n%s' % (str(arg), exc))
ValueError: to_rgba: Invalid rgba arg "(1.0, 1.0, 1.5)"
number in rbg sequence outside 0-1 range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Ok, fine. So I gave an invalid argument, and it gave back an error. Unfortunately -- and this is what is unique to `pylab` mode -- plotting is now completely unresponsive. Moreover, the above error message is printed repeatedly whenever I enter new lines of code into ipython. So, I essentially have to restart the session, a minor annoyance, depending on the amount of non-scripted work that I have to recreate. This behavior doesn't occur in ipython without `pylab`.

**Comment by minrk** [comment]
I think the issue is because the error is raised in a background qt thread, rather than during your plot call. The repeated error is probably because the plot is still 'open' so any time the matplotlib eventloop fires, it tries to draw again until the figure is closed. I'm surprised this gets us in a hung state, though. Maybe related to the way we talk to prompt-toolkit?

**Comment by notmatthancock** [comment]
> Maybe related to the way we talk to prompt-toolkit?

I'm not sure how recently prompt-toolkit was introduced, but this bug appears in both ipython versions 4 and 5.

It would be nice if it failed more gracefully, so that starting the figure from scratch wasn't necessary. I haven't the faintest idea where to start looking, but perhaps I'll try digging around a little bit when I get some time.

**Comment by minrk** [comment]
PT is new in 5, so that rules it out as introducing the problem.
