### ISSUE TITLE
Starting IPython - Attribute Error: 'module' object has no attribute 'error'

### ISSUE THREAD

**Issue by asinode** [ipython/ipython#9968]
I tried to search a lot online to find if somebody had the same issue. But I don't find anything with this problem. 

Whenever I type `ipython` in my terminal, it ends up with the following error, and terminal won't go back to prompt. Jupyter-notebook works fine. Spyder is launching fine. Python interpreter has no issues. It is only with IPython.

```py
$  ipython
Python 2.7.11 |Anaconda custom (64-bit)| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/as/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/as/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/as/anaconda2/lib/python2.7/site-packages/prompt_toolkit/eventloop/inputhook.py", line 66, in thread
    input_is_ready_func(wait=True)
  File "/home/as/anaconda2/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 101, in ready
    return self._ready_for_reading(current_timeout[0] if wait else 0) != []
  File "/home/as/anaconda2/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 184, in _ready_for_reading
    r, _, _ =_select(read_fds, [], [], timeout)
  File "/home/as/anaconda2/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 279, in _select
    except select.error as e:
AttributeError: 'module' object has no attribute 'error'
```

- The only recent change I made on my machine is, as far as I could remember, installing PyDev plugins for Eclipse and configuring interpreters there with Jython. 
- And I installed R along with IRKernel for Jupyter-notebook. That works fine too.

Please help.

**Comment by takluyver** [comment]
Do you have a file called `select.py` or `select/__init__.py` in the working directory? If so, it's clashing with a standard library module.

**Comment by asinode** [comment]
You mean from where I cam calling `ipython`? No. This happens whichever location I call it from. 

What exactly is a working directory? I am sorry for these questions, but I usually maintain my own folders where I keep my python code and jupyter notebooks. And I tried calling ipython from different locations and the same results.

And if you mean ipython's executable location, this is what I see. There are no files with the names you mentioned.

```sh
$  which ipython
/home/as/anaconda2/bin/ipython
```

```sh
$  ls -l ~/anaconda2/bin/*.py
-rwxr-xr-x 1 as as  1195 Aug 12 00:19 /home/as/anaconda2/bin/get_objgraph.py
-rwxr-xr-x 1 as as  1688 Sep 14 14:10 /home/as/anaconda2/bin/jp.py
-rwxr-xr-x 1 as as   607 Aug 12 00:19 /home/as/anaconda2/bin/rst2html.py
-rwxr-xr-x 1 as as   804 Aug 12 00:19 /home/as/anaconda2/bin/rst2latex.py
-rwxr-xr-x 1 as as   613 Aug 12 00:19 /home/as/anaconda2/bin/rst2man.py
-rwxr-xr-x 1 as as  1711 Aug 12 00:19 /home/as/anaconda2/bin/rst2odt_prepstyles.py
-rwxr-xr-x 1 as as   777 Aug 12 00:19 /home/as/anaconda2/bin/rst2odt.py
-rwxr-xr-x 1 as as   614 Aug 12 00:19 /home/as/anaconda2/bin/rst2pseudoxml.py
-rwxr-xr-x 1 as as   650 Aug 12 00:19 /home/as/anaconda2/bin/rst2s5.py
-rwxr-xr-x 1 as as   799 Aug 12 00:19 /home/as/anaconda2/bin/rst2xetex.py
-rwxr-xr-x 1 as as   615 Aug 12 00:19 /home/as/anaconda2/bin/rst2xml.py
-rwxr-xr-x 1 as as   683 Aug 12 00:19 /home/as/anaconda2/bin/rstpep2html.py
-rwxr-xr-x 1 as as 16314 Aug 12 00:19 /home/as/anaconda2/bin/runxlrd.py
-rwxr-xr-x 1 as as 18552 Sep 19 13:45 /home/as/anaconda2/bin/smtpd.py
-rwxr-xr-x 1 as as   421 Aug 12 00:19 /home/as/anaconda2/bin/unpickle.py
-rwxr-xr-x 1 as as  1966 Aug 12 00:19 /home/as/anaconda2/bin/vba_extract.py

$  ls -l ~/anaconda2/bin/select
ls: cannot access '/home/as/anaconda2/bin/select': No such file or directory
```

**Comment by asinode** [comment]
By the way, let me just add, just in case. I maintain a couple environments using Anaconda's `conda` and one of the envs has Python3. There is no problem with `ipython` in this setup at all.

```sh
$  conda-env list
# conda environments:
#
DApy3                    /home/as/anaconda2/envs/DApy3
cobol                    /home/as/anaconda2/envs/cobol
floobits                 /home/as/anaconda2/envs/floobits
root                  *  /home/as/anaconda2

$  source activate DApy3
$  which ipython
/home/as/anaconda2/envs/DApy3/bin/ipython
$  ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: print ("Hello, World!")
Hello, World!

In [2]: 
```

**Comment by takluyver** [comment]
If you launch Python 2 and do this, what do you get:

```python
import select
print(select)
```

The standard library select module definitely should have [select.error](https://docs.python.org/2.7/library/select.html#select.error), which is why I think it's finding another select module somewhere.

**Comment by asinode** [comment]
Got this result:

```py
$  python
Python 2.7.11 |Anaconda custom (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import select
>>> print(select)
<module 'select' from '/home/as/anaconda2/lib/python2.7/lib-dynload/select.so'>
>>> 
```

**Comment by takluyver** [comment]
That looks OK. And if you do `select.error` there, what does it show?

**Comment by takluyver** [comment]
Ah,  I think you've got a broken prompt_toolkit installation. Try:

```
conda uninstall prompt_toolkit
pip install prompt_toolkit
```

**Comment by asinode** [comment]
Oh, I guess that just removed everything that had to do with ipython. Shall I now run `conda install ipython` and `conda install jupyter`?

```sh
$  conda uninstall prompt_toolkit
Fetching package metadata .......
Solving package specifications: ..........

Package plan for package removal in environment /home/as/anaconda2:

The following packages will be REMOVED:

    _nb_ext_conf:       0.3.0-py27_0
    ipykernel:          4.5.0-py27_0
    ipython:            5.1.0-py27_0
    ipywidgets:         5.2.2-py27_0
    jupyter:            1.0.0-py27_3
    jupyter_console:    5.0.0-py27_0
    nb_anacondacloud:   1.2.0-py27_0
    nb_conda:           2.0.0-py27_0
    nb_conda_kernels:   2.0.0-py27_0
    nbpresent:          3.0.2-py27_0
    notebook:           4.2.3-py27_0
    prompt_toolkit:     1.0.3-py27_0
    qtconsole:          4.2.1-py27_0
    spyder:             2.3.9-py27_1
    widgetsnbextension: 1.2.6-py27_0

Proceed ([y]/n)? 

Unlinking packages ...
[      COMPLETE      ]|###########################################################################################################################################| 100%

$  pip install prompt_toolkit
Requirement already satisfied (use --upgrade to upgrade): prompt_toolkit in ./anaconda2/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./anaconda2/lib/python2.7/site-packages (from prompt_toolkit)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in ./anaconda2/lib/python2.7/site-packages (from prompt_toolkit)

$  ipython
The program 'ipython' is currently not installed. You can install it by typing:
sudo apt install ipython
```

**Comment by takluyver** [comment]
Give that a try, but because of the way conda works, it might bring the problem right back. If so, try using pip to install everything:

```
conda uninstall prompt_toolkit
pip uninstall prompt_toolkit  # Just to make sure it's not there
pip install jupyter ipython
```

**Comment by asinode** [comment]
Yes. I guess that did it. I had to struggle getting `prompt_toolkit` uninstalled though. Coz each time I would uninstall and re-install it, it would again tell me `trying to install from cached prompt_tool wheel.....requirement already satisfied` and I would freak out. 

Finally, I thought I should close all my terminal sessions before trying to re-install. And that did the work!

Thank you very much. I am back on IPython. I really like it a lot.

**Comment by takluyver** [comment]
Great, glad you got it solved.

For future reference, this probably came about when you had prompt_toolkit installed by conda, and something you did with pip installed a newer version over it. They don't always play well together. It's ideal to remove a package with one before trying to install it with the other, but with dependencies, that's not always possible.

**Comment by Stonenumber** [comment]
> Do you have a file called `select.py` or `select/__init__.py` in the working directory? If so, it's clashing with a standard library module.

thanks, you solved my problem.

**Comment by Dsk7082** [comment]
Yes the init.py is clashing ..so what to do with that
