### ISSUE TITLE
Interpreter raises UnicodeEncodeError on startup

### ISSUE THREAD

**Issue by dor-d** [ipython/ipython#9972]
iPython interpreter raises UnicodeEncodeError on startup when the user's home directory name contains Unicode characters.
The exception comes from `pathlib` module which trying to convert the home directory's path from unicode string into regular str.

When another directory  is set as home directory, by `SET USERPROFILE=C:\temp ` for example, the interpreter opens without any problems.

Here is the traceback:
> Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 309, in initialize
    self.init_shell()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 325, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "c:\python27\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 396, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "c:\python27\lib\site-packages\IPython\core\interactiveshell.py", line 475, in __init__
    self.db = PickleShareDB(os.path.join(self.profile_dir.location, 'db'))
  File "c:\python27\lib\site-packages\pickleshare.py", line 73, in __init__
    self.root = Path(root)
  File "c:\python27\lib\site-packages\pathlib2.py", line 1095, in __new__
    self = cls._from_parts(args, init=False)
  File "c:\python27\lib\site-packages\pathlib2.py", line 760, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "c:\python27\lib\site-packages\pathlib2.py", line 748, in _parse_args
    parts.append(str(a))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

**Comment by takluyver** [comment]
I'm inclined to say that's a bug in the [pathlib2 backport](https://github.com/mcmtroffaes/pathlib2). Paths on Windows are natively unicode, so it should be valid to pass in a unicode string for a path.

In general, if you're using unicode paths on Windows, we strongly recommend using Python 3.
