### ISSUE TITLE
Unicode error in traceback

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9979]
Sorry for the long traceback, but I got this in the _terminal_ output while working in a notebook. My matplotlib install is borked so I would expect that to be _rare_ and difficult to reproduce:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2865, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e27d371d6baa>", line 1, in <module>
    get_ipython().magic('matplotlib inline')
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2142, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2063, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-104>", line 2, in matplotlib
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/magics/pylab.py", line 100, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2931, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/pylabtools.py", line 299, in activate_matplotlib
    import matplotlib.pyplot
  File "/Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/font_manager.py", line 55, in <module>
    from matplotlib import ft2font
ImportError: dlopen(/Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/ft2font.cpython-35m-darwin.so, 2): Library not loaded: libfreetype.6.dylib
  Referenced from: /Users/bussonniermatthias/dev/matplotlib/lib/matplotlib/ft2font.cpython-35m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 1805, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ImportError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2811, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2882, in run_code
    self.showtraceback()
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 1808, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1391, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1299, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1150, in structured_traceback
    tb_offset)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1095, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 822, in format_records
    frames.append(self.format_record(*r))
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 930, in format_record
    for token_type, token, start, end, line in generate_tokens(linereader):
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/tokenize.py", line 488, in tokenize
    encoding, consumed = detect_encoding(readline)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/tokenize.py", line 426, in detect_encoding
    if first.startswith(BOM_UTF8):
TypeError: startswith first arg must be str or a tuple of str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 1805, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 498, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2701, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 2830, in run_ast_nodes
    self.showtraceback()
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/interactiveshell.py", line 1808, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1391, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1299, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1150, in structured_traceback
    tb_offset)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 1095, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 822, in format_records
    frames.append(self.format_record(*r))
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/ultratb.py", line 930, in format_record
    for token_type, token, start, end, line in generate_tokens(linereader):
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/tokenize.py", line 488, in tokenize
    encoding, consumed = detect_encoding(readline)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/tokenize.py", line 426, in detect_encoding
    if first.startswith(BOM_UTF8):
```

**Comment by Carreau** [comment]
PEBKAC.
