### ISSUE TITLE
IPython 5.1.0 crashing on startup (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by dbrowneup** [ipython/ipython#9996]
Hi,

I'm having a problem with IPython that I've never had before. I run most of my packages with MacPorts and long ago installed IPython via port. Recently I upgraded my outdated packages and IPython is now broken with the following error generated upon calling `ipython` in the terminal:

```
$ ipython
Python 2.7.12 (default, Jun 29 2016, 12:53:15) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/eventloop/inputhook.py", line 66, in thread
    input_is_ready_func(wait=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 101, in ready
    return self._ready_for_reading(current_timeout[0] if wait else 0) != []
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 184, in _ready_for_reading
    r, _, _ =_select(read_fds, [], [], timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 279, in _select
    except select.error as e:
AttributeError: 'module' object has no attribute 'error'
```
I've tried uninstalling and reinstalling via MacPorts but that doesn't help. Any thoughts on how to fix this?

Thanks

**Comment by minrk** [comment]
Here's a hunch: what you do you get from:

    python -c 'import select; print(select.__file__)'

 when you are seeing this?

**Comment by dbrowneup** [comment]
```
$ python -c 'import select; print(select.__file__)'
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so
```
That's from the Bash terminal, not inside IPython. Not sure which you were suggesting. I can't do anything when I call `ipython` because that error pops up and the kernel freezes. Control-C won't get me out of it, so I just have to close the terminal window.

**Comment by minrk** [comment]
Hm. Is there a `select.py` or `select/` directory anywhere you can find? I'm guessing the error is due to something being imported instead of the stdlib module.

**Comment by takluyver** [comment]
I ran across something similar recently, where a conda installation and a pip installation of prompt_toolkit had clashed and produced a broken result. Some version of PT had a `select.py` in that folder, and some other version had an `import select`, which wound up doing relative import on Python 2.

Try uninstalling `prompt_toolkit` entirely (whatever it's called in macports), and reinstalling. If it still doesn't work, uninstall both IPython and prompt_toolkit with macports, and then use pip to install them:

```
pip install --upgrade setuptools pip
pip install ipython
```

**Comment by dbrowneup** [comment]
@minrk yes, I found a file select.py. Three of them, in fact:
```
[13][11:19:50][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] find ./ -name "select.py"
.//site-packages/prompt_toolkit/eventloop/select.py
.//site-packages/tornado/platform/select.py
.//site-packages/zmq/backend/select.py
```
I thought that namespaces were a honking great idea and we should do more of them, haha. Can't imagine why people would develop a module with the same name as a stdlib module.

My environment setup is a big mess honestly, because I started installing packages through either MacPorts or pip when I was still a total Python noob. It wasn't pretty, but it worked, so I never bothered to clean it up. I've considered switching to something like Homebrew, but I find the idea of uninstalling everything rather daunting.

@takluyver I followed your suggestion of uninstalling and reinstalling PT/IPython and that did the trick! Though it took a couple of tries for some reason...
```bash
[1][11:31:17][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] ipython
Traceback (most recent call last):
  File "/opt/local/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
ImportError: No module named prompt_toolkit.enums
[2][11:31:19][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] sudo port uninstall py27-prompt_toolkit
--->  Unable to uninstall py27-prompt_toolkit @1.0.3_0, the following ports depend on it:
--->  	py27-ipython @5.1.0_0
Error: org.macports.uninstall for port py27-prompt_toolkit returned: Please uninstall the ports that depend on py27-prompt_toolkit first.
Please see the log file for port py27-prompt_toolkit for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_registry_portfiles_py27-prompt_toolkit-1.0.3_0_d685e5767ab1de3f47cfbbb80304ae33cb9f0593ee9d2bc0810897f2f60f944f-1282/py27-prompt_toolkit/main.log
Warning: Failed to execute portfile from registry for py27-prompt_toolkit @1.0.3_0
--->  Unable to uninstall py27-prompt_toolkit @1.0.3_0, the following ports depend on it:
--->  	py27-ipython @5.1.0_0
Error: port uninstall failed: Please uninstall the ports that depend on py27-prompt_toolkit first.
[3][11:31:40][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] sudo port uninstall py27-ipython
--->  Deactivating py27-ipython @5.1.0_0
--->  Cleaning py27-ipython
--->  Uninstalling py27-ipython @5.1.0_0
--->  Cleaning py27-ipython
[4][11:32:00][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] sudo port uninstall py27-prompt_toolkit
--->  Deactivating py27-prompt_toolkit @1.0.3_0
--->  Cleaning py27-prompt_toolkit
--->  Uninstalling py27-prompt_toolkit @1.0.3_0
--->  Cleaning py27-prompt_toolkit
[5][11:32:07][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] sudo port install py27-ipython
--->  Computing dependencies for py27-ipython
--->  Dependencies to be installed: py27-prompt_toolkit
--->  Fetching archive for py27-prompt_toolkit
--->  Attempting to fetch py27-prompt_toolkit-1.0.3_0.darwin_14.noarch.tbz2 from https://packages.macports.org/py27-prompt_toolkit
--->  Attempting to fetch py27-prompt_toolkit-1.0.3_0.darwin_14.noarch.tbz2.rmd160 from https://packages.macports.org/py27-prompt_toolkit
--->  Installing py27-prompt_toolkit @1.0.3_0
--->  Activating py27-prompt_toolkit @1.0.3_0
--->  Cleaning py27-prompt_toolkit
--->  Fetching archive for py27-ipython
--->  Attempting to fetch py27-ipython-5.1.0_0.darwin_14.noarch.tbz2 from https://packages.macports.org/py27-ipython
--->  Attempting to fetch py27-ipython-5.1.0_0.darwin_14.noarch.tbz2.rmd160 from https://packages.macports.org/py27-ipython
--->  Installing py27-ipython @5.1.0_0
--->  Activating py27-ipython @5.1.0_0

Please note that since version 4.0 IPython was refactored and splitted across several packages under new project named Jupyter.

To make this the default IPython or IPython2 (i.e., the version run by the 'ipython' or 'ipython2' commands), run one or both of:

    sudo port select --set ipython py27-ipython
    sudo port select --set ipython2 py27-ipython
    

--->  Cleaning py27-ipython
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.
[6][11:32:23][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] sudo port select --set ipython py27-ipython
Selecting 'py27-ipython' for 'ipython' succeeded. 'py27-ipython' is now active.
[7][11:32:35][dbrowne][/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7] ipython
Python 2.7.12 (default, Jun 29 2016, 12:53:15) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit
```

Thank you both very much for the help!!!
